### ISSUE TITLE
Couldn't authenticate WebSocket connection

### ISSUE THREAD

**Issue by mvoelske** [millejoh/emacs-ipython-notebook#100]
I'm using EIN version 20160422.629 from ELPA. Since updating to Jupyter 4.1.0, I can't run any code cells from emacs-ipython-notebook anymore. 

I'm running `ein:notebooklist-login` followed by `ein:notebooklist-open`, which works and lets me navigate to and open the notebook. I can run `ein:notebook-restart-kernel-command` successfully, but trying to evaluate a code cell is always is always met with a "Kernel not ready yet" message.

In the messages buffer, I get the following output:

```
ein: [info] Opened notebook list at 8888 with path XYZ
ein: [info] Opening notebook XYZ/XYZ.ipynb...
Blocking call to accept-process-output with quit inhibited!! [2 times]
ein: [info] Reading nbformat4 notebook.
ein: [info] Worksheet XYZ.ipynb is ready
ein: [info] Notebook XYZ.ipynb is ready
Blocking call to accept-process-output with quit inhibited!!
ein: [info] Kernel started: e96498c2-6e34-4b70-9759-36bb0b390318
ein: [info] Starting channels WS: "ws://127.0.0.1:8888/api/kernels/e96498c2-6e34-4b70-9759-36bb0b390318/channels?session_id=1afbe04b-734a-4f8a-913e-3179b5eb98b0"
error in process filter: byte-code: Error response received from websocket server
error in process filter: Error response received from websocket server
ein: [warn] Kernel is not ready yet! (or closed already.)
```

At the same time, the ipython notebook server outputs the following:

```
[I 11:43:34.661 NotebookApp] 302 POST /login (127.0.0.1) 0.67ms
[W 11:43:34.662 NotebookApp] 405 POST / (127.0.0.1) 0.25ms referer=None
[W 11:44:00.180 NotebookApp] Notebook XYZ/XYZ.ipynb is not trusted
[W 11:44:09.935 NotebookApp] Couldn't authenticate WebSocket connection
[W 11:44:09.936 NotebookApp] 403 GET /api/kernels/e96498c2-6e34-4b70-9759-36bb0b390318/channels?session_id=1afbe04b-734a-4f8a-913e-3179b5eb98b0 (127.0.0.1) 2.85ms referer=None
```

**Comment by millejoh** [comment]
Darn, I thought I had this one working. Could you give me some more information on your environment? Linux, Mac, Windows. How is jupyter configured and how are you calling it from the command line?

Also, do you know which backend the request package is using - curl or url-retrieve?

**Comment by mvoelske** [comment]
I'm running Linux (Ubuntu 14.04 LTS). My jupyter configuration is nearly the default, the only thing I've set is a password (`c.NotebookApp.password` setting). My Jupyter startup script simply calls: 
`jupyter notebook --ip="*" --no-browser`.

The request package seems to be using the curl backend:
```
(describe-variable 'request-backend) 
#("request-backend is a variable defined in `request.el'.
Its value is curl
```
My curl version is the following:
```
% curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 
```

I've noticed that if I remove the Jupyter password, running notebook cells from EIN works, so it must be related to that; however, with a password set, `ein:notebooklist-login` does report success after entering the correct password.

**Comment by millejoh** [comment]
If I use curl as the backend for request I can reproduce the error, however not with url-retrieve. Leads me to think that the issue is with how curl stores cookies - when the client authenticates with the jupyter server it is supposed to store a cookie with the session key that is needed to authenticate websocket connections.

For some reason url-retrieve stores the cookie in such a way that EIN is able to later find and use it to authenticate when opening a ws: or wss: connection, so for the moment I recommend that as a workaround.

Call `M-x customize-group RET request` and set `Request Backend` to `url-retrieve`. Also make sure that `Request Storage Directory` is set to a directory that you have read and write access to.

**Comment by mvoelske** [comment]
Thanks, can confirm that it works with the `url-retrieve` backend  (even when Jupyter has a password set).

**Comment by reconmaster** [comment]
I am having the exact same problem with a password protected notebook. I tried to switch to url-retrieve as suggested, but I am still getting the same websocket error.

```
error in process filter: byte-code: Error response received from websocket server
error in process filter: Error response received from websocket server
Blocking call to accept-process-output with quit inhibited!! [4 times]
```

**Comment by reconmaster** [comment]
I had this working briefly using the `url-retrieve` workaround above. However, with jupyter still at 4.1.0 and updating ein to ein-20161021.1010, this no longer works. I still need to the `url-retrieve` workaround to login and load the notebook; without it, I can't even load the notebook. I vaguely remember seeing `url-retrieve` may have updated at some point.

I get no server-side errors when using `notebooklist-login` and `notebooklist-open`, the 302 Post / login works followed by a kernel start with kernel ID. Unfortunately, while ein displays the existing work, attempting to run any command gives a kernel failure message though no such message exists on the server. I am using emacs 24.5.50.

```
[info] Login to https://research.edu:8888 complete. Now you can open notebook list by `ein:notebooklist-open'. @#<buffer *Org Agenda*>
[info] Opened notebook list at https://research.edu:8888 with path  @#<buffer *ein:notebooklist https://research.edu:8888*>
[info] Opened notebook list at https://research.edu:8888 with path 161020_experiment @#<buffer *ein:notebooklist https://research.edu:8888*>
[info] Opening notebook 161020_experiment/config_verification.ipynb... @#<buffer *ein:notebooklist https://research.edu:8888*>
[info] Reading nbformat4 notebook. @#<buffer research.org>
[info] Worksheet config_verification.ipynb is ready @#<buffer *ein: https://research.edu:8888/config_verification.ipynb*>
[info] Enabling autosaves for config_verification.ipynb with frequency 60 seconds. @#<buffer research.org>
[info] Notebook config_verification.ipynb is ready @#<buffer research.org>
[info] Writing notebook config_verification.ipynb as nbformat 4. @#<buffer *ein: https://research.edu:8888/config_verification.ipynb*>
[info] Opened notebook list at https://research.edu:8888 with path 161020_experiment @#<buffer *ein:notebooklist https://research.edu:8888*>
[warn] Kernel is not ready yet! (or closed already.) @#<buffer *ein: https://research.edu:8888/config_verification.ipynb*>
```

**Comment by millejoh** [comment]
Think I have this one figured out, see #148 and #147. Jupyter changed how they use cookies, which breaks emacs-request. I have managed to work around, though, and it appears that authentication is working again.

**Comment by slackline** [comment]
Hi,

I've encountered this issue of `Couldn't authenticate WebSocket connection` and EIN failing to detect that the kernel is ready `ein: [warn] Kernel is not ready yet! (or closed already)`.

I'm connecting to a Notebook that is running on a server rather than on the same computer.  I've set passwords under Jupyter Notebook on the remote and from EIN use `ein:notebooklist-login` to enter the password and can then connect using `ein:notebooklist-open` and explicitly providing the URL and port.  This opens a list of notebooks and I can then navigate and open any of these.  When I switch to the buffer though I can not run any code sections with `C-c C-c` as I'm informed the kernel isn't ready.  Code can be executed from a web-browser though so the kernel is running.  Screenshot of Emacs [here](https://i.imgur.com/YsLg6vt.png).

The console output shows...

    [W 07:44:45.189 NotebookApp] Notebook createAverageSpeedSegments.ipynb is not trusted
    [W 07:44:49.648 NotebookApp] Couldn't authenticate WebSocket connection
    [W 07:44:49.651 NotebookApp] 403 GET /api/kernels/5990768d-694e-422c-a2a0-6fc633554040/channels?session_id=85baeb89-62f9-4f3d-9a7a-4168d872374d (::1) 6.57ms referer=None

Whilst the EIN log shows...

    [info] Opened notebook list at http://localhost:8906 with path . @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Opening notebook createAverageSpeedSegments.ipynb... @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Reading nbformat4 notebook. @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Worksheet createAverageSpeedSegments.ipynb is ready @#<buffer *ein: http://localhost:8906/createAverageSpeedSegments.ipynb*>
    [info] Enabling autosaves for createAverageSpeedSegments.ipynb with frequency 60 seconds. @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Notebook createAverageSpeedSegments.ipynb is ready @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Kernel started: 5990768d-694e-422c-a2a0-6fc633554040 @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Starting channels WS: "ws://localhost:8906/api/kernels/5990768d-694e-422c-a2a0-6fc633554040/channels?session_id=85baeb89-62f9-4f3d-9a7a-4168d872374d" @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Opened notebook list at http://localhost:8906 with path . @#<buffer *ein:notebooklist http://localhost:8906*>
    [warn] Kernel is not ready yet! (or closed already.) @#<buffer *ein: http://localhost:8906/createAverageSpeedSegments.ipynb*>
    [warn] Kernel is not ready yet! (or closed already.) @#<buffer *ein: http://localhost:8906/createAverageSpeedSegments.ipynb*>
    [warn] Kernel is not ready yet! (or closed already.) @#<buffer *ein: http://localhost:8906/createAverageSpeedSegments.ipynb*>
    

I tried the solution suggested above of switching to `url-retrieve` instead of `curl` but this prevented me from connecting to the Notebook list at all....

    [W 08:00:53.399 NotebookApp] Forbidden
    [W 08:00:53.399 NotebookApp] 403 GET /api/contents/ (::1) 0.97ms referer=None
    [W 08:01:21.243 NotebookApp] Forbidden
    [W 08:01:21.244 NotebookApp] 403 GET /api/contents/ (::1) 2.08ms referer=None

Reverting to `curl` and I can connect to the Notebook list again.

Jupyter version is 4.4.0 and EIN was installed from MELPA and is version 0.14.1

Let me know if I can provide any more information.
