### ISSUE TITLE
When running with zeroein.el, indents have size 3 spaces and tabs also make their way into files

### ISSUE THREAD

**Issue by sebjameswml** [millejoh/emacs-ipython-notebook#101]
I'm working on a notebook which previously had 4 spaces for an indent, but tab chars are making their way into my file now I'm editing it in EIN. Also, where does the 3 space indentation come from?

**Comment by millejoh** [comment]
What is your setting for `ein:notebook modes` in the customize group for ein? If it is Multi-Lang then what ein does is copy the text to a temporary buffer running the appropriate major mode (i.e. Python for python, Markdown for markdown, etc.) and calls `font-lock-fontify-buffer` and then places the resulting text properties back into the notebook buffer.

If you are seeing weirdness with tabs/spaces, etc then I want to say something is up with your python major mode configuration, or perhaps EIN is getting confused on which major mode to use.

Are you using python.el or python-mode.el?
