### ISSUE TITLE
(require 'ein) is a no-op

### ISSUE THREAD

**Issue by sebjameswml** [millejoh/emacs-ipython-notebook#102]
In the current code, there seems to be nothing in ein.el apart from (provides 'ein) so the documentation which says you just have to (require 'ein) is misleading for new users.

**Comment by millejoh** [comment]
Yes, not exactly user friendly that bit. Most people use ein through MELPA or spacemacs, or zeroein, thankfully. I'm not sure what I want to do as keeping ein.el keeps some useful description text for the emacs package manager.

I don't think I want to get rid of ein, but for sure I should update the documentation. Some day.

**Comment by millejoh** [comment]
And thanks to @sam-s we finally have a use for ein.el! I am a happy camper, hope you don't mind as I close out this issue.
