### ISSUE TITLE
Fail opening ipython 4.0 notebook page from emacs-25 .

### ISSUE THREAD

**Issue by dov** [millejoh/emacs-ipython-notebook#107]
Connecting to a ipython notebook 4 server from emacs 25 fails.

To reproduce:
1. Run `ipython notebook`.
2. cd to .../emacs-ipython-notebook/lisp
3. Copy request.el (version 0.2.0) and websocket.el (version 1.6) there.
4. Run `emacs -Q` and eval the following
   
   (setq load-path (append (list ".") load-path))
   (require 'ein)
   (require 'ein-loaddefs)

Result:
1. No new emacs buffer is opened as expected.
2. The ipython console contains the following error

```
[I 09:56:43.581 NotebookApp] Creating new file in 
[W 09:56:44.232 NotebookApp] /api/notebooks is deprecated, use /api/contents
[I 09:56:44.232 NotebookApp] 302 GET /api/notebooks/untitled1%2Funtitled1 (127.0.0.1) 0.97ms
[W 09:56:44.233 NotebookApp] /api/notebooks is deprecated, use /api/contents
[I 09:56:44.234 NotebookApp] 302 GET /api/notebooks/ (127.0.0.1) 0.79ms
[W 09:56:44.236 NotebookApp] No such file or directory: untitled1/untitled1
[W 09:56:44.236 NotebookApp] 404 GET /api/contents/untitled1/untitled1 (127.0.0.1) 1.87ms referer=No

```
1. The emacs _Messages_ buffer contains the following:

```
ein: [info] Opening notebook untitled1/untitled1...
ein: [error] Content list call http://127.0.0.1:8888/api/notebooks/untitled1%2Funtitled1 failed with status error.
Blocking call to accept-process-output with quit inhibited!! [2 times]
ein: [info] Opened notebook list at 8888 with path 

```

Versions:

Os: Fedora 24
emacs: 25.1.1
emacs-ipython-notebook commit id: 0bbe7ad

**Comment by millejoh** [comment]
Try M-x `ein:force-ipython-version-check`. From the error messages it looks like ein is trying to communicate using the pre-4.0 notebook API. This can happen if you switch IPython versions in the middle of an emacs session as EIN caches the notebook API version for performance reasons.

**Comment by Sengege** [comment]
I met this issue too. 
I fixed it by use 
jupyter notebook password. set a password for jupyter login auth.
then 
M-x ein:notebooklist-login
input password setting before
then
M-x ein:notebooklist-open
