### ISSUE TITLE
Send buffer text to connected notebook as node

### ISSUE THREAD

**Issue by kootenpv** [millejoh/emacs-ipython-notebook#108]
Using `ein:connect-eval-region` it is possible to evaluate a snippet in one buffer, and have the result available in the notebook buffer. However, I would like a visual indication that it worked. Preferably, I would like `eval-region` (or a differently named function) to create a new node in the notebook buffer, and have that be evaluated. Create an [In] and an [Out].

Is this functionality already included but I cannot find it? Why is it not there, do you consider it bad practice? 

Before I would start hacking something together, I would like to know what's up :)

**Comment by millejoh** [comment]
The idea of the shared-output buffer is to show output from execution from possibly different notebooks. It is possible to show the executed snippets, but some additional bookkeeping would need to be done to track which snippet is associated with the notebook it is being executed in. There is also the concern that the snippets could be very large in the case that you are evaluating an entire Python file.

The execution counter in the shared-output buffer should at least be incrementing as you evaluate; there also should be indications in the ein-log buffer that the code is being executed.

Note that if the code you are evaluating should generate a return value, but nothing is appearing in the shared-output buffer then there may be a bug in ein. Let me know if that is happening, along with the code you are evaluating, and I will try to debug.

**Comment by kootenpv** [comment]
@millejoh Somehow `ein:connect-to-notebook` just hangs (after having creating a new untitled `*ein: 8888/Untitled7.ipynb` buffer. 

It throws: `progn: Lisp nesting exceeds `max-lisp-eval-depth'`

I just did a latest install from MELPA and the same story.

**Comment by millejoh** [comment]
So, `ein-connect-to-notebook` calls a function which recurses through calls to the jupyter server to generate a list of all the notebooks that can be served. If you have a large number of directories and files in the server hierarchy this can quickly overwhelm the default settings for emacs. One way to work around this is to be more generous with these defaults:

```lisp
(setq max-lisp-eval-depth 100000)
(setq max-specpdl-size 100000)
```

Doing this will at least allow `ein:connect-to-notebook` to run, but may cause some performance issues. Note that `ein:connect-to-notebook-buffer` is more efficient as it only looks for running notebooks.

Doing this recursively certainly made the code easier to write and understand, but obviously was not so good performance-wise. I will have to think if there is a better way to perform this task. Thanks for pointing this out!

**Comment by kootenpv** [comment]
I tried from somewhere else than home-folder, and that works better.

However, now I get issues on `ein:connect-to-notebook` like:

    [W 20:56:29.899 NotebookApp] 404 GET /api/contents/notebooks/Untitled.ipynb (127.0.0.1) 0.86ms referer=None

This is after playing around with a notebook on "http://127.0.0.1:8888/notebooks/Untitled.ipynb". It has been saved/checkpointed.

Tried ein:connect-to-notebook with the following:

    http://127.0.0.1:8888/notebooks/Untitled.ipynb
    127.0.0.1:8888/notebooks/Untitled.ipynb
    localhost:8888/notebooks/Untitled.ipynb
    8888/notebooks/Untitled.ipynb
    8888/Untitled.ipynb
    Untitled.ipynb
    8888

None works. Any ideas?

**Comment by millejoh** [comment]
Cobwebs are cropping up on this one, but before I close out I would like to point out the recent existence of [pynt](https://github.com/ebanner/pynt) which looks to have the functionality you are looking for and then some. Good luck!

**Comment by kootenpv** [comment]
Thanks! I'll have a look. Cobwebs, removed!
