### ISSUE TITLE
indentation issue

### ISSUE THREAD

**Issue by florisvanvugt** [millejoh/emacs-ipython-notebook#110]
First of all, let me tell you I love this package. It's really such an improvement over the usual Jupyther web-interface. I love being able to use all my Emacs key commands.
I have an issue with indentation, though. Here is the issue: make a new notebook, and in a cell, type the following class definition:

```
class Learner:
    def __init__(self):
        """ Do something """
        print ("Hello")
```

After typing each line, simply press <ENTER>. For me, this causes the next line to start already 4 spaces indented (which is what I want).
However, when I execute this cell, I get the following error message underneath it:

```
  File "<ipython-input-1-0ad078468081>", line 3
    """ Do something """
                        ^
TabError: inconsistent use of tabs and spaces in indentation
```

I think what happened is that the line with the comment is actually indented using tabs whereas the `def __init__` line was indented using spaces.
When I use Emacs to create a python file (i.e. not using `ein`) the indenting is correct, 4 spaces and 8 spaces respectively.

I realise I might be doing something wrong here so I am happy if anybody can point this out to me. Thanks!

**Comment by millejoh** [comment]
Thanks for the kind comments! I'm not sure what it is, but I too prefer the interface provided by ein over the web UI - even with emacs keybindings enabled in the notebook web interface.

Unfortunately I'm not able to reproduce what your are seeing, so I think it may be a configuration issue with either ein or python-mode.

What is your settings for `ein:notebook-modes`? The value is a list - if `ein:notebook-plain-mode` is at the front this might explain why you are getting the noted behavior. I set this variable to `(ein:notebook-multilang-mode ein:notebook-mumamo-mode ein:notebook-python-mode)`.

Do you have both python.el and python-mode installed? I cannot remember all the settings that control indentation, but there is one that controls whether Emacs uses tabs or spaces. If you have both modes set to different defaults it might be confusing things, but of that I can't be sure.

**Comment by millejoh** [comment]
Defaulting to `ein:notebook-multilang-mode` and encouraing the use `ein:edit-cell-contents` (bound to `C-'`) might be the solution to many of these editing/indentation issues.
