### ISSUE TITLE
Select kernel for existing notebook

### ISSUE THREAD

**Issue by millejoh** [millejoh/emacs-ipython-notebook#111]
We can choose a kernel when creating a notebook, but ein has no way to change this selection once the notebook is created.

**Comment by rambalachandran** [comment]
Does this mean its possible now to apply a kernel through ein? I will be interested to know, since I'm looking to create a kernel for various virtualenvs that I intend to use following this [link](http://www.alfredo.motta.name/create-isolated-jupyter-ipython-kernels-with-pyenv-and-virtualenv/)
