### ISSUE TITLE
MOVED: List all open notebooks

### ISSUE THREAD

**Issue by nwieder** [millejoh/emacs-ipython-notebook#112]
--- MOVED FROM tkf/emacs-ipython-notebook ---

Either I cannot figured out how to do it, or it doesn't exist. I am missing a simple function that lists all open notebooks, so I can manage them easily. Any plans to include something like that anytime soon? It would improve my workflow significantly...

Keep up the great work!

--- MILLEJOH ANSWER ---

Sorry about the very slow response, but I don't always see the issues posted to this repository. Note that tkf is no longer maintaining ein. Come by https://github.com/millejoh/emacs-ipython-notebook - that's where all the fun is these days.

The command ein:notebooklist-open-notebook-global sort of does what you are asking. Or are you hoping to have the entire list of notebooks available in one buffer?

Be careful, though, if you have a large number of subdirectories and files running in your jupyter server Emacs can choke, see millejoh/emacs-ipython-notebook#108.

**Comment by nwieder** [comment]
Thanks for the answer! I moved the issue here, hope that's ok...

I tried `ein:notebooklist-open-notebook-global` but it gets stuck with the `progn: Lisp nesting exceeds 'max-lisp-eval-depth'` error. I tried to adjust the two variables as suggested in [#108](https://github.com/millejoh/emacs-ipython-notebook/issues/108):
```
(setq max-lisp-eval-depth 100000)
(setq max-specpdl-size 100000)
```
but emacs keeps on getting stuck (even after restarting the jupyter server and only one open notebook)

I am actually looking for a function the resembles the "Running" tab of the jupyter notebook browser interface. Ideally with the respective switches to stop the notebooks...

Thanks!

**Comment by millejoh** [comment]
You are welcome.

I pushed some updates, don't know when they will show up, but once they do update your copy of ein and let me know what you think of the new and improved notebooklist buffer view.

**Comment by nwieder** [comment]
Just updated ein and the new notebooklist buffer view is great! Exactly what I had in mind, thank you!
Only one little suggestion/request that would make it perfect: If you could add an [Close] as it appears in the standard notebook list, would make managing ipython notebooks that are opened and located in different directories very convenient!

The more I get into this makes me realize that I should finally take some time and dive into elisp. I feel kind of stupid requesting such minor hacks :/
