### ISSUE TITLE
Jedi autocomplete

### ISSUE THREAD

**Issue by mayanez** [millejoh/emacs-ipython-notebook#113]
Hi,

I currently use jedi for my usual Python scripts. However, I've had some difficulty getting it to work properly with EIN. I've followed what is in the documentation here: https://millejoh.github.io/emacs-ipython-notebook/#id13 but it doesn't seem to be working. For some reason I'm not seeing the 'C-c C-i' keybind that its supposed to add. Any suggestions?

Thanks!

**Comment by millejoh** [comment]
The only thing I can think of is that you need to set `ein:connect-mode-hook` after you have loaded ein. Is `C-c C-i` bound to anything else while you are in a notebook buffer? What happens if you call `M-x jedi-complete`?

**Comment by mayanez** [comment]
I don't have anything else bound to `C-c C-i` that I know of. `jedi-complete` does nothing while in the notebook buffer. The problem I think is that `ein:jedi-setup` doesn't exist. When I do `jedi:setup` autocomplete works fine, but if I'm not mistaken that would use my local python installation when running a remote notebook, correct?

**Comment by peterewills** [comment]
@millejoh I'm also having this problem - `ein:jedi-setup` doesn't seem to exist. I'm trying to run `M-x ein:jedi-setup` from a notebook.

**Comment by dickmao** [comment]
The documentation is fairly out of date.  There is no explicit jedi support within EIN.

I recommend installing [Elpy](https://github.com/jorgenschaefer/elpy) and following EIN's README instructions for activating polymode.
