### ISSUE TITLE
indentation and autocompletion not working!

### ISSUE THREAD

**Issue by kirk86** [millejoh/emacs-ipython-notebook#115]
Hi everyone, apologies for the disturbance I'm trying to get indentation and autocompletion to work on ein but apparently I haven't figured that out yet.

Every time I try to use the the shift+tab or the ein:completer... I get the following error.
Any advice would be much appreciated. 

`Error (websocket): in callback 'on-message': Wrong type argument: number-or-marker-p, ni`

Also the indentation doesn't work as compared to when I write the same stuff on a usual buffer instead to ein. How can I fix that?

**Comment by millejoh** [comment]
What are the settings for the configuration variables `Ein:Notebook Modes`,  and `Ein:Use Auto Complete`?

Does auto-complete work for you in a python-mode buffer?

I'm not sure if it will help with this, but can you execute `ein:dev-bug-report-template` and paste the results here?

**Comment by millejoh** [comment]
What are the settings for the configuration variables `Ein:Notebook Modes`,  and `Ein:Use Auto Complete`?

Does auto-complete work for you in a python-mode buffer?

I'm not sure if it will help with this, but can you execute `ein:dev-bug-report-template` and paste the results here?

**Comment by millejoh** [comment]
What are the settings for the configuration variables `Ein:Notebook Modes`,  and `Ein:Use Auto Complete`?

Does auto-complete work for you in a python-mode buffer?

I'm not sure if it will help with this, but can you execute `ein:dev-bug-report-template` and paste the results here?

**Comment by kirk86** [comment]
These are my settings for ein:

`(require 'ein)`
`(setq ein:use-auto-complete t)`
`(setq ein:use-smartrep t)`

Auto-complete works just fine for python-mode.

How should I set the `Ein:Notebook Modes` and `Ein:Use Auto`?

Here's the output from `ein:dev-bug-report-template`

```
("EIN system info"
 :emacs-version
 "GNU Emacs 24.5.1
 :emacs-bzr-version nil
 :window-system ns
 :emacs-variant nil
  :lsb-release nil)
 :image-types
 (png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.7"
           :source-dir "/Users/user/.emacs.d/elpa/ein-20160725.621/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/elpa/websocket-20160720.2051/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.5")
  (:name "request"
         :path "~/.emacs.d/elpa/request-20160822.1659/request.elc"
         :featurep t
         :version-var request-version
         :version "0.2.0")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20160827.649/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20160827.649/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/elpa/popup-20160709.729/popup.elc"
         :featurep t
         :version-var popup-version
         :version "0.5.3")
  (:name "python"
         :path "/Applications/Editors/Emacs.app/Contents/Resources/lisp/progmodes/python.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "python-mode"
         :path "~/.emacs.d/elpa/python-mode-20160812.1245/python-mode.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path "~/.emacs.d/elpa/markdown-mode-20160830.820/markdown-mode.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "smartrep"
         :path "~/.emacs.d/elpa/smartrep-20150508.1930/smartrep.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "helm"
         :path "~/.emacs.d/elpa/helm-core-20160830.609/helm.elc"
         :featurep t
         :version-var nil
         :version nil)))
```

**Comment by millejoh** [comment]
To get behavior close to python-mode you should have `ein:notebook-modes` set to something like `(ein:notebook-multilang-mode ein:notebook-python-mode ein:notebook-plain-mode)` or `(ein:notebook-python-mode ein:notebook-plain-mode)`.

The websocket error is odd, and unfortunately those are very hard to reproduce and debug. What version of Jupyter/IPython notebook are you running? Is there any error-like output in the console where you are running the notebook server?

**Comment by kirk86** [comment]
Just to clarify, should I be doing:

`(autoload 'ein:notebook-multilang-mode "ein-multilang" "\Notebook mode with multiple language fontification.\(fn)" t nil)`

also for `ein:notebook-python-mode ein:notebook-plain-mode`

or is just enough to set it once for the `multilang-mode`?

**Comment by millejoh** [comment]
You shouldn't need to be calling autoload for ein features, ein already does this.

You should be able to call `M-x customize-variable RET ein:notebook-modes` and set the value menu from the customize interface. If you don't like Emacs customize interface you can do the following in your init code:

`(setq ein:notebook-modes '(ein:notebook-multilang-mode ein:notebook-python-mode))`

**Comment by kirk86** [comment]
@millejoh Thank you for all your help and your patience. I'm still not able to get the same behavior as I would get in a normal python or lua buffer. In the `ein:notebook` I can't get auto-completion as I would get in a normal python buffer where I would type and automatically get auto-completion or just press `<tab>` and get the auto-completion. Plus syntax checking and highlighting don't work the same in the `ein:notebook` as in the normal python/lua buffer. Maybe I'm missing some other configuration?

**Comment by millejoh** [comment]
Looks like you are downloading ein from melpa - which is good. You should not need to do `(require 'ein)` or set any other configuration for ein in your init.el file. With this type of installation it is best to use emacs configuration interface to control ein's configuration: `M-x customize-group RET ein RET`.

So, let's try the following:
 1. Delete all the settings for ein you have placed in your init.el file.
 2. Restart emacs.

Now, does `ein:notebooklist-open` still work? If it doesn't then try deleting and reinstalling ein from melpa.

Open an ipython notebook:
 1. What is `C-c C-i` bound to?
 2. What happens when you call `ein:completer-complete` next to a symbol?

Let's get autocomplete working then we can take a look at what's happening with syntax highlighting.

**Comment by kirk86** [comment]
Ok everything works with removed ein: configuration.

1. `C-c C-i` is bound to a complete menu if under stand correctly

e.g. typing  `importC-c C-i` gives me a a menu bar prompting with the following text `Complete: import`

2. `ein:completer_complete` does the same thing

When I try those command next to something like `np.random.C-c C-i` I get nothing as suggestion.

Maybe I am mistaking auto-complete with suggestions? For instance using `elpy` I get auto-complete and suggestion when i type `np.random.` I get a dropdown with automatically suggestions. This is what I'm trying to simulate to `ein` but I don't know if it's possible?

**Comment by millejoh** [comment]
Make sure auto-complete-mode is turned on in your notebook buffer. If I don't do that then I do not get the popup, but rather emacs opens a new window with the completion candidates.

**Comment by kirk86** [comment]
@millejoh Thanks. `auto-complete-mode` is enabled. What I observed is that every time I'm in a a word I'm trying to expand using `C-c C-i` or `win:completer-complete` I get the following error messages:

```
Error (websocket): in callback `on-message': Wrong type argument: number-or-marker-p, nil
Error (websocket): in callback `on-message': Wrong type argument: number-or-marker-p, nil
Error (websocket): in callback `on-message': Wrong type argument: number-or-marker-p, nil
Error (websocket): in callback `on-message': Wrong type argument: number-or-marker-p, nil
Error (websocket): in callback `on-message': Wrong type argument: number-or-marker-p, nil
```

Any hints on how t overcome those?

**Comment by cgustad** [comment]
I'm also having the  same problem :(

**Comment by millejoh** [comment]
Not exactly a solution, but as a workaround you could try using a new feature I just added. Typing `C-c '` will open a buffer running the appropriate major-mode to edit the contents of the current cell. I've tried to make it work like ORG's source block editing feautre. This should at least bypass the problems you are seeing.

I do wonder if some of the problem comes from having both python and python-mode installed. I think in the past EIN has had issues working well with python-mode.

**Comment by millejoh** [comment]
EIN has made some strides in the past year or so to improve support for autocompletion, and the discussion on this seems dead so I'm going to close, but do feel free to reopen if you are continuing to have troubles.
