### ISSUE TITLE
ace-jump conflict

### ISSUE THREAD

**Issue by mattharrison** [millejoh/emacs-ipython-notebook#12]
When I try to use ace-jump with ein emacs stops responding. In the Messages buffer it states:

```
ace-jump-done: Wrong type argument: stringp, nil
```

I have to kill emacs as it no longer responds. Not sure if this is an ein error or ace-jump issue.

**Comment by millejoh** [comment]
Yeah, I could work a bit on my response time (in my defense I was focused on getting ein compatible with IPython 3.0 at the time).

I just downloaded latest ace-jump-mode from MELPA and tried executing C-c SPC from inside a notebook buffer. Everything seemed to work, though I'm not all too familiar with ace-jump. Is ace-jump still not working for you? If not, could you provide me some more details so I can try to reproduce?
