### ISSUE TITLE
is evil/vim-like style supported in jupyter notebook cel?

### ISSUE THREAD

**Issue by JayDeng2837** [millejoh/emacs-ipython-notebook#120]
Hi, i am a heavy user of jupyter notebook and I have beening searching for an enhancement to jupyter's native web gui for a long time.  The project looks really awesome! 

However i am not familiar with emacs( actually i am learning it soley because of your awesome project EIN) Could you kindly let me know if vim/evil could be supported in Ein? Thank you a lot!

Best,
Jay

**Comment by millejoh** [comment]
I believe [Spacemacs](http://spacemacs.org/) with the [ipython-notebook](http://spacemacs.org/layers/+lang/ipython-notebook/README.html) layer has what you are look for.

Even if you didn't want to install spacemacs I think you could crib the setup being used in the layer to setup keybindings for your ein installation.

**Comment by quinn-dougherty** [comment]
does anyone know how to enable evil in [doom's ein module](https://github.com/doomemacs/doomemacs/tree/master/modules/tools/ein)?
