### ISSUE TITLE
Error during redisplay: Error during redisplay: (eval (ein:header-line)) signaled (wrong-type-argument arrayp nil)

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#122]
Here is the message that keep polluting my `*Messages*` buffer:
```
Error during redisplay: (eval (ein:header-line)) signaled (wrong-type-argument arrayp nil) [N times]
```
It is caused by the `ein:notification-tab-create-line ((tab ein:notification-tab))` method where `(ein:$notebook-kernelspec ein:%notebook%)` returns `nil` which is then passed to `ein:$kernelspec-name`.

PS. debugging ein is hard because the objects are huge and emacs takes forever to display them

**Comment by millejoh** [comment]
Tell me about it. It is amazing to me what @tkf was able to accomplish in elisp, but he sure loves to throw in the kitchen sink with his data structures, though I can't say I've done much better in my time as maintainer. I've noticed some redundancy in how data structures are passed around, but I'm not sure I am smart enough to optimize it all.
