### ISSUE TITLE
Emacs hangs saving notebook

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#133]
When `WebSocket ping timeout` occurs on the `jupyter` terminal, Emacs hangs at 100% CPU utilization.
The top line says `IP[3]: Saving Notebook... | 1 [+] | not connected|`
The only way out is to kill the process ("Force Quit" on mac).
This is unbelievably frustrating.

**Comment by sam-s** [comment]
it appears that the reason is an attempt to save.
IOW, `WebSocket ping timeout after 119253 ms.` appears on the terminal *after* Emacs have been stuck with the `Saving Notebook` status.

**Comment by sam-s** [comment]
At this time, emacs is still non-responsive and eating up 100% CPU.
However, I can see the `*Backtrace*` buffer (which will disappear - together with all display - if I try hit `C-g` or `C-]`):
```
lisp error: invalid-function ein:log
ein:log(verbose "saving content successful status %s" nil)
ein:content-save-success
...(apply bytecodes)
request--safe-apply
request--callback
apply(request--callback)
request--curl-callblack
```
this might be a red herring though; it is quite possible that this disaster stems from something else (probably from your recent fix of my [previous bug report](https://github.com/millejoh/emacs-ipython-notebook/issues/131))

**Comment by sam-s** [comment]
the server terminal now looks like this:
```
[W 12:51:06.733 NotebookApp] Notebook twitter.ipynb is not trusted
[I 12:53:15.797 NotebookApp] Saving file at /twitter.ipynb
[W 12:53:15.816 NotebookApp] Saving untrusted notebook twitter.ipynb
[W 12:55:14.731 NotebookApp] WebSocket ping timeout after 119253 ms.
[I 13:04:43.426 NotebookApp] Saving file at /twitter.ipynb
[W 13:04:43.430 NotebookApp] Saving untrusted notebook twitter.ipynb
[I 13:04:44.439 NotebookApp] Saving file at /twitter.ipynb
[W 13:04:44.443 NotebookApp] Saving untrusted notebook twitter.ipynb
[I 13:04:45.560 NotebookApp] Saving file at /twitter.ipynb
[W 13:04:45.565 NotebookApp] Saving untrusted notebook twitter.ipynb
[I 13:04:46.609 NotebookApp] Saving file at /twitter.ipynb
[W 13:04:46.614 NotebookApp] Saving untrusted notebook twitter.ipynb
[I 13:04:47.799 NotebookApp] Saving file at /twitter.ipynb
[W 13:04:47.804 NotebookApp] Saving untrusted notebook twitter.ipynb
[I 13:04:48.902 NotebookApp] Saving file at /twitter.ipynb
[W 13:04:48.908 NotebookApp] Saving untrusted notebook twitter.ipynb
[I 13:04:50.060 NotebookApp] Saving file at /twitter.ipynb
[W 13:04:50.065 NotebookApp] Saving untrusted notebook twitter.ipynb
[I 13:04:51.068 NotebookApp] Saving file at /twitter.ipynb
[W 13:04:51.074 NotebookApp] Saving untrusted notebook twitter.ipynb
[I 13:04:52.183 NotebookApp] Saving file at /twitter.ipynb
[W 13:04:52.186 NotebookApp] Saving untrusted notebook twitter.ipynb
[I 13:04:53.249 NotebookApp] Saving file at /twitter.ipynb
[W 13:04:53.255 NotebookApp] Saving untrusted notebook twitter.ipynb
[I 13:04:54.335 NotebookApp] Saving file at /twitter.ipynb
[W 13:04:54.340 NotebookApp] Saving untrusted notebook twitter.ipynb
[I 13:05:58.102 NotebookApp] Saving file at /twitter.ipynb
[W 13:05:58.109 NotebookApp] Saving untrusted notebook twitter.ipynb
[I 13:06:30.063 NotebookApp] Saving file at /twitter.ipynb
[W 13:06:30.066 NotebookApp] Saving untrusted notebook twitter.ipynb
```

**Comment by millejoh** [comment]
This, in part, may be a Jupyter [issue](https://github.com/jupyter/notebook/issues/1164). A suddenly terminated websocket connection definitely should not cause emacs CPU utilization to go to 100%, though.

A couple of things: 

1) Not sure why the notebook is saving once every second. EIN should only be saving if the notebook has been modified - at least that is what it does on my machine. I'd call `M-X ein:byte-compile-ein` and restart, just to be sure that all your elc files are up to date.

2) I think the saving is a red herring, but I've been fooled by my instincts before - saving uses the [contents](http://jupyter-notebook.readthedocs.io/en/latest/extending/contents.html) REST API and is distinct from the websocket communication with the notebook kernel. Maybe somebody is polling the websocket connection after it has closed?

3) Are you running any python code when you get the ping timeout message? Or is it something else? I'd like to try to recreate what is happening on my machine. It will help track this down.

**Comment by millejoh** [comment]
One other thought - if you use url-retrieve instead of curl for requests backend (see customization variable `request-backend`) do you continue to see the hangs?

As a wild shot in the dark I also am commenting out the line of code with the ein:log call that is appearing in your backtrace.

**Comment by sam-s** [comment]
I opened console list, opened a notebook, and edited a cell, and emacs hang - even before I evaluated a single form.

**Comment by sam-s** [comment]
the hang happens in preparing the backtrace.
I have a strong suspicion that the problem is the string representation of highly nested structures.
your "notebook" objects (IIRC) are humongous.
I wonder if the first step to finding the actual solution would be to define print methods which produce a compact representation.

**Comment by millejoh** [comment]
`ein:dev-patch-backtrace` monkey-patches backtrace to have `print-level` of 1. Does anything improve if you call this function before opening a notebook and editing a cell?

**Comment by sam-s** [comment]
Following your advice, I loaded `ein-dev.el` and ran `ein:dev-patch-backtrace`.
The backtrace that I got when I edited the notebook is
```
Debugger entered--Lisp error: (error #("Multibyte text in HTTP request: PUT /api/contents/twitte
MIME-Version: 1.0
Connection: keep-alive
Extension: Security/Digest Security/SSL
Host: 127.0.0.1:8888
Accept-encoding: gzip
Accept: */*
User-Agent: URL/Emacs Emacs/26.0.50.10 (OpenStep; x86_64-apple-darwin16.1.0)
Content-Type: application/json
Content-length: 771361
{\"type\":\"notebook\",\"name\":\"twitter.ipynb\",\"path\":\"twitter.ipynb\",\"format\":\"json\"
  signal(error (#("Multibyte text in HTTP request: PUT /api/contents/twitter.ipynb HTTP/1.1
\nM
  error("Multibyte text in HTTP request: %s" #("PUT /api/contents/twitter.ipynb HTTP/1.1
\nMIME
  url-http-create-request()                                                                     
  url-http([cl-struct-url "http" nil nil "127.0.0.1" 8888 "/api/contents/twitter.ipynb" nil nil 
  url-retrieve-internal("http://127.0.0.1:8888/api/contents/twitter.ipynb" request--url-retrieve
  url-retrieve("http://127.0.0.1:8888/api/contents/twitter.ipynb" request--url-retrieve-callback
  request--url-retrieve("http://127.0.0.1:8888/api/contents/twitter.ipynb" :type "PUT" :headers 
  apply(request--url-retrieve "http://127.0.0.1:8888/api/contents/twitter.ipynb" #622=(:type "PU
  request("http://127.0.0.1:8888/api/contents/twitter.ipynb" :type "PUT" :headers (...) :timeout
  apply(request "http://127.0.0.1:8888/api/contents/twitter.ipynb" (:type "PUT" :headers ... :ti
  ein:query-singleton-ajax((content-save 8888 "twitter.ipynb") "http://127.0.0.1:8888/api/conten
  ein:content-save([cl-struct-ein:$content 8888 4 #1="twitter.ipynb" "twitter.ipynb" "notebook" 
  ein:notebook-save-notebook(#6=[cl-struct-ein:$notebook 8888 nil "twitter.ipynb" #5=[cl-struct-
  ein:notebook-maybe-save-notebook(#6=[cl-struct-ein:$notebook 8888 nil "twitter.ipynb" #5=[cl-s
  apply(ein:notebook-maybe-save-notebook #551=(#6=[cl-struct-ein:$notebook 8888 nil "twitter.ipy
  timer-event-handler(#551=[t 22573 63574 127389 60 ein:notebook-maybe-save-notebook ... nil 0])
```
yes, I do have non-ASCII in the notebook.
thanks

**Comment by millejoh** [comment]
Progress, of sorts. I tried to recreate the issue in the small notebook uploaded to the link below. It has some chinese multibyte characters in it, but I do not any errors trying to save using emacs 25.1 on Windows.

My only though at the moment is that you are running Emacs 26.0.50.10 on OSX. Do you have the same issues running an earlier version of Emacs? Unfortuantely I do not have any Apple machines to test ein on - most of my development is on Windows, though I also have a computer running Ubuntu that I occasionally boot up to check things on.

[Multibyte.zip](https://github.com/millejoh/emacs-ipython-notebook/files/600336/Multibyte.zip)

**Comment by sam-s** [comment]
I have a stock GNU Emacs 22.1.1 (from 2007), I doubt that it will work with ein (it fails to load my .emacs).
maybe you could pro-actively encode all http request using unicode escapes?

**Comment by JoeOsborn** [comment]
I'm using emacs 25.1.1 on OS X and also seeing hangs and indefinite timeouts on notebook saving.  I don't think I have any multi-byte characters in my notebook, though.  Not every save hangs, but when they do it's extremely disruptive.

**Comment by millejoh** [comment]
@JoeOsborn I definitely recommend you put call to `ein:dev-patch-backtrace` in your .emacs file. Actually, even better would be to call `ein:dev-start-debug`, which should cause a backtrace to be generated when you get an error along with enabling detailed logging.

@sam-s request.el calls `url-hexify-string`, so multibyte should be getting handled correctly. My suspicion is that this is either 1) An Emacs 26 thing or 2) `url-hexify-string` is missing a multibyte character for some reason.

I will work on installing a dev version of 26 to test idea 1. I will need to think a bit on how to test for idea 2.

**Comment by JoeOsborn** [comment]
So, I tried setting `ein:dev-start-debug`, but then the next time I encountered a save hang (while executing a long-running Theano compile) emacs proceeded to consume 7 GB of RAM and 44 GB of swap.  I never did get a chance to see the backtrace and I'm not sure where to look up the logs.

**Comment by millejoh** [comment]
@sam-s Problem is not 1 (which probably should have been obvious if I had spent a bit more time thinking before writing) running emacs 26.0.50 on my Windows machine my simple multibyte notebook does not generate an error, so my only thought is something is slipping through `url-hexify-string`. Request seems to use a custom `allowed-chars` for backwards compatibility with emacs versions earlier than 24.3. To be able to investigate further I really need to reproduce the error, though. Can you share the notebook that is causing all the trouble?

**Comment by millejoh** [comment]
Gents - let me know if this latest commit does anything to help your issues.

**Comment by sam-s** [comment]
seems to be working now.
thanks!
