### ISSUE TITLE
Cant create new notebook with jupyter notebook 4.2.3 and emacs  24.5.1

### ISSUE THREAD

**Issue by mukuact** [millejoh/emacs-ipython-notebook#136]
## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have
Cant create new notebook

in buffer *ein:notobooklist 8888* , I pushed the button [new notebook] and return `wrong-type-argument stringp nil`

## Steps to reproduce the problem

1. exe jupyter notebook 
2. open notebooklist (ein:noteboklist-open)
3. pushed the button [new notebook] 

## Expected output
create new notebook and open in new buffer

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):
   - 5.1.0 (jupyter version is 4.2.3)
 
2. How do you start IPython? (e.g., `ipython notebook --port 9999`):
   - jupyter notebook --no-browser

3. What is your IPython notebook port number or URL?:
   - localhost:8888

## Additional information (if any)
maybe it is because this part below in ein-notobooklist.el l.121~, version 4 is not in base-path list

```
(defun ein:notebooklist-new-url (url-or-port version &optional path)
  (let ((base-path (cond ((= version 2) "api/notebooks")
                         ((= version 3) "api/contents"))))
    (ein:log 'info "New notebook. Port: %s, Path: %s" url-or-port path)
    (if (and path (not (string= path "")))
        (ein:url url-or-port base-path path)
      (ein:url url-or-port base-path))))
```

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.23)
 of 2016-04-26 on hela"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux hela 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
"
  :lsb-release
  "No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
")
 :image-types
 (png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.12.0"
           :source-dir "/home/muku/project/dotfiles/emacs/.cask/24.5.1/elpa/ein-20161110.1931/")
 :lib
 ((:name "websocket"
         :path
         "~/project/dotfiles/emacs/.cask/24.5.1/elpa/websocket-20161113.1736/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.5")
  (:name "request"
         :path "~/project/dotfiles/emacs/.cask/24.5.1/elpa/request-20160822.1659/request.elc"
         :featurep t
         :version-var request-version
         :version "0.2.0")
  (:name "auto-complete"
         :path
         "~/project/dotfiles/emacs/.cask/24.5.1/elpa/auto-complete-20161029.643/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "auto-complete"
         :path
         "~/project/dotfiles/emacs/.cask/24.5.1/elpa/auto-complete-20161029.643/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/project/dotfiles/emacs/.cask/24.5.1/elpa/popup-20160709.729/popup.elc"
         :featurep t
         :version-var popup-version
         :version "0.5.3")
  (:name "python"
         :path "/usr/local/share/emacs/24.5/lisp/progmodes/python.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path
         "~/project/dotfiles/emacs/.cask/24.5.1/elpa/markdown-mode-20160928.932/markdown-mode.elc"
         :featurep t
         :version-var markdown-mode-version
         :version "2.1")
  (:name "helm"
         :path "~/project/dotfiles/emacs/.cask/24.5.1/elpa/helm-core-20161113.908/helm.elc"
         :featurep t
         :version-var nil
         :version nil)))
```

stacktrace:

> Debugger entered--Lisp error: (wrong-type-argument stringp nil)
>   string-match("^\\(/\\)+" nil)
>   ein:trim-regexp(nil "^\\(/\\)+")
>   ein:trim-left(nil "/")
>   ein:url(8888 nil)
>   ein:notebooklist-new-url(8888 4 "")
>   ein:notebooklist-new-notebook(8888 [cl-struct-ein:$kernelspec "python2" (:logo-32x32 "/kernelspecs/python2/logo-32x32.png" :logo-64x64 "/kernelspecs/python2/logo-64x64.png") (:argv ("/usr/bin/python" "-m" "ipykernel" "-f" "{connection_file}") :env nil :display_name "Python 2" :language "python") nil])
>   #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5](--default-kernel-- --kernels-- (link :args nil :value "New Notebook" :notify (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--)) :button-overlay #<overlay from 40 to 54 in *ein:notebooklist 8888*> :from #<marker (moves after insertion) at 40 in *ein:notebooklist 8888*> :to #<marker at 54 in *ein:notebooklist 8888*>) (link :args nil :value "New Notebook" :notify (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--)) :button-overlay #<overlay from 40 to 54 in *ein:notebooklist 8888*> :from #<marker (moves after insertion) at 40 in *ein:notebooklist 8888*> :to #<marker at 54 in *ein:notebooklist 8888*>) (mouse-2 (#<window 73 on *ein:notebooklist 8888*> 46 (61 . 92) 597075002 nil 46 (6 . 4) nil (7 . 16) (9 . 19))))
>   apply(#[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5] --default-kernel-- --kernels-- ((link :args nil :value "New Notebook" :notify (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--)) :button-overlay #<overlay from 40 to 54 in *ein:notebooklist 8888*> :from #<marker (moves after insertion) at 40 in *ein:notebooklist 8888*> :to #<marker at 54 in *ein:notebooklist 8888*>) (link :args nil :value "New Notebook" :notify (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--)) :button-overlay #<overlay from 40 to 54 in *ein:notebooklist 8888*> :from #<marker (moves after insertion) at 40 in *ein:notebooklist 8888*> :to #<marker at 54 in *ein:notebooklist 8888*>) (mouse-2 (#<window 73 on *ein:notebooklist 8888*> 46 (61 . 92) 597075002 nil 46 (6 . 4) nil (7 . 16) (9 . 19)))))
>   (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--))((link :args nil :value "New Notebook" :notify (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--)) :button-overlay #<overlay from 40 to 54 in *ein:notebooklist 8888*> :from #<marker (moves after insertion) at 40 in *ein:notebooklist 8888*> :to #<marker at 54 in *ein:notebooklist 8888*>) (link :args nil :value "New Notebook" :notify (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--)) :button-overlay #<overlay from 40 to 54 in *ein:notebooklist 8888*> :from #<marker (moves after insertion) at 40 in *ein:notebooklist 8888*> :to #<marker at 54 in *ein:notebooklist 8888*>) (mouse-2 (#<window 73 on *ein:notebooklist 8888*> 46 (61 . 92) 597075002 nil 46 (6 . 4) nil (7 . 16) (9 . 19))))
>   widget-apply((link :args nil :value "New Notebook" :notify (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--)) :button-overlay #<overlay from 40 to 54 in *ein:notebooklist 8888*> :from #<marker (moves after insertion) at 40 in *ein:notebooklist 8888*> :to #<marker at 54 in *ein:notebooklist 8888*>) :notify (link :args nil :value "New Notebook" :notify (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--)) :button-overlay #<overlay from 40 to 54 in *ein:notebooklist 8888*> :from #<marker (moves after insertion) at 40 in *ein:notebooklist 8888*> :to #<marker at 54 in *ein:notebooklist 8888*>) (mouse-2 (#<window 73 on *ein:notebooklist 8888*> 46 (61 . 92) 597075002 nil 46 (6 . 4) nil (7 . 16) (9 . 19))))
>   widget-item-action((link :args nil :value "New Notebook" :notify (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--)) :button-overlay #<overlay from 40 to 54 in *ein:notebooklist 8888*> :from #<marker (moves after insertion) at 40 in *ein:notebooklist 8888*> :to #<marker at 54 in *ein:notebooklist 8888*>) (mouse-2 (#<window 73 on *ein:notebooklist 8888*> 46 (61 . 92) 597075002 nil 46 (6 . 4) nil (7 . 16) (9 . 19))))
>   widget-apply((link :args nil :value "New Notebook" :notify (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--)) :button-overlay #<overlay from 40 to 54 in *ein:notebooklist 8888*> :from #<marker (moves after insertion) at 40 in *ein:notebooklist 8888*> :to #<marker at 54 in *ein:notebooklist 8888*>) :action (mouse-2 (#<window 73 on *ein:notebooklist 8888*> 46 (61 . 92) 597075002 nil 46 (6 . 4) nil (7 . 16) (9 . 19))))
>   widget-apply-action((link :args nil :value "New Notebook" :notify (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--)) :button-overlay #<overlay from 40 to 54 in *ein:notebooklist 8888*> :from #<marker (moves after insertion) at 40 in *ein:notebooklist 8888*> :to #<marker at 54 in *ein:notebooklist 8888*>) (mouse-2 (#<window 73 on *ein:notebooklist 8888*> 46 (61 . 92) 597075002 nil 46 (6 . 4) nil (7 . 16) (9 . 19))))
>   #[0 "\306 r\307\310\311\312\313\314!\315\"\316\317%DC\216\320\321\300\242!\211@\262!\210\212\322\321\300\242!!b\210\323\304\324\"\323\304\325\"\2065,\326\327\"\326\330\"\307\310\311\331\313\314	#\332\"\333\317%DC\216\212\203c\334\327#\210\334\330#\210\335\304\336\300\242#\204\351\337-\340\300\242!\204\350\300\341 \240\210\302\203\232\300\242\211\242\342=\262\203\232\300\242.B.\300\301\240\210\343\344\337\"\210\300\242\250\204o\300\242@\345>\204o\300\242@\346=\204o\303\347\300\242!\240\210\303\242\203\331\350\303\242\351\"\304=\203\331\203o\334\327#\210\334\330#\210\202o\334\327#\210\334\330#\210\202o)\303\242\203\350\303\242\351\"\304=\203\303\242b\210\352\304\300\242\"\210/\203\305`\240\210*\266)\305\242\203\305\242b\210*\210\353\207" [((mouse-2 (#<window 73 on *ein:notebooklist 8888*> 46 (61 . 92) 597075002 nil 46 (6 . 4) nil (7 . 16) (9 . 19)))) (down-mouse-1 (#<window 73 on *ein:notebooklist 8888*> 46 (61 . 92) 597074914 nil 46 (6 . 4) nil (7 . 16) (9 . 19))) (mouse-1 down-mouse-1) (46) (link :args nil :value "New Notebook" :notify (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--)) :button-overlay #<overlay from 40 to 54 in *ein:notebooklist 8888*> :from #<marker (moves after insertion) at 40 in *ein:notebooklist 8888*> :to #<marker at 54 in *ein:notebooklist 8888*>) (nil) internal--before-save-selected-window funcall make-byte-code 0 "\301\300!\207" vconcat vector [internal--after-save-selected-window] 2 "\n\n(fn)" select-window event-start posn-point widget-get :button-overlay :pressed-face overlay-get face mouse-face "\303\300\304\301#\210\303\300\305\302#\207" [overlay-put face mouse-face] 4 overlay-put widget-apply :mouse-down-action t widget-button-release-event-p read-event mouse-movement throw button-press-cancelled (switch-frame select-window) scroll-bar-movement widget-event-point get-char-property button widget-apply-action nil widget-button-pressed-face track-mouse unread-command-events widget-button-click-moves-point] 14 "\n\n(fn)"]()
>   funcall(#[0 "\306 r\307\310\311\312\313\314!\315\"\316\317%DC\216\320\321\300\242!\211@\262!\210\212\322\321\300\242!!b\210\323\304\324\"\323\304\325\"\2065,\326\327\"\326\330\"\307\310\311\331\313\314	#\332\"\333\317%DC\216\212\203c\334\327#\210\334\330#\210\335\304\336\300\242#\204\351\337-\340\300\242!\204\350\300\341 \240\210\302\203\232\300\242\211\242\342=\262\203\232\300\242.B.\300\301\240\210\343\344\337\"\210\300\242\250\204o\300\242@\345>\204o\300\242@\346=\204o\303\347\300\242!\240\210\303\242\203\331\350\303\242\351\"\304=\203\331\203o\334\327#\210\334\330#\210\202o\334\327#\210\334\330#\210\202o)\303\242\203\350\303\242\351\"\304=\203\303\242b\210\352\304\300\242\"\210/\203\305`\240\210*\266)\305\242\203\305\242b\210*\210\353\207" [((mouse-2 (#<window 73 on *ein:notebooklist 8888*> 46 (61 . 92) 597075002 nil 46 (6 . 4) nil (7 . 16) (9 . 19)))) (down-mouse-1 (#<window 73 on *ein:notebooklist 8888*> 46 (61 . 92) 597074914 nil 46 (6 . 4) nil (7 . 16) (9 . 19))) (mouse-1 down-mouse-1) (46) (link :args nil :value "New Notebook" :notify (lambda (&rest --cl-rest--) (apply (quote #[(G82449 G82450 &rest ignore) "\303\304H	>\204\305\306\307\310#\210\311H\nJ\"\207" [ein:%notebooklist% cl-struct-ein:$notebooklist-tags G82449 ein:notebooklist-new-notebook 0 error "%s accessing a non-%s" ein:$notebooklist-url-or-port ein:$notebooklist 1] 5]) (quote --default-kernel--) (quote --kernels--) --cl-rest--)) :button-overlay #<overlay from 40 to 54 in *ein:notebooklist 8888*> :from #<marker (moves after insertion) at 40 in *ein:notebooklist 8888*> :to #<marker at 54 in *ein:notebooklist 8888*>) (nil) internal--before-save-selected-window funcall make-byte-code 0 "\301\300!\207" vconcat vector [internal--after-save-selected-window] 2 "\n\n(fn)" select-window event-start posn-point widget-get :button-overlay :pressed-face overlay-get face mouse-face "\303\300\304\301#\210\303\300\305\302#\207" [overlay-put face mouse-face] 4 overlay-put widget-apply :mouse-down-action t widget-button-release-event-p read-event mouse-movement throw button-press-cancelled (switch-frame select-window) scroll-bar-movement widget-event-point get-char-property button widget-apply-action nil widget-button-pressed-face track-mouse unread-command-events widget-button-click-moves-point] 14 "\n\n(fn)"])
>   widget-button-click((down-mouse-1 (#<window 73 on *ein:notebooklist 8888*> 46 (61 . 92) 597074914 nil 46 (6 . 4) nil (7 . 16) (9 . 19))))
>   call-interactively(widget-button-click nil nil)
>   command-execute(widget-button-click)

**Comment by millejoh** [comment]
PR #135 fixed this the other day, if you are downloading through MELPA I would check back and see if the update has made its way through the system.

**Comment by nwieder** [comment]
I experienced the same issue and it was fixed after updating ein through MELPA. Thanks

**Comment by mukuact** [comment]
Thanks!
This problem was fixed after updating ein through MELPA.
