### ISSUE TITLE
undo doesn't work

### ISSUE THREAD

**Issue by adrsta** [millejoh/emacs-ipython-notebook#139]
it that normal?

## Description of the problem you have
Undo doesn't work

## Steps to reproduce the problem
1. modify an input cell
2. excecute the input cell
3. try to undo

## Expected output
modification of the input cell are reverted

## Your EIN configuration (in .emacs.d/init.el or somewhere else)
default spacemacs configuration:
https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/ipython-notebook/packages.el

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):
5.1.0

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):
anaconda navigator

3. What is your IPython notebook port number or URL?:
8.8.8.8

## System info:

```cl
("EIN system info"
 :emacs-version "GNU Emacs 25.1.1 (x86_64-w64-mingw32)
 of 2016-09-17"
 :emacs-bzr-version nil
 :window-system w32
 :emacs-variant nil
 :os
 (:uname nil
         :lsb-release nil)
 :image-types
 (svg png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (svg png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.12.0"
           :source-dir "c:/Users/kordian/.emacs.d/elpa/ein-20161123.1034/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/elpa/websocket-20161113.1736/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.5")
  (:name "request"
         :path "~/.emacs.d/elpa/request-20161121.600/request.elc"
         :featurep t
         :version-var request-version
         :version "0.2.0")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20161029.643/auto-complete.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20161029.643/auto-complete.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/elpa/popup-20160709.729/popup.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "python"
         :path "c:/Portables/emacs/share/emacs/25.1/lisp/progmodes/python.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "helm"
         :path "~/.emacs.d/elpa/helm-core-20161113.908/helm.elc"
         :featurep nil
         :version-var nil
         :version nil)))
```

**Comment by millejoh** [comment]
It is experimental, but try setting `ein:worksheet-enable-undo` to `Full`. This was originally implemented by tkf, and his note for this configuration is as follows:

       Enable full undo in notebook buffers.  It is powerful but
       sometime (typically after the cell specific commands) undo
       mess up notebook buffer.  Use it on your own risk.  When the
       buffer is messed up, you can just redo and continue editing,
       or save it once and reopen it if you want to be careful.

I don't think it will corrupt your notebook (i.e. make it unreadable in EIN or the web interface) but keep a backup around just in case.

**Comment by millejoh** [comment]
I finally got around to checking this myself and this solution doesn't really work. This is a popular one, also mentioned in #151. I have an idea for a solution, but it may take some time to implement. Certainly would be good to have this since it is also supported in the web interface so I will try to give this one some priority.

**Comment by millejoh** [comment]
EIN supports undo better now, though not perfectly. I'm going to close this out, but if you encounter a specific issue with undo do create a new issue with the details of what is happening.
