### ISSUE TITLE
When using "%gui qt" for interactive GUI programming, creating an additional QApplication breaks the session. The problem persists across kernel restart through EIN.

### ISSUE THREAD

**Issue by BeauRugHill** [millejoh/emacs-ipython-notebook#140]
Hi!

I'm trying to get into doing interactive GUI and visualization work with PyQtGraph.
I have hit a problem that breaks the IPython  session worse than I'm used to seeing:
The PyQtGraph examples contain "QtGui.QApplication([])" and on on an attempt to run them after "%gui qt" it fails. The  terminal associated with the IPython notebook shows the message "QCoreApplication::exec: The event loop is already running".
After this has occurred no further inputs evaluate (permanent status [*] ) and what's more, in EIN some aspects of the problem persists even after requesting (and getting) a kernel restart. After the restart "%gui qt" will by itself be sufficient for no more inputs to be successfully evaluated.
Manually killing "ipython notebook" in the terminal and starting it again shows the same problem. 

Restarting Emacs does seem to reset the session to the original state, of being able to evaluate other cells after "%gui qt", until broken again by a call to "QtGui.QApplication([])"
By contrast the standard IPython Notebook does not appear to suffer the same persistence of the error, and there it is sufficient to request a kernel restart to once again be able to evaluate other cells after "%gui qt" until the session is broken again by a call to "QtGui.QApplication([])".

My understanding is that there should only be one QApplication per program and trying to create an additional one could reasonably be expected to fail. It would of course be desirable that such a failure would be more graceful than blocking all further evaluations and necessitating a kernel restart.

For EIN in particular, the problem persisting over kernel restarts seems to me to suggest that something should be reset on kernel restart in addition to what is already being done.

**Comment by millejoh** [comment]
Only 2.5 year turnaround on this one, but this appears to be an IPython issue, not ein as I can get similar behavior from the command line, bypassing the use of emacs and ein altogether.
