### ISSUE TITLE
Emacs hangs opening notebooks

### ISSUE THREAD

**Issue by pstch** [millejoh/emacs-ipython-notebook#141]
I recently updated to Emacs 25, and now one of my notebooks makes Emacs hang when opening. It stays at 100% CPU until I close Emacs (or get out with `C-g` and luck), and the interface is not responsive at all.

Usually, the UI hangs just after I hit `[Open]` in the notebook list, I just have time to see `Can't guess python-indent-offset, using defaults: 4`. Sometimes it only hangs later, after a simple `C-n` keystroke.

Most of the time, I can "get out" of the hang by repeatedly spamming `C-g`, and after that the notebook will not hang anymore (and `ein` works properly). Just after the `C-g` succeeds, I see this line in `*Messages`:

    Error during redisplay: (jit-lock-function 1579) signaled (error "Error in syntax_table logic for to-the-end intervals")

I tried enabling `ein:dev-start-debug`, but it does not show more information.

**Comment by millejoh** [comment]
Can you share a copy of the offending notebook?

**Comment by millejoh** [comment]
Fingers crossed that a year and a half later ein is a bit more stable and performant...
