### ISSUE TITLE
Unicode Character encoding is buggy. Can't save file.

### ISSUE THREAD

**Issue by uroybd** [millejoh/emacs-ipython-notebook#142]
Hi,
Problem is, It is working fine when I am using Jupyter from browser. But, in ein I am unable to save file if I have Non-latin character in markdown. So I dug a little. There is something wrong with the JSON Request from ein. For example if I write **'না'** (which is 'No' in Bengali) browser send **b'\xe0\xa6\xa8\xe0\xa6\xbe'** for it but ein is sending **b'\xa8\xbe'** for it.

**Comment by millejoh** [comment]
Good news is that at least the character is displayed correctly in EIN and seems to be trasmitted correctly over the wire to Python (i.e. `'না'.encode('utf-8')` generates the correct byte sequence). 

I get an error when I try to save a notebook with this line of code in it however, so I think this may not be a bug with EIN, but rather with `json-encode`.

I will have to do some more testing to see if that is the case.

**Comment by uroybd** [comment]
I also think so. I saw notebook-to-json debug buffer and it is ok. Either
it is about `json-encode` or the request library of emacs.

উৎসব রায় (Utsob Roy)
Code Maestro
Codjuro IT Solution.

https://uroybd.github.io

**Comment by millejoh** [comment]
@uroybd - Let me know if this latest commit works for you.

**Comment by uroybd** [comment]
It is fixed! :)
