### ISSUE TITLE
Messed up indentation

### ISSUE THREAD

**Issue by uroybd** [millejoh/emacs-ipython-notebook#143]
As far as I know ein uses python mode. So first of all I am using standard settings for python mode. But indentation is messy. Consider this snippet:
```
a = [1,2,3,4]
for i in a:
    if i % 2 == 0:
        print("Even")
```
When I am writing this Emacs naturally control the indentation. But here things are getting messed up. In first level indentation is all space and in second level it is tab. And not also 2 tabs for two level but a single tab. Did I missed any settings?

**Comment by uroybd** [comment]
Solved it out by explicitly setting `indent-tabs-mode` to `nil` for `ein:notebook-mode`. It would be nice if you make it default. :)

**Comment by millejoh** [comment]
Good news... What is your setting for the customizable variable `ein:notebook-modes`? This also partially explains why I have never been able to recreate this problem as my `indent-tabs-mode` is set to `nil`, though I am at a loss to explain why that is so for me and not others.

**Comment by uroybd** [comment]
This is my current `ein` related configuration:
```
(add-hook 'ein:ein-mode-hook
	  (lambda ()
	    (setq-default indent-tabs-mode nil)
	    (setq-default tab-width 4)
	    (setq-default py-indent-tabs-mode nil)
	    (add-to-list 'write-file-functions 'delete-trailing-whitespace)))

(add-hook 'ein:notebook-mode-hook
	  (lambda ()
	    (setq indent-tabs-mode nil)))
```

**Comment by millejoh** [comment]
I am actually curious if `ein:notebook-modes` (the `s` is significant) is set to something like `ein:notebook-multilang-mode` or `ein:notebook-python-mode`. I am not sure if means anything significant, but more data is generally good.

**Comment by millejoh** [comment]
With the latest commit I force `indent-tabs-mode` to nil; I'm not sure if I need to be more clever with this (like only set when `ein:notebook-multilang-mode` is active).

**Comment by uroybd** [comment]
Nice! I think it is good how you have done for now. :)
