### ISSUE TITLE
RFE: before save hook

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#145]
I have
```
(add-hook 'before-save-hook 'delete-trailing-whitespace)
```
in my `.emacs` and, of course, `ein` ignores it.
is there a hook which I could add `delete-trailing-whitespace` to?

**Comment by millejoh** [comment]
Sam - I could add a `(run-hooks 'before-save-hook)` before converting the notebook buffer to JSON and saving to jupyter using the contents API. Note that calling `delete-trailing-whitespace` generates 'Text is read only' warning, but otherwise seems to work.

That commit should go up soon, let me know how it works. Long term I think the right thing is to get notebook/worksheet buffers to behave more like normal text buffers and have that hook work automagically.

**Comment by sam-s** [comment]
John - I fixed the "ro error" in the emacs git master.
I agree that TRT is making the normal emacs save facilities work with notebooks, see my other report https://github.com/millejoh/emacs-ipython-notebook/issues/130
You might consider ignoring this one in favor of 130 if 130 is to be fixed soon.
thanks!

**Comment by flamingbear** [comment]
@millejoh Actually, I'm getting the 'Text is read only' warning, but I can't save the notebook any longer.

**Comment by flamingbear** [comment]
Is there something I can to do get better logs.

in my *messages* buffer I'm getting
```
ein: [info] Opened notebook list at http://dev.seaice.savoie.dev.int.nsidc.org:8888/ with path matt-scratch
run-hooks: Text is read-only [3 times]
No server editing buffers exist
C-x C-# is undefined
This notebook has unsaved changes. Discard those changes? (y or n) y
```

**Comment by sam-s** [comment]
`delete-trailing-whitespace` fails on RO text properties (I fixed that in gnu emacs git tree - but it has not been released yet).

**Comment by flamingbear** [comment]
@sam-s, 

Thanks, that's what I get for not reading all of the messages carefully.  I just finished putting together a bug report to ask how to debug this.  I'll see if removing `delete-trailing-whitespace` in my hooks will solve this for now.

Matt

**Comment by MC-Escherichia** [comment]
I just opened Issue #155 before reading this. Not adding `delete-trailing-whitespace` to my `before-save-hook` in my init file fixes the issue for now.

**Comment by nilsdeppe** [comment]
Here's a solution that allows trailing whitespace to be deleted in other modes but not in EIN

```
(add-hook 'before-save-hook
          (lambda ()
            (when (not (derived-mode-p 'ein:notebook-multilang-mode))
              (delete-trailing-whitespace))))
```
