### ISSUE TITLE
bug: C-c C-n is broken

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#146]
When I hit `C-c C-n` (`ein:worksheet-goto-next-input`), the point is positioned between `I` and `n` in the next `In [...]`.
However, then hit `C-c C-n` the _second_ time, **nothing happens** - the point does not move.

1. `C-c C-p` does not have this problem - repeated keypresses move point up.
1. The positioning between `I` and `n` seems wrong anyway - the point should go to the beginning of the text area, not its header.

**Comment by sam-s** [comment]
I don't know what happened, by now it works fine.
same notebook, same session.
please keep open, I may try to investigate...

**Comment by sam-s** [comment]
... and we are back in trouble (same notebook &c)...

**Comment by millejoh** [comment]
`ein:worksheet-goto-next-input` must be getting confused on what the current ewoc node is (or maybe there is no ewoc node associated where the point is located?), though how that is happening is beyond me. It shouldn't depend on what kernel is running, but may have something to do with what is in the notebook.

Is the problem with just the one notebook, or does it also occur in others?

**Comment by sam-s** [comment]
so far just one, cannot reproduce it reliably.
can you suggest what to look at specifically when the problem resurfaces?
thanks!

**Comment by sam-s** [comment]
How to reproduce: when I hit `C-x C-n` (by mistake, instead of `C-c C-n`), I set `goal-column`.
When the goal column is set, I observe the broken behavior. 
When I unset the goal column with `C-u C-x C-n`, the correct behavior is resumed.
The cause is that `ewoc-goto-node` respects `goal-column`.
Solution: binf `goal-column` to `nil` in `ein:cell-goto` around the call to `ewoc-goto-node`.
I will create a pull request shortly.
