### ISSUE TITLE
ein:notebooklist-open fails with json-readtable-error

### ISSUE THREAD

**Issue by nbecker** [millejoh/emacs-ipython-notebook#147]
emacs 25.1.1 (spacemacs)
jupyter-4.2.1

[verbose] Error thrown: (json-readtable-error) @#<buffer debug-ein.el>
[error] Content list call http://127.0.0.1:8888/api/contents/ failed with status parse-error. @#<buffer debug-ein.el>

**Comment by millejoh** [comment]
How do you start the jupyter notebook? Also, what is the output in the console where the notebook server is running?

**Comment by millejoh** [comment]
In jupyter notebook [4.3.0](http://jupyter-notebook.readthedocs.io/en/latest/changelog.html#release-4-3) token [authentication ](http://jupyter-notebook.readthedocs.io/en/latest/security.html#server-security) is enabled by default.

EIN doesn't directly support tokens, yet, but there are a couple ways around this:

1) Set a password via the setting for `c.NotebookApp.password` and instead of calling `ein:notebooklist-open` first call `ein:notebooklist-login`, supply the password, then call `ein:notebooklist-open`.

2) Completely disable token authentication by setting both 'c.NotebookApp.token' and 'c.NotebookApp.password' to ''.

**Comment by nbecker** [comment]
unfortunately, it seems ein:notebooklist-login is not defined

**Comment by millejoh** [comment]
And after a bit more investigation, you can call `ein:notebooklist-login` and use as the password the token jupyter logs to the terminal when starting up.

If you can't find `ein:notebooklist-login` then something is wrong with your installation. Are you installing from MELPA? Two things to try:

1. Reinstall EIN.
2. Call `ein:byte-compile-ein`.

**Comment by nbecker** [comment]
I am using spacemacs, ipython-notebook layer.  In any case, I just did M-x load-library ein-notebooklist.

But after putting
c.NotebookApp.password = 'mypassword'

In
 ~/.ipython/profile_default/ipython_config.py

and restarting
$ jupyter notebook

Then
ein:notebooklist-login

fails
ein: [info] Failed to login to 8888

All I see on console is
[nbecker@nbecker2 inroute-efficiency]$ [W 07:46:27.622 NotebookApp] 401 POST /login (127.0.0.1) 4.76ms referer=None


Is   ~/.ipython/profile_default/ipython_config.py the correct location?  Or does maybe this now go somewhere under ~/.jupyter?

**Comment by nbecker** [comment]
OK, I got it:
1. jupyter notebook --generate-config
2. $ipython
In [1]:         from notebook.auth import passwd
In [2]:         passwd()
3. copy hashed passwd into file generated by step 1

**Comment by nbecker** [comment]
But it still doesn't work.  I can open a new notebook, but it doesn't connect with kernel

console says:
[I 07:59:08.152 NotebookApp] Kernel started: 0f3d5de5-1ff6-4ea8-937a-f3a4a50324c2
[W 07:59:08.241 NotebookApp] Couldn't authenticate WebSocket connection
[W 07:59:08.243 NotebookApp] 403 GET /api/kernels/0f3d5de5-1ff6-4ea8-937a-f3a4a50324c2/channels?session_id=163dfebd-c143-4f89-9dd5-0e619130f7a2 (127.0.0.1) 3.99ms referer=None

*ein:log-all* says
[warn] Kernel is not ready yet! (or closed already.) @#<buffer *ein: 8888/Untitled2.ipynb*>

**Comment by millejoh** [comment]
Thanks for all the comments - I have an idea now of what is going on, see #148.

**Comment by millejoh** [comment]
Commit 3fef68d0539c4f7c0a858b2eb114c863b368a0a0 may fix this - let me know when MELPA updates.

**Comment by nbecker** [comment]
I updated ein this morning.  Minimal testing appears to now work (I can open a new notebook, enter '1+1', C-c C-c, and I get a response).  Thanks!

**Comment by rambalachandran** [comment]
Ok I'm confused, where should I set the option `c.NotebookApp.password = 'mypassword'`. In which file?

**Comment by rambalachandran** [comment]
My bad I forgot to set the token to ''. Setting that made the trick
