### ISSUE TITLE
bug: matplotlib charts disappear from the buffer on notebook save or checkpoint

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#149]
just updated from git and now whenever I save the notebook or it is checkpointed, all charts disappear from it.
i.e., `C-c C-c` (run cell) creates them and they are gone the next minute.

**Comment by millejoh** [comment]
Believe `delete-trailing-whitespace` is the culprit here. EIN uses `insert-image` or `insert-sliced-image`. I think this because of the following.

> IMAGE is displayed by inserting STRING into the current buffer
> with a ‘display’ property whose value is the image.  STRING
> defaults to a single space if you omit it.
> AREA is where to display the image.  AREA nil or omitted means
> display it in the text area, a value of ‘left-margin’ means
> display it in the left marginal area, a value of ‘right-margin’
> means display it in the right marginal area.
> SLICE specifies slice of IMAGE to insert.  SLICE nil or omitted
> means insert whole image.  SLICE is a list (X Y WIDTH HEIGHT)
> specifying the X and Y positions and WIDTH and HEIGHT of image area
> to insert.  A float value 0.0 - 1.0 means relative to the width or
> height of the image; integer values are taken as pixel values.
> 

I'll send an update that should fix this very soon...

**Comment by sam-s** [comment]
alas, the problem is still there.

**Comment by millejoh** [comment]
What is in your `before-save-hook`? So far I haven't been able to reproduce except when calling `delete-trailing-whitespace`.

**Comment by sam-s** [comment]
```
before-save-hook
==> (delete-trailing-whitespace time-stamp)
```

**Comment by millejoh** [comment]
Still having this problem? Can you confirm that your version of `ein:insert-image` looks like the below:

```elisp
(defun ein:insert-image (&rest args)
  (let* ((img (apply #'create-image args)))
    (if ein:slice-image
        (destructuring-bind (&optional rows cols)
            (when (listp ein:slice-image) ein:slice-image)
          (insert-sliced-image img "." nil (or rows 20) cols))
      (insert-image img "."))))
```

**Comment by sam-s** [comment]
yes, indeed now that I pull the above code from git, the problem is solved.
thanks!
