### ISSUE TITLE
undo does not work after executing a cell

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#151]
after I run a cell, undo `C-/` no longer works:
```
user-error: No further undo information
```
even the browser interface supports undo after cell evaluation!

**Comment by millejoh** [comment]
I see the problem (I think) and have an idea of a solution. I think this will be my Christmas vacation project.

**Comment by millejoh** [comment]
Undo support should be improved with latest commit, 773d22c3656377280f0bac74ae68288c9b0b1613, though I have been wrong before.

I don't have undo for cell deletion, I will have to think about that some more.
