### ISSUE TITLE
obsolete json code?

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#153]
`json-encode-char` is not defined in modern emacs; only `json-encode-string` is:
```
2015-03-22  Dmitry Gutov  <dgutov@yandex.ru>

	* json.el (json-encode-char0): Delete this alias.
	(json-encode-string): Rewrite to improve performance (bug#20154).
	(json-encode-char): Fold into `json-encode-string'.
```

**Comment by millejoh** [comment]
I finally got around to deleting the defadvice's in ein a few commits ago; nothing has broken so far so I'm going to close this one out.
