### ISSUE TITLE
Cannot save notebook (Text is read-only)

### ISSUE THREAD

**Issue by MC-Escherichia** [millejoh/emacs-ipython-notebook#155]
I am experiencing a weird error with the latest version of ein and emacs 25.1.1

## Description of the problem you have

When I try to save a notebook, the message bar reads "Text is read-only" and the notebook doesn't save.

I've tried this with both remote and local notebooks and locally with an extremely simple notebook. 

## Steps to reproduce the problem

1. Open a notebook local or remote.
2. Make a change. Enter `C-x C-s`(ein:notebook-save-notebook-command)
3. "Text is read-only" appears in message buffer, changes aren't saved

## Expected output

It used to say notebook saved or something like that. 

## Your EIN configuration (in .emacs.d/init.el or somewhere else)

    (require 'ein)
    (require 'ein-notebook)
    (require 'ein-notebooklist)
    (require 'ein-jedi)
    (add-hook 'ein:notebook-multilang-mode-hook (lambda () (auto-complete-mode 1)))
    (require 'jedi)
    (add-hook 'ein:notebook-multilang-mode-hook 'ein:jedi-setup)
    (setq ein:console-executable "/usr/bin/jupyter-console")
    (setq ein:console-args '("--existing" ))

## Your IPython configuration

1. What is your IPython version? (run `jupyter-notebook --version`):
4.2.3
2. How do you start IPython? (e.g., ):
`jupyter-notebook --ip "*" --no-browser`
3. What is your IPython notebook port number or URL?:
8888 or mydomain.com:8888

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.5)
 of 2016-12-17"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux lewitt 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
"
  :lsb-release nil)
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend url-retrieve)
 :ein
 (:version "0.12.0"
		   :source-dir "/home/matt/.emacs.d/.cask/25.1/elpa/ein-20161218.2120/")
 :lib
 ((:name "websocket"
		 :path "~/.emacs.d/.cask/25.1/elpa/websocket-20161113.1736/websocket.elc"
		 :featurep t
		 :version-var websocket-version
		 :version "1.5")
  (:name "request"
		 :path "~/.emacs.d/.cask/25.1/elpa/request-20161121.600/request.elc"
		 :featurep t
		 :version-var request-version
		 :version "0.2.0")
  (:name "auto-complete"
		 :path "~/.emacs.d/.cask/25.1/elpa/auto-complete-20161029.643/auto-complete.elc"
		 :featurep t
		 :version-var nil
		 :version nil)
  (:name "auto-complete"
		 :path "~/.emacs.d/.cask/25.1/elpa/auto-complete-20161029.643/auto-complete.elc"
		 :featurep t
		 :version-var nil
		 :version nil)
  (:name "popup"
		 :path "~/.emacs.d/.cask/25.1/elpa/popup-20160709.729/popup.elc"
		 :featurep t
		 :version-var popup-version
		 :version "0.5.3")
  (:name "python"
		 :path "/usr/share/emacs/25.1/lisp/progmodes/python.elc"
		 :featurep t
		 :version-var nil
		 :version nil)
  (:name "python-mode"
		 :path "~/.emacs.d/.cask/25.1/elpa/python-mode-20161124.930/python-mode.elc"
		 :featurep nil
		 :version-var nil
		 :version nil)
  (:name "markdown-mode"
		 :path "~/.emacs.d/.cask/25.1/elpa/markdown-mode-20160928.932/markdown-mode.elc"
		 :featurep t
		 :version-var markdown-mode-version
		 :version "2.1")
  (:name "helm"
		 :path "~/.emacs.d/.cask/25.1/elpa/helm-core-20161215.1209/helm.elc"
		 :featurep t
		 :version-var nil
		 :version nil)))
```

**Comment by spencerahill** [comment]
I am trying to use EIN for the first time and am having the same problem.

**Comment by millejoh** [comment]
Do you have `delete-trailing-white`space in your `before-save-hooks`? There is a bug there, though a fix has been pushed I'm not sure when it will reach most users. In the meantime I will add a check to make sure this function isn't called. Until I can get to this I recommend you remove `delete-trailing-whitespace`.

**Comment by spencerahill** [comment]
@millejoh Very sorry, yes this was causing the problem.  I realized that right after posting the comment, so I then deleted it.  But you must have gotten the notification anyways -- I should have edited the comment first to state that I had solved it, and then deleted it.  Thanks anyways!

(Maybe closing this issue would help prevent people making the same mistake in the future?)

**Comment by flamingbear** [comment]
John, 

Is there a hook I could use to remove my delete-trailing-whitespace only for notebook buffers?

Matt

**Comment by millejoh** [comment]
My latest commit wraps the `run-hooks` call in a `condition-case`. In the case of error it will print out a scary looking message, but will still try to save the notebook. Go ahead and add back in `delete-trailing-whitespace` and let me know how it works. Only one caveat - if one of the functions in your before-save-hook errors than there is no guarantee that any of the other hooks will be run.

**Comment by flamingbear** [comment]
Thanks, I'll let you know.
Matt

**Comment by edVonSchleck** [comment]
I had the same problems (Text is read only) until a few days ago. Now saving works again.
However, every time the notebook is saved the buffer switches to a Warnings buffer saying:

Warning (emacs): Error running save hooks: ’Text is read-only’. I will still try to save the notebook.

How can I disable displaying this message?

Ed

**Comment by millejoh** [comment]
Okay - I'll send the message to *ein:log-all* instead. Hopefully that will not trigger the annoying buffer-switching behavior.

**Comment by edVonSchleck** [comment]
Thanks. I'll get back to you if it does not work.


2017-01-29 18:45 GMT+01:00 John Miller <notifications@github.com>:

**Comment by reconmaster** [comment]
I'm experiencing the same behavior as well. I too had
`delete-trailing-whitespace` enabled before save with Emacs 25.

Here's system info (similar):

```
("EIN system info" :emacs-version "GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.7)\n of 2017-02-07" :emacs-bzr-version nil :window-system x :emacs-variant nil :os
 (:uname "Linux boxname 4.4.52-1-lts #1 SMP Sun Feb 26 19:45:38 CET 2017 x86_64 GNU/Linux\n" :lsb-release nil)
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend url-retrieve)
 :ein
 (:version "0.13.0" :source-dir "/home/reconmaster/.emacs.d/elpa/ein-20170224.1115/")
 :lib
 ((:name "websocket" :path "~/.emacs.d/elpa/websocket-20161113.1736/websocket.elc" :featurep t :version-var websocket-version :version "1.5")
  (:name "request" :path "~/.emacs.d/elpa/request-20170131.1747/request.elc" :featurep t :version-var request-version :version "0.3.0")
  (:name "auto-complete" :path "~/.emacs.d/elpa/auto-complete-20170124.1845/auto-complete.elc" :featurep t :version-var nil :version nil)
  (:name "auto-complete" :path "~/.emacs.d/elpa/auto-complete-20170124.1845/auto-complete.elc" :featurep t :version-var nil :version nil)
  (:name "popup" :path "~/.emacs.d/elpa/popup-20160709.729/popup.elc" :featurep t :version-var popup-version :version "0.5.3")
  (:name "pos-tip" :path "~/.emacs.d/elpa/pos-tip-20150318.813/pos-tip.elc" :featurep t :version-var pos-tip-version :version "0.4.6")
  (:name "python" :path "/usr/share/emacs/25.1/lisp/progmodes/python.elc" :featurep t :version-var nil :version nil)
  (:name "markdown-mode" :path "~/.emacs.d/elpa/markdown-mode-20161222.1416/markdown-mode.elc" :featurep t :version-var markdown-mode-version :version "2.1")
  (:name "helm" :path "~/.emacs.d/elpa/helm-core-20170223.2326/helm.elc" :featurep t :version-var nil :version nil)))
```

When I try to save with the `delete-trailing-whitespace` enabled
before save, I get a dump of the entire notebook in the *Messages*
buffer. The particular notebook I was testing with was rather large
and had images, so I had some memory issues with emacs trying to
navigate back up the buffer. Perhaps there would be a cleaner way to
warn if not saving in the *Messages* buffer?

Here is the top part of the dump when I try to save before the whole
JSON file ends up in *Message*

```
This notebook has unsaved changes. Discard those changes? (y or n) n
Contacting host: localhost:9999
ein: [info] Opened notebook list at https://localhost:9999 with path
ein: [warn] Error running save hooks: 'Text is read-only'. I will still try to save the notebook.
Contacting host: localhost:9999
url-http-create-request: Multibyte text in HTTP request: PUT /api/contents/python/data/calcs.ipynb HTTP/1.1
MIME-Version: 1.0
Connection: keep-alive
Extension: Security/Digest Security/SSL
Host: localhost:9999
Accept-encoding: gzip
Accept: */*
User-Agent: URL/Emacs
Cookie: cookie stuff
Content-length: 537701
```

After disabling the save hook, it seems to be performing reasonably well.

**Comment by lukeorland** [comment]
I added this to my .spacemacs in `(defun dotspacemacs/user-config () ... )`

``` elisp
  (add-hook 'ein:notebook-multilang-mode-hook
            #'(lambda () (spacemacs/toggle-whitespace-cleanup-off)))
```

to disable the automatic whitespace cleanup in the notebook buffer. Saving seems to work now.
