### ISSUE TITLE
Accessing a newly created jupyter kernerl through ein

### ISSUE THREAD

**Issue by rambalachandran** [millejoh/emacs-ipython-notebook#156]
Here is a document [link](http://www.alfredo.motta.name/create-isolated-jupyter-ipython-kernels-with-pyenv-and-virtualenv/) that describes how to create a new kernel in jupyter notebook for every virtualenv. This in turn can enable us to use a single ipython (jupyter) installation for various virtualenvs. My question is, is it possible to change the kernel behavior in ein and if so how can this be achieved?

**Comment by millejoh** [comment]
Unless I am understanding you incorrectly, ein already supports multiple kernels. See the command `ein:notebook-switch-kernel`.
