### ISSUE TITLE
what to do with stale connections?

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#160]
When I come back to the notebook in the morning and try to evaluate a cell, I get this error:
```
Debugger entered--Lisp error: (websocket-closed . [cl-struct-websoc
  signal(websocket-closed [cl-struct-websocket-frame text "{\"heade
  websocket-send(#1=[cl-struct-websocket open #4=[cl-struct-ein:$we
  websocket-send-text(#1=[cl-struct-websocket open #4=[cl-struct-ei
  ein:websocket-send(#1=[cl-struct-ein:$websocket [cl-struct-websoc
  ein:websocket-send-shell-channel(#4=[cl-struct-ein:$kernel 8888 #
  ein:kernel-execute(#4=[cl-struct-ein:$kernel 8888 #9=[eieio-class
```
`jupyther` reports
```
[W 11:41:37.127 NotebookApp] Replacing stale connection: 8b947c5b-bf8d-4276-b4b9-7473bfd889ce:d3146b8a-d4a6-49b0-9b41-4c89eeb6f847
```
how do I reset `ein`?
the only way I see so far is killing all the `ein` buffers and starting everything from scratch.
Is there a better way?

**Comment by millejoh** [comment]
Just to confirm, executing `ein:notebook-restart-kernel-command` does nothing to fix the problem?

**Comment by sam-s** [comment]
I don't want to restart the kernel.
I want to restart my connection.

**Comment by millejoh** [comment]
Okay - try `ein:notebook-reconnect-kernel`.
