### ISSUE TITLE
Smart tab indentation not working

### ISSUE THREAD

**Issue by lev-kusanagi** [millejoh/emacs-ipython-notebook#161]
Hi @millejoh,

Running emacs 25.1.1, using zeroin.el with emacs -Q -l lisp/zeroein.el as you suggest in your bug report template, all .elc files in the ein directory and its dependencies having been deleted and emacs restarted, hitting tab inside a notebook buffer just inserts a tab.

Is this expected? How could I have smart tab indentation upon pressing tab?

iPython version is 5.1.0.

Thank you, and thanks for this phenomenal client.

NB. Additional system info from M-x ein:dev-bug-report-template

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 25.1.1 (x86_64-apple-darwin16.1.0, Carbon Version 157 AppKit 1504.6)
 of 2016-11-15"
 :emacs-bzr-version nil
 :window-system mac
 :emacs-variant nil
 :os
 (:uname
  "Darwin Levs-MacBook-Pro.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
"
  :lsb-release nil)
 :image-types
 (svg image-io imagemagick png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (svg image-io imagemagick png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.12.0"
	   :source-dir "/Users/javier/.emacs.d/elpa/ein-20161205.1432/")
 :lib
 ((:name "websocket"
	 :path "~/.emacs.d/elpa/websocket-20161113.1736/websocket.elc"
	 :featurep t
	 :version-var websocket-version
	 :version "1.5")
  (:name "request"
	 :path "~/.emacs.d/elpa/request-20161221.1711/request.elc"
	 :featurep t
	 :version-var request-version
	 :version "0.2.0")
  (:name "auto-complete"
	 :path "~/.emacs.d/elpa/auto-complete-20161029.643/auto-complete.elc"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "auto-complete"
	 :path "~/.emacs.d/elpa/auto-complete-20161029.643/auto-complete.elc"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "popup"
	 :path "~/.emacs.d/elpa/popup-20160709.729/popup.elc"
	 :featurep t
	 :version-var popup-version
	 :version "0.5.3")
  (:name "python"
	 :path
	 "/usr/local/Cellar/emacs-mac/emacs-25.1-z-mac-6.1/share/emacs/25.1/lisp/progmodes/python.elc"
	 :featurep t
	 :version-var nil
	 :version nil)))
```

**Comment by millejoh** [comment]
Yes, I am slow, sorry for that. I'm surprised and pleased that zeroein.el works for you.

What is the setting of `ein:notebook-modes`? When Multi-lang is enabled it mostly does the right thing when editing cells. If you set it to Python then editing should be even better for Python code, but editing Markdown will be more painful.

Another option is to call `C-'` on a cell which will open a dedicated buffer, similar to what org-mode implements for editing source code blocks.

**Comment by lev-kusanagi** [comment]
Oh not at all, I'm really thankful for your software, I use it everyday. I wish I could help, I'm sorry that I can't.

I can't seem to open any notebooks at this moment*, but I'll respond to your questions as soon as I'm capable.

Forgive my late replies, I wasn't receiving email notifications.

* I'm getting: 
"Error (wrong-type-argument number-or-marker-p ein: [warn] Null value passed to ein:get-ipython-major-version.) on query contents, try calling ‘ein:notebooklist-login‘ first..."
but if I don't figure that out, I should probably open another issue.

**Comment by lev-kusanagi** [comment]
This seems to have been resolved, thank you.
PS: The current version is very cool.
