### ISSUE TITLE
Missing xsrf token

### ISSUE THREAD

**Issue by aagaard** [millejoh/emacs-ipython-notebook#162]
With Jupyter notebook 4.3.1 I get following problem:
 
`[W 17:14:25.734 NotebookApp] 403 POST /login (127.0.0.1): '_xsrf' argument missing from POST`

And ein cannot connect to the kernel. It seems that header needs a 'X-XSRFToken' field with the xsrf token in the cookie.

**Comment by lwoloszy** [comment]
I'm getting the same error.

**Comment by millejoh** [comment]
After reading the latest [blog](https://blog.jupyter.org/2016/12/21/jupyter-notebook-4-3-1/) post I was afraid something like this would happen. I'll make it a priority to fix this, but for the time being your best option is to probably go back to v4.3.0.

**Comment by millejoh** [comment]
I'm getting kind of good at this - fix should be going up now. I expect MELPA will update within the next few hours.

**Comment by aagaard** [comment]
It works! Thanks for the great work!
