### ISSUE TITLE
Better org babel output

### ISSUE THREAD

**Issue by Yevgnen** [millejoh/emacs-ipython-notebook#164]
Currently the org babel output is truncated and put into a org table. Personally I think it would be nice to have more friendly output of the evaluation.

<img width="626" alt="screen shot 2017-01-17 at 10 48 40 pm" src="https://cloud.githubusercontent.com/assets/16749790/22025038/1ec1aa6c-dd07-11e6-9358-3dae01a69c00.png">

**Comment by millejoh** [comment]
Some recent updates try to do this better, let me know what you think.

**Comment by Yevgnen** [comment]
Thanks for your works. The output looks much better than before. For me, having a output like in *.ipynb is enough. But the inline image seems can not be displayed correctly. The example in the document alerts
<img width="499" alt="screen shot 2017-01-30 at 1 20 51 pm" src="https://cloud.githubusercontent.com/assets/16749790/22413009/0e6f501e-e6ef-11e6-8029-b2220b663f01.png">

```
#+BEGIN_SRC ein :session 8888/Untitled.ipynb :image output.png
    import matplotlib.pyplot as plt
    import numpy as np
    x = np.linspace(0, 1, 100)
    y = np.random.rand(100,1)
    print(x)
    %matplotlib inline
    plt.plot(x,y)
#+END_SRC
```

under an org mode `Org mode version 9.0.4` from elpa and Emacs `GNU Emacs 25.1.1 (x86_64-apple-darwin16.3.0, Carbon Version 157 AppKit 1504.76) of 2017-01-14`.

**Comment by millejoh** [comment]
Apparently my workaround needs another workaround. Handling image output has been more challenging than I thought. The `:image` header argument is not official and  is a workaround for a problem I encountered trying to implement image output. 

I take the same route as ob-ipython, which is to save images to file and then return a link to the file. I originally used the `:file` argument, but this did not always work so a workaround ob-ein looks for an `:image` header argument that specifies a file to save the image to.

Obviously the image header is being specified, but somehow the code is not seeing it. I will see what I can find...

**Comment by millejoh** [comment]
Silly me - ob-ein is looking for an `:images` header argument, not `:image`. I'm not at my development machine, but I will try to push a fix as soon as I can.

**Comment by Yevgnen** [comment]
I'm so glad to see this and thanks for your work. I've checked the latest version on elpa and I have one more question. 

Without any other output, the image file link looks like 
<img width="351" alt="screen shot 2017-02-02 at 8 40 30 pm" src="https://cloud.githubusercontent.com/assets/16749790/22549997/f1daef52-e988-11e6-9102-39e50b671123.png">

while with some system output the image file link looks like
<img width="402" alt="screen shot 2017-02-02 at 8 47 04 pm" src="https://cloud.githubusercontent.com/assets/16749790/22549966/cea381d4-e988-11e6-95f8-89c0f71585f6.png">

Is it possible to turn both into 
<img width="435" alt="screen shot 2017-02-02 at 8 41 51 pm" src="https://cloud.githubusercontent.com/assets/16749790/22549877/77fdce16-e988-11e6-95b1-ae1f9d70c8fc.png">
namely, the file link is seperated so that one can use `C-c C-x C-v` (`org-toggle-inline-images`) to show the inline image? It would also nice to ignore things like `[<matplotlib.lines.Line2D at 0x118c69780>]`.😁
