### ISSUE TITLE
how to use juypter after installing anaconda(including juypter) in emacs 25

### ISSUE THREAD

**Issue by jameswq** [millejoh/emacs-ipython-notebook#165]
hi , so i just installed anaconda(including juypter), but my development is emacs 25,so i dont know how to config juypter notebook in my emacs, how to do with emacs-ipython-notebook? thanks advanced.

**Comment by millejoh** [comment]
The easiest way to get ein running is to install it from [MELPA](https://melpa.org/#/ein). This will ensure all of ein's dependencies are correctly installed. If you are using spacemacs you can enable the [ipython-notbook](http://spacemacs.org/layers/+lang/ipython-notebook/README.html) layer and it will do much the same thing, plus configure keybindings that might feel more natural for vim users.

Next open a shell and call `jupyter notebook` wherever you want to work. If you are running current versions of jupyter note that they have [token authentication](https://blog.jupyter.org/2016/12/21/jupyter-notebook-4-3-1/) enabled by default so you will need to note that jupyter generates on starting up - see the blog entry I linked to for details on where to find the token.

Once you have found and copied the token go back to emacs and do the following:

1. Call `M-x ein:notebooklist-login`. Specifiy the port you are running the jupyter notebook on, then supply the token you previously copied as the password.
2. Assuming everything goes well you can then call `M-x ein:notebooklist-open`, select the appropriate port or url, and go from there. Hopefully at this point things should look familiar enough to use!

There is some documentation [available](http://millejoh.github.io/emacs-ipython-notebook/). It isn't perfect, but it describes the system accurately enough that you should be able to figure out how to do things.

Hope that helps, and good luck!

**Comment by millejoh** [comment]
Before I close this wanted to point out you can automate a lot of this now by calling `ein:jupyter-start`. Happy Python-ing!
