### ISSUE TITLE
XSRF cookie does not match POST argument

### ISSUE THREAD

**Issue by lev-kusanagi** [millejoh/emacs-ipython-notebook#168]
With Jupyter Notebook 4.3.1 and the latest version of EIN from melpa, I get the following error :
[W 20:54:49.851 NotebookApp] 403 POST /login (127.0.0.1): XSRF cookie does not match POST argument
I cannot connect to the kernel.
Thanks in advance.

**Comment by millejoh** [comment]
Which request backend are you using (`C-h v request-backedn`)? It seems to be completely random which backend will work, curl or url-retrieve. For whatever reason I have a hard time getting url-retrieve to work as a backend, but for others it is the opposite, curl won't work!

Others things to check - where is request saving its cookie jar (`C-h v request-storage-directory`) and is that a place you have read/write access to? Also what are the contents of the cookie jar?

Good luck.

**Comment by lev-kusanagi** [comment]
I'm using curl as
request-backend. 'url-retrieve' hasn't worked either, it produces the
following error:
[W 07:13:06.238 NotebookApp] 403 POST /login (127.0.0.1): '_xsrf'
argument missing from POST

request-storage-directory is "~/.emacs.d/request

7za x curl-cookie-jar produces "Error: Can not open file as archive"
unzip curl-cookie-jar produces "unzip: cannot find zipfile directory in one of curl-cookie-jar or curl-cookie-jar.zip, and cannot find curl-cookie-jar.ZIP, period

I'll try to figure out how to look into curl-cookie-jar

**Comment by reconmaster** [comment]
I've run into this a few times as well using curl as my backend. If this occurs, I generally open ~/.emacs.d/request/curl-cookie-jar and remove the line for the host that is giving me the static.

After manually deleting that line, just restart the server and login again. If you have the curl-cookie-jar open in a buffer, you'll see the new cookie appear.

@lev-kusanagi that file is simple text, so you can just open it up with emacs. In general I've found that your best bet is try emacs on anything. It generally warns you if you land on a huge file.

@millejoh perhaps there would be a way to prompt the user if this occurs if they would like to delete the cookie for that server from the cookie jar? I would assume only one working cooking would be acceptable.

Incidentally, I noticed the cookie begins with #HttpOnly. Perhaps that form of cookie is the root of #182? I also realized that Apple has declared OpenSSL obsolete. The new abondendment of [SHA1](https://en.wikipedia.org/wiki/SHA-1#The_SHAppening) has led to some issues with gnu-tls and DigiCert using emacs w/ GitHub. I'll follow up with #182 when I figure out how to compile with openssl on OS X.
