### ISSUE TITLE
open session directly from EIN

### ISSUE THREAD

**Issue by Pitometsu** [millejoh/emacs-ipython-notebook#169]
It's a feature request. It would be handy to run `jupyter` session directly from emacs with no need to copy&paste secret token each time. Or there already exist any specialized plugins/workarounds for that?

**Comment by millejoh** [comment]
See the jupyter dev teams [blog](https://blog.jupyter.org/2016/12/21/jupyter-notebook-4-3-1/) post about the new security features. Entering the token should be only needed very infrequently, so long as you do not delete the cookie jar.

That is, after you execute `ein:notebooklist-login` you should be able thereafter simply call `ein:notebooklist-open`, even between emacs and jupyter sessions, which has been my experience so far.

**Comment by Pitometsu** [comment]
Thank you, didn't know that. So, it's just enough just to [run](https://github.com/ilya-babanov/emacs-bpr) `jupyter` process from emacs each time (and probably make alias and key binding for that).
