### ISSUE TITLE
long timeouts

### ISSUE THREAD

**Issue by Pitometsu** [millejoh/emacs-ipython-notebook#172]
Not sure about reason, but during navigating at ein notebook buffer, experienced time to time long timeouts that freeze cursor navigation, and than produce huge output to \*Messages\* buffer (some data from notebook). Looks like, ein trying to recalculate all the buffer time to time. Can I turn it off or force doing it in background (in jupyter notebook there's no freezes)

**Comment by Pitometsu** [comment]
UPD: ein periodically freeze emacs cursor not only at notebook buffer.

**Comment by millejoh** [comment]
1) What is the output in the *Messages* buffer?
2) What are you running in your notebook? Does it occur with all notebooks, or some/one in particular?

**Comment by timseries** [comment]
May be related...I also have noticed emacs utlizing 100% cpu when using ein. cpu-profiler points to most (80%) of the time spent in sp-show--pair-function

**Comment by millejoh** [comment]
If you disable smartparens mode - which I think you can do via `show-smartparens-mode` do you still see the utilization issues? I like paredit much better for editing lisp code, so I have never enabled smartparens which might explain why I am not seeing the issue.

**Comment by Pitometsu** [comment]
Yeah, I use sp-mode too. Will check today, later, thanks for suggestion.

**Comment by timseries** [comment]
Tried disabling sp-mode via `show-smartparens-mode`, seems to have resolved the cpu usage issue. Any ideas on why this issue only crops up when using ein?
