### ISSUE TITLE
complaining about non-ein buffers

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#173]
I see this in the `*Warnings*` buffer:
```
Warning (emacs): Error running save hooks: ’Buffer is read-only: #<buffer *Summary gmane.lisp.clisp.devel*>’. I will still try to save the notebook.
```
why does `ein` even look at a `gnus` buffer?

**Comment by millejoh** [comment]
This is what ein currently does when running before-save-hooks:

```lisp
(condition-case err
      (run-hooks 'before-save-hook)
    (error (ein:log 'warn "Error running save hooks: '%s'. I will still try to save the notebook." (error-message-string err))))
```

One change I've made is to log these messages to *ein:log-all*, but that won't stop what you are seeing, I think. My first though is that one of the hooks in before-save-hooks is trying to do something in the gnus buffer. So, ein isn't looking at the gnus buffer (probably), but more likely on of the hooks is.

**Comment by sam-s** [comment]
yeah, I found that piece of code, but I could not figure out why ein code is running in a  a gnus buffer. I guess I will have to remove `condition-case` and loot at the backtrace ...
