### ISSUE TITLE
Proper way to add bindings to ein:notebook-mode-map

### ISSUE THREAD

**Issue by UndeadKernel** [millejoh/emacs-ipython-notebook#174]
What is the proper way to add (or remove) custom bindings for a notebook?
It seems that ein:notebook-mode-map is initialized very late, making the keymap unavailable for modifications.

This next code, for example, does not work as "ein:notebook-mode-map" is void at this point:
```
(use-package ein
  :commands (ein:notebooklist-open)
  :config
  (require 'ein-loaddefs)
  (require 'ein)
  (define-key ein:notebook-mode-map (kbd "<C-tab>") 'my-function))
```

**Comment by yyadavalli** [comment]
Try using `:bind` keyword provided by `use-package`. Also I don't think you need the `require` statements in `:config`

**Comment by millejoh** [comment]
Not sure if it helps, but you can look at how the spacemacs ein [layer](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/ipython-notebook/packages.el) does things.

Maybe you need to wrap the code in :config with a progn? The code in :config should not run until after `ein:notebooklist-open` is called, which should cause all the important code in ein (including the notebook mode keymap) to be loaded.

If for some reason none of that is working I would add an `(require 'ein-notebook)` before defining custom keys.

**Comment by arthurcgusmao** [comment]
This worked for me:

```emacs-lisp
(use-package ein
  :defer t
  :commands ein:notebooklist-open
  :init
  (progn
    (with-eval-after-load 'ein-notebooklist
      ;; removing keybindings
      (define-key ein:notebook-mode-map (kbd "M-p") nil)
      (define-key ein:notebook-mode-map (kbd "<M-up>") nil)
      (define-key ein:notebook-mode-map (kbd "<M-down>") nil)
      ;; changing keybinding
      (define-key ein:notebook-mode-map (kbd "C-s") 'ein:notebook-save-notebook-command)
      (define-key ein:notebook-mode-map (kbd "<M-S-up>") 'ein:worksheet-move-cell-up)
      (define-key ein:notebook-mode-map (kbd "<M-S-down>") 'ein:worksheet-move-cell-down)
      )))
```

**Comment by UndeadKernel** [comment]
@arthurcgusmao have you tried placing all your "define-key" statements inside the ":config" section? In theory, that should also work (as the ":config" section is called after loading ein-notebook).
I can also set my own key bindings for the ein:notebook-mode-map if I create a function, in the ":init" section, and hook it to "ein:notebook-mode-hook".

**Comment by jgarvin** [comment]
Things that don't work for me:

* (require 'ein)
* (require 'ein-notebook)
* arthurcgusmao's solution

What did work:

* UndeadKernel's solution. Code:

`(use-package
    ein
    :ensure t
    :init
    (progn
      ;; fix smartparens not wanting to write closing parenthises when highlighting a region
      (defun insert-open-parens-or-wrap (&optional arg)
        (interactive "P")
        (if (region-active-p)
            (insert-parentheses arg)
          (insert "()")
          (backward-char))
        )

      (defun setup-key-hack ()
        (define-key ein:notebook-mode-map (kbd "(") #'insert-open-parens-or-wrap))

      (add-hook 'ein:notebooklist-mode-hook #'setup-key-hack)
      )
  )
`

I've never had so much trouble setting an emacs binding before. What is ein doing that's so unusual? Is it being really aggressive about lazy loading?

**Comment by dickmao** [comment]
```
(use-package ein-notebook
  :bind (:map ein:notebook-mode-map ("(" . insert-open-parens-or-wrap))
  :init
  (defun insert-open-parens-or-wrap (&optional arg)
    (interactive "P")
    (if (region-active-p)
	(insert-parentheses arg)
      (insert "()")
      (backward-char))))
```
Yes, EIN engages in some unwholesome lazy loading that gets it into more trouble than it saves.

**Comment by indigoviolet** [comment]
@dickmao - I must be missing something - I get an error about `ein-notebook` not being in any of my package repositories.

**Comment by dickmao** [comment]
I must be missing something as #714 complains of the same.  I suggested a diagnostic at #714 to find out what I'm missing.

**Comment by tkravichandran** [comment]
**What worked for me:**

Based on he [second suggestion](https://github.com/millejoh/emacs-ipython-notebook/issues/174#issuecomment-278412129) from @millejoh 

```lisp
(require 'ein-notebook)
  (define-key ein:notebook-mode-map "\C-c\C-d"
    'ein:worksheet-delete-cell)
```

**What didn't work for me:** 

The first suggestion by @millejoh  to use `'ein:notebooklist-open`

```lisp
(eval-after-load 'ein:notebooklist-open 
  '(define-key ein:notebook-mode-map "\C-c\C-d"
     'ein:worksheet-delete-cell))
```
@arthurcgusmao [way of defining](https://github.com/millejoh/emacs-ipython-notebook/issues/174#issuecomment-280844022) also didn't work for me :(

In all cases where things don't work I get the `Symbol's value as variable is void: ein:notebook-mode-map` error.

**Comment by dickmao** [comment]
> **What worked for me:**
> ```lisp
> (require 'ein-notebook)
>   (define-key ein:notebook-mode-map "\C-c\C-d"
>     'ein:worksheet-delete-cell)
> ```

Every emacs user `require`s without hesitation, and that's fine -- I did that for most of my life.

The purist however disdains `require` because it unnecessarily slows startup, that is, if you never use EIN during your session, you've incurred the loading cost with no benefit.  The `use-package` package was written to make on-demand loading easier, although quite frankly, `use-package` is incomprehensible to beginners.

Like this:

```
(use-package ein-notebook
  :bind (:map ein:notebook-mode-map
	      ("C-c C-d" . ein:worksheet-delete-cell)))
```

**Comment by tkravichandran** [comment]
> The purist however disdains `require` because it unnecessarily slows startup, that is, if you never use EIN during your session, you've incurred the loading cost with no benefit. The `use-package` package was written to make on-demand loading easier, although quite frankly, `use-package` is incomprehensible to beginners.
> 
> Like this:
> 
> ```
> (use-package ein-notebook
>   :bind (:map ein:notebook-mode-map
> 	      ("C-c C-d" . ein:worksheet-delete-cell)))
> ```

Awesome. This works really well. Thank You for taking the time to show me. Yes beginner here. Additional key bindings can just be added like this:

```lisp
(use-package ein-notebook
  :bind (:map ein:notebook-mode-map
	      ("C-c C-d" . ein:worksheet-delete-cell)
	      ("C-c C-x C-a" . ein:worksheet-execute-all-cells-above)
	      ("C-c C-x C-b" . ein:worksheet-execute-all-cells-below)
	      ))
```
