### ISSUE TITLE
Allow setting arbitrary jupyter notebook server arguments

### ISSUE THREAD

**Issue by UndeadKernel** [millejoh/emacs-ipython-notebook#178]
Currently, the function "ein:jupyter-server--cmd" does not allow the user to set the arguments used for the jupyter command. For example, I would like the jupyter function call to be: "jupyter notebook --notebook-dir:/some/path --no-browser ".
Adding an extra variable with user defined arguments could solve this issue. Something like the following could do the trick:

```
(defun ein:jupyter-server--cmd (path dir &optional arguments)
  (unless arguments (setq arguments ""))
  (list path
        "notebook"
        (format "--notebook-dir=%s" dir))
        arguments)
```

Of course this would require to also change how "ein:jupyter-server-start" is called.

**Comment by millejoh** [comment]
Ask and ye shall [receive](6b7e2516589f86b095430aa95100795a5930cf69). Check the customizable variable `ein:jupyter-server-args`. You may have to do a `(require 'ein-jupyter)` before you can see the variable the first time.
