### ISSUE TITLE
SSL error making HTTP requests instead of HTTPS

### ISSUE THREAD

**Issue by reconmaster** [millejoh/emacs-ipython-notebook#182]
Looks like SSL is acting up again. Running a server setup
([Jupyter SSL guide](https://jupyter-notebook.readthedocs.io/en/latest/public_server.html#using-ssl-for-encrypted-communication)) remote server as mentioned in #94.

Thought it might be my certs that were ought of date, so I regenerated
them again and went ahead and upgraded EIN and Jupyter for good
measure. 

Running pyenv w/ conda to install jupyter and related research
packages. I was initially having this problem on OSx, complaining with
about SSL v3 even to a local host. I then switched over to *nix and at
least that is working on a localhost.

Then after duplicating the config on the remote server with the same
conda research environment, I was able to login and load the notebook.
But again, getting the same problem in #94 where EIN says the
following when trying to evaluate any cell:

```
[warn] Kernel is not ready yet! (or closed already.) @#<buffer *ein:https://researchbox.edu:9999/calcs.ipynb*>
```

So then I tried to restart:

```
[E 2017-03-09 21:29:50.260 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/home/reconmaster/.local/lib/python2.7/site-packages/tornado/http1connection.py", line 674, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/home/reconmaster/.local/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/home/reconmaster/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/home/reconmaster/.local/lib/python2.7/site-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/home/reconmaster/.local/lib/python2.7/site-packages/tornado/http1connection.py", line 165, in _read_message
        io_loop=self.stream.io_loop)
      File "/home/reconmaster/.local/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/home/reconmaster/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 111, in result
        raise self._exception
    SSLEOFError: EOF occurred in violation of protocol (_ssl.c:661)
```

I found this which is about as close to what I'd imagine the solution
is (@minrk's Are you making HTTP requests to an HTTPS server?).

https://github.com/ipython/ipython/issues/8621

Is there anyway to change the protocol by which we connect to the
jupyter server?

**Comment by reconmaster** [comment]
On the nix side of things, it looks that with the jupyter I'm using 4.2.1 does work. There is the one caveat that I do experience the issues mentioned in #166. It does resolve itself if I issue a login again.

As for the SSL issue here, it seems that this is only a problem with osx. I have run into isseus with its certificate management before. It may be that I need to use a different certificate that is signed by some CA? I tried registering the certificate generated as per the Jupyter documentation with the KeyChain, but that didn't resolve the problem.

Let me know if you need any additional information. I'm pleased that it does seem to work for now on nix as that is where I usually work.

PS nice work with the support for org-mode. I am very happy to have that functionality.

**Comment by millejoh** [comment]
I also occasionally see the need to do multiple logins or multiple notebook starts to get things to work. Unfortunately it has proven hard to reliably reproduce, but hopefully inspiration will strike.

I'm back to having weird issues with curl not correctly starting websocket connections, but I did get far enough to see that calling `ein:notebooklist-login` and `ein:notebooklist-open` on a jupyter server with certs enabled does seem to work. The key is to make sure that you specify the connection url using https, and don't forget a trailing slash. For example: `ein:notebooklist-login RET https://localhost:8889/ RET [super-secret password here] RET`.

**Comment by reconmaster** [comment]
Well from continuing to look into this, it appears that the issue only seems to occur when attempting to connect to the jupyter server from osx (Sierra). Even then `ein:notebooklist-login` and `ein:notebooklist-open` work. I do explicitly specify the https:// protocol when connect as that is the protocol I am attempting to use. The server-side error when connecting with osx client is the following:

```
SSL Error on 23 ('127.0.0.1', 55727): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:661)
```

I thought perhaps the issue might be the self-signed certificate, so I implemented the https://certbot.eff.org/ certificate on the server. This did remove the warning jupyter was giving me regarding an invalid CA. However, while *nix could connect and run the notebooks fine as before, osx still gave the same error on the server side and kernel closed/not ready error in EIN. 

This only occurs when I actually try to launch the notebook from the notebooklist. The notebook opens fine, but after the gnutls-cli call from EIN, the openssl triggers the server-side warning and the kernel is dropped. The debug backtrace shows that the kernel is killed by the request--safe-apply from the tornado server.

I also tried using both the osx openssl to generate the certificates as well as that of the coreutils under homebrew/dupes. The result was the same. When connecting, EIN does use the gnutls-cli which may be an issue? I am not sure about this since this is what *nix is using.

**Comment by millejoh** [comment]
@reconmaster, unfortunately I do not have any OSX machines to test on, so looks like this is going to be difficult to reproduce and debug. I'll do what I can, but this may not be easily resolved in the short term.

**Comment by reconmaster** [comment]
I've got a better handle on this now. It looks like the issue is indeed the incompatablility of OS X with OpenSSL. As Apple has declared OpenSSL obsolete (along this lines of this ridiculous [stupidity](https://hynek.me/articles/apple-openssl-verification-surprises/), there is a bit of a circuitous route to get it working with a Jupyter server.

1) OpenSSL needs to be installed from either source/homebrew.

2) The real version of openssl needs to take precedent over the crippled osx version.

3) Emacs must be compiled with gnu-tls support.

4) I realize my problem arose when Xcode upgraded and subsequently supplanted my brew openssl with the bogus version of apple's openssl. As the osx version isn't aware of the shappening, it still things SHA1 is fine which led to the cascade of invalid algorithm responses from the server.

Everything seems ok on the EIN side of things so I am closing this. If any intrepid osx users want to access a remote jupyter server with self-signed certificates, just make sure you aren't using Apple's ridiculous openssl and make sure your recompile your emacs if you happen to upgrade xcode.

**Comment by lujianmei** [comment]
@reconmaster Thank you for you recommendation.
I got the same issue response on server side:

`SSL Error on 23 ('127.0.0.1', 55727): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:661)`

And also i have changed default openssl into my Brew installed one, from Openssl 0.9 to Openssl 1.0.2. Then i regenerated all key and pem file using:
`$ openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout mykey.key -out mycert.pem`

But I still got the error on my Mac (Sierra).

As you told, Emacs must be compiled with gnu-tls, since i used following way to reinstall Emacs on my Mac
`brew reinstall emacs --with-cocoa`
There is no --with-gnu-tls out there. So which means i have to compile a new emacs from source code by myself?
Thanks.
