### ISSUE TITLE
ein20170319 + defalt org seems to conflict.

### ISSUE THREAD

**Issue by flamingbear** [millejoh/emacs-ipython-notebook#184]
## Check list

- [x ] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x ] Does IPython works from the web browser?
- [x ] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x ] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have

Can't start up emacs because of conflicts with org and ein.

Using:
Org-mode version 8.2.10 (release_8.2.10 @ /Applications/Emacs.app/Contents/Resources/lisp/org/)
Using latest ein-20170319.1119

Starting up results in : 

"progn: Symbol’s function definition is void: org-link-set-parameters"

A quick search shows org-link-set-parameters wasn't added until org 9.0

## Steps to reproduce the problem

Start up emacs with this command and init..
`
/Applications/Emacs.app/Contents/MacOS/Emacs -q --eval '(setq user-emacs-directory "~/projects/broken-ein")' --eval '(load-file "~/projects/broken-ein/init.el")' --debug-init`

```
;;; init.el --- debug ein                            -*- lexical-binding: t; -*-

(setq user-init-file (or load-file-name (buffer-file-name)))
(setq user-emacs-directory (file-name-directory user-init-file))


(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))



(use-package ein :ensure t)
(use-package org :ensure t)
(custom-set-variables
 '(package-selected-packages (quote (ein use-package))))
(custom-set-faces
 )

```

## Expected output

Expect to start emacs with no errors.

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):
`nohup bash -c "jupyter-notebook  --ip=0.0.0.0 --no-browser --notebook-dir=/share/apps/g02135-sii-asina-all/scratch/ipynb/" &`
3. What is your IPython notebook port number or URL?:

8888

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))
 of 2016-09-17"
 :emacs-bzr-version nil
 :window-system ns
 :emacs-variant nil
 :os
 (:uname
  "Darwin savoie-laptop.users.int.nsidc.org 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64
"
  :lsb-release nil)
 :image-types
 (png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.13.0"
	   :source-dir "/Users/savoie/projects/broken-ein/elpa/ein-20170319.1119/")
 :lib
 ((:name "websocket"
	 :path "~/projects/broken-ein/elpa/websocket-20161113.1736/websocket.elc"
	 :featurep t
	 :version-var websocket-version
	 :version "1.5")
  (:name "request"
	 :path "~/projects/broken-ein/elpa/request-20170131.1747/request.elc"
	 :featurep t
	 :version-var request-version
	 :version "0.3.0")
  (:name "python"
	 :path "/Applications/Emacs.app/Contents/Resources/lisp/progmodes/python.elc"
	 :featurep nil
	 :version-var nil
	 :version nil)))
```

**Comment by flamingbear** [comment]
I can confirm that downgrading ein to 0.12, or upgrading org to 9.0.5 keeps me working.

**Comment by jschwab** [comment]
Do you want to check if #185 fixes this?

**Comment by flamingbear** [comment]
I will see if I can confirm.  Thanks.

**Comment by millejoh** [comment]
The PR looks good to me so I just merged it. Good luck!

John




On Mon, Mar 20, 2017 at 1:41 PM -0500, "Matt Savoie" <notifications@github.com> wrote:












I will see if I can confirm.  Thanks.

**Comment by flamingbear** [comment]
All good to me too. Thanks for the quick work.
