### ISSUE TITLE
Cannot modify an area being edited in a dedicated buffer

### ISSUE THREAD

**Issue by amosbird** [millejoh/emacs-ipython-notebook#188]
When doing `c-c c-c` inside cell edit buffer, I got `user-error: Cannot modify an area being edited in a dedicated buffer`. Here is the screenshot ![](https://paste.wentropy.com/0-8P.jpg)

**Comment by cpbotha** [comment]
That usually happens to me when I open a new cell edit buffer on the same cell without having closed the previous one. (in org-mode, it automatically will jump to the already existign dedicated edit buffer if possible, but this is not yet the case with EIN)

**Comment by millejoh** [comment]
That certainly sounds like a bug to me. Been kind of busy lately, but I will try to look at this as soon as I can.

**Comment by amosbird** [comment]
To reproduce this, try to switch to the notebook buffer and switch back using emacs buffer navigation.

**Comment by millejoh** [comment]
@amosbird, let me know if this commit fixes you problem.
