### ISSUE TITLE
Unknown event: status_idle\.Kernel

### ISSUE THREAD

**Issue by nicholascarroll** [millejoh/emacs-ipython-notebook#192]
Hi John,

Thanks for EIN, it works nicely. However every time I execute I get these messages:
ein: [info] Unknown event: status_idle\.Kernel
ein: [info] Unknown event: execution_count\.Kernel

It works but I just wanted to tidy those up.

**Comment by nicholascarroll** [comment]
closing this because i have uninstalled EIN from my emacs v 24. I plan to install it once i go to 25.

**Comment by millejoh** [comment]
@nicholascarroll, good luck with the upgrade. FYI I tested out version 12.1 of ein (which happens to be the ein that is available on [melpa stable](https://stable.melpa.org/#/) on emacs 24.4 and it seems to work without any problems.

**Comment by nicholascarroll** [comment]
hey great, I installed 12.2 from melpa-stable and it solves this and also #193.
