### ISSUE TITLE
Cannot save notebook

### ISSUE THREAD

**Issue by nicholascarroll** [millejoh/emacs-ipython-notebook#193]
When trying to save the notebook I get this error:
ein:content-from-notebook: Wrong type argument: arrayp, nil
and it is not saved.
### VERSION
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)

**Comment by nicholascarroll** [comment]
It seems to be all the functions in the File menu that do this.

**Comment by millejoh** [comment]
It seems like some of my recent commits have broken compatibility with emacs 24. Do you have the option of installing emacs 25 on your system? Other option would be to install EIN from melpa stable. It is missing some recently added functionality and bug fixes, but I think it still works with emacs 24.

**Comment by nicholascarroll** [comment]
I am not going to upgrade Emacs for a little while. I will do without EIN until I do.
