### ISSUE TITLE
Is there an ein-jupyterhub.el?

### ISSUE THREAD

**Issue by ehebert** [millejoh/emacs-ipython-notebook#194]
In this commit which ran `update-directory-autoloads` (https://github.com/millejoh/emacs-ipython-notebook/commit/4061a58c94ceda00a4fef87a1414db58ff478a42) an entry for `ein-jupyterhub.el` was added to `ein-loaddefs.el`; however, `ein-jupyterhub.el` does not exist within the `lisp` directory on current master.

@millejoh is `ein-jupyterhub.el` an intentionally untracked file?
If it is in development, would you be willing to share it on a branch?

**Comment by millejoh** [comment]
There is and I just published it to the branch named jupyter. Not much there, honestly. I looked at getting login working a long time ago, but didn't get too far.

**Comment by ehebert** [comment]
Thank you. I'll make an attempt to get it working with a running
JupyterHub.






On Fri, Apr 7, 2017, at 09:29 AM, John Miller wrote:

> There is and I just published it to the branch named jupyter. Not much
> there, honestly. I looked at getting login working a long time ago,
> but didn't get too far.
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 


Links:

  1. https://github.com/millejoh/emacs-ipython-notebook/issues/194#issuecomment-292536257

**Comment by xeono15** [comment]
It is working? How can I help?

**Comment by millejoh** [comment]
No and yes! First I need to get jupyterhub running on my dev machine, then need to figure out what the REST API looks like. If you have any pointers on either I would be more than happy to hear them.

**Comment by xeono15** [comment]
This is what you need?
http://jupyterhub.readthedocs.io/en/latest/rest.html

please if you want something specific send a message on my email, I am actually very new on this emacs environment but if you tell me exactly what you want maybe I can do something.
Thanks

**Comment by millejoh** [comment]
If you want to check out b68d8eff8f1e0682559c24631c544ef4ed263f4a you can try playing with the new command `ein:jupyterhub-connect`.

Looks like I can get EIN to authenticate with jupyterhub and start a notebook server on the hub, but when I try to call `ein:notebooklist-open` to access the server I always get redirected to the hub login page. I've asked the mailing list if they have any idea what is happening, but if somebody here knows why I'd be happy to hear!

**Comment by millejoh** [comment]
As of 4f5f29d3516d687025ad9423dc98bcd202efed56 ein now has some support for jupyterhub. Check out the new command `ein:jupyterhub-connect`.

Note that you need to you need to be running the development version of jupyterhub. There is a bug in v0.7 that keeps ein from working. Otherwise let me know if you run into any issues!
