### ISSUE TITLE
Missing field in JSON data: notebook.path

### ISSUE THREAD

**Issue by jeb2239** [millejoh/emacs-ipython-notebook#195]
## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have

EIN is not executing cells and providing their output.
I think this is due to a warning that says missing field in JSON data: notebook.path 

## Steps to reproduce the problem

1. start jupyter notebook
2. open any kernel
3. try to run a cell with code

## Expected output

[I 20:19:36.970 NotebookApp] Saving file at /SimHwk1718.ipynb
[W 20:20:31.934 NotebookApp] Missing field in JSON data: notebook.path
[W 20:20:31.935 NotebookApp] 400 POST /api/sessions (127.0.0.1) 1.24ms referer=None
[I 20:20:36.988 NotebookApp] Saving file at /SimHwk1718.ipynb

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):

This was package from conda-forge and is version 5.3.0 and the jupyter version is 4.3.0 

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):

jupyter notebook

3. What is your IPython notebook port number or URL?:

http://localhost:8888/notebooks/SimHwk1718.ipynb

## System info:

```cl
("EIN system info"
 :emacs-version "GNU Emacs 25.1.2 (x86_64-pc-linux-gnu, GTK+ Version 3.20.9)
 of 2016-09-28"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux ThinkPad-W530 4.8.0-46-generic #49-Ubuntu SMP Fri Mar 31 13:57:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
"
  :lsb-release
  "No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.13.0"
           :source-dir "/home/barriosj/.emacs.d/elpa/ein-20170407.618/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/elpa/websocket-20161113.1736/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.5")
  (:name "request"
         :path "~/.emacs.d/elpa/request-20170131.1747/request.elc"
         :featurep t
         :version-var request-version
         :version "0.3.0")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20170124.1845/auto-complete.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20170124.1845/auto-complete.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/elpa/popup-20160709.729/popup.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "fuzzy"
         :path "~/.emacs.d/elpa/fuzzy-20150729.2037/fuzzy.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "pos-tip"
         :path "~/.emacs.d/elpa/pos-tip-20150318.813/pos-tip.elc"
         :featurep t
         :version-var pos-tip-version
         :version "0.4.6")
  (:name "python"
         :path "/usr/share/emacs/25.1/lisp/progmodes/python.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path "~/.emacs.d/elpa/markdown-mode-20170317.1202/markdown-mode.elc"
         :featurep t
         :version-var markdown-mode-version
         :version "2.1")
  (:name "helm"
         :path "~/.emacs.d/elpa/helm-core-20170409.1007/helm.elc"
         :featurep t
         :version-var nil
         :version nil)))
```

**Comment by millejoh** [comment]
Do you start jupyter via calls to `ein:jupyter-server-start`? If so can you send a dump of the contents of the *ein:jupyter-server* buffer?

If not, can you provide a dump of the console where you are running the jupyter notebook server?

And for good measure the contents of `*ein:log-all*`. Thanks.

**Comment by jeb2239** [comment]
is ein:log-all a command or a file?

**Comment by jeb2239** [comment]
Also `ein:jupyter-server-start` 

![image](https://cloud.githubusercontent.com/assets/5044729/24876261/08590ef4-1df9-11e7-9015-6542f541a0d8.png)

Seems to get just hang there

Also I am new to emacs and using spacemacs.

But the dump of the console output manually starting jupyter from terminal is
Terminal jupyter
```
[I 14:27:11.317 NotebookApp] [nb_conda_kernels] enabled, 3 kernels found
[I 14:27:11.321 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 14:27:11.731 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 14:27:11.731 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 14:27:11.759 NotebookApp] Loaded extension jupyter_nbextensions_configurator
[I 14:27:11.819 NotebookApp] JupyterLab alpha preview extension loaded from /home/barriosj/anaconda/lib/python2.7/site-packages/jupyterlab
[I 14:27:11.825 NotebookApp] [nb_conda] enabled
[I 14:27:11.839 NotebookApp] [nb_anacondacloud] enabled
[I 14:27:11.842 NotebookApp] Serving notebooks from local directory: /home/barriosj/Documents/simhwk1718
[I 14:27:11.842 NotebookApp] 0 active kernels 
[I 14:27:11.842 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 14:27:11.842 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[18157:18187:0410/142712.181037:ERROR:nss_util.cc(808)] After loading Root Certs, loaded==false: NSS error code: -8018
Created new window in existing browser session.
[W 14:28:00.302 NotebookApp] /home/barriosj/Documents/simhwk1718/.#SimHwk1718.ipynb doesn't exist
[W 14:28:30.005 NotebookApp] /home/barriosj/Documents/simhwk1718/.#SimHwk1718.ipynb doesn't exist
[W 14:28:58.301 NotebookApp] /home/barriosj/Documents/simhwk1718/.#SimHwk1718.ipynb doesn't exist
[W 14:29:03.088 NotebookApp] Missing field in JSON data: notebook.path
[W 14:29:03.089 NotebookApp] 400 POST /api/sessions (127.0.0.1) 1.17ms referer=None
[W 14:29:04.198 NotebookApp] Missing field in JSON data: notebook.path
[W 14:29:04.199 NotebookApp] 400 POST /api/sessions (127.0.0.1) 0.95ms referer=None
[W 14:29:04.222 NotebookApp] Missing field in JSON data: notebook.path
[W 14:29:04.222 NotebookApp] 400 POST /api/sessions (127.0.0.1) 0.97ms referer=None
[W 14:29:04.240 NotebookApp] Missing field in JSON data: notebook.path
[W 14:29:04.241 NotebookApp] 400 POST /api/sessions (127.0.0.1) 1.31ms referer=None
[W 14:29:04.258 NotebookApp] Missing field in JSON data: notebook.path
[W 14:29:04.258 NotebookApp] 400 POST /api/sessions (127.0.0.1) 1.00ms referer=None
[W 14:29:06.039 NotebookApp] /home/barriosj/Documents/simhwk1718/.#SimHwk1718.ipynb doesn't exist

```
Emacs console
```
ein: [info] Worksheet SimHwk1718.ipynb is ready
ein: [info] Enabling autosaves for SimHwk1718.ipynb with frequency 60 seconds.
ein: [info] Notebook SimHwk1718.ipynb is ready
evil-magit initialized
ein: [info] Encountered issue error starting kernel, 3 retries left.
ein: [info] Encountered issue error starting kernel, 2 retries left.
ein: [info] Encountered issue error starting kernel, 1 retries left.
ein: [info] Encountered issue error starting kernel, 0 retries left.
ein: [info] Encountered issue error starting kernel, -1 retries left.
ein: [info] Opened notebook list at http://127.0.0.1:8888 with path 
Auto-saving...
Can’t guess python-indent-offset, using defaults: 4
ein: [warn] Kernel is not ready yet! (or closed already.) [2 times]
<mouse-6> is undefined [2 times]
mwheel-scroll: End of buffer [4 times]
<mouse-6> is undefined [10 times]
mwheel-scroll: Beginning of buffer
<mouse-6> is undefined
mwheel-scroll: Beginning of buffer [2 times]
<mouse-6> is undefined
mwheel-scroll: Beginning of buffer [2 times]
<mouse-6> is undefined [2 times]
```

![image](https://cloud.githubusercontent.com/assets/5044729/24876515/fc87e612-1df9-11e7-97f0-7cc2d2f32dab.png)

**Comment by millejoh** [comment]
Hmm. The only thing that stands out to me is the reference to the secret cookie. I can't find much [documentation](http://jupyter-notebook.readthedocs.io/en/latest/config.html) that explains what the secret cookie file is for. A lot of recent issues with ein have been due to authentication, but that does not seem to be the case here.

There are a couple things you can do to try to get more information:

 1. Call 'M-x ein:dev-start-debug` before opening a notebook list.
 2. Send me the contents of the `*ein:log-all*` buffer.
 3. When debugging is enabled a buffer will be created to log communication over the websocket connection. The name of this buffer is complex, but will start with `*websocket ws://` and be followed by the url used to start the kernel/notebook session.

Note that EIN does somewhat support non-Python kernels, but for testing I'd recommend working with just Python kernels for the moment.

Also note that `ein:jupyter-server-start` is  supposed to wait for the notebook server to start, then try to determine what the login token is and use it to automatically log in and open a notebooklist buffer. You seem to have token authentication disabled so obviously this part won't work. EIN may block emacs for an uncomfortably long time (20-30 seconds) while it waits for something that will never happen, but it should still at least start the jupyter notebook. I would 'hang' (harhar I am such a funny old man) in there a bit longer (maybe 1 minute?) when executing `ein:jupyter-server-start`.

**Comment by jeb2239** [comment]
Hello after doing some debugging on my own I can see that the issue currently is that ein can't start notebooks because notebook.path is missing from the post request.

```
[W 14:29:03.089 NotebookApp] 400 POST /api/sessions (127.0.0.1) 1.17ms referer=None
[W 14:29:04.198 NotebookApp] Missing field in JSON data: notebook.path
[W 14:29:04.199 NotebookApp] 400 POST /api/sessions (127.0.0.1) 0.95ms referer=None
[W 14:29:04.222 NotebookApp] Missing field in JSON data: notebook.path
[W 14:29:04.222 NotebookApp] 400 POST /api/sessions (127.0.0.1) 0.97ms referer=None
[W 14:29:04.240 NotebookApp] Missing field in JSON data: notebook.path
[W 14:29:04.241 NotebookApp] 400 POST /api/sessions (127.0.0.1) 1.31ms referer=None
[W 14:29:04.258 NotebookApp] Missing field in JSON data: notebook.path
[W 14:29:04.258 NotebookApp] 400 POST /api/sessions (127.0.0.1) 1.00ms referer=None
```

**Comment by luismoneda** [comment]
@jeb2239 have you found a solution?

**Comment by rprospero** [comment]
I'm encountering the same issues and deleting .ipython from my home directory has not had an effect.

**Comment by karawoo** [comment]
I'm having this issue as well, and I don't believe anyone has included the `*ein:log-all*` output yet, so here's mine:

```
[info] Opened notebook list at http://127.0.0.1:8888 with path  @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
[info] Creating a new notebook at ... @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
[info] New notebook. Port: http://127.0.0.1:8888, Path:  @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
[info] Creating a new notebook ()... Done. @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
[info] Opening notebook Untitled2.ipynb... @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
[debug] Opening notebook at Untitled2.ipynb @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
[info] Reading nbformat4 notebook. @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
[info] Worksheet Untitled2.ipynb is ready @#<buffer *ein: http://127.0.0.1:8888/Untitled2.ipynb*>
[info] Enabling autosaves for Untitled2.ipynb with frequency 60 seconds. @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
[info] Notebook Untitled2.ipynb is ready @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
[info] Encountered issue error starting kernel, 3 retries left. @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
[info] Encountered issue error starting kernel, 2 retries left. @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
[info] Encountered issue error starting kernel, 1 retries left. @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
[info] Opened notebook list at http://127.0.0.1:8888 with path  @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
[info] Encountered issue error starting kernel, 0 retries left. @#<buffer *ein: http://127.0.0.1:8888/Untitled2.ipynb*>
[info] Encountered issue error starting kernel, -1 retries left. @#<buffer *ein: http://127.0.0.1:8888/Untitled2.ipynb*>
[warn] Kernel is not ready yet! (or closed already.) @#<buffer *ein: http://127.0.0.1:8888/Untitled2.ipynb*>
[verbose] Writing notebook Untitled2.ipynb as nbformat 4. @#<buffer *ein:log-all*>
[debug] Event: notebook_saving\.Notebook @#<buffer *ein:log-all*>
[verbose] Notebook is saved. @#<buffer *ein:log-all*>
[debug] Event: notebook_saved\.Notebook @#<buffer *ein:log-all*>
[debug] Event: notebook_create_checkpoint\.Notebook @#<buffer *ein:log-all*>
[verbose] Checkpoint checkpoint for Untitled2.ipynb generated. @#<buffer *ein:log-all*>
[debug] Event: notebook_checkpoint_created\.Notebook @#<buffer *ein:log-all*>
[warn] Kernel is not ready yet! (or closed already.) @#<buffer *ein: http://127.0.0.1:8888/Untitled2.ipynb*>
[warn] Kernel is not ready yet! (or closed already.) @#<buffer *ein: http://127.0.0.1:8888/Untitled2.ipynb*>
```

**Comment by millejoh** [comment]
Okay, I think I know what I did wrong to cause all this anguish - and I feel suitably dumb for doing it. I'm trying to confirm my suspicion, but if anyone is online can they comment exactly what version of Jupyter notebook they are running?

**Comment by rprospero** [comment]
Here's my server information:

    Server Information:

    You are using IPython notebook.

    The version of the notebook server is 3.2.3-d296ce3 and is running on:

    Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

    Current Kernel Information:

    Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
    Type "copyright", "credits" or "license" for more information.

    IPython 3.2.3 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    %guiref   -> A brief reference about the graphical user interface.

**Comment by millejoh** [comment]
As I thought - I was a little over-eager in supporting current jupyter development and broke backwards compatibility with a change I made a bit ago. I just pushed a commit that should fix this.

Really sorry about that - let me know if things are working again once you are able to update.

**Comment by karawoo** [comment]
Things are working for me now. Thank you!

**Comment by rprospero** [comment]
Fixed on my end as well.
