### ISSUE TITLE
error saving a notebook

### ISSUE THREAD

**Issue by JosefAssad** [millejoh/emacs-ipython-notebook#199]
My setup:

- emacs 24.5.1 from Debian
- ein ein-20170421.1829 from the package list
- jupyter 4.3.0 running in a virtualenv on Debian 9 (using virtualenvwrapper, works fine in browser)

Tested with emacs -Q with ein being the only package installed.

Steps to reproduce:

1. Run `jupyterhub notebook`
2. Run `ein:notebooklist-login` and give it the right port and token
3. Observe notebook list opens correctly
4. Create new python 3 notebook
5. Observe: we do not pop to the newly created notebook in emacs
6. Observe: the newly created notebook does not get added to the list under the "All Opened Notebooks" header in the notebook list
7. Observe: reverting the notebook list buffer also does not make the newly created notebook appear in the "All Opened Notebooks" list
8. Manually switch to the emacs buffer for the newly created notebook
9. Enter trivial python code such as `print('hello')`
10. Run `ein:notebook-save-notebook-command` via C-x C-s
11. Observe the following in the `*Messages*` buffer:

```
ein: [warn] Error running save hooks: 'Wrong type argument: arrayp, nil'. I will still try to save the notebook.
ein:content-from-notebook: Wrong type argument: arrayp, nil
```

My elisp skills are laughable but I've poked around a little and I suspect what's happening is the notebook buffer isn't getting its buffer-local variable containing its name (i.e. `ein:%notebook%`). To fuel this theory, I noticed that the function `ein:notebook-restart-kernel-command` also fails in the notebook, giving the message `ein: [error] Not in notebook buffer!`. As I read the code, this happens when the buffer-local variable `ein:%notebook%` is `nil`.

If setting the `ein:%notebook%` variable depends on the notebook buffer having focus, then maybe it's the failure to pop to the notebook buffer which is causing the issue?

UPDATE: testing with a fresh emacs 25.2 cannot reproduce the problem

**Comment by millejoh** [comment]
The key here is that you are using emacs 24.5.1. Unfortunately ein stopped working on emacs 24 some point after v0.12.2. All of my development and testing is on emacs 25 and 26 these days.

If you want to use ein with emacs 24 then ny suggestion is to download ein from MELPA stable, as that points to v0.12.2.

**Comment by JosefAssad** [comment]
Yes you're absolutely right. I discovered Debian Stretch has emacs 25 in the repos (I try to stick to distro packages) and it's all good here. I've updated the README.rst in a trivial pull request in case it makes your life easier.
