### ISSUE TITLE
Inline images are impossibly small

### ISSUE THREAD

**Issue by JonathanReeve** [millejoh/emacs-ipython-notebook#202]
Inline images (plots) are about half as big as they should be, using `%matplotlib inline`. It could have something to do with the fact that I have a HiDPI display. I can set `figsize` on plots, but then the text is still too small. It'd be nice if there were a way to scale all images up to twice their current size.

**Comment by millejoh** [comment]
Try this:
```python

import matplotlib as plt

plt.rcParams['figure.dpi'] = 150 # Or 200 to double
```
You can also set this parameter in [matplotlibrc](http://matplotlib.org/users/customizing.html#the-matplotlibrc-file) file and save yourself some typing.

**Comment by JonathanReeve** [comment]
Awesome. I'll do that. Thanks!
