### ISSUE TITLE
Tooltip/help doesn't seem to work

### ISSUE THREAD

**Issue by JonathanReeve** [millejoh/emacs-ipython-notebook#203]
Using the spacemacs install, tooltips/help for python functions don't seem to work. It seems to be trying, but whenever I have the cursor over a function, I get the message "Search failed. This means there is an unmatched expression somewhere, or we are at the beginning, end of file." This seems to work well in python-mode, so that if, in a notebook, I run python-mode to enable python mode, I can see the tooltips/help fine.

**Comment by millejoh** [comment]
By tooltip do you mean autocomplete, or something more along the line of the arugment list for a function? If we are talking about autocompletion then what completion backend do you use? If you want to use company then I believe you have to do some additional configuration ala the comments in issue #157.

**Comment by JonathanReeve** [comment]
Something like the argument list for a function. Autocomplete seems to work if I enable it, then explicitly call `auto-complete-mode`. But every time I start typing a function, say, `pandas.Series(`, I get the message above. 

I've tried using company, too, following those comments, but I can't get that to work at all. I don't seem to have the function `spacemacs|add-company-backends`, and I tried this following spacemacs docs, but couldn't quite get it to work: 

```elisp
(auto-completion :variables
                      spacemacs-default-company-backends
                      '(company-files company-capf ein:company-backend))
```

**Comment by tutysara** [comment]
@JonathanReeve can you try adding

```
(spacemacs|add-company-backends
      :backends ein:company-backend
      :modes ein:notebook-mode)
```

to user/config and see if it works. I am on develop branch and it works for me. I have submitted a PR to spacemacs and it got merged, so, updating to latest version in develop should also work.

**Comment by JonathanReeve** [comment]
When I add the above line to my user config, I get: 

```
Error in dotspacemacs/user-config: Symbol’s function definition is void: spacemacs|add-company-backends
```

That's on the master branch.

**Comment by JonathanReeve** [comment]
If I switch to the develop branch, Company seems to work for completing most things, except for tooltips/help on functions. When I start typing a function, I still get the error: "Search failed. This means there is an unmatched expression somewhere, or we are at the beginning, end of file." The same thing happens if I place the cursor on a function and do `C-C, C-F`.

**Comment by millejoh** [comment]
What is `C-c C-f` bound to in your emacs? It should be `ein:pytools-request-tooltip-or-help`.

Eventually ein will try call `ein:object-at-point`, which devolves into essentially a call to `(thing-at-point 'word)` with some additional logic to try to handle python syntax. If you call `M-: (ein:object-at-point)` where you want to have a tooltip what happens?

All this is to try to pinpoint where this is breaking down. My suspicion is that your spacemacs configuration has 'improved' something somewhere along the way causing all these headaches.

**Comment by JonathanReeve** [comment]
C-c C-f is bound to that function, and it seems to run automatically when I start typing the beginning of a function, i.e. `print(`, but all it says is `Search failed. This means there is an unmatched expression somewhere, or we are at the beginning/end of a file.`. When I manually call M-: `(ein:object-at-point)` I get the same error.

**Comment by JonathanReeve** [comment]
Also, I don't think it's anything with my spacemacs config. I just tested it by deleting my .spacemacs and having it generate a new config from scratch, and I get the same error.

**Comment by millejoh** [comment]
Weird - I thought I made a comment, but apparently it never made it through.

Anyway, I was going to comment that ein will make a call to `search-backward` if it detects that it inside a parenthesis.  The exact call looks like: `(search-backward "(" (point-at-bol) t)`. The `t` should ensure that an error is not generated if the search fails, but it doesn't seem to be happening with you.

On my work machine I notice I get the same message as soon is I type the '(', but manually executing 'C-c C-f' works as it should. The error may not be in pytools tooltip code, but in my company implementation. Let me take a closer look.
