### ISSUE TITLE
jedi with ein

### ISSUE THREAD

**Issue by DrWaleedAYousef** [millejoh/emacs-ipython-notebook#204]
Thanks so much for the great package. When working with ein, I have the following two issues although I have automated my .emacs:
1- I have to start jedi manually using M-x jedi-setup
2- I have to start the highlight-indentation-mode manually as well.

This is my .emacs related part:

(use-package jedi
  :ensure t
  :init
  (add-hook 'python-mode-hook 'jedi:setup)
  (setq jedi:setup-keys t)                      ; optional
  (setq jedi:complete-on-dot t)                 ; optional
  )

(use-package elpy
  :ensure t
  :init
  (elpy-enable)
  :config
  (setenv "WORKON_HOME" "~/Downloads/AAProgramsAA/anaconda3/envs/")
  (pyvenv-mode 1)
  (pyvenv-workon "MyDefaultEnv")
  )

(use-package ein
  :ensure t
  :init
  (add-hook 'ein:connect-mode-hook 'ein:jedi-setup)
  (setq
   ein:jupyter-default-server-command "/home/wyousef/Downloads/AAProgramsAA/anaconda3/envs/MyDefaultEnv/bin/jupyter"
   ;;ein:jupyter-default-notebook-directory "/home/wyousef/Downloads/ZZPythonTryingZZ/code"
   ein:use-auto-complete t
   ein:complete-on-dot t
   )
  :config
  (highlight-indentation-mode t)
  (setenv "WORKON_HOME" "~/Downloads/AAProgramsAA/anaconda3/envs/")
  (pyvenv-mode 1)
  (pyvenv-workon "MyDefaultEnv")
  )

**Comment by millejoh** [comment]
You may need to do add a `(require ein-loaddefs)` and a `(require ein-subpackages)` in the init. There is also a dependency on auto-complete, though I am unsure if that needs to be made explicit. 

 I don't use use-package myself, but my init file looks a bit like this:

```elisp
(require 'ein)
(require 'ein-dev)
(require 'auto-complete)
(require 'jedi)
(add-hook 'ein:connect-mode-hook 'ein:jedi-setup)
```

Requiring ein-dev is the equivalent of loading ein-loaddefs, ein-notebook, and ein-subpackages.

**Comment by podiki** [comment]
This doesn't work for me either. I have tried your above code (I normally use `use-package`) and didn't see any difference. I'm using `company` instead of `auto-complete`, but I think I see a few problems.

First, I don't see `jedi:setup` called anywhere from `ein`, even in `ein:jedi-setup` (as far as I can tell it only sets up a keybinding and completing handling).

Second, even if I add `jedi:setup` to `ein:connect-mode-hook`, this doesn't seem to get `jedi` going. Only after loading a notebook if I do `M-x jedi:setup` does anything seem to change. Then it seems to work.

**Comment by podiki** [comment]
I was thinking to just do `(add-hook 'ein:notebook-mode-hook 'jedi:setup)` which seems to properly load, but this causes a problem when you first open the notebook list. So here is my hack that seems to work (jedi shows up in the list of minor modes upon opening a notebook):
```
(add-hook 'ein:notebooklist-first-open-hook
          (lambda () (add-hook 'ein:notebook-mode-hook 'jedi:setup)))
```

**Comment by millejoh** [comment]
With my commit 08d2792d690cefb9ef2e00a14d3bbb1da55252a9 I've changed a bit how one configures which completion backend to use in ein.

Please see the variable `ein:completion-backend`. Now, to use jedi, all you should need to do is call `(setq ein:completion-backend 'ein:use-ac-jedi-backend) in your init file before loading ein.

Give it a try and let me know how it works!

I have tried to remain compatible with the old ways of enabling code completion, so my fingers are crossed that this does not immediately break anyone's configuration.

**Comment by podiki** [comment]
Great, looks good! And I hope it won't be too difficult to finish adding in `ein:use-company-jedi-backend` in the near future.

Thanks for the great Emacs package, so much easier than fighting Emacs instincts with editing notebooks in the browser.

**Comment by DrWaleedAYousef** [comment]
Thanks so much for your update;  before I report the few problems I still have please confirm for me the soundness of this init file:

(use-package auto-complete)
(ac-config-default)

(use-package jedi)
(jedi-setup)

(require 'ein)
(require 'ein-loaddefs)
(require 'ein-notebook)
(require 'ein-subpackages)
(setq
 ein:jupyter-default-server-command "/home/wyousef/Downloads/AAProgramsAA/anaconda3/envs/MyDefaultEnv/bin/jupyter"
 ein:jupyter-default-notebook-directory "/home/wyousef/Downloads/ZZPythonTryingZZ/code"
 ein:completion-backend 'ein:use-ac-jedi-backend
 )

**Comment by millejoh** [comment]
@DrWaleedAYousef, this looks reasonable. EIN should take care of the call to `jedi:setup` and enable autocomplete when you open a notebook, but the extra calls shouldn't hurt anything. Let me know what issues you are seeing, but note I'm going to be on vacation for the next two weeks, so I might not be too quick to respond.

**Comment by DrWaleedAYousef** [comment]
Thanks so much for fast reply;

1. Neither auto-complete nor Jedi starts by themselves! I have to enable
   them from .emacs or through M-x ....
2. When the pop-up appears with selections the yellow help sometimes
   takes long time to appear or does not appear at all unless I keep
   going back and forth with arrows!
3. After typing the "dot" the hitting TAB does not pop-up any
   suggestions.

Thanks so much.

**Comment by dickmao** [comment]
`jedi` capability falls out of elpy.
