### ISSUE TITLE
Cell Output Area face

### ISSUE THREAD

**Issue by lgmoneda** [millejoh/emacs-ipython-notebook#205]
Is there a way to change the Output Area just like it's possible to the Input Area? Why the Output Area does not have a customize face too?

**Comment by millejoh** [comment]
Only tkf would know for sure why, but I see no reason why the output face could not be made a custom value - in fact there is already some machinery there in way of the `ein:cell-output-stderr` customizable variable. I haven't had much time lately to work on ein except for fixing critical bugs, but I am happy to add this to my things-to-do list.

**Comment by garfielde** [comment]
Similarly, it would be nice to have different faces for markdown and code cells.

**Comment by dickmao** [comment]
> Similarly, it would be nice to have different faces for markdown and code cells.

And now you can.
