### ISSUE TITLE
Initialization cells

### ISSUE THREAD

**Issue by boffi** [millejoh/emacs-ipython-notebook#206]
I wonder if EIN could support initialization cells (for now it's a `nbextension`)

> Internals
Cells are marked as initialization cells in their metadata, as
 `cell.metadata.init_cell = true`
The running of initialization cells on kernel ready is bound to the Jupyter event `kernel_ready.Kernel`.

using maybe a customizable variable.

Thank you in advance (and also in retrospect, EIN is a really good thing to have around...)

yours — gb

**Comment by millejoh** [comment]
Something like this definitely sounds possible; the only real question is the time I have available. I'll throw this into the Enhacments bucket and get to it when I can.

**Comment by boffi** [comment]
OK, thank you

**Comment by dickmao** [comment]
I've no intention to work on this.  Sorry.
