### ISSUE TITLE
EIN erases unknown metadata from saved cells/notebooks

### ISSUE THREAD

**Issue by boffi** [millejoh/emacs-ipython-notebook#207]
IPython/Jupyter notebook browser interface has received in the last
months a number of enhancements, the so called `nbextension`s, many of
them saving their state in terms of `cell`s' metadata.

Now it happens that when I use EIN to edit a notebook that contains
such metadata (in my case, generated by the "Initialization cells"
extension), when I save the notebook EIN **nukes** said additional
metadata.

Please EIN, respect the metadata you don't understand...

Yours — g

**Comment by millejoh** [comment]
That is definitely not desired behavior. I think I know what the problem is - if you can share a notebook where you know metadata is getting deleted it would save me some time in testing. Otherwise I will have to generate one myself. Not a horribly difficult task, just a bit time consuming.

Thanks.

**Comment by millejoh** [comment]
Just made some commits that should address this. If you are updating through MELPA you should see the changes in a few hours, I hope. Let me know if this works for you.

**Comment by boffi** [comment]
Thanks a lot for coming to the rescue!
I'll test the new MELPA version tomorrow morning (it's 23:30 here in Italy) and let you know

**Comment by boffi** [comment]
I have installed via MELPA the new (May 15) version of EIN

Here two notebooks
[Untitled.sav.txt](https://github.com/millejoh/emacs-ipython-notebook/files/1007256/Untitled.sav.txt)  
[Untitled.txt](https://github.com/millejoh/emacs-ipython-notebook/files/1007259/Untitled.txt)  
(the mechanism of github doesn't like that I attach `.ipynb` files, so I had to rename them to `.txt`,
sorry for the inconvenience)

The first file (`.sav.txt`) is a copy of the notebook as saved by Jupyter,
the second one is the notebook as saved by EIN.
There is a bit of noise because I executed the notebook in EIN, but the relevant part is

```
    "metadata": {
-    "collapsed": true,
-    "init_cell": true
+    "autoscroll": "json-false",
+    "collapsed": false,
+    "ein.tags": [
+     "worksheet-0"
+    ],
+    "slideshow": {
+     "slide_type": "-"
+    }
```
especially the `init_cell": true` part that's gone away.

The new version not only modifies the cell metadata (and that's good), but also erases the part about the `init_cell`ness.

**Comment by millejoh** [comment]
The latest release is http://melpa.org/packages/ein-20170516.1307.tar - you may not be quite up to date. Given the complexity of ein I find that sometimes I need to recompile the elc files to get updates to register. You can do this by calling `ein:byte-compile-ein` and then restarting Emacs.

With ein-20170516.1307 I get the following JSON when I save your notebook (thanks for sharing!)

```json
{
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "autoscroll": false,
    "collapsed": false,
    "ein.tags": "worksheet-0",
    "init_cell": true,
    "slideshow": {
     "slide_type": "-"
    }
   },
   "outputs": [],
   "source": [
    "def test(x): return x"
   ]
  }
```

**Comment by boffi** [comment]
I made a mistake identifying the version of EIN, the version I've installed is indeed `20170516.1307`.  
To be sure of what I'm doing I reinstalled `20170516.1307`, issued `ein:byte-compile-ein` and I did as follows

```
$ cp Untitled.sav.txt test.ipynb
# emacs -q &
$ # loaded test.ipynb in EIN, made a fake edit, saved, stopped
$ diff Untitled.sav.txt test.ipynb
6c6,15
<    "metadata": {},
---
>    "metadata": {
>     "autoscroll": "json-false",
>     "collapsed": false,
>     "ein.tags": [
>      "worksheet-0"
>     ],
>     "slideshow": {
>      "slide_type": "-"
>     }
>    },
27,28c36,43
<     "collapsed": true,
<     "init_cell": true
---
>     "autoscroll": "json-false",
>     "collapsed": false,
>     "ein.tags": [
>      "worksheet-0"
>     ],
>     "slideshow": {
>      "slide_type": "-"
>     }
39d53
<    "language": "python",
53c67,68
<   }
---
>   },
>   "name": "test.ipynb"
$ 
```
In my setup, the problem is still present.

**Comment by millejoh** [comment]
Looks like there was some duplicate code in another file doing the old-style, bad-actor way of treating metadata. Why, I have no idea, but I just removed the code. You should see the change soon and I think it all should work, finally.
