### ISSUE TITLE
ein with spacemacs

### ISSUE THREAD

**Issue by fab6** [millejoh/emacs-ipython-notebook#208]
Hello,

I try to start the jupyter server by using 'ein:jupyter-server-start' using spacemacs (just updated the packages) and get this error message:

Error (use-package): ein :config: Symbol's value as variable is void: ein:cell-to-nb4-json

Python is anaconda python 3.6.0

Do you have an idea what I am doing wrong?

Thanks!

**Comment by millejoh** [comment]
What happens if you execute `ein:byte-compile-ein`, then restart Emacs?

Also what version of emacs are you using?

**Comment by fab6** [comment]
Thanks, GNU emacs version is 24.5.1 this is the output:
Leaving directory `/WORK2/fbraenns/HF6/Fire_Simulation/HRR/SMALL_Scale/SideLining_2017/EXP/'

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-ac.el at Fri May 19 07:10:25 2017
Entering directory `/home/fbraenns/.emacs.d/elpa/ein-20170516.1307/'
ein-ac.el:33:28:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-cell-edit.el at Fri May 19 07:10:26 2017
ein-cell-edit.el:27:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-cell-output.el at Fri May 19 07:10:26 2017
ein-cell-output.el:29:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-cell.el at Fri May 19 07:10:26 2017

In ein:cell-from-json:
ein-cell.el:275:24:Warning: assignment to free variable `cell'
ein-cell.el:276:37:Warning: reference to free variable `cell'

In ein:get-slide-show:
ein-cell.el:511:19:Warning: assignment to free variable `slide_type'
ein-cell.el:511:30:Warning: assignment to free variable `SS_table'
ein-cell.el:512:3:Warning: reference to free variable `SS_table'
ein-cell.el:511:40:Warning: reference to free variable `slide_type'

In ein:maybe-show-slideshow-data:
ein-cell.el:516:43:Warning: reference to free variable `ein:%worksheet%'
ein-cell.el:869:18:Warning: function `equalp' from cl package called at
    runtime
ein-cell.el:1051:1:Warning: `(cell ein:codecell)' is a malformed function
ein-cell.el:1051:15:Warning: reference to free variable `ein:cell-to-nb4-json'
ein-cell.el:1051:57:Warning: reference to free variable `wsidx'
ein-cell.el:1051:63:Warning: reference to free variable `&optional'
ein-cell.el:1051:73:Warning: reference to free variable `discard-output'
ein-cell.el:1052:40:Warning: reference to free variable `cell'
ein-cell.el:1071:31:Warning: function `copy-list' from cl package called at
    runtime

In end of data:
ein-cell.el:1291:1:Warning: the following functions are not known to be defined:
    ein:worksheet--show-slide-data-p, cl-defmethod

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-company.el at Fri May 19 07:10:26 2017
ein-company.el:86:7:Warning: assignment to free variable `ein:complete-on-dot'

In end of data:
ein-company.el:89:1:Warning: the function `ein:pytools-find-source' is not
    known to be defined.

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-completer.el at Fri May 19 07:10:26 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-connect.el at Fri May 19 07:10:26 2017
ein-connect.el:36:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-console.el at Fri May 19 07:10:27 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-contents-api.el at Fri May 19 07:10:27 2017
ein-contents-api.el:33:1:Warning: cl package required at runtime
ein-contents-api.el:40:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-core.el at Fri May 19 07:10:27 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-dev.el at Fri May 19 07:10:27 2017
ein-dev.el:32:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-events.el at Fri May 19 07:10:27 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-file.el at Fri May 19 07:10:28 2017
ein-file.el:57:1:Error: (ein:$content-raw-content ein:content-file-buffer--content) is not a valid place expression

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-helm.el at Fri May 19 07:10:28 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-iexec.el at Fri May 19 07:10:28 2017
ein-iexec.el:28:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-inspector.el at Fri May 19 07:10:28 2017

In end of data:
ein-inspector.el:103:1:Warning: the function `ein:goto-file' is not known to
    be defined.

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-ipdb.el at Fri May 19 07:10:28 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-ipynb-mode.el at Fri May 19 07:10:28 2017
ein-ipynb-mode.el:29:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-jedi.el at Fri May 19 07:10:28 2017
ein-jedi.el:31:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-junk.el at Fri May 19 07:10:29 2017
ein-junk.el:29:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-jupyter.el at Fri May 19 07:10:29 2017
ein-jupyter.el:27:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-kernel.el at Fri May 19 07:10:30 2017

In end of data:
ein-kernel.el:910:1:Warning: the following functions are not known to be defined: ein:$notebook-p,
    ein:$notebook-notebook-path, ein:$notebook-notebook-name,
    ein:$notebook-kernelspec, ein:$kernelspec-name

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-kernelinfo.el at Fri May 19 07:10:30 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-kill-ring.el at Fri May 19 07:10:30 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-log.el at Fri May 19 07:10:30 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-multilang-fontify.el at Fri May 19 07:10:30 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-multilang.el at Fri May 19 07:10:31 2017
ein-multilang.el:32:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-node.el at Fri May 19 07:10:31 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-notebook.el at Fri May 19 07:10:31 2017
ein-notebook.el:43:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-notebooklist.el at Fri May 19 07:10:31 2017
ein-notebooklist.el:33:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-notification.el at Fri May 19 07:10:31 2017
ein-notification.el:264:55:Warning: reference to free variable
    `ein:%notebook%'

In end of data:
ein-notification.el:392:1:Warning: the following functions are not known to be defined: ein:$notebook-kernelspec,
    ein:$kernelspec-name, ein:notebook-opened-buffer-names,
    ein:list-available-kernels, ein:$notebook-url-or-port,
    ein:notebook-switch-kernel

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-org.el at Fri May 19 07:10:31 2017
ein-org.el:30:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-output-area.el at Fri May 19 07:10:35 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-pager.el at Fri May 19 07:10:35 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-pseudo-console.el at Fri May 19 07:10:35 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-python.el at Fri May 19 07:10:35 2017
ein-python.el:31:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-pytools.el at Fri May 19 07:10:36 2017

In end of data:
ein-pytools.el:388:1:Warning: the following functions are not known to be defined: ein:notebook-buffer,
    ein:$notebook-notebook-name, ein:notebook-opened-notebooks,
    ein:notebook-to-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-query.el at Fri May 19 07:10:36 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-scratchsheet.el at Fri May 19 07:10:36 2017
ein-scratchsheet.el:29:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-shared-output.el at Fri May 19 07:10:36 2017
ein-shared-output.el:33:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-smartrep.el at Fri May 19 07:10:36 2017
ein-smartrep.el:29:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-subpackages.el at Fri May 19 07:10:36 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-traceback.el at Fri May 19 07:10:36 2017
ein-traceback.el:51:1:Warning: `(traceback ein:traceback)' is a malformed
    function
ein-traceback.el:51:15:Warning: reference to free variable `ein:tb-get-buffer'
ein-traceback.el:52:29:Warning: reference to free variable `traceback'
ein-traceback.el:61:1:Warning: `(traceback ein:traceback)' is a malformed
    function
ein-traceback.el:61:15:Warning: reference to free variable `ein:tb-render'
ein-traceback.el:61:56:Warning: reference to free variable `tb-data'
ein-traceback.el:73:1:Warning: `(traceback ein:traceback)' is a malformed
    function
ein-traceback.el:73:15:Warning: reference to free variable `ein:tb-popup'
ein-traceback.el:93:1:Warning: `(traceback ein:traceback)' is a malformed
    function
ein-traceback.el:93:15:Warning: reference to free variable
    `ein:tb-range-of-node-at-point'
ein-traceback.el:100:1:Warning: `(traceback ein:traceback)' is a malformed
    function
ein-traceback.el:100:15:Warning: reference to free variable
    `ein:tb-file-path-at-point'
ein-traceback.el:114:1:Warning: `(traceback ein:traceback)' is a malformed
    function
ein-traceback.el:114:15:Warning: reference to free variable
    `ein:tb-file-lineno-at-point'
ein-traceback.el:122:1:Warning: `(traceback ein:traceback)' is a malformed
    function
ein-traceback.el:122:15:Warning: reference to free variable
    `ein:tb-jump-to-source-at-point'
ein-traceback.el:123:44:Warning: reference to free variable `&optional'
ein-traceback.el:123:54:Warning: reference to free variable `select'

In end of data:
ein-traceback.el:181:1:Warning: the following functions are not known to be defined: cl-defmethod,
    ein:tb-get-buffer, ein:tb-render, ein:tb-popup,
    ein:tb-range-of-node-at-point, ein:tb-file-path-at-point,
    ein:tb-file-lineno-at-point, ein:$notebook-worksheets,
    ein:worksheet-get-cells, ein:notebook-buffer,
    ein:tb-jump-to-source-at-point

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-utils.el at Fri May 19 07:10:36 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-websocket.el at Fri May 19 07:10:37 2017

Compiling file /home/fbraenns/.emacs.d/elpa/ein-20170516.1307/ein-worksheet.el at Fri May 19 07:10:37 2017
ein-worksheet.el:34:1:Error: Symbol's value as variable is void: ein:cell-to-nb4-json

**Comment by millejoh** [comment]
Only the version of ein from MELPA stable is still compatible with emacs 24, unfortunately. Also I am not sure there is an easy way to make spacemacs download from MELPA stable.

Is upgrading to Emacs 25 a viable option?

**Comment by fab6** [comment]
Yes, sorry I missed this requirement. I will update emacs to 25.2. Thanks!
