### ISSUE TITLE
Maximum string size exceeded

### ISSUE THREAD

**Issue by maxhgerlach** [millejoh/emacs-ipython-notebook#21]
Thanks for reviving EIN! It is a pleasure to be able to work with ipython notebooks in Emacs again. I am experiencing a technical issue, though:

Working with a notebook that contains some inline plots, after a while Emacs (version 24.3.1) gives me messages "Maximum string size exceeded" after trying to do virtually anything -- even `M-x kill-emacs` only gives this message, but does nothing.

At least according to `htop` there is not a lot of memory is consumed. Do you have any clou what could be going on?

**Comment by millejoh** [comment]
Not really, sorry. I haven't had this particular error pop up in my day-to-day use of ein. I dimly remember getting a similar error during debugging -  but my memory is probably faulty.

If you want you can send me your notebook and see if I can run it and see if I get the same error, though I am busy with work at the moment and it probably won't be until sometime next week that I can take a look at this.
