### ISSUE TITLE
org-mode link no longer working in notebook

### ISSUE THREAD

**Issue by reconmaster** [millejoh/emacs-ipython-notebook#210]
I've noticed that with my latest version of EIN (ein-20170518.1252), when I try to use the org-mode store link in a notebook in EIN, I now get the following error:

```
user-error: No method for storing a link from this buffer
```

I was very pleased when this functionality was introduced, and it was working fine until somewaht recently.  Searching through the issues, I noticed #99  produced a similar error message. Not sure where this problem is arising, but let me know if I can provide any additional information.

**Comment by millejoh** [comment]
Issue was that starting in org 9 everything is done using `org-set-link-parameters`. Fixing this was exceptionally tedious, but I think I got it - fixes should be appearing in MELPA very soon.

**Comment by reconmaster** [comment]
Looks like everything is copacetic. Thanks for fixing this. It is an incredibly useful for keeping track of where everything is.
