### ISSUE TITLE
AUCTeX / Latex in Raw cells

### ISSUE THREAD

**Issue by visionnoob** [millejoh/emacs-ipython-notebook#212]
First of all, thanks a lot for maintaining this package. 

I would like to have Latex markup in Raw cells and then run nbconvert to generate a pdf.  

With respect to #171   

In order to enable latex as major-mode when editing raw cells, I modified the function `ein:create-edit-cell-buffer` in `ein-cell-edit.el` as follows: 

```
(condition-case e
    (ein:case-equal type
      (("markdown") (markdown-mode))
      (("raw") (TeX-latex-mode))
      (("code")
       (case (ein:get-mode-for-kernel (ein:$notebook-kernelspec notebook))
	 (python (python-mode)))))
```

It seems to work but I do not know if it will break something else down the line. Do you have a better local solution to add to my .emacs so that latex support is untouched if I update EIN? 

I was thinking of `(add-hook 'ein:edit-cell-mode-hook '(setq-default major-mode 'latex-mode))` but I guess that creates more problems than it solves.
  
P.S Btw, I do not know emacs lisp well. I just hack around to my solution.

**Comment by millejoh** [comment]
If you are embedding mostly math in your LaTeX fragments you might want to try setting `markdown-enable-math` to `T`, or call `markdown-toggle-math` in the edit buffer.

Your modification is great, but I don't think it is the best for everyone. I think the Right Thing in this case is to make some or all of these user-customizable variables, or have some sort of user hook as you suggest above. I think it also would be desirable to detect if the cell is html or javascript (ala `%%html` or `%%javascript`) or whatever and have EIN do the right thing.

Okay - adding this to my list of Things To Do. Thanks for the suggestion.

**Comment by visionnoob** [comment]
Yes, ok. Looking forward to this feature update :)

**Comment by millejoh** [comment]
I pushed a commit late yesterday that should support this. Check the commit note for details, but by default EIN will use LaTEX-mode for raw cells. It will also detect if you use magic like %%latex or %%html and use the appropriate mode.

**Comment by visionnoob** [comment]
cell magic and latex as default behaviour works! Thank you so much! makes me want to learn elisp all the more. Have a nice weekend!
