### ISSUE TITLE
I can't use ein:jupyter-server-start and connect my code to a notebook

### ISSUE THREAD

**Issue by lucaspeixotot** [millejoh/emacs-ipython-notebook#217]
Before everything, I'm a very beginner in emacs and I don't have much experience, so I'm sorry for any stupid questions. I have some problems.

1. I could not start jupyter server by ein:jupyter-server-start command. When I execute the emacs ask me "Server command" and "Notebook directory", I don't have idea what I need exactly write in this two questions. Because this, my jupyter server is not running by this way. I have to create jupyter server in terminal, so I copy the token and then use ein:notebooklist-login to connect(this is a bit tiring).

2. When I connect to the jupyter I open a notebook named test.ipynb, next I open my script in another buffer. I think that now, all I need is connect my python script buffer to my test notebook, and execute my code on notebook to see the outputs. For this I'm using ein:connect-to-notebook, but it asks me "Notebook to connect: [URL-OR-PORT/NAME]" and when I read this I thought that this would be "http://localhost:8888/test.ipynb" or "http://127.0.0.1:8888/test.ipynb" or "8888/test.ipynb" but this gave me something like "ein: [info] Notebook http://localhost:8888/test.ipynb not found", "ein: [info] Notebook http://127.0.0.1:8888/test.ipynb not found" and "wrong type argument: number-of-marker-p, nil", respectively.

PS: My notebook buffer named "ein: http://127.0.0.1:8888/test.ipynb", it was created in main page of my jupyter.

I know that my issue is very beginner and probabily my questions would be easily solved by many. However, for being easy questions I didn't get answers in my searches. My goals is have my code and jupyter notebook side by side, execute cells in my code and see the execution in jupyter, I feel I'm very close to this. May someone help me, please?

**Comment by millejoh** [comment]
The command you want to use is `ein:connect-to-notebook-buffer` and select the name of the buffer that test.ipynb has been opened as. This command is used when connecting to an already opened notebook buffer.

`ein:connect-to-notebook` will try to list all the notebooks available on the currently running jupyter notebook session, open or not. You need to specify the path (in your case probably just `test.ipynb` or `/test.ipynb` to the notebook, but not the host or port. I don't use this function very often, but I do know it has some problems, especially when a user has a large number of notebooks in their system.

For "Server Command" you want to enter the path to the jupyter executable. At the shell you can try executing `which jupyter` and it will report the path. 

For "Notebook Directory" you want to enter the path to where you keep all your notebooks. What is the path when you start jupyter in the terminal?

Once you know the path to the jupyter executable, I would do the following.

1. `M-x customize-variable RET ein:jupyter-default-server-command` and set the value to the path you determined above.
2. `M-x customize-variable RET ein:jupyter-default-notebook-directory` and set it to the path where you are keeping your jupyter notebooks.

Good luck.

**Comment by lucaspeixotot** [comment]
Thank you man, you were really good. With "which jupyter" and setting the Notebook Directory I was able to open my jupyter server easily and using "ein:connect-to-notebook-buffer" I was able to connect my code buffer and notebook as well. If it's not a problem, I have one more question. I split my window in 2 buffers, my text code and my notebook in jupyter. Are there EIN hotkeys or something similar that execute my lines of code in the notebook buffer? I mean that I don't have that copy my lines, switch window to the notebook buffer windown and paste there my code then press ALT-RET to execute my cells.

**Comment by millejoh** [comment]
Once you execute `ein:connect-to-notebook-buffer` you should be able to execute the buffer contents in the running notebook kernel via `C-c C-c`. Check out the [documentation](http://millejoh.github.io/emacs-ipython-notebook/#connected-buffer) for other key-bindings.

**Comment by Nicholas-Mitchell** [comment]
@millejoh  I would suggest linking the setup explanation you provided above to the homepage. Even just a few lines of it under the part explaining to set those variables. It will save newcomers a lot of time  :)
