### ISSUE TITLE
 Unknown method kind :around

### ISSUE THREAD

**Issue by khourhin** [millejoh/emacs-ipython-notebook#219]
Hi, 

I just updated my version of ein through `list-package` (now 20170612.1430 installed) and I cannot login anymore:
`M-x ein:notebooklist-login` gives me the message:

> Unknown method kind :around

Please let me know if you need more information.

Finally, thanks a lot for taking care of ein! It has been really useful to me for the past 6 months !

Cheers

Etienne

**Comment by millejoh** [comment]
What version of Emacs are you running? It sounds like you are missing cl-generic, which is weird since I thought the Emacs package manager would make sure to install all dependencies listed in ein's pacakge file (see ein-pkg.el).

**Comment by khourhin** [comment]
I was running 24.5+1-6ubuntu1. Indeed the package manager installed all dependencies and I was having cl-generic apparently properly installed.

I took benefit from this to move to emacs25. After fresh install of emacs25 and ein, no errors anymore. Not a proper solution, but at least a workaround.
