### ISSUE TITLE
Cannot open notebook created in chrome

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#220]
Now that I recovered from issue#213, I am trying to `[Open]` a notebook I created using Chrome and I am getting this error:
```
(wrong-type-argument symbol (quote input-prompt-number) slot)
```
backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument symbol (quo
  signal(wrong-type-argument (symbol (quote input-prompt-numbe
  eieio-oref(#13=#s(#8=#s(eieio--class ein:codecell nil (#2=#s
  #[(cell) "\302\303\304\305\306\"\203\307\310\"\206
  apply(#[(cell) "\302\303\304\305\306\"\203\307\310\"
  ein:cell-insert-prompt(#13=#s(#8=#s(eieio--class ein:codecel
  ein:cell-pp(#13=(prompt) #14=#s(#8=#s(eieio--class ein:codec
  ein:worksheet-pp(#13=[cl-struct-ein:$node (cell prompt) #s(#
  ewoc--refresh-node(ein:worksheet-pp #1=[#3=[#2=[#4=[#1# #2# 
  ewoc--insert-new-node(#1=[#3=[#2=[#14=[#1# #2# DL-LIST #<mar
  ewoc-enter-before(#13=#s(ewoc #<buffer *ein: http://127.0.0.
  ewoc-enter-last(#13=#s(ewoc #<buffer *ein: http://127.0.0.1:
  #[(&rest path) "\303\304\302        B\n\"\"\207" [ewoc pat
  ein:cell-make-element(#[(&rest path) "\303\304\302  B\n\"\
  #[(cell) "\305\301\"\306\307\n\310!\"\311\f\30
  apply(#[(cell) "\305\301\"\306\307\n\310!\"\31
  ein:cell-enter-last(#13=#s(#8=#s(eieio--class ein:codecell n
  #[(c) "\303       \302\n#\210)\304!\207" [c v ewoc eie
  mapc(#[(c) "\303  \302\n#\210)\304!\207" [c v ewoc eie
  #[(ws) "r\306!q\210\307\310 \210\311\312\313\314!\31
  apply(#[(ws) "r\306!q\210\307\310 \210\311\312\313\3
  #[385 "\301\302\303\304\305!\306\"\307$\310K\311K\301\
  apply(#2=#[385 "\301\302\303\304\305!\306\"\307$\310K\
  #[128 "\302\300\303\304\305\306\307\301\"\310\"\311\312%
  apply(#[128 "\302\300\303\304\305\306\307\301\"\310\"\31
  ein:worksheet-render(#11=#s(#2=#s(eieio--class ein:worksheet
  ein:notebook--worksheet-render(#11=#s(ein:$notebook #1="http
  ein:notebook-from-json(#11=#s(ein:$notebook #1="http://127.0
  ein:notebook-request-open-callback(#11=#s(ein:$notebook #1="
  ein:notebook-request-open-callback-with-callback(#11=#s(ein:
  apply(ein:notebook-request-open-callback-with-callback (#11=
  #[128 "\302\300\303\301\"\"\207" [ein:notebook-request-ope
  ein:new-content(#86=#s(ein:$content "http://127.0.0.1:8888" 
  apply(ein:new-content (#86=#s(ein:$content "http://127.0.0.1
  #[128 #1="\302\300\303\301\"\"\207" [ein:new-content (#s(e
  apply(#87=#[128 #1="\302\300\303\301\"\"\207" [ein:new-con
  apply(apply #87=#[128 #1="\302\300\303\301\"\"\207" [ein:n
  request--safe-apply(#87=#[128 #1="\302\300\303\301\"\"\207
  request--callback(#<killed buffer> :type #88="GET" :timeout 
  apply(request--callback #<killed buffer> #88=(:type "GET" :t
  request--curl-callback(#<process request curl> "finished\n")
```

**Comment by millejoh** [comment]
If I interpret the backtrace correctly, emacs is complaining that `'input-prompt-number` is not a symbol - which seems nonsensical to me.

This is looksto be happening in `ein:cell-insert-prompt` called with a codecell instance and while trying to determine the input prompt number. The codecell instance should have a slot named `input-prompt-number` and the code wraps access to the slot via `ein:oref-safe` which is a macro that checks the slot is bound before calling `slot-value`.

It's possible something weird is happening with the macro expansion. Maybe re-evaluating or byte-compiling the entire file (ein-cell.el) will help?

If you can I recommend deleting all of ein's elc files and then restarting emacs and finally follow up with a call to `ein:byte-compile-ein`.

**Comment by sam-s** [comment]
`ein:byte-compile-ein` failed on compiling `ein-ac` because I did not have `auto-complete` installed.
It appears that `auto-complete` is *not* optional (despite being described as such in `README`).

**Comment by sam-s** [comment]
After installing `auto-complete`, running `ein:byte-compile-ein`, and reloading all `*.elc`, it seems to be working now.
Thank you very much!
PS. I urge you to mark `ac` as required.

**Comment by millejoh** [comment]
Thanks Sam. I agree that and will add autocomplete to the requirements, though the list of dependencies is starting to become a bit long. 

I have been thinking since there are now multiple completion options for EIN (autocomplete, jedi+autocomplete, and company) it might make sense to split each of these into their own package.

It seems the right thing to do design wise, but I fear in doing so I will break a lot of people's installations so maybe not so good an idea after all. Maybe EIN is destined to be this huge, sprawling monolithic package.

**Comment by sam-s** [comment]
I am afraid the solution was bad.
When enabled, `auto-complete` competes with `company`.
It would be nice if ein could work without it.
For now, setting `ein:use-auto-complete` to `nil` seems to work.
