### ISSUE TITLE
Plot Images Don't Show Around Markdown Cells

### ISSUE THREAD

**Issue by jcpetkovich** [millejoh/emacs-ipython-notebook#221]
This issue started after I recently update elpa packages. I can't quite pin down the cause. It is reproducible even with zeroein.el on the latest version of `ein`.

I can reproduce it with the following notebook:

```python
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
```
```markdown
This is a markdown cell
```

```python
plt.plot(np.random.randn(1000), np.random.randn(1000))
```

The steps to reproduce:
1. start a jupyter notebook
2. create a new notebook from emacs (`ein:notebooklist-open` etc.)
3. fill in with above template *without* the markdown
4. run the plot cell
5. observe plot, check plot with `M-x describe-text-properties`, display property present.
6. add markdown cell
7. run plot cell again
8. observe plot missing with only "." present, check plot with `M-x describe-text-properties`, display property not present.

**Comment by millejoh** [comment]
Thanks, I am seeing this on my work machine which runs emacs 25 and downloads using the spacemaces ipython-noteobok layer, but not on my development machine which runs emacs 26.0.50.

Could you run `ein:dev-bug-report-template` and send me the info it generates regarding your system setup?

**Comment by millejoh** [comment]
If I uninstall the markdown [layer](http://spacemacs.org/layers/+lang/markdown/README.html) on my work machine running Emacs 25.1+spacemacs the problem goes away. I don't think this is EIN, but rather something happening with on of the packages installed by spacemacs. I'll post again when I know some more of what is going on.

**Comment by jcpetkovich** [comment]
As requested.

```cl
("EIN system info"
 :emacs-version "GNU Emacs 25.2.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.15)
 of 2017-06-19"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux tellan 4.7.9-gentoo #1 SMP Sun Nov 6 13:54:51 EST 2016 x86_64 Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz GenuineIntel GNU/Linux
"
  :lsb-release
  "LSB Version:	n/a
Distributor ID:	Gentoo
Description:	Gentoo Base System release 2.3
Release:	2.3
Codename:	n/a
")
 :image-types
 (svg png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.13.0"
           :source-dir "/home/jcp/.emacs.d/elpa/ein-20170616.1117/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/elpa/websocket-20170610.2117/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.5")
  (:name "request"
         :path "~/.emacs.d/elpa/request-20170131.1747/request.elc"
         :featurep t
         :version-var request-version
         :version "0.3.0")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20170124.1845/auto-complete.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20170124.1845/auto-complete.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/elpa/popup-20160709.729/popup.elc"
         :featurep t
         :version-var popup-version
         :version "0.5.3")
  (:name "fuzzy"
         :path "~/.emacs.d/elpa/fuzzy-20150729.2037/fuzzy.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "pos-tip"
         :path "~/.emacs.d/elpa/pos-tip-20150318.813/pos-tip.elc"
         :featurep t
         :version-var pos-tip-version
         :version "0.4.6")
  (:name "python"
         :path "/usr/share/emacs/25.2/lisp/progmodes/python.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path "~/.emacs.d/elpa/markdown-mode-20170618.1607/markdown-mode.elc"
         :featurep t
         :version-var markdown-mode-version
         :version "2.3-dev")
  (:name "helm"
         :path "~/.emacs.d/elpa/helm-core-20170619.518/helm.elc"
         :featurep t
         :version-var nil
         :version nil)))
```

**Comment by jcpetkovich** [comment]
I can confirm that removing the markdown layer appears to fix this, although I'm a bit at a loss as to why.

**Comment by jcpetkovich** [comment]
It seems like the markdown-toc package. When I exclude that package it works.

**Comment by jcpetkovich** [comment]
This is confusing, whenever I have markdown-toc or markdown-mode enabled, the problem happens. If I comment out both packages in the markdown-packages list, then plots show just fine.

**Comment by millejoh** [comment]
@jcpetkovich, Plots have suddenly started appearing for me again with the markdown layer installed - are you seeing the same?

**Comment by jcpetkovich** [comment]
No, I am not, did you update anything?

**Comment by millejoh** [comment]
Turns out I set `ein:notebook-modes` to `'(ein:notebook-python-mode)`. Whatever is happening, it appears to be interaction between markdown-mode and ein:notebook-multilang-mode.

**Comment by jcpetkovich** [comment]
This is a decent workaround for now. Any ideas what that interaction might be?

**Comment by jcpetkovich** [comment]
Tried narrowing down the problem. Commenting out the "Font lock" section of  `markdown-mode` seems to allow plots to show. Can't quite figure out what part yet.

**Comment by millejoh** [comment]
Thanks, and interesting. I am not sure how it is happening, but somehow the code in markdown-mode is causing the 'display property to be set to NIL throughout the notebook buffer. And not just the one notebook buffer with the markdown cell - this starts occurring with all other noteboko buffes whether they have markdown cells or not.

**Comment by millejoh** [comment]
This looks fixed with the most recent markdown-mode update. Let me know if that is not the case with you.

**Comment by jcpetkovich** [comment]
Looks fixed to me!

**Comment by Ariussssss** [comment]
```
M-x customize-group RET ein
  Ein:Output Area Inlined Images
```
Turn it on and it works for me.
Relative: https://awesomeopensource.com/project/millejoh/emacs-ipython-notebook
