### ISSUE TITLE
How do I revert the notebook?

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#222]
is there a way to reload a notenbook modified by Chrome?
(all I can do now is kill the buffer and re-open it)
thanks!

**Comment by millejoh** [comment]
I'm not 100% sure it is the behavior you want, but you can try `ein:notebook-restore-to-checkpoint`. I think when you save via the web interface it will automatically create a checkpoint.

If that doesn't do what you want then it shouldn't be too hard to add a new command to reload the notebook. And while I'm at it I should probably implement #215 as well.
