### ISSUE TITLE
ein:company-backend provides spurious completions that do not begin with the prefix typed

### ISSUE THREAD

**Issue by LordZorgoth** [millejoh/emacs-ipython-notebook#225]
ein:company-backend provides spurious competions that do not begin with the prefix typed. See "Steps to reproduce the problem" for details. This bug is probably closely related to the bug report I just filed about relative paths not completing correctly, https://github.com/millejoh/emacs-ipython-notebook/issues/224. However, this bug is even more of a problem, as even simple Python expressions result in wacky completions, essentially preventing the user from being able to safely press `RET`.

## Check list

- [*] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [*] Does IPython works from the web browser?
- [*] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [*] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have

ein:company-backend provides completions for IPython magic without typing a `%`. This is a major problem, because `%` is alphabetically before all letters, so if you type something like `a` and hit enter, you will get something like `%alias` 

## Steps to reproduce the problem

1. Start an IPython notebook

2. Enable Company mode using `M-x company-mode` and by adding `ein:company-backend` to the list of company backends using `M-x customize`.

3. Type a friendly little `a=5` and execute using `M-RET`

4. Execute the elisp expressions `(setq-local company-minimum-prefix-length 1)` and `(setq-local company-dabbreb-minimum-length 1)` in the IPython notebook by typing them in somewhere and hitting `C-x C-e` after the `)`s.

5. Let's say we want to remember what `a` was. So we type `a`.

6. Wait for the company completions to show up. You don't get `a` first. The first thing that comes up is `%alias`, because ein:company-backend simply ignores the % when determining a match! If you were to tpye ENTER, you'd get `%alias` instead of `a`, becasue `%` comes before `a` alphabetically!

But wait, it gets worse... Try this one:

Repeat steps 1--3 from before.

4b. Type "print(a)" and wait for the completions menu to come up. If you naively hit `ENTER` at this point, you will get `pri%%!`, which I'm sure no one wants. In fact, it seems that `print(a)` gives a list of everything in the dictionary.

## Expected output

In step 6, the first completion should have been a. In step 4b, there should have been no completions at all.

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`): 6.1.0

2. How do you start IPython? (e.g., `ipython notebook --port 9999`): jupyter notebook --port 9999

3. What is your IPython notebook port number or URL?: 9999

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21)
 of 2017-05-22"
 :emacs-bzr-version nil
 :window-system mac
 :emacs-variant nil
 :os
 (:uname
  "Darwin Jonathans-MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
"
  :lsb-release nil)
 :image-types
 (svg image-io imagemagick png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (svg image-io imagemagick png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.13.0"
	   :source-dir "/Users/jonathan/.emacs.d/elpa/ein-20170616.1117/")
 :lib
 ((:name "websocket"
	 :path "~/.emacs.d/elpa/websocket-20170610.2117/websocket.elc"
	 :featurep t
	 :version-var websocket-version
	 :version "1.5")
  (:name "request"
	 :path "~/.emacs.d/elpa/request-20170131.1747/request.elc"
	 :featurep t
	 :version-var request-version
	 :version "0.3.0")
  (:name "auto-complete"
	 :path "~/.emacs.d/elpa/auto-complete-20170124.1845/auto-complete.elc"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "auto-complete"
	 :path "~/.emacs.d/elpa/auto-complete-20170124.1845/auto-complete.elc"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "popup"
	 :path "~/.emacs.d/elpa/popup-20160709.729/popup.elc"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "python"
	 :path "/Applications/Emacs.app/Contents/Resources/lisp/progmodes/python.elc"
	 :featurep t
	 :version-var nil
	 :version nil)))
```

**Comment by millejoh** [comment]
I think commit 08d2792d690cefb9ef2e00a14d3bbb1da55252a9 should help with this problem. I have introduced a new variable `ein:completion-backend`. 

If you want to use company call  `(setq ein-completion-backend 'ein:use-company-backend)` before loading ein. You shouldn't need to do anything else in your configuration, though I would recommend restarting emacs before opening a notebook.

If you have existing code that tries to enable company-mode in ein notebook buffers I would remove it.

**Comment by millejoh** [comment]
I followed your steps, but the first completion candidate that comes up is 'a' in my setup. Note that I've just commited some changes (08d2792d690cefb9ef2e00a14d3bbb1da55252a9) to streamline how one chooses a completion backend. See the documentation for variable `ein:completion-backend`.

**Comment by sam-s** [comment]
I am far far too busy ATM to file a similarly detailed report, but I do get a HUMONGOUS list of possible completions after a space(!!!), starting with `" %%!"` then `" %%HTML"`, then `" %%SVG"` ...
it is a major nuisance.

**Comment by millejoh** [comment]
I know what is causing this, if not exactly why. I have a workaround, but I too am a bit busy. Maybe later today I can push something out.

John

**Comment by millejoh** [comment]
@LordZorgoth. It was a long summer. Fall isn't looking much better but I think I've addressed the issue you so thoroughly documented. If you are updating through MELPA you should try updating later today.

@sam-s - it was even worse than that. Most types of punctuation seemed to be triggering the behavior. But no longer, I hope. I've probably missed something so let me know if it continues to crop up.
