### ISSUE TITLE
SSL Error on 28 on login to server

### ISSUE THREAD

**Issue by tim-tx** [millejoh/emacs-ipython-notebook#226]
When I do `ein:notebooklist-login` on my server, set up in the [normal fashion](http://jupyter-notebook.readthedocs.io/en/latest/public_server.html) with a self-signed certificate, I see `SSL Error on 28 ('<MY-IP-HERE>', 56116): [SSL: HTTP_REQUEST] http request (_ssl.c:749)` in the server console. Changing the request backend to `url-retrieve` as suggested [here](https://github.com/millejoh/emacs-ipython-notebook/issues/94#issuecomment-204071178) let me login, accept the cert, and open the notebook list, though I did also see from the server:

    [W 13:39:08.276 NotebookApp] 403 POST /login (<MY-IP-HERE>): '_xsrf' argument missing from POST
    [W 13:39:08.278 NotebookApp] 403 POST /login (<MY-IP-HERE>) 4.36ms referer=None

**Comment by reconmaster** [comment]
I've had sporadic issues with hosting an encrypted notebook server. For now I've had a fair amount of success using cur with the caveat that you will need to do something like

```
echo "insecure" > .curlrc
```

if you want to avoid the issue (which I think this is) of the server not liking the self-signed certificate. If that doesn't get you sorted, I'll take a look at my notes about my latest fix. I've had a number of issues relating to this which may help you out #182, #94 , #89 .

**Comment by tim-tx** [comment]
The `.curlrc` trick seems to have helped, thanks.

**Comment by millejoh** [comment]
Thanks gentlemen - I have updated the [Tips](https://github.com/millejoh/emacs-ipython-notebook/wiki/Tips) page on the wiki based on this information. Hope I paraphrased things well!
