### ISSUE TITLE
Out Displayed as XML

### ISSUE THREAD

**Issue by kevinjfoley** [millejoh/emacs-ipython-notebook#228]
## Check list

- [X] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [X] Does IPython works from the web browser?
- [X] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [X] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have
When I try to view DataFrames the results seem to be displayed as XML.  Using the print function displays the DataFrame properly.  Also if I close and reopen the notebook the results will be displayed properly until I rerun that cell.

![image](https://user-images.githubusercontent.com/11020413/28096353-24f6743c-6676-11e7-89fa-7795aeb9cadf.png)

## Your EIN configuration (in .emacs.d/init.el or somewhere else)

```
(use-package ein
    :commands (ein:notebooklist-open))
```

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):
5.3.0

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):
`ipython notebook`

3. What is your IPython notebook port number or URL?:
8888
## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.31)
 of 2017-07-02"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux ubuntu-laptop 4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
"
  :lsb-release
  "No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
")
 :image-types
 (png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.13.0"
	   :source-dir "/home/kevin/.emacs.d/lib/ein/lisp/")
 :lib
 ((:name "websocket"
	 :path "~/.emacs.d/lib/websocket/websocket.elc"
	 :featurep t
	 :version-var websocket-version
	 :version "1.5")
  (:name "request"
	 :path "~/.emacs.d/lib/request/request.elc"
	 :featurep t
	 :version-var request-version
	 :version "0.3.0")
  (:name "python"
	 :path "/usr/local/share/emacs/25.2/lisp/progmodes/python.elc"
	 :featurep t
	 :version-var nil
	 :version nil)))
```

**Comment by millejoh** [comment]
EIN tries to detect when a dataframe is being printed and print a readable result, which it is doing at least on my similarly-configured system. The only difference is that I'm running on Windows at the moment - when I get a chance I'll check my Linux setup.

A few questions:

1. What version of pandas are you using?
2. Have you set any display options elsewhere in your notebook (i.e. via `pd.options.set_option()`).
3. What happens when you execute `x.style`?

**Comment by kevinjfoley** [comment]
I had a friend take a look and they weren't having the same issue on their Linux setup if that helps.

1. 0.20.1
2. Nope, no display options set
3. I get the following:
```
<style  type="text/css" >
</style>  
<table id="T_216ed9fc_6771_11e7_b98a_a434d913c13a" > 
<thead>    <tr> 
        <th class="blank level0" ></th> 
        <th class="col_heading level0 col0" >0</th> 
        <th class="col_heading level0 col1" >1</th> 
        <th class="col_heading level0 col2" >2</th> 
        <th class="col_heading level0 col3" >3</th> 
        <th class="col_heading level0 col4" >4</th> 
        <th class="col_heading level0 col5" >5</th> 
        <th class="col_heading level0 col6" >6</th> 
        <th class="col_heading level0 col7" >7</th> 
        <th class="col_heading level0 col8" >8</th> 
    </tr></thead> 
<tbody>    <tr> 
        <th id="T_216ed9fc_6771_11e7_b98a_a434d913c13a" class="row_heading level0 row0" >0</th> 
        <td id="T_216ed9fc_6771_11e7_b98a_a434d913c13arow0_col0" class="data row0 col0" >1</td> 
        <td id="T_216ed9fc_6771_11e7_b98a_a434d913c13arow0_col1" class="data row0 col1" >2</td> 
        <td id="T_216ed9fc_6771_11e7_b98a_a434d913c13arow0_col2" class="data row0 col2" >3</td> 
        <td id="T_216ed9fc_6771_11e7_b98a_a434d913c13arow0_col3" class="data row0 col3" >4</td> 
        <td id="T_216ed9fc_6771_11e7_b98a_a434d913c13arow0_col4" class="data row0 col4" >5</td> 
        <td id="T_216ed9fc_6771_11e7_b98a_a434d913c13arow0_col5" class="data row0 col5" >6</td> 
        <td id="T_216ed9fc_6771_11e7_b98a_a434d913c13arow0_col6" class="data row0 col6" >7</td> 
        <td id="T_216ed9fc_6771_11e7_b98a_a434d913c13arow0_col7" class="data row0 col7" >8</td> 
        <td id="T_216ed9fc_6771_11e7_b98a_a434d913c13arow0_col8" class="data row0 col8" >9</td> 
    </tr></tbody> 
</table>
```

**Comment by millejoh** [comment]
@kevinjfoley, what is the setting for the variable `ein:output-type-preference`? If it isn't already, try setting it to `ein:output-type-prefer-pretty-text-over-html`.

**Comment by kevinjfoley** [comment]
@millejoh - it was originally `emacs-lisp svg image/svg png image/png jpeg image/jpeg html text/html latex text/latex javascript text/javascript text text/plain` 
After running `(setq ein:output-type-preference 'ein:output-type-prefer-pretty-text-over-html)` things seem to be working properly.  Thanks for your help!
