### ISSUE TITLE
doc bug: emacs -Q -l lisp/zeroein.el does not work

### ISSUE THREAD

**Issue by holtzermann17** [millejoh/emacs-ipython-notebook#230]
https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md says to try zeroein, but links to [this page](http://millejoh.github.io/emacs-ipython-notebook/#quick-try) which says it is not supported but should still work.

It doesn't seem to work.

```
joe@Teacup:~$ git clone git://github.com/tkf/emacs-ipython-notebook.git
Cloning into 'emacs-ipython-notebook'...
remote: Counting objects: 7463, done.        
remote: Total 7463 (delta 0), reused 0 (delta 0), pack-reused 7463        
Receiving objects: 100% (7463/7463), 4.43 MiB | 947.00 KiB/s, done.
Resolving deltas: 100% (4433/4433), done.
Checking connectivity... done.
[1]+  Done                    gnome-terminal
joe@Teacup:~$ cd emacs-ipython-notebook/
joe@Teacup:~/emacs-ipython-notebook$ emacs -Q -l lisp/zeroein.el
```

I then try to run `M-x ein:notebooklist-login` but I get "[no match]".

**Comment by millejoh** [comment]
zeroein is a remnant of when @tkf was the man (well, he's still the man as far as I'm concerned, just not for ein). I'll take a look at it and see what's broken, but the best way to get EIN working these days is to download from MELPA or el-get, or via spacemacs.

I'd also recommend trying `ein:jupyter-server-start` which attempts to automate the process of starting a jupyter notebook server, authenticate, and open the notebooklist. See my soon-to-be comments in #231 .
