### ISSUE TITLE
curl and url-retrieve backends support different functions

### ISSUE THREAD

**Issue by holtzermann17** [millejoh/emacs-ipython-notebook#231]
## Description of the problem you have

I can successfully run `M-x ein:notebooklist-login` with `request-backend` set to curl, but I then cannot successfully run  `M-x ein:notebooklist-open`.  If I change the request backend to `url-retrieve` I can then run the second command, but no longer the first.

It is worth noting that I have a password set in Jupyter, via `jupyter notebook --generate-config`. If that is not supported at this time, this explains the behaviour.

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):

$ jupyter notebook --version
5.0.0

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):

jupyter notebook

3. What is your IPython notebook port number or URL?:

8888

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 25.1.50.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.13)
 of 2016-08-15"
 :emacs-bzr-version "9c2ea5cdd626f011cb535824223e49e5bdb20146"
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux Teacup 3.19.0-84-generic #92-Ubuntu SMP Fri Mar 24 15:46:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
"
  :lsb-release
  "No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend url-retrieve)
 :ein
 (:version "0.13.0"
           :source-dir "/home/joe/.emacs.d/elpa/ein-20170803.629/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/elpa/websocket-20170610.2117/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.5")
  (:name "request"
         :path "~/.emacs.d/elpa/request-20170131.1747/request.elc"
         :featurep t
         :version-var request-version
         :version "0.3.0")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20170124.1845/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20170124.1845/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/elpa/popup-20160709.729/popup.elc"
         :featurep t
         :version-var popup-version
         :version "0.5.3")
  (:name "python"
         :path "/usr/local/share/emacs/25.1.50/lisp/progmodes/python.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path "~/postdoc.git/elisp/markdown-mode.el"
         :featurep t
         :version-var markdown-mode-version
         :version "2.0")
  (:name "helm"
         :path "~/postdoc.git/elisp/helm/helm.elc"
         :featurep t
         :version-var nil
         :version nil)))
```

**Comment by millejoh** [comment]
Part of the problem may be an out of date websocket.el - try upgrading to the most recent version, which should be 1.8. Once doing that if you still have issues please send me the output of the console where jupyter is running as well as the contents of the `*ein:log-all*` buffer. You can enable extra debugging information by calling `ein:dev-start-debug` before calling any of the notebooklist functions.

Note that you can start jupyter from Emacs by calling `ein:jupyter-server-start`. See the [docs](http://millejoh.github.io/emacs-ipython-notebook/#running-a-jupyter-notebook-server-from-emacs). Output from jupyter will go to the `*ein:jupyter-sever*` buffer.

**Comment by holtzermann17** [comment]
NB. trying to start jupyter with `ein:jupyter-server-start` gives an error in `*ein:jupyter-server*`:

> Error executing Jupyter command 'notebook': [Errno 2] No such file or directory
> 
> Process EIN: Jupyter notebook server exited abnormally with code 1

Websockets version is 1.8.

Here is the Jupyter console output on failed login, with `request-backend` set to `url-retrieve`.

```
joe@Teacup:~/ds4d/ds4d_labs/Week3$ jupyter notebook
[I 08:08:48.169 NotebookApp] Serving notebooks from local directory: /home/joe/ds4d/ds4d_labs/Week3
[I 08:08:48.169 NotebookApp] 0 active kernels 
[I 08:08:48.169 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 08:08:48.169 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[3613:3646:0824/080848.482271:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
Created new window in existing browser session.
[W 08:09:37.232 NotebookApp] 403 POST /login (127.0.0.1): '_xsrf' argument missing from POST
[W 08:09:37.239 NotebookApp] 403 POST /login (127.0.0.1) 6.85ms referer=None
[I 08:09:37.244 NotebookApp] 302 POST /login (127.0.0.1) 0.96ms
[W 08:09:37.246 NotebookApp] 405 POST / (127.0.0.1) 0.82ms referer=None

```

*ein:log-all* contents on failed login:

```
[debug] NOTEBOOKLIST-LOGIN: 8888 @#<buffer *shell*>
[debug] NOTEBOOKLIST-LOGIN: 8888 @#<buffer *mu4e-view*>
[info] Failed to login to 8888 @#<buffer *mu4e-view*>
[info] Failed to login to 8888 @#<buffer *mu4e-view*>
```

**Comment by millejoh** [comment]
Try setting `ein:jupyter-default-server-command` to the full path to the jupyter executable. On my Windows sytem the variable looks like this

 `c:/Users/E341194/AppData/Local/Continuum/Anaconda3_x86/Scripts/jupyter.exe`. 

EIN knows to call jupyter with the `notebook` command, so no need to specify that.

The _xsrf error may be related to #168. It looks like you have the latest version of emacs-request so it should be seeing the #HttpOnly cookies. You can find the cookie jar by looking at the value of `request-storage-directory`.

**Comment by holtzermann17** [comment]
No luck with starting the server with `ein:jupyter-default-server-command`, but I am finding that with the `curl` request backend, I can go through the whole process (assuming the server has been started separately). However, I get a debugger error when loading a notebook:

```
Debugger entered--Lisp error: (websocket-invalid-header . "Incorrect handshake from websocket: is this really a websocket connection?")
  signal(websocket-invalid-header "Incorrect handshake from websocket: is this really a websocket connection?")
  websocket-outer-filter([cl-struct-websocket closed [cl-struct-ein:$websocket #0 (lambda (&rest --cl-rest--) (apply (function #[(G300 packet) "\302J	\"\207" [G300 packet ein:kernel--handle-channels-reply] 3]) (quote --kernel--) --cl-rest--)) nil ein:kernel--ws-closed-callback ([cl-struct-ein:$kernel "http://127.0.0.1:8888" [eieio-class-tag--ein:events #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data (maybe_reset_undo\.Worksheet ((#[... "\301\302!!\205
```

Then if I try to evaluate a cell (<kbd>C-c C-c</kbd>), I see:

```
ein: [warn] Kernel is not ready yet! (or closed already.)
```

**Comment by holtzermann17** [comment]
I blanked out the cookie jar file `/home/joe/.emacs.d/request/curl-cookie-jar` and then got a different message, possibly more informative:

> ein: [info] Opened notebook list at http://127.0.0.1:8888 with path 
> ein: [info] Opening notebook 03-loop.ipynb...
> ein: [info] Reading nbformat4 notebook.
> ein: [info] Worksheet 03-loop.ipynb is ready
> ein: [info] Enabling autosaves for 03-loop.ipynb with frequency 60 seconds.
> ein: [info] Notebook 03-loop.ipynb is ready
> ein: [info] Kernel started: 3faedc2d-a815-4fd8-b93d-2405e3913374
> ein: [info] Starting channels WS: "ws://127.0.0.1:8888/api/kernels/3faedc2d-a815-4fd8-b93d-2405e3913374/channels?session_id=1f7baf18-382d-492f-be79-0768c1df29e1"
> websocket-outer-filter: Invalid HTTP header sent

**Comment by holtzermann17** [comment]
Here's the header in question (dumped out from `websocket-outer-filter`:

```
HTTP/1.1 101 Switching Protocols
Content-Length: 0
Sec-Websocket-Accept: 458//D9tye9a+zQfQzflpLl1rwY=
Date: Fri, 25 Aug 2017 17:35:35 GMT
Server: TornadoServer/4.5.1
Connection: Upgrade
Upgrade: websocket
```

**Comment by millejoh** [comment]
I haven't had _xsrf issues in some time, so you are going to have to do some extra sleuthing. First, delete and reinstall ein. Select curl as the backend for request. Restart emacs.

Then:

 1. Call `ein:dev-start-debug`. This will enable extra logging for EIN and websocket.
 2. Set `request-log-level` and `request-message-level` to `debug` (you can find both in the customization group for request).
 3. Try to open a notebook. When it fails I'll need dumps of the following.

   * The contents of the cookie jar file.
   * The contents of the websocket log buffer. The name of the buffer will start with `*websocket ws://`
   * All the messages generated by request while trying to connect to the kernel. These will be in the `*Messages*` buffer.

Good luck. I went through a similar exercise with issue #213 and #163. Note that we no longer need the `(advice-add 'request--netscape-cookie-parse :around #'fix-request-netscape-cookie-parse)` with current versions of request.

**Comment by duffer008** [comment]
i am also having trouble launching jupyter notebook because it says the requested url cannot be retreived

**Comment by millejoh** [comment]
Note that url-retrieve is essentially deprecated at this point. Also a lot of effort has gone into making the login and connection experience seamless and (mostly) painless. Given age and lack of current comments I am going to close this case out, but please do not hesitate to open a new issue with details of any new issues you may encounter.

**Comment by TobiasZawada** [comment]
Note, completely independent of ipython I also have problems with `url-retrieve` under Windows Subsystem For Linux WSL 1 and Ubuntu installed.

`wget` and `curl` do not work with https requests but `url-retrieve` does not. `url-retrieve` works with `http` requests. I noticed that strange behavior because of `package-refresh-contents` does not work.

Output of `uname -a`:
Linux XXX 4.4.0-17134-Microsoft #706-Microsoft Mon Apr 01 18:13:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
Output of `emacs-version`:
`GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-16`
