### ISSUE TITLE
Using obsolete ‘org-add-link-type’

### ISSUE THREAD

**Issue by benf-wspdigital** [millejoh/emacs-ipython-notebook#232]
As of Org version “20170731”, the ‘org-add-link-type’ function is obsolete and causes an error.

This was deprecated for a time, as acknowledged in commit b39634d64a13898e. But as of ‘ein’ version “0.12.8” it is still using the now-obsolete function.

This causes Emacs to fail when loading ‘ein’:

```
Lisp error: (void-function org-add-link-type)
  (org-add-link-type "ipynb" :follow (quote ein:org-open))
  (if (fboundp (quote org-link-set-parameters)) (org-link-set-parameters "ipynb" :follow (quote ein:org-open) :help-echo "Open ipython notebook." :store (quote ein:org-store-link)) (org-add-link-type "ipynb" :follow (quote ein:org-open)) (add-hook (quote org-store-link-functions) (quote ein:org-store-link)))
  (lambda nil (if (fboundp (quote org-link-set-parameters)) (org-link-set-parameters "ipynb" :follow (quote ein:org-open) :help-echo "Open ipython notebook." :store (quote ein:org-store-link)) (org-add-link-type "ipynb" :follow (quote ein:org-open)) (add-hook (quote org-store-link-functions) (quote ein:org-store-link))))()
  funcall((lambda nil (if (fboundp (quote org-link-set-parameters)) (org-link-set-parameters "ipynb" :follow (quote ein:org-open) :help-echo "Open ipython notebook." :store (quote ein:org-store-link)) (org-add-link-type "ipynb" :follow (quote ein:org-open)) (add-hook (quote org-store-link-functions) (quote ein:org-store-link)))))
  mapc(funcall ((lambda nil (if (fboundp (quote org-link-set-parameters)) (org-link-set-parameters "ipynb" :follow (quote ein:org-open) :help-echo "Open ipython notebook." :store (quote ein:org-store-link)) (org-add-link-type "ipynb" :follow (quote ein:org-open)) (add-hook (quote org-store-link-functions) (quote ein:org-store-link))))))
[…]
```

**Comment by millejoh** [comment]
@benf-wspdigital, this is fixed on master. I'm working on some changes to get master compatible with emacs 24 once again. Once I am comfortable things are working okay I will push out another release. I'm on vacation at the moment so it might be a week or so before I get to this.

Thanks for the report.

**Comment by millejoh** [comment]
Should be fixed in the latest 'official' release, which is v0.13.0. Let me know if you are still seeing this error.

**Comment by rocha** [comment]
@millejoh I am getting the same error in v0.13.0. There are still a few references to `org-add-link-type`, for example at the start of the `ein:org-open` function.

**Comment by rocha** [comment]
@millejoh I also get this error with `ein` `0.13.0` and `org` `9.1.2`.

**Comment by millejoh** [comment]
Maybe okay now? Do reopen this if not the case...
