### ISSUE TITLE
Parse notebook server tokens automatically

### ISSUE THREAD

**Issue by leezu** [millejoh/emacs-ipython-notebook#233]
Currently the user is required to call `ein:notebooklist-login` manually and provide the token / password before being able to interact with notebooks. Arguably in most cases however the notebook is running locally and the token can be obtained from the output of `jupyter notebook list`. When specifying the connecting string in `ein:notebooklist-open` I propose to run `jupyter notebook list` and check if a token is listed for the connection string specified. If so, `ein:notebooklist-login` should be called automatically with that token.

**Comment by millejoh** [comment]
This is a good idea and something to work towards; I wasn't aware of the `jupyter notebook list` command, so thanks!

In the meantime the functions `ein:jupyter-server-start` and `ein:jupyter-server-login-and-open` do something similar to what you propose by running a jupyter notebook process from Emacs and scanning the output for the token authentication data. It's not bulletproof (curse you async programming), but great when it works.

**Comment by millejoh** [comment]
EIN now has this! Many thanks to @dickmao for implementing.
