### ISSUE TITLE
Keeping kernel alive after losing connection?

### ISSUE THREAD

**Issue by kootenpv** [millejoh/emacs-ipython-notebook#234]
I'm wondering if it is possible to start an EIN notebook, and then connect to an existing kernel after emacs closes (and opens again)?
Thanks a lot for the package :)

**Comment by millejoh** [comment]
If you call `ein:notebook-close`, which is bound to `C-c C-#`, it will close the notebook buffer but not stop the kernel. You can later re-open the notebook and re-connect to the still-running kernel.

Also, if emacs should crash (god forbid) while you are editing a notebook, so long as the jupyter server does not also crash you should be able to restart emacs, reopen the notebook and reconnect to the running kernel.

Hope that is what you were looking for!

**Comment by kootenpv** [comment]
@millejoh thank you for your reply, I'll try it out. 

When I close emacs myself `(kill-emacs)`, it does kill the kernel though, right? 
I think this is the case since when I reopen emacs, I cannot find any kernel...
