### ISSUE TITLE
Is it possible to use the package to open jupyter-qtconsole without notebooks?

### ISSUE THREAD

**Issue by LouisAsh** [millejoh/emacs-ipython-notebook#235]
I rarely use Jupyter Notebooks, but I would still love to be able to use ipython through a jupyter-qtconsole, in order to have the inline plotting. This is trivial if one wants to launch a console via terminal/cmd, and it is also integrated with Spyder.

I wonder if with your `emacs-ipython-notebook` Emacs package, it would be possible to have an ipython interpreter within Spacemacs that accepts inline plotting (that is, one that uses the qtconsole). I have been trying all that I could find, but nothing allowed me to call a interpreter (besides obviously the standard interpreter that comes with `C-c C-p`) without having a notebook opened.

Is that possible?

**Comment by millejoh** [comment]
Using the `%qtconsole` magic from an opened notebook in ein works as expected. Is that the behavior you are looking for?
