### ISSUE TITLE
requesting travis debug mode

### ISSUE THREAD

**Issue by heroxbd** [millejoh/emacs-ipython-notebook#240]
`func-test.el` passes all the tests 100% of time on my local environment:

> Debian Sid
> Emacs 25.2
> js2-mode-20170721
> popup-0.5.3
> request-0.3.0
> request-deferred-0.3.0
> simple-httpd-1.4.6
> skewer-mode-1.7.0
> websocket-1.8

However, the [travis tests](https://travis-ci.org/millejoh/emacs-ipython-notebook/builds/281640128) failed. Even with emacs 25, the [test results](https://travis-ci.org/millejoh/emacs-ipython-notebook/jobs/281640133) are unstable.

Would it be possible to request permission to enter [travis debug mode](https://docs.travis-ci.com/user/running-build-in-debug-mode/) to debug this interactively?

**Comment by millejoh** [comment]
Travis sent an email earlier today saying they have enabled debug mode, my eager testing friend. I think you should be able to debug any of the more recent jobs. I run mostly on a Windows environment, so I'm not sure how much debugging I will be able to do, though I shall try.

Good luck - let me know if you need anything else.

**Comment by heroxbd** [comment]
Thanks John, according to 
  https://docs.travis-ci.com/user/running-build-in-debug-mode/
> To have the feature enabled for a public repository, please email us at support@travis-ci.com indicating which ones. Push access to the repository is also required.

Could you please grant me push access to the repository?  I will only use it for debugging travis tests.  All my subsequent contributions will still be done in pull requests.

**Comment by millejoh** [comment]
Done. Though know now that should anything happen to me it will fall to you to represent and maintain ein's glory. Good luck.

**Comment by heroxbd** [comment]
That worked like a charm.   Debugging finished :)
