### ISSUE TITLE
error starting ein

### ISSUE THREAD

**Issue by DrWaleedAYousef** [millejoh/emacs-ipython-notebook#241]
All of the sudden, when starting ein it gives me:
deferred error : (void-variable ein:connect-mode-map)

**Comment by millejoh** [comment]
@DrWaleedAYousef , not sure exactly what is causing this, but should be able to fix by putting a call to `(require 'ein-connect)` in your init file.

To help me track down where this is ocurring: what command are you executing that is causing this error? Thanks.

**Comment by DrWaleedAYousef** [comment]
ein:jupyter-server-start , which is what I used to run all the
time. Another question, please; I need also to use elpy but with ipython
shell so that when I execute a plot command in the .py file emacs plots
in the ipython shell. do you know how to do it?
