### ISSUE TITLE
Request Error connecting to server.

### ISSUE THREAD

**Issue by riririaan** [millejoh/emacs-ipython-notebook#243]
Hello @millejoh and others,

I am on Mac OS X running emacs 25.3.1, using ipython 6.2.1 and jupyter-1.0.0 and the newest version of ein available in melpa.

I am able to start the jupyter server using `ein:jupyter-server-start` and the jupyter server fine in the web browser. However after starting I get a `REQUEST [error] Error (error) while connecting to http://localhost:8888/api.`

This error also prevents me from opening a notebook with `ein:notebooklist-open`. Is this because i'm using too new a version of jupyter? Any idea on what version of jupyter I should use?

also seeing this from the jupyter server output:

[W 14:18:19.072 NotebookApp] 404 GET /api (127.0.0.1) 2.37ms
referer=None [W 14:18:19.084 NotebookApp] /api/notebooks is
deprecated, use /api/contents [I 14:18:19.084 NotebookApp] 302 GET
/api/notebooks/ (127.0.0.1) 0.55ms

**Comment by millejoh** [comment]
Does it help if you do `M-x ein:force-ipython-version-check` followed by `M-x ein:jupyter-server-login-and-open`?

**Comment by riririaan** [comment]
`ein:force-ipython-version-check` also returns the same request error. Am I using the wrong versions of ipython and jupyter? E.g. does the jupyter 1.0.0 not support the `/api` endpoint? I tried to find earlier versions but couldn't through pip.

**Comment by millejoh** [comment]
I've been using jupyter for some time without problems, so I think it may be something else. It most likely is a configuration issue, but tracking this down will probably take a couple iterations.

Let's start with the contents of the `*ein:jupyter-server*` buffer. Could you send me what it shows after starting the server and trying to open a notebook list buffer?

John
