### ISSUE TITLE
Jupyter server fails to start

### ISSUE THREAD

**Issue by jgrueb** [millejoh/emacs-ipython-notebook#248]
I start the jupyter server with 
`M-x ein:jupyter-server-start` 
Server command: /usr/local/bin/jupyter-notebook (from `which jupyter`) 
Notebook directory: ~/

After some time I get a
Warning (emacs): [EIN] Jupyter server failed to start, cancelling operation.

Hope I did not miss something here. Starting a jupyter server via terminal and logging in with the token as the password via EIN works for me. 

Debian 9.2
GNU Emacs 24.5.1
ipython 5.5.0
jupyter-notebook 5.2.1

EDIT: Sorry for the inconvenience, the problem was an already existing installation. Spyder uses jupyter as well. EIN and Spyder do not seem to like each others jupyter istallations.

**Comment by nothingface0** [comment]
Same problem for me, solved by removing anaconda altogether.

**Comment by liar666** [comment]
In my case none of the above seems to work.
When I use bash to run the /exact/ same command (for starting jupyter) that DoomEmacs reports, it does works.
However, as the machine I use is very old, it takes a long time to start.
Is it possible that there is a timeout somewhere in ein that would report the command in DoomEmacs does not work before it even had the time to start ?
In such a case, how could I increase this timeout?

**Comment by liar666** [comment]
FYI, I've succeeded by:
- starting jupyter externally (with the exact command DoomEmacs syas it cannot run)
- Using `ein:login` and selecting (the proposed entry) http://127.0.0.1:8889

S it seems jupyter works and ein manages to connect to it. The problem resides in ein:run that says it cannot run jupyter whereas the command perfectly work when ran externally.

So I confirm I think there's something like a timeout that makes ein thinks the command didnot succeed whereas it did.
