### ISSUE TITLE
ein:cell-append-mime-type does not support dynamic javascript

### ISSUE THREAD

**Issue by fabriziojpiva** [millejoh/emacs-ipython-notebook#254]
Hello guys how is it going. As the title says, I am having this message in `*ein:log-all*` when trying to compile a worksheet (`C-c C-c`) containing some plots with matplotlib. Skewer mode is supposed to give EIN the ability to execute dynamic javascript in the notebook, but it seems like it is not working. Does anyone have any idea about this trouble?

**Comment by millejoh** [comment]
The support for javascript is very basic at the moment and getting things like widgets and interactive plots is still beyond ein's capabilities.

If you want to see plots in the notebook buffer then you will need to call `%matplotlib inline` first. As far as I know, packages like plotly and bokeh will not work with ein/emacs unless you can find a way to configure them to output static images.

**Comment by fabriziojpiva** [comment]
Thanks John I just added `%matplotlib inline` at the beginning of the worksheet that I wanted to compile and it worked fine. It didn't had widgets and interactive plots that's why I thought I was missing something!
