### ISSUE TITLE
Feature request: Change notebook kernel interactively

### ISSUE THREAD

**Issue by dzbee** [millejoh/emacs-ipython-notebook#255]
Made a PR on the wrong repo: https://github.com/tkf/emacs-ipython-notebook/issues/195

When using a notebook in-browser, you can change the kernel on the fly.

![image](https://user-images.githubusercontent.com/25496468/33455147-2aa8c7ee-d5e9-11e7-9924-fc4b7e2093e8.png)

I really like the interface for creating new notebooks using different kernels, but if I want to change the kernel an existing notebook uses then I have to directly edit the JSON of the notebook file. I have not been able to find any existing feature that allows for changing the kernel of an existing notebook using EIN. Being able to change kernel on the fly would be very convenient.

(I just noticed this issue was raised before: https://github.com/millejoh/emacs-ipython-notebook/issues/82)

**Comment by millejoh** [comment]
This feature is already available. Check out this screen grab:

![kernel selection](https://user-images.githubusercontent.com/4049168/33459296-034dbcbc-d5ef-11e7-8471-faf76e1b581d.PNG)

There are also commands to restart the kernel (`ein:notebook-restart-kernel`), clear outputs (`ein:worksheet-clear-all-output`), and run all outputs (`ein:worksheet-execute-all-cell`). You can also reconnect and even have ein attempt to connect to a kernel running on a different server (`ein:notebook-update-url-or-port` and `ein:notebooklist-change-url-port`).

The only thing EIN lacks is a hearbeat function that checks if the kernel has died and tries to reconnect/restart.

**Comment by dzbee** [comment]
D'oh, it literally never occurred to me to click...thanks for relieving my ignorance.
