### ISSUE TITLE
EIN Not Recognizing User-defined Kernels

### ISSUE THREAD

**Issue by Hamzehn** [millejoh/emacs-ipython-notebook#260]
Hi,

Here are the steps I use to start Jupyter notebooks in Emacs with EIN:

1. `M-x ein:jupyter-server-start`
2. `M-x ein:notebooklist-login`
3. `M-x ein:notebooklist-open`

I noticed that if I create a new python environment to work on a new project, and register its kernel with Jupyter using ipykernel as documented [here](http://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments) in the following manner:

In bash shell:
```shell
user@host: ~ $ source activate myenv
(myenv) user@host: ~ $ python -m ipykernel install --user --name crypto-analysis --display-name "Python [myenv]"
```

The kernel `Python [myenv]` appears when I access the Jupyter server from the web browser, but doesn't appear in the EIN Notebook List until I restart Emacs. It doesn't appear even if I kill the running Jupyter server using `M-x ein:jupyter-server-stop` and do the above 3 steps again.

Am I following the wrong steps to start my Jupyter notebooks?

Thanks.

**Comment by millejoh** [comment]
One additional step to try - restart emacs. I've added kernels using the method you show above and it takes restarting emacs before the new kernel appears. This is likely a caching issue as ein stores kernelspec queries in a hashtable.

**Comment by Hamzehn** [comment]
Thank you. Yes, restarting emacs fixed this.

**Comment by ghachey** [comment]
Any chance we can get the fix merged and pushed to melpa? Meanwhile, restarting Emacs is easy enough :)

**Comment by millejoh** [comment]
Erm, yes. Totally had this on my todo list. I added an interactive function `ein:notebooklist-refresh-kernelspecs`. Should do the trick. There is also a new widget on the notebooklist buffer that will do the same. Let me know if you run into trouble.

**Comment by ghachey** [comment]
Seems to be working. It's great joy to work jupyter within Emacs, thank you :)

**Comment by Charlescad** [comment]
Hello, I cannot find this ein:notebooklist-refresh-kernelspecs
I am using https://www.melpa.org/#/ein
Was it removed?
