### ISSUE TITLE
Inline plot axes not visible when using dark themes

### ISSUE THREAD

**Issue by njunxuan** [millejoh/emacs-ipython-notebook#261]
Hi, when using dark themes, the axes and titles of matplotlib plots are not visible as they inherit the background of the buffer. Is there someway to ensure that the axes and title are white, just like the plot itself?

Thanks.

**Comment by millejoh** [comment]
As ein is just inserting an image that matplotlib is generating there is not much I can do from the emacs side. You will have to configure matplotlib to invert the color of the axis from the python side. I think seaborn's [darkgrid](https://seaborn.pydata.org/tutorial/aesthetics.html#seaborn-figure-styles) style might get you what you want.  `plt.style.use('dark-background')` might also be [work](https://matplotlib.org/gallery/style_sheets/dark_background.html?highlight=dark%20background%20style%20sheet).

**Comment by njunxuan** [comment]
I see. Thanks for this then!
