### ISSUE TITLE
RFE: Finding files for remote sessions

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#263]
When the server is remote, file finding from Traceback should be remote too, using Tramp.

**Comment by millejoh** [comment]
@sam-s. I will have to think about how to test this on my local network, but for the moment I've pushed a commit that tries to create tramp-friendly paths when jumping to a remote file from a Traceback. Let me know if this anything at all.

**Comment by dickmao** [comment]
This is tough.  A project is added.

**Comment by chookity-pokk** [comment]
I just tried launching EIN while I was in a directory on a server over TRAMP and wasn't able to get it to launch. I was wondering if this is actually possible? If so, can you please point me in the direction of the documentation on how to do so?
