### ISSUE TITLE
logging output has extra newlines

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#264]
when a cell produces output using logging, the output looks normally spaces (one newline between messages), but when the notebook is re-opened, messages are separated by 2 newlines.

code:
```
import logging
import sys

logger = logging.getLogger("foo")
console = logging.StreamHandler(stream=sys.stderr)
console.setFormatter(logging.Formatter("%(message)s"))
logger.addHandler(console)
logger.setLevel(logging.INFO)
logger.info("foo")
logger.info("bar")
```
output (as expected):
```
foo
bar
```
when the notebook is closed (buffer killed) and re-opened (click on open in notebooklist buffer) the output looks like
```
foo

bar

```

**Comment by millejoh** [comment]
Not sure if it is the cause but looks like the json is going from this:

```json
      "outputs": [
        {
          "name": "stderr",
          "text": "foo\n",
          "output_type": "stream"
        },
        {
          "name": "stderr",
          "text": "bar\n",
          "output_type": "stream"
        }
 ```

To this:

```json
      "outputs": [
        {
          "name": "stdout",
          "name": "stderr",
          "text": "foo\n",
          "output_type": "stream"
        },
        {
          "name": "stdout",
          "name": "stderr",
          "text": "bar\n",
          "output_type": "stream"
        }
```

Not sure why that extra stdout is appearing, but I hope once I figure out how to get it to stop this issue will go away.

**Comment by sam-s** [comment]
I am not sure if it is related, but I now see logging messages _duplicated_: for each `logger.info("foo")` I see 
```
2018-01-29 13:59:06 INFO 29348/MainThread/<ipython-input-221-b2d85110535b> foo

INFO:stdout:foo

```
the 1st (expected) message on normal background (default face), the second (unexpected) in `ein:cell-output-stderr` face (`PeachPuff` background).

I am not sure how I (or ein?) managed to get the logger to send output to both `stdout` and `stderr` and how to fix that. `logger.handlers` is a list of 1 element.
