### ISSUE TITLE
Feature request: output narrowing

### ISSUE THREAD

**Issue by ebanner** [millejoh/emacs-ipython-notebook#268]
Regarding cell output it is currently only possible to display all of it or hide all of it (e.g. through `M-x ein:worksheet-toggle-output`). The jupyter notebook web client has a nice feature to "scroll" the output like so.

![image](https://user-images.githubusercontent.com/2068912/36080785-a4f8f470-0f4a-11e8-972e-bb166c25b371.png)

The EIN equivalent IMO would be to cut the cell output off after, say, 10 lines (it would be nice for it to be customizable).

From what I can gather the cell output is rendered through ewoc. I don't have any experience with ewoc so I'm not sure how much effort it would be to tell ewoc to cut the output off after 10 lines, but I think that is what is required to make this happen!

**Comment by millejoh** [comment]
Try this - once you update ein play around with `ein:truncate-long-cell-output`; set it to an integer to tell ein the number of lines to print in a cell output. If you don't want truncation set the variable to nil.

**Comment by ebanner** [comment]
Wonderful! Can't wait to try it out.

By the way the reason I have been so active with EIN is that I built a minor mode called [pynt]((https://github.com/ebanner/pynt)) on top of it and heavily depend on it.

I just want to say thank you for all the time and effort you have put and continue to put into EIN. Without EIN I don't think I would have ever started working on pynt. EIN is truly amazing and has been very inspiring for me!

**Comment by ebanner** [comment]
Looks like it works! Great work!
![image](https://user-images.githubusercontent.com/2068912/38395708-1b5f4c50-38e9-11e8-9006-d9955a693325.png)
