### ISSUE TITLE
ein-contents-api.el locked

### ISSUE THREAD

**Issue by treese** [millejoh/emacs-ipython-notebook#27]
When I updated ein from the package listing to the current git version, I get an error:

...54/ein-contents-api.el locked by E34119@TX0GL... (pid 15104)

I think this is just because the file lisp/.#ein-contents.api.el got checked in by accident.

**Comment by millejoh** [comment]
Oops. Not sure how that snuck in to begin with, but I think it was fixed with the latest commit.
