### ISSUE TITLE
Changing cell to markdown mode eventually leads to memory leak

### ISSUE THREAD

**Issue by drc-bsorenson** [millejoh/emacs-ipython-notebook#273]
Every time I change cell mode to `markdown`, emacs begins chewing up memory and processor (I killed the process after 20Gb). The issue seems to be related to `backtrace`, as invoking `backtrace` (`M-x backtrace`) results in the same behavior.  It also appears to only happen once the notebook auto-saves.

I am running:
  - OS; Windows 10
  - spacemacs: 0.200.13
  - emacs: 25.3.1
  - python: 3.6
  -  jupyter: 1.0.0
  - ein: 20180225.1046
  - notebook: 5.4.0

I don't know if this is an issue with emacs or `emacs-ipython-notebook`. Unfortunately, I can't provide a backtrace because, well, backtrace seems to be the issue.  Please let me know if there is any other information you need from me.

**Comment by millejoh** [comment]
Might be an issue with markdown - I recall having some issues with an older version sometime last year. The slowdown in the backtrack is likely because emacs is trying to print one of ein’s many circular structures. Something that might help would be to evaluate `(require 'ein-dev)` then call ‘M-x ein:dev-patch-backtrace’.

**Comment by drc-bsorenson** [comment]
Thank you for the suggestion. If I run into this again, I will give it try. For now, I think it may have been a broken install. I ran `git clean -xfd` in `.emacs.d`, reinstalled everything, and I haven't had a problem since.

**Comment by drc-bsorenson** [comment]
I'm closing this--backtrace and markdown cells have caused no issues since starting from a clean `.emacs.d`.
