### ISSUE TITLE
Content list call failed with status abort

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#275]
When I click on `[open]` in the `notebooklist` buffer, I get this:
```
ein: [error] Content list call http://datasci-1.clear.io:8888/api/contents/ failed with status abort.
```
Chrome shows a 15k-long JSON string, apparently listing the available notebooks.
The notebook is fairly large (almost 5M).
I also see 
```
ein: [error] Content list call http://datasci-1.clear.io:8888/api/contents/getwit.ipynb failed with status timeout. 
```
in the `*Messages*` buffer.

**Comment by millejoh** [comment]
Maybe a timeout issue. What is the value of `ein:content-query-timeout`? Default is 6000ms.

**Comment by sam-s** [comment]
`60000` (1 minute?)

**Comment by millejoh** [comment]
Yes - not sure how fast your internet connection, but big notebooks can take a while even on my local machine to load. If you set to nil that means no timeout.

**Comment by sam-s** [comment]
dramatically reducing the file size solved the problem for now.
thanks

**Comment by millejoh** [comment]
I also wonder if the large file is causing emacs to GC excessively. I checked in some commits that try to increase the cons threshold dramatically when opening a notebook. Maybe it will help.
