### ISSUE TITLE
org-edit-special (C-c ') not associated with EIN

### ISSUE THREAD

**Issue by ganesh-krishnan** [millejoh/emacs-ipython-notebook#277]
I'm using EIN source blocks in my org docs. Things are working pretty well.

One frustration however is editing using `C-c ' (org-edit-special)`. While editing works fine, things don't work quite as well, if I attempt to execute any code in this buffer. Specifically, executing code from this buffer, starts a regular python comint. I would like it to use the EIN python kernel. How do I do this?

**Comment by millejoh** [comment]
Ask me to add this as a feature, I think. I have noticed the same and wished as do you. I'll try to take a look at this when I have some free time.

**Comment by ganesh-krishnan** [comment]
Thanks @millejoh. How do I ask you to add it as a feature? Is there a tracker somewhere? :)

Also, I'm happy to help with this item. I don't know how `org-edit-special` associates buffers to comints.  If you have any pointers, that would be useful.

**Comment by millejoh** [comment]
You just did, :-). I imagine it will have to something similar to what I do in `ein:edit-cell-contents`l, but I don't know enough about how `org-edit-special` works to know where to hook in.

**Comment by millejoh** [comment]
Actually, now that I took a close look, when you edit an EIN source block the code in `org-babel-edit-prep:ein` should execute, which will connect to the notebook specified in the `:session` setting via the command `ein:connect-buffer-to-notebook`.

Sounds like that might not be happening in your setup, though I'm not sure why. In the edit buffer what happens when you call `M-x ein:connect-pop-to-notebook`?

**Comment by ganesh-krishnan** [comment]
It pops to the notebook buffer just fine. But somehow it doesn't execute code in the notebook. I'll try and take a look this weekend. Thanks for the pointer on where to look.

**Comment by ganesh-krishnan** [comment]
Ok I found part of the problem. The mini-buffer does say that the org buffer connected to the notebook buffer. But what's happening is that the major mode of the buffer is being set to `python-mode`. 

`org-edit-special` calls `org-edit-src-code`. `org-edit-src-code` then sets the major mode of the buffer, based on the language. In that case, it happens to be `python-mode`. In my specific case, I use `elpy`, so it sets up `elpy-mode`. 

How do I fix this?

**Comment by millejoh** [comment]
What you will have to do is something like what `ein:edit-cell-save-and-execute` does, though note that ob-ein uses `ein:shared-output-eval-string` to execute the actual code.

Maybe what you want to do is bind whatever key combo you are using to execute code in the edit buffer to wrap a call to `org-babel-execute:ein`?

**Comment by ganesh-krishnan** [comment]
Yeah that should work. I found that calling `ein:shared-output-eval-string` interactively works. Now all I have to do is create a function that will pass the current buffer or line to `ein:shared-output-eval-string`, bind that to a key combo and I'm off to the races. Awesome!

**Comment by millejoh** [comment]
Okay, sounds like you found a workaround, but FYI I pushed commit with a new function `org-babel-edit:ein-execute` which does the heavy lifting required to execute code an source edit buffer and automatically update the org file where the code originates with the execution results.

I've bound by default to `C-c C-c`, and I'm not sure the way I have done it makes this binding easy to customize.

Anyway, let me know if this helps with what you are trying to do. Thanks for using ein!

**Comment by ganesh-krishnan** [comment]
Ok. So tried this out today. Good news is that `org-babel-edit:ein-execute` works. Noticing a couple of problems:

1. I'm not sure `org-babel-edit-prep:ein` is getting executed. `C-c C-c` in the `org-babel-edit` buffer is still bound to `elpy-shell-send-region-or-block`.
2. When I execute `org-babel-edit:ein-execute` manually, it works. However, I have to manually mark the region. I see that you are trying to set the whole buffer as a region in the code. Somehow, that is not working. 

I'm also seeing a new error message with the latest ein build, every time I execute `org-babel` ein source blocks. The error is as follows:

```
deferred error : (search-failed "[[ob-ein-async-running: XXXXX-XX-XXX-XX]]")
```

I don't have time to debug right now, but thought I'd give you some feedback.

**Comment by millejoh** [comment]
EIN support for org source blocks is much improved at this point, so I am going to close this. Reopen with details of any issues, if you continue to have them.
