### ISSUE TITLE
No axes in inline pyplots 

### ISSUE THREAD

**Issue by falematte** [millejoh/emacs-ipython-notebook#279]
Do you have any idea why inline plots are working fine but I get no axis? If I open the notebook in my browser all the images have the axes... Here is the code

```
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
n = np.arange(0, 20, 1)
delta=0.01
t = 0.025
plt.plot(n,(1+t)**n + delta*(((t+1)**n-1)/t),'b--',n,(1+t)**n, 'r--')
plt.show()
```

**Comment by millejoh** [comment]
This is what I get when I execute the above code. My guess is that your axes are blending in with the background color for whatever theme you are using. If that is the case the problem isn't really with ein, but can be solved easily enough with appropriate Matplotlib rc settings.

![screenshot from 2018-03-10 14 07 16](https://user-images.githubusercontent.com/4049168/37246318-db8d2e5c-246c-11e8-9137-08bc64843eac.png)

**Comment by falematte** [comment]
This was exactly the problem. In particular this is due to the fact that I am using:

`(invert-face 'default)`

**Comment by millejoh** [comment]
Through either the [rc file](https://matplotlib.org/users/customizing.html) or dynamically updating [rcParams ](https://matplotlib.org/api/matplotlib_configuration_api.html#matplotlib.rcParams) in your notebook.

The [dark background](https://matplotlib.org/gallery/style_sheets/dark_background.html#sphx-glr-gallery-style-sheets-dark-background-py) style might help with what you are doing.
