### ISSUE TITLE
ein doesn't show image

### ISSUE THREAD

**Issue by Puzzlovaski** [millejoh/emacs-ipython-notebook#280]
When I execute
`In [4]
from IPython.display import Image
Image(filename='./t.png')`
It's just show
![image](https://user-images.githubusercontent.com/31467241/37457813-9f341e68-2875-11e8-9ea6-03c5f5f99382.png)
in *Message* buffer

**Comment by millejoh** [comment]
Could you run `M-: (require 'ein-dev) and then `M-x ein:dev-show-sys-info` and post the results here? Also, what happens if you open the png file in a buffer?

**Comment by Puzzlovaski** [comment]
This is `M-: (require 'ein-dev)` and then `M-x ein:dev-show-sys-info`
![image](https://user-images.githubusercontent.com/31467241/37469080-14db967a-2897-11e8-80b3-6a1bf7a8d0c5.png)
and this is when open .png
![image](https://user-images.githubusercontent.com/31467241/37469189-4c22af88-2897-11e8-8bea-e7be55a3ceb1.png)

**Comment by millejoh** [comment]
This isn't an ein issue - your emacs doesn't support png files. Looks like your emacs only supports some basic file types per the `:image-types-available`.

Also looks like you are running on Windows. Have you tried the [emax64](https://ntemacs.sourceforge.io/) or the [emacs-w64](https://sourceforge.net/projects/emacsbinw64/) packages. Both have support for a variety of image types built-in to the package.

**Comment by Puzzlovaski** [comment]
@millejoh 
Oh! Thankyou
