### ISSUE TITLE
List Opened Notebooks above directories 

### ISSUE THREAD

**Issue by patrickeganfoley** [millejoh/emacs-ipython-notebook#281]
Super small issue - would you be open to listing the `---------- All Opened Notebooks ---------- ` section above the directories section?  I think it's probably pretty common to have a ton of things in the directory list so you can't see the open notebooks.

Happy to PR if you are open to this.

**Comment by millejoh** [comment]
Sounds reasonable to me - though I think the right thing is to make this configurable so the user can select whether they want the list above or below. I'm always happy to get PR's...

**Comment by dickmao** [comment]
I am generally enthused about community contributions.  However, I feel the "All Opened Notebooks" doesn't provide enough value to justify the statefulness required for it to work.  Currently, killing the notebook buffer or clicking "[Delete]" in the notebooklist buffer do not update the "All Opened Notebooks" status.

> I think it's probably pretty common to have a ton of things in the directory list so you can't see the open notebooks.

I don't feel this pain for some reason.  The opened notebooks all appear at the top of the tkf notebooklist.
