### ISSUE TITLE
collapsing input cells

### ISSUE THREAD

**Issue by manandearth** [millejoh/emacs-ipython-notebook#282]
It will be very useful to be able to collapse the input cells to show only the first line, in order to fit more in the screen. i am writing classes definitions and loading instances to check and debug and such a feature will make navigation a breeze...

**Comment by vv111y** [comment]
SE won't let me comment yet...
How has origami+hydra worked so far? 
Also, +1 vote for this.

**Comment by manandearth** [comment]
@vv111y origami works generally, but I didn't include it in my workflow so far.. 
I will write something when I get to work with it for a bit.
cheers.

**Comment by millejoh** [comment]
Well, origami does work as far as collapsing nested expressions, but not an entire input cell. Agree this would by nice functionality to have. To the todo list you go!

**Comment by dickmao** [comment]
I've no intention to work on this.  Sorry.

**Comment by bhipple** [comment]
Being able to have `org-mode` like folding by hitting TAB to fold/unfold the current input/output cell and `shift-TAB` to fold/unfold all cells would be really nice.

I haven't investigated thoroughly, but is it possible to just use some of the same libraries to do this implementation?  I'd be willing to give it a try hacking on it if you have any pointers/ideas.

**Comment by dickmao** [comment]
To maintain multiple visual elements (cells, output areas, etc.), EIN
maintains its own undo accounting, which is truly a house of cards.

Cell folding is doable (we support output folding via `C-c C-e`), but 
because of undo accounting, it's involved and I don't recommend it.  I'd stick
with org-mode.

Closes #282

**Comment by bhipple** [comment]
Ah that's too bad; I'll give the org-mode version a shot and see how it handles.  Thanks for the quick response and saving me from going down an unproductive rabbit hole!
