### ISSUE TITLE
Disable whitespace-based indentation

### ISSUE THREAD

**Issue by ballardt** [millejoh/emacs-ipython-notebook#283]
First, thank you so much for all of your work on EIN, it's such a useful piece of software!

By default, code blocks seem to indent based on the whitespace after the header line's keyword. Examples:

    class MyClass:
          pass()

    if bool_is_true:
       pass()

    def func():
        pass()

This behavior is nice sometimes (e.g. when lining up arguments or conditions), but for things like `class` or `if`, I'd just prefer 4 spaces on the next line.

If I use `customize-group` and prefer `ein:python` over `ein:ml` I get the correct behavior, but I'd like to know if there's a way to change it while still using `ein:ml`.

**Comment by millejoh** [comment]
Hmmm, I am not seeing this behavior in my setup, and I have `ein:notebook-modes` set to `ein:notebook-multilang-mode`. Note that setting it to `ein:ml` won't really work as some magic has to occur before the buffer mode can be set to `ein:ml` for indentation and font-lock to work correctly.
