### ISSUE TITLE
Why does ein:kernel-restart kill then start?

### ISSUE THREAD

**Issue by ebanner** [millejoh/emacs-ipython-notebook#285]
I noticed that [`ein:kernel-restart`](https://github.com/millejoh/emacs-ipython-notebook/blob/710a5a6b915d9d9288eb43a750641cf4c8431c66/lisp/ein-kernel.el#L142) does this:

```
(ein:kernel-kill kernel
    (apply-partially #'ein:kernel-start kernel (ein:get-notebook-or-error)))
```

and that [right below that](https://github.com/millejoh/emacs-ipython-notebook/blob/710a5a6b915d9d9288eb43a750641cf4c8431c66/lisp/ein-kernel.el#L149-L156) it looks like there is an attempt to do a "proper" restart:

```
    ;; (ein:query-singleton-ajax
    ;;  (list 'kernel-restart (ein:$kernel-kernel-id kernel))
    ;;  (ein:url (ein:$kernel-url-or-port kernel)
    ;;           (ein:$kernel-kernel-url kernel)
    ;;           "restart")
    ;;  :type "POST"
    ;;  :parser #'ein:json-read
    ;;  :success (apply-partially #'ein:kernel--kernel-started kernel))
```

I am wondering what the story is behind using the former approach? I only am curious because I wrote a custom kernel manager and I wanted to embed different behavior in a kernel restart versus a kernel start.

The former code is "correct" in the sense that ostensibly restarts a kernel but is not correct in the sense it will only run [`start_kernel()`](https://github.com/jupyter/notebook/blob/a2f72da17f3d0a8b8eea7912d1e24174f3f0ac4b/notebook/services/kernels/kernelmanager.py#L128) whereas the latter code will run [`restart_kernel()`](https://github.com/jupyter/notebook/blob/a2f72da17f3d0a8b8eea7912d1e24174f3f0ac4b/notebook/services/kernels/kernelmanager.py#L269) in whatever kernel manager is being used.

It's fine for me now as I was able to workaround it by moving my restart kernel functionality into `kernel_start()` in my custom kernel manager. But this might not be possible for everyone.

**Comment by millejoh** [comment]
To be honest I'm not sure myself. For some reason the REST call wasn't working, or something was off with the behavior, so I had to hack around using the current solution. Might have been an issue with IPython that has since been resolved, so may be worth uncommenting the code and seeing what happens.
