### ISSUE TITLE
autoexec cells executed before buffer in ein:connect-eval-buffer

### ISSUE THREAD

**Issue by ebanner** [millejoh/emacs-ipython-notebook#287]
When I hit `C-u C-c C-c` (`ein:connect-eval-buffer`) in a code buffer I always expect autoexec cells to be executed *after* the code buffer. Indeed it is clear looking at [the code in `ein:connect-eval-buffer`](https://github.com/millejoh/emacs-ipython-notebook/blob/115c16eb9f38447790a75c71e67036c5f4be15e0/lisp/ein-connect.el#L224-L225) that that is what is intended:

```
(ein:shared-output-eval-string (buffer-string) nil nil nil :silent t)
(ein:connect-execute-autoexec-cells)
```

However I recently upgraded ein and now when I hit `C-u C-c C-c` it looks like the autoexec cells are executed *before* the buffer, which is causing errors. For example, I call a function in the notebook which is defined in the code buffer.

My guess is that [`73747d8`](https://github.com/millejoh/emacs-ipython-notebook/commit/73747d86d91f104dfd016619c0de0fc354c7b088) introduced this bug as there are now [150ms worth of `deferred` calls in `ein:shared-output-eval-string`](https://github.com/millejoh/emacs-ipython-notebook/blob/73747d86d91f104dfd016619c0de0fc354c7b088/lisp/ein-shared-output.el#L219-L232), which is causing `(ein:connect-execute-autoexec-cells)` to run first**.

It looks like this change was made to enable functionality in `ob-ein`. Since I am not familiar with `ob-ein` I am not sure what a suitable fix is. But I would really like the old behavior to come back as re-evaluating the code buffer each time before evaluating autoexec cells is a really nice way to keep the notebook up to date with changes in the code buffer.

** *For the record I am unable to confirm this as I was trying to build ein with commit [`a8fc712`](https://github.com/millejoh/emacs-ipython-notebook/tree/a8fc712ca837591c39927a41d6ddf884257d904b) but [was having an issue getting melpa to pull that commit](https://github.com/melpa/melpa/issues/5404).*

**Comment by millejoh** [comment]
I will try to confirm what is going on, but one solution would be to have a version of `ein:shared-output-eval-string` that doesn't use deferred by default. I'll work on adding this in.

**Comment by millejoh** [comment]
I wrapped the call in a deferred chain which should make things execute sequentially as per the original behavior. At least my simple test seemed to work, but let me know how it works for you.

**Comment by ebanner** [comment]
Yes it works now! Your solution to leverage the deferred machinery makes a lot of sense. Nice work!
