### ISSUE TITLE
Not working with Emacs 24.4

### ISSUE THREAD

**Issue by GongYiLiao** [millejoh/emacs-ipython-notebook#29]
Running ```ein:notebooklist-open``` will lead to error 

~~~~
REQUEST [error] Error (error) while connecting to http://127.0.0.1:8889/api.
split-string: Wrong type argument: stringp, nil
~~~~

**Comment by millejoh** [comment]
GongYiLiao,

Can you provide some information on your setup? Run `M-x ein:dev-bug-report-template` and post the results as a comment to this issue.

Thanks!

**Comment by millejoh** [comment]
I'm cleaning up some older issues - hope this is working for you now. If not feel free to open a new issue.
