### ISSUE TITLE
Tag 0.13.1 and release to melpa-stable

### ISSUE THREAD

**Issue by heroxbd** [millejoh/emacs-ipython-notebook#291]
The documentation mentions [version 0.13.1](http://millejoh.github.io/emacs-ipython-notebook/#v0-13-1).  However, it is neither tagged nor released in melpa-stable.

**Comment by millejoh** [comment]
I went ahead and bumped to 0.14.0. It seemed the thing to do.

**Comment by heroxbd** [comment]
That's cool.  Thanks John!
