### ISSUE TITLE
notebook order in notebooklist buffer

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#293]
notebooks in `ein/lnotebooklist` buffers are listed in apparently random order.
it would be nice if I could sort them, alphabetically, by mtime and by size 
(basically, all `ls(1)` sorting options would be welcome).

**Comment by millejoh** [comment]
It's not pretty, but I've implemented some of this in a couple commits. Jupyter doesn't return size info, from what I can see so all I can do is offer sorting based on last modified time and name. Happy to hear your thoughts on the changes.

**Comment by sam-s** [comment]
Totally great!
Thanks!
The only thing that makes me cringe is `(format-time-string "%x" dt)` in `ein:format-nbitem-data`.
`%x` makes sense until you realize that it means `%D` and not `%F` ;-(
could you please make that customizable?
https://github.com/millejoh/emacs-ipython-notebook/pull/294
