### ISSUE TITLE
403 forbidden with URL, not with port

### ISSUE THREAD

**Issue by colehaus** [millejoh/emacs-ipython-notebook#297]
After calling `ein:notebook-list-open` I'm prompted for a URL or port number. If I use `8888`, everything works and the notebooklist buffer opens. If I use `localhost:8888` (which does work in the browser), I get an error about `ein: [error] Kernelspc query call failed with status error.`. Here are the logs:

`*ein:log-all*`:
```
[debug] NOTEBOOKLIST-OPEN: http://localhost:8888/ @#<buffer  *Minibuf-1*>
[debug] NOTEBOOKLIST-OPEN: http://localhost:8888/ @#<buffer *ein:log-all*>
[verbose] Error thrown: (error http 403) @#<buffer *ein:log-all*>
[error] Kernelspc query call failed with status error. @#<buffer *ein:log-all*>
[debug] [GC-COMPLETE-OPERATION] Reverting cons threshold to 100000000. @#<buffer *ein:log-all*>
[verbose] Error thrown: (error http 403) @#<buffer *ein:log-all*>
[error] Content list call http://localhost:8888/api/contents/ failed with status error. @#<buffer *ein:log-all*>
[debug] NOTEBOOKLIST-OPEN: 8888/ @#<buffer *ein:log-all*>
[info] Opened notebook list at http://127.0.0.1:8888 with path . @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
```

`*ein:jupyter-server*`:
```
[I 15:06:24.764 NotebookApp] Serving notebooks from local directory: /home/foo/code/colex
[I 15:06:24.764 NotebookApp] 0 active kernels
[I 15:06:24.764 NotebookApp] The Jupyter Notebook is running at:
[I 15:06:24.764 NotebookApp] http://localhost:8888/
[I 15:06:24.765 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Fontconfig warning: "/etc/fonts/fonts.conf", line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
Created new window in existing browser session.
[W 15:07:17.219 NotebookApp] Forbidden
[W 15:07:17.219 NotebookApp] 403 GET /api/kernelspecs (::1) 1.03ms referer=None
[W 15:07:17.234 NotebookApp] Forbidden
[W 15:07:17.235 NotebookApp] 403 GET /api/contents/ (::1) 1.11ms referer=None
```

**Comment by colehaus** [comment]
I thought about it a bit and made sure to `ein:notebooklist-login` to `localhost:8888` rather than `8888`. When I do, I get 

```
[W 18:58:09.256 NotebookApp] 403 POST /login (::1): '_xsrf' argument missing from POST
[W 18:58:09.269 NotebookApp] 403 POST /login (::1) 13.67ms referer=None
```
in `*ein:jupyter-server*` and
```
[debug] NOTEBOOKLIST-LOGIN: localhost:8888: @#<buffer main.org>
[info] Failed to login to localhost:8888 @#<buffer main.org>
```
in `*ein:log-all*`.

instead of
```
[I 18:59:38.183 NotebookApp] 302 POST /login (127.0.0.1) 1.08ms
[W 18:59:38.184 NotebookApp] 405 POST / (127.0.0.1) 0.62ms referer=None
```
```
[debug] NOTEBOOKLIST-LOGIN: 8888: @#<buffer *ein:log-all*>
[info] Login to 8888 complete. Now you can open notebook list by `ein:notebooklist-open'. @#<buffer *ein:log-all*>
```
from `ein:notebooklist-login` to `8888`.

`127.0.0.1:8888` and `::1:8888` produce the some problematic behavior as `localhost:8888`.

**Comment by colehaus** [comment]
I was able to come up with a workaround, I think. Starting the server from ein and not using a password with jupyter (let ein use the token instead) seems to avoid the issue.

**Comment by millejoh** [comment]
The _xsrf error tells me that ein can't find the cookies it needs to convince the jupyter server that everything is on the up-and-up.

ein tries to respect any redirect requests it receives from the jupyter server, so the actual URL it is using to communicate with jupyter may not be the one that you entered for ein:notebooklist-open. This may be where the confusion is ocurring - the cookie is stored under one url while ein is querying using another.

The cookies should be in the directory set in the `request-storage-directory` variable. Take a look at the cookie jar in that directory, it might be useful to see under what url's the _xsrf cookies are being stored under.

This has always been hard to debug, mostly because I usually can't recreate the problems in my own environment.

**Comment by millejoh** [comment]
I should have realized this a lot sooner, but you should enter `http://localhost:8888` and not `localhost:888` as it will end up storing the authentication cookie under the wrong name. If you just enter a port number ein will detect this and do the right thing, but not if you enter a partial URL.

I kind of think forcing the user to enter the full URL is the right thing as EIN shouldn't assume if the connection is http: or https:, but en definitely should be more helpful in guiding the user towards entering a valid input.
