### ISSUE TITLE
Detach from tkf.

### ISSUE THREAD

**Issue by Carreau** [millejoh/emacs-ipython-notebook#31]
Github only index main repo principally. 

I would suggest writing to GitHub and asking to be detached as "main" repo to be indexed and searchable. [See last sentence of page](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork).

Might be more difficult for people to find this though tkf repo  and looking at network, but might improge google indexing.

**Comment by millejoh** [comment]
I did not know you could do that. Thanks for the suggestion.

**Comment by Carreau** [comment]
Great !  Awesome !
