### ISSUE TITLE
matplotlib plots not showing in ein

### ISSUE THREAD

**Issue by altosaar** [millejoh/emacs-ipython-notebook#310]
Minimal example:

```IP[19]: Checkpoint created. | /1\ [+] |python3|

In [18]
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np


In [19]
plt.plot(np.random.rand(10), np.random.rand(10))

Out [19]:
[<matplotlib.lines.Line2D at 0x1166e5e10>]
```

There is no png that shows up. At the bottom, there is a warning: `ein: [warn] Could not insert image: (error Invalid image type ‘png’)`.

**Comment by millejoh** [comment]
Are your running on Windows? What is the result of executing `(image-type-available-p 'png)` in the scratch buffer or in an ielm buffer? Also, the output from `M-x ein:dev-bug-report-template` will show what image types your Emacs installation supports.

**Comment by altosaar** [comment]
Thanks!

```
*** Welcome to IELM ***  Type (describe-mode) for help.
ELISP> (image-type-available-p 'png)
nil
```

Running `M-x ein:dev-bug-report-template` shows ` :image-types nil
 :image-types-available nil`. 

To install emacs I used homebrew (`brew install emacs`). 

Changing this to `brew cask install emacs` and launching emacs from the terminal with `/Applications/Emacs.app/Contents/MacOS/Emacs` supports png now.

However, I prefer using emacs from iTerm2. I tried `brew install emacs --with-librsvg --with-imagemagick@6` but still no png support.

Installing emacs using 

and running it with `/usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.0/bin/emacs` has png support:

```
ELISP> (image-type-available-p 'png)
t
``` 

From `ein:dev-bug-report-template`:
```
:image-types
 (svg image-io imagemagick png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (svg image-io imagemagick png gif tiff jpeg xpm xbm pbm)
```

But ein does not display plots still (this is running in iTerm2, using `/usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.0/bin/emacs`):
```
IP[13]: Checkpoint created. | /1\ [+] |python3|

In [13]
%matplotlib inline
import numpy as np
from matplotlib import pyplot as plt

plt.plot(np.arange(10), np.arange(10))
Out [13]:
[<matplotlib.lines.Line2D at 0x110e78be0>]
.
```

What else can I try?

**Comment by millejoh** [comment]
I unfortunately don't have a machine running OS X to test this all out on, but reading briefly about iTerm2 it sounds like it extends the xterm protocol in order to display images within the terminal. Again, I'm not too familiar with all this but likely Emacs doesn't know about the protocol - you can check this out by trying to open an image file in a buffer. Make sure `image-mode` is active. If you still don't see the image then my guess is that Emacs doesn't know about iTerm2's protocol for images.

Your best bet in that case is to run emacs as a windowed GUI application.

**Comment by altosaar** [comment]
Thanks! Yes, it seems only the windowed GUI application lets `ein` show plots:

![image](https://user-images.githubusercontent.com/5317244/41369510-134a65a8-6f13-11e8-9648-1594d9487ca0.png)

To get this working, here's what I had to do on Mac Sierra:
```
brew tap railwaycat/emacsmacport
brew cask install emacs-mac
```
Then run Emacs.app, make sure `ein` is installed from MELPA and compiled against this version of emacs.
Next, launch the jupyter notebook using `M-:` followed by `(ein:jupyter-server-start "/usr/local/anaconda3/bin/jupyter" "/tmp")`. Then plots will show up.

Launching `ein` with `M-x` `ein:jupyter-server-start` led to 
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-exists-p(nil)
  ein:jupyter-server-start(nil "/tmp/")
  funcall-interactively(ein:jupyter-server-start nil "/tmp/")
  call-interactively(ein:jupyter-server-start record nil)
  command-execute(ein:jupyter-server-start record)
  helm-M-x(nil #("ein:jupyter-server-start" 0 24 (match-part "ein:jupyter-server-start")))
  funcall-interactively(helm-M-x nil #("ein:jupyter-server-start" 0 24 (match-part "ein:jupyter-server-start")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

**Comment by millejoh** [comment]
Looks like you need to set a value for `ein:jupyter-default-server-command`. I thought ein tried to look for the jupyter command on the user PATH, but maybe I was wrong about that. If you call `ein:jupyter-server-start` with a prefix argument (`C-u`) you will be prompted for the location of the jupyter command.

**Comment by Ariussssss** [comment]
I fixed it by turning this variable on.
```
M-x customize-group RET ein
  Ein:Output Area Inlined Images
```

**Comment by ashutosh-dwivedi-e3502** [comment]
> I fixed it by turning this variable on.
> 
> ```
> M-x customize-group RET ein
>   Ein:Output Area Inlined Images
> ```
> 
> Related: https://awesomeopensource.com/project/millejoh/emacs-ipython-notebook;

Thanks this worked for me (Emacs 26 on macOS Cataline)
