### ISSUE TITLE
Couldn't authenticate WebSocket connection

### ISSUE THREAD

**Issue by slackline** [millejoh/emacs-ipython-notebook#315]
Hi,

I've encountered the issue of `Couldn't authenticate WebSocket connection` and EIN failing to detect that the kernel is ready `ein: [warn] Kernel is not ready yet! (or closed already)`.  I found a closed issue (#100) on this and it references some solutions which are also closed (#147 and #148) but I still have the 

I'm connecting to a Notebook that is running on a server rather than on the same computer.  I've set passwords under Jupyter Notebook on the remote and from EIN use `ein:notebooklist-login` to enter the password and can then connect using `ein:notebooklist-open` and explicitly providing the URL and port (`http://localhost:8906/`).  This opens a list of notebooks and I can then navigate and open any of these.  When I switch to the buffer though I can not run any code sections with `C-c C-c` as I'm informed the kernel isn't ready.  Code can be executed from a web-browser though so the kernel is running.  Screenshot of Emacs [here](https://i.imgur.com/YsLg6vt.png).

The console output shows...

    [W 07:44:45.189 NotebookApp] Notebook createAverageSpeedSegments.ipynb is not trusted
    [W 07:44:49.648 NotebookApp] Couldn't authenticate WebSocket connection
    [W 07:44:49.651 NotebookApp] 403 GET /api/kernels/5990768d-694e-422c-a2a0-6fc633554040/channels?session_id=85baeb89-62f9-4f3d-9a7a-4168d872374d (::1) 6.57ms referer=None

Whilst the EIN log shows...

    [info] Opened notebook list at http://localhost:8906 with path . @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Opening notebook createAverageSpeedSegments.ipynb... @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Reading nbformat4 notebook. @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Worksheet createAverageSpeedSegments.ipynb is ready @#<buffer *ein: http://localhost:8906/createAverageSpeedSegments.ipynb*>
    [info] Enabling autosaves for createAverageSpeedSegments.ipynb with frequency 60 seconds. @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Notebook createAverageSpeedSegments.ipynb is ready @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Kernel started: 5990768d-694e-422c-a2a0-6fc633554040 @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Starting channels WS: "ws://localhost:8906/api/kernels/5990768d-694e-422c-a2a0-6fc633554040/channels?session_id=85baeb89-62f9-4f3d-9a7a-4168d872374d" @#<buffer *ein:notebooklist http://localhost:8906*>
    [info] Opened notebook list at http://localhost:8906 with path . @#<buffer *ein:notebooklist http://localhost:8906*>
    [warn] Kernel is not ready yet! (or closed already.) @#<buffer *ein: http://localhost:8906/createAverageSpeedSegments.ipynb*>
    [warn] Kernel is not ready yet! (or closed already.) @#<buffer *ein: http://localhost:8906/createAverageSpeedSegments.ipynb*>
    [warn] Kernel is not ready yet! (or closed already.) @#<buffer *ein: http://localhost:8906/createAverageSpeedSegments.ipynb*>
    

I tried the solution suggested in #100 of switching to `url-retrieve` instead of `curl` but this prevented me from connecting to the Notebook list at all....

    [W 08:00:53.399 NotebookApp] Forbidden
    [W 08:00:53.399 NotebookApp] 403 GET /api/contents/ (::1) 0.97ms referer=None
    [W 08:01:21.243 NotebookApp] Forbidden
    [W 08:01:21.244 NotebookApp] 403 GET /api/contents/ (::1) 2.08ms referer=None

Reverting to `curl` and I can connect to the Notebook list again but the kernel remains unresponsive.

Jupyter version is 4.4.0 and EIN was installed from MELPA and is version 0.14.1

Let me know if I can provide any more information.

**Comment by millejoh** [comment]
I am a little confused - you say your are trying to connect to a remote server, but the URL you are using above is for a localhost? Have you tried using a URL that incorporates the IP address of the remote server?

You should also take a look at your cookie file, it is probably in `~/.emacs.d/.cache/request` or similar (you can look at the customization options for `request`). There should be one or more cookies that look like the following:

```
localhost	FALSE	/	FALSE	0	_xsrf	2|d17d4541|281babd5b93c6f19f91c2f9ec9e8778a|1512146724
#HttpOnly_localhost	FALSE	/	FALSE	1530910813	username-localhost-8888	"2|1:0|10:1528318813|23:username-localhost-8888|44:YTZjMzUwMGU1YjQxNDMwMTlmNTYxY2JhMGY1YTYzNzg=|ee9a3f9ec02c67d2ec3236aaf3719d983ae4da939183fd34e369be12f7ea3177"
```

Really important that along with a line starting with `localhost` you also have a line starting with `#HttpOnly`.

**Comment by slackline** [comment]
Ah, yes, my apologies I forgot that my `~/.ssh/config` has port-forwarding set up for the server...

    Host ds2
     User slackline
     Port 2219
     LocalForward 8906 localhost:8906
     IdentityFile ~/.ssh/id_ed25519

The IP address of the target server is actually `10.10.10.80` (on the intranet here at work) and specifying 10.10.10.80:8906` when asked to by `ein:notebooklist-open` results in Emacs hanging for a while and erroring out with...

    ein: [error] Kernelspc query call failed with status error.

Looking at the cookies you suggest I've the following (as I've also tried using EIN with a Jupyter notebook that genuinely is running on `localhost`)....


    127.0.0.1	FALSE	/	FALSE	0	_xsrf	2|2f0009a6|7f5509291e9f0ac655d05ee209145055|1528126913
    localhost	FALSE	/	FALSE	0	_xsrf	2|c6b581ca|0e0607245b10634b79d3bf819a72bd51|1528183492
    #HttpOnly_localhost	FALSE	/	FALSE	1530775492	username-localhost-8906	"2|1:0|10:1528183492|23:username-localhost-8906|44:MWFlZGEyYjY2NWQzNDIyMTljMjQ5Zjg5NzM3YjIwMzM=|fef782a3a31d8634f77737f6714167eb47b15afb3ebc0fb87a8aef5b6c3581e3"
    #HttpOnly_localhost	FALSE	/	FALSE	1530879668	username-localhost-8888	"2|1:0|10:1528287668|23:username-localhost-8888|44:NzNlZDI1MDI3ZDM1NGQ3NmFkNDNlMmFlODNkNTEzNTU=|e7097057068c68303b1f014a2af340bc8ef197e60d922fee4bd6c058a9f39b92"

I've double checked EIN against a genuinely locally running service (not port-forwarded) and have the same error of the kernel not being ready (although in the browser version it is responding fine), the log in `*Messages*` shows the kernel as having started but the Websocket error crops up when trying to run a code section and the message says the kernel isn't ready again....

    ein: [info] Login to http://localhost:8888 complete. Now you can open notebook list by `ein:notebooklist-open'.
    ein: [info] Opened notebook list at http://localhost:8888 with path .
    ein: [info] Opening notebook Scratch.ipynb...
    ein: [info] Reading nbformat4 notebook.
    ein: [info] Worksheet Scratch.ipynb is ready
    ein: [info] Enabling autosaves for Scratch.ipynb with frequency 60 seconds.
    ein: [info] Notebook Scratch.ipynb is ready
    Can't guess python-indent-offset, using defaults: 4
    ein: [info] Opened notebook list at http://localhost:8888 with path .
    ein: [info] Kernel started: 7a99145b-cbbe-4d5c-b3f6-54135a2494e5
    ein: [info] Starting channels WS: "ws://localhost:8888/api/kernels/7a99145b-cbbe-4d5c-b3f6-54135a2494e5/channels?session_id=5db3caa1-0e79-4ad5-be58-98fe0edef450"
    error in process filter: Error response received from websocket server [2 times]
    ein: [warn] Kernel is not ready yet! (or closed already.)


Thank you for taking the time to look at and investigate this, appreciated.

**Comment by slackline** [comment]
Ah, my apologies I overlooked the fact that I'm using port-forwarding (via `~/.ssh/config`) here...

    Host ds2
         User neilshephard
         Port 2219
         LocalForward 8906 localhost:8906
         IdentityFile ~/.ssh/id_ed25519

Looking at the request cookies I have two pairs of entires, one for this remote connection (masquerading as a local one) and one for a genuinely local connection.  Looking at it perhaps there is a conflict here...

    $ cat .emacs.d/request/curl-cookie-jar 
    # Netscape HTTP Cookie File
    # http://curl.haxx.se/docs/http-cookies.html
    # This file was generated by libcurl! Edit at your own risk.
    
    127.0.0.1	FALSE	/	FALSE	0	_xsrf	2|2f0009a6|7f5509291e9f0ac655d05ee209145055|1528126913
    localhost	FALSE	/	FALSE	0	_xsrf	2|c6b581ca|0e0607245b10634b79d3bf819a72bd51|1528183492
    #HttpOnly_localhost	FALSE	/	FALSE	1530775492	username-localhost-8906	"2|1:0|10:1528183492|23:username-localhost-8906|44:MWFlZGEyYjY2NWQzNDIyMTljMjQ5Zjg5NzM3YjIwMzM=|fef782a3a31d8634f77737f6714167eb47b15afb3ebc0fb87a8aef5b6c3581e3"
    #HttpOnly_localhost	FALSE	/	FALSE	1531042977	username-localhost-8888	"2|1:0|10:1528450977|23:username-localhost-8888|44:ZmE2YTc2ZWVkOTM3NDc0ZWJjODkzOGZiZDE3ZGE4ZDQ=|94973e52cbc9705b53ab7e054272952d9f080cc3148cfd1d08739af58f8602c1"

I've therefore deleted these cookies and re-entered the password and opened the netbook. I can connect to the notebook and open a specific one fine, but before even trying to run a code section the Websocket error has cropped up

    ein: [info] Opened notebook list at http://localhost:8906 with path .
    ein: [info] Opening notebook createAverageSpeedSegments.ipynb...
    ein: [info] Reading nbformat4 notebook.
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    read slidetype -
    reconstructed slideshow #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (slide_type -))
    ein: [info] Worksheet createAverageSpeedSegments.ipynb is ready
    ein: [info] Enabling autosaves for createAverageSpeedSegments.ipynb with frequency 60 seconds.
    ein: [info] Notebook createAverageSpeedSegments.ipynb is ready
    ein: [info] Kernel started: 5990768d-694e-422c-a2a0-6fc633554040
    ein: [info] Starting channels WS: "ws://localhost:8906/api/kernels/5990768d-694e-422c-a2a0-6fc633554040/channels?session_id=85baeb89-62f9-4f3d-9a7a-4168d872374d"
    error in process filter: Error response received from websocket server [2 times]
    ein: [info] Opened notebook list at http://localhost:8906 with path .
    

Try running a code chunk and I'm again told that the kernel isn't ready (although it runs fine on the browser version)...

    ein: [warn] Kernel is not ready yet! (or closed already.)



Thanks for taking the time to look at this, if there's anything else I can do or try please let me know.

**Comment by millejoh** [comment]
Just to be sure I'm not going crazy, could you verify a couple things:

 1. You can connect to notebooks no problem using the browser interface, right?
 2. Could you provide a dump of the entire contents of the console? I want to see what Jupyter is logging from the moment it starts up until you get the weboscket authentication error.

Could you also send me the output generated by `ein:dev-bug-report-template`?

**Comment by slackline** [comment]
> 1. You can connect to notebooks no problem using the browser interface, right?

Yes, works fine in a browser.

> 2. Could you provide a dump of the entire contents of the console? I want to see what Jupyter is logging from the moment it starts up until you get the weboscket authentication error.

Sure, restarted the notebook and connected from EIN then opened an existing notebook and tried to run the first code chunk. This is the Jupyter output...

    $ jupyter notebook 
    [I 14:32:29.956 NotebookApp] Serving notebooks from local directory: /ssd/floow-smooth-score/python
    [I 14:32:29.956 NotebookApp] 0 active kernels
    [I 14:32:29.956 NotebookApp] The Jupyter Notebook is running at:
    [I 14:32:29.956 NotebookApp] http://localhost:8906/
    [I 14:32:29.956 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    [W 14:33:20.624 NotebookApp] 404 GET /api/kernels/56d37030-4970-4e99-99d7-096a3149a80e/channels?session_id=baf5461f91e245ac8f212d52d8a39eaf (::1): Kernel does not exist: 56d37030-4970-4e99-99d7-096a3149a80e
    [W 14:33:20.732 NotebookApp] 404 GET /api/kernels/56d37030-4970-4e99-99d7-096a3149a80e/channels?session_id=baf5461f91e245ac8f212d52d8a39eaf (::1) 122.54ms referer=None
    [W 14:33:26.617 NotebookApp] 404 GET /api/kernels/5990768d-694e-422c-a2a0-6fc633554040/channels?session_id=b6a0f370839b47a895f5dbba43fc3866 (::1): Kernel does not exist: 5990768d-694e-422c-a2a0-6fc633554040
    [W 14:33:26.619 NotebookApp] 404 GET /api/kernels/5990768d-694e-422c-a2a0-6fc633554040/channels?session_id=b6a0f370839b47a895f5dbba43fc3866 (::1) 6.70ms referer=None
    [W 14:33:26.637 NotebookApp] 404 GET /api/kernels/b2462b35-0af9-4bee-a0ac-3e9a399d93dc/channels?session_id=b2cca68b771e45e09562685e4effa562 (::1): Kernel does not exist: b2462b35-0af9-4bee-a0ac-3e9a399d93dc
    [W 14:33:26.639 NotebookApp] 404 GET /api/kernels/b2462b35-0af9-4bee-a0ac-3e9a399d93dc/channels?session_id=b2cca68b771e45e09562685e4effa562 (::1) 5.78ms referer=None
    [I 14:35:05.748 NotebookApp] Kernel started: 506268b3-4fa1-4dfa-8a3e-129ef6c8193b
    [W 14:35:05.924 NotebookApp] Couldn't authenticate WebSocket connection
    [W 14:35:05.926 NotebookApp] 403 GET /api/kernels/506268b3-4fa1-4dfa-8a3e-129ef6c8193b/channels?session_id=4faf36f6-738d-4175-b1da-ce2fcb260e76 (::1) 3.87ms referer=None

There is nothing reported at the jupyter console on trying to report a code chunk (with `C-c C-c`) within emacs I'm told...

    ein: [warn] Kernel is not ready yet! (or closed already.)

Completed bug report....

## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have

Connecting to a Jupyter Notebook that is running on a different server but via port-forwarding its on localhost.  I can login/authenticate ok and open the main page and individual notebooks but am seeing WebSocket connection errors and am informed the kernel is not ready.

## Steps to reproduce the problem

1. ein:notebooklist-login
2. ein:notebooklist-open
3. http://localhost:8906
4. Open a notebook from the list provided.
5. C-c C-c on a code chunk

## Expected output

Expect the code chunk to run, but instead am told the kernel is not ready.

## Your EIN configuration (in .emacs.d/init.el or somewhere else)

N/A - I've not got as fars as configuring EIN


## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):

$ jupyter --version
4.4.0

$ ipython --version
6.4.0

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):

jupyter-notebook

3. What is your IPython notebook port number or URL?:

http://localhost:8906

But this is via protforwarding as I've the following in ~/.ssh/config

Host abc
     User slackline
     Port 2219
     LocalForward 8906 localhost:8906
     IdentityFile ~/.ssh/id_ed25519
	 
## Additional information (if any)


## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
 of 2017-09-20 on lcy01-07, modified by Debian"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux 583.datascience.thefloow.com 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
"
  :lsb-release
  "No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.14.0"
	   :source-dir "/home/neil.shephard@samba.sheffield.thefloow.com/.emacs.d/elpa/ein-0.14.1/")
 :lib
 ((:name "websocket"
	 :path "~/.emacs.d/elpa/websocket-1.10/websocket.elc"
	 :featurep t
	 :version-var websocket-version
	 :version "1.9")
  (:name "request"
	 :path "~/.emacs.d/elpa/request-0.2.0/request.elc"
	 :featurep t
	 :version-var request-version
	 :version "0.2.0")
  (:name "auto-complete"
	 :path "~/.emacs.d/elpa/auto-complete-1.5.1/auto-complete.elc"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "auto-complete"
	 :path "~/.emacs.d/elpa/auto-complete-1.5.1/auto-complete.elc"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "popup"
	 :path "~/.emacs.d/elpa/popup-0.5.3/popup.elc"
	 :featurep t
	 :version-var popup-version
	 :version "0.5.3")
  (:name "python"
	 :path "/usr/share/emacs/24.5/lisp/progmodes/python.elc"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "markdown-mode"
	 :path "~/.emacs.d/elpa/markdown-mode-2.3/markdown-mode.elc"
	 :featurep nil
	 :version-var nil
	 :version nil)))
```

**Comment by millejoh** [comment]
Your request looks slightly out of date - I have been developing against 0.3.0. Also while I try to keep ein backwards compatible against emacs 24, I haven't exactly been testing against this version for some time.

I think this may be an issue with Jupyter 4.4, though the error message in my Jupyter console is different from yours.

Is running a more recent version on the server an option? Do you have more recent, local version of jupyter that you can run and test againts?

**Comment by slackline** [comment]
> Your request looks slightly out of date - I have been developing against 0.3.0.

I hadn't checked versions as I thought I'd just installed all requirements/dependencies from MELPA, quite how I ended up with request-0.2.0 installed I don't know.  Updating has however solved the issue, thank you very much for being so patient and guiding me through to a solution, I am really grateful.

**Comment by julienchastang** [comment]
I have a similar issue to this one and #100, but

- I **am** using `request  0.3.0`
- I am running  Jupyter `5.5.0` on a **remote** server: https://js-17-236.jetstream-cloud.org
- I do not get any `403`s so `curl` is happy

As was stated earlier in this issue, I am able to login fine and get a list of notebooks etc. But when I try to start a notebook:

```
error in process filter: websocket-outer-filter: Error response received from websocket server
error in process filter: Error response received from websocket server
```

followed by when I try to execute cells

```
ein: [warn] Kernel is not ready yet! (or closed already.)
```

digging into this deeper with edebug, `websocket.el` `1.10` in the `websocket-outer-filter` function is reporting

```
Result: (websocket-invalid-header . "Invalid HTTP status line")

Result: "Invalid HTTP status line"

Invalid HTTP header sent: 73, 110, 118, 97, 108, 105, 100, 32, 72, 84, 84, 80, 32, 115, 116, 97, 116, 117, 115, 32, 108, 105, 110, 101
````

I wonder if the Jupyter API changed in Jupyter `5.5.0`.

**Comment by millejoh** [comment]
Note that seeing the log of the jupyter server can be helpful in knowing where things break down.

Let me try to break down what happens when you open a notebook, which essentially is a call to `ein:notebook-open`.

 1. If the the notebook buffer doesn't already exist, ein uses the Jupyter [REST API](https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API) to get the json nbformat that represents the notebook.
 2. If that is succesful ein will try to determine the kernelspec for the notebook just opened - this just queries cached data and will not result in a call to the Jupyter server.
 3. Start a kernel for notebook (see below for steps 4, 5, and 6).
 4. We eventually end up in the `ein:kernel-start` which makes a call to the REST api to create a new session, via a POST to `/api/sessions/`.
 5. If this is successful jupyter will return a session ID and a kernel ID in the json response. EIN uses this information to construct a URL for the websocket connection (`ein:kernel--ws-url`).
 6. EIN starts the websocket communication channel in a call to `ein:websocket`. Prior to doing this ein tries to make sure all the cookies set during the earlier calls to the jupyter REST API are available when the call to `websocket-open` is made. This is handled in `ein:websocket-prepare-cookies`.
 7. Parse the json representing the notebook and create all the internal elisp data structures that represent a Jupyter notebook. This is where the notebook buffer is created and rendered.

Without seeing the jupyter log I'm not really sure where things are breaking down for you. It sounds like the REST calls are working okay, so maybe things are breaking down in either 5 or 6.

Maybe ein is getting the websocket url wrong - since you are using https, ein should generate a URL that uses the `wss` protocol.

Or, maybe ein is missing a needed authentication cookie for step 6. Looking at the cookie jar file might provide some insight here. If the host and port for the websocket URL don't match the URL used for the REST API calls then things will break down.

Also note that `ein:dev-enable-debug` is your friend - it enables extra logging and enables debugging for websocket, which will open a log buffer for each websocket that is opened.

**Comment by julienchastang** [comment]
Thank you for the thorough, in depth response. Here is the Jupyter log (so my `403` comment earlier is incorrect) :

```
[I 18:23:12.959 NotebookApp] Kernel started: 7bab4a9f-6da6-4d39-b349-50da43ec1604
[W 18:23:13.248 NotebookApp] Couldn't authenticate WebSocket connection
[W 18:23:13.253 NotebookApp] 403 GET /api/kernels/7bab4a9f-6da6-4d39-b349-50da43ec1604/channels?session_id=b3dee539-45a6-47cf-8d7b-c74672307caa (128.117.144.140) 9.34ms referer=None
```

Also, since you mention it here is the `curl-cookie-jar`

```
# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

js-17-236.jetstream-cloud.org	FALSE	/	FALSE	0	_xsrf	2|0c8fdd3d|49979a217d14307fb9162b00d58fdcd2|1531333351
#HttpOnly_js-17-236.jetstream-cloud.org	FALSE	/	TRUE	1533925351	username-js-17-236-jetstream-cloud-org	"2|1:0|10:1531333351|38:username-js-17-236-jetstream-cloud-org|44:ZjcxNzE2YmY4Y2I5NDY4ODhmMTc4MzQ4ZDFmNjEwYWI=|05fdd654753761e463ecbffe91282372811ff7be39f7893e04aa64af28f893f2"

```

I am using a letsencrypt cert BTW and I make sure to reference the full cert chain in the `jupyter_notebook_config.py` (this bit me in the ass previously).

If we are not able to make more progress here, I will open an new issue with `ein:dev-enable-debug ` as you suggest. I am busy for the next couple of weeks so I won't be able to get around to it until later this month. Thanks again.
