### ISSUE TITLE
JupyterLab Support

### ISSUE THREAD

**Issue by Cadair** [millejoh/emacs-ipython-notebook#320]
Thanks for the awesome project! 

I have just started experimenting with JupyterLab, which is planned to eventually replace the notebook (so I am told), and it seems that ein doesn't work when connected to a jupyter lab instance. The notebook list and the notebooks open but when trying to execute cells I get `Kernel is not ready yet (or closed already).`. I am assuming there are a few subtle but important differences in the implementation between the two.

I thought it would be worth opening an issue for this, even though I understand if it's not a high priority or easy task!

**Comment by findesgh** [comment]
Do you connected to the instance via HTTPS? And if yes, can you try using an unencrypted connection? I get the same behavior you describe if I connect to a jupyter server over HTTPS.
