### ISSUE TITLE
Tab completion broken

### ISSUE THREAD

**Issue by malb** [millejoh/emacs-ipython-notebook#325]
When running tab completion I'm getting

```
[I 10:45:21.811 NotebookApp] Adapting to protocol v5.1 for kernel d8fa8e64-2eb3-4519-8e7b-0a4ff5ad59a2
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/opt/sage-devel/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 232, in dispatch_shell
    handler(stream, idents, msg)
  File "/opt/sage-devel/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 429, in complete_request
    code = content['code']
KeyError: 'code'
```

I'm seeing the same exception with another Jupyter installation. Tab completion from the browser works fine.

My ein config is:

```emacs-lisp
(use-package ein
  :defer 30
  :after ob
  :commands (ein:notebooklist-open ein:notebooklist-login ein:query-ipython-version)
  :config (progn
            (setq ein:use-auto-complete t
                  ein:complete-on-dot nil
                  ein:notebook-create-checkpoint-on-save t
                  ein:completion-backend 'ein:use-company-backend
                  ein:url-or-port '(8890 8889)
                  ein:default-url-or-port 8890
                  ein:console-args '("--simple-prompt")
                  ein:console-security-dir "")

            (defun malb/ein-hook ()
              (toggle-truncate-lines t))

            (add-hook 'ein:notebook-multilang-mode-hook #' malb/ein-hook)

            (add-to-list 'org-babel-load-languages '(ein . t))

            (require 'ein-notebook)

            (defun malb/ein-open-here ()
              "We have a link to our projects top directory, this function goes to anything below that."
              (interactive)
              (let ((url (replace-regexp-in-string malb/projects-dir "projects" default-directory)))
                (ein:notebooklist-open 8890 url)))

            (bind-key "S-<return>" #'ein:worksheet-execute-cell-and-goto-next ein:notebook-mode-map)
            (bind-key "C-<return>" #'ein:worksheet-execute-cell ein:notebook-mode-map)))
```

Jupyter version

```
$ ipython --version
5.5.0
```

**Comment by xor-xor** [comment]
@malb - out of curiosity - which version of EIN do you use..? I'm asking because I've noticed the same error on my other laptop, where I have 20180809.1416 installed, but I haven't noticed this issue with 20180626.1257.

**Comment by millejoh** [comment]
For both of you, are you using company or autocomplete and what is the setting of `ein:completion-backend`?

**Comment by malb** [comment]
For me it's ` ein:completion-backend 'ein:use-company-backend` but I also tried with auto-complete and tab completion didn't work either.

**Comment by millejoh** [comment]
Think I found it - I missed a change in the protocol for sending completion requests. It's probably been there a while, so not sure why it took so long to catch this one. I'll push something shortly.

**Comment by xor-xor** [comment]
> For both of you, are you using company or autocomplete and what is the setting of ein:completion-backend?

FWIW, I have `ein:completion-backend` set to `ein:use-ac-backend`, and I don't use any kind of autocompletion in Emacs (be it company-mode or anything else) apart from the one that comes by default with EIN.

**Comment by malb** [comment]
Wow, that was quick. Your fix works for me. Thank you!

**Comment by xor-xor** [comment]
Yep, 20180816.1343 works for me too - thanks!
