### ISSUE TITLE
`q` gets rebound upon second call of `C-u C-c C-f`.

### ISSUE THREAD

**Issue by joostkremers** [millejoh/emacs-ipython-notebook#328]
If I call `C-u C-c C-f` on a function, I get a help buffer, which I can conveniently dismiss with `q`. However, if I then call `C-u C-c C-f` again (on the same or another function), the help buffer pops up again, but pressing `q` gives an error saying that the buffer is read-only.

The first time the help buffer pops up, `q` is bound to `View-quit`, but the second time it pops up, `q` is bound to `self-insert-command`.

Do you have any idea what might be causing this?

Emacs 26.1.50, latest `ein` installed from Melpa (`ein-20180826.1456`).

**Comment by millejoh** [comment]
Not sure yet, but I see that if you kill the pager buffer then you get back the correct behavior for q, but again multiple calls to `C-u C-c C-f` without killing the pager buffer will result in the incorrect behavior you described.

**Comment by millejoh** [comment]
Looks like this behavior is inherited from `view-mode.`  `q` has the description

> `q`	quit View mode, restoring this window and buffer to previous state.
>	  q is the normal way to leave view mode.

Then further down it says:

> c	quit View mode and maybe switch buffers, but don’t kill this buffer.
> C	quit View mode, kill current buffer and go back to other buffer.

If I exit the buffer using `C` then subsequent calls to `C-u C-c C-f` show expected behavior. I would consider this a workaround, though, as in my mind at least typing `q` should not bork additional calls to `ein:pytools-request-tooltip-or-help`. I'll leave this open until I can either 1) Convince Emacs to treat `q` correctly, or 2) Convince myself Emacs is exhibiting the right behavior.

Thanks.

**Comment by joostkremers** [comment]
Heh, I just found out the same thing. :smile: Looking into it a bit further suggests two possible solutions:

* bind `view-exit-action` to some function that makes sure the buffer is killed. Probably binding it to `kill-buffer` would do.
* make a buffer-local binding of `view-no-disable-on-exit` and bind it to `nil`. This will keep `q` from disabling `view-mode`.

**Comment by joostkremers** [comment]
> make a buffer-local binding of view-no-disable-on-exit and bind it to t. This will keep q from disabling view-mode.

Yup, the following seems to work:

```
(define-derived-mode ein:pager-mode view-mode "ein:pager"
  "IPython notebook pager mode.
Commands:
\\{ein:pager-mode-map}"
  (setq-local view-no-disable-on-exit t)
  (font-lock-mode))
```

**Comment by millejoh** [comment]
Well done! Thanks! The change should be appearing any time now in the repository.

**Comment by joostkremers** [comment]
Great, thanks!
