### ISSUE TITLE
websocket error on IPython 3.0.0

### ISSUE THREAD

**Issue by shiyuangu** [millejoh/emacs-ipython-notebook#33]
## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have
The version is master: 68e14(March 11, 2015)
emacs -Q -l zeroin.el
Error: 
error in process filter: condition-case: Error response received from websocket server
error in process filter: Error response received from websocket server

## Steps to reproduce the problem
1. emacs -Q -l zeroin.el

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):

3. What is your IPython notebook port number or URL?:

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.3.1 (i686-pc-linux-gnu, GTK+ Version 3.10.7)
 of 2014-03-07 on toyol, modified by Debian"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux sgu-VirtualBox 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:45:15 UTC 2015 i686 i686 i686 GNU/Linux
"
  :lsb-release
  "No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.3.68e14af"
	   :source-dir "/home/sgu/.emacs.d/emacs-ipython-notebook/lisp/")
 :lib
 ((:name "websocket"
	 :path "~/.emacs.d/emacs-ipython-notebook/lib/websocket/websocket.el"
	 :featurep t
	 :version-var websocket-version
	 :version "0.93.1")
  (:name "request"
	 :path "~/.emacs.d/emacs-ipython-notebook/lib/request/request.el"
	 :featurep t
	 :version-var request-version
	 :version "0.2.0alpha1")
  (:name "auto-complete"
	 :path "~/.emacs.d/emacs-ipython-notebook/lib/auto-complete/auto-complete.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "mumamo"
	 :path "~/.emacs.d/emacs-ipython-notebook/lib/nxhtml/util/mumamo.el"
	 :featurep t
	 :version-var mumamo:version
	 :version "0.91")
  (:name "auto-complete"
	 :path "~/.emacs.d/emacs-ipython-notebook/lib/auto-complete/auto-complete.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "popup"
	 :path "~/.emacs.d/emacs-ipython-notebook/lib/popup/popup.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "fuzzy"
	 :path "~/.emacs.d/emacs-ipython-notebook/lib/fuzzy/fuzzy.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "pos-tip"
	 :path "~/.emacs.d/emacs-ipython-notebook/lib/pos-tip/pos-tip.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "python"
	 :path "~/.emacs.d/emacs-ipython-notebook/lib/python/python.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "markdown-mode"
	 :path "~/.emacs.d/emacs-ipython-notebook/lib/markdown-mode/markdown-mode.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "smartrep"
	 :path "~/.emacs.d/emacs-ipython-notebook/lib/smartrep/smartrep.el"
	 :featurep nil
	 :version-var nil
	 :version nil)))
```

**Comment by shiyuangu** [comment]
using websocket versison: 1.3 (commit 69a377a in repos: https://github.com/ahyatt/emacs-websocket.git)  seems to work(almost, at least EIN seems to be able to talk the ipython notebook kernel).
 Some errors remain: 
when  some random string is being entered in  a cell, the kernel starts to throw out error immediately  even before the cell is excuted: 
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/kernel/zmq/kernelbase.py", line 175, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "/usr/local/lib/python2.7/dist-packages/IPython/kernel/zmq/session.py", line 848, in deserialize
    return adapt(message)
  File "/usr/local/lib/python2.7/dist-packages/IPython/kernel/adapter.py", line 367, in adapt
    return adapter(msg)
  File "/usr/local/lib/python2.7/dist-packages/IPython/kernel/adapter.py", line 70, in __call__
    return handler(msg)
  File "/usr/local/lib/python2.7/dist-packages/IPython/kernel/adapter.py", line 287, in inspect_request
    new_content['detail_level'] = content['detail_level']
KeyError: 'detail_level'

**Comment by millejoh** [comment]
Try updating to the latest on Github (commit 68e14af9eaf916088204f4b210b29df461eac16f). There is a change in the kernel messaging protocol for Jupyter that was resulting in this messaging being generated.

**Comment by millejoh** [comment]
Also see #36. Problem with zeroein.el was with the submodule checking out an old version of websocket.. I just pushed a couple commits that should fix this.
