### ISSUE TITLE
on-the-fly code checking with pyflakes

### ISSUE THREAD

**Issue by rc** [millejoh/emacs-ipython-notebook#332]
Hi, thanks for developing EIN!

is it possible to use a static code checker such as pyflakes in the notebook buffer to check the code on-the-fly, similarly to flymake+pyflakes combo in a regular emacs buffer?

**Comment by rc** [comment]
Thanks for the answer. Yes, `M-x flymake-mode` in the buffer does not work (no file to work with). `C-c '` works and I can run `M-x flymake-mode` in the edit cell buffer, but then nothing happens - the errors are not reported. There is probably something more to do, that is over my limited emacs knowledge.

**Comment by dickmao** [comment]
flymake checking falls out of elpy.
