### ISSUE TITLE
Can't undo any changes

### ISSUE THREAD

**Issue by dov** [millejoh/emacs-ipython-notebook#338]
In git master, it is not possible to undo any changes in an input cell. 

To reproduce:

1. Select any input cell, emarkdown or code.
2. Insert a character
3. Do the emacs command undo, e.g. bound to C-_

The result is the error message (copied from *Messages*): ``user-error: No undo information in this buffer''

**Comment by falematte** [comment]
Undo is still not working for me. Is this normal?

**Comment by dickmao** [comment]
Please file a steps-to-reproduce via `ein:dev-bug-report-template`

**Comment by RyanMatlock** [comment]
## Problem description
Unable to undo using `C-_` (minibuffer say "No undo information in this buffer"
even if I make a brand new cell, input a couple of characters, and try to
invoke undo)

## Steps to reproduce the problem
Create a new cell, enter a character, and try to undo it with `C-_`


## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511))
 of 2018-05-28"
 :emacs-bzr-version nil
 :window-system ns
 :emacs-variant nil
 :os
 (:uname
  "Darwin <computername>.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
"
  :lsb-release nil)
 :notebook
 "Name: notebook
Version: 5.7.8
Summary: A web-based notebook environment for interactive computing
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /usr/local/lib/python3.7/site-packages
Requires: ipykernel, tornado, nbformat, ipython-genutils, Send2Trash, terminado, traitlets, jinja2, jupyter-client, prometheus-client, nbconvert, pyzmq, jupyter-core
Required-by: widgetsnbextension, jupyter
"
 :ipython "7.4.0
"
 :image-types
 (png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.15.0-20190401.2115"
           :source-dir "~/.emacs.d/elpa/ein-20190401.2115/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/elpa/websocket-20180423.16/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.9")
  (:name "request"
         :path "~/.emacs.d/elpa/request-20181129.1138/request.elc"
         :featurep t
         :version-var request-version
         :version "0.3.0")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20170125.245/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/elpa/popup-20160709.1429/popup.elc"
         :featurep t
         :version-var popup-version
         :version "0.5.3")
  (:name "python"
         :path "/Applications/Emacs.app/Contents/Resources/lisp/progmodes/python.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "python-mode"
         :path "~/.emacs.d/plugins/python-mode/python-mode.el"
         :featurep t
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path "~/.emacs.d/elpa/markdown-mode-20190305.319/markdown-mode.elc"
         :featurep t
         :version-var markdown-mode-version
         :version "2.4-dev")
  (:name "helm"
         :path "~/.emacs.d/elpa/helm-core-20190326.921/helm.elc"
         :featurep nil
         :version-var nil
         :version nil)))
```

**Comment by dickmao** [comment]
Hi, can you "Create a new cell, enter a character", then `C-x b *Warnings*` (note the asterisks around the buffer name).  You may not have such a buffer, in which case please report back with the minibuffer output of:
```
M-: ein:worksheet-enable-undo
M-: buffer-local-enable-undo
M-: (key-binding (kbd "C-/"))
```

**Comment by RyanMatlock** [comment]
There was no `*Warnings*` buffer, so here are the `*Messages*` entries from evaluating those expressions:

```
nil [2 times]
undo
```

**Comment by dickmao** [comment]
Do you set `ein:worksheet-enable-undo` anywhere in your `.emacs` or `init.el`?

Otherwise, you might have gotten here:
https://github.com/millejoh/emacs-ipython-notebook/blob/3d16ccf62af8d61a7b7d01e9d792f97a26e6ca54/lisp/ein-worksheet.el#L181

but if you did, you would have gotten a `*Warning*` like "Undo diagnostic failure," which it doesn't seem like you did.

**Comment by RyanMatlock** [comment]
I just added

``` lisp
(setq ein:worksheet-enable-undo t)
```

to my `.emacs` and ran my `reload-dotemacs` function, (essentially `(load-file "~/.emacs")`) and didn't get a `*Warning*`

**Comment by dickmao** [comment]
That variable is required to be true and defaults to true,
https://github.com/millejoh/emacs-ipython-notebook/blob/3d16ccf62af8d61a7b7d01e9d792f97a26e6ca54/lisp/ein-worksheet.el#L44
so I'm afraid I'm out of ideas what's setting it to false.  Sorry.

**Comment by RyanMatlock** [comment]
I didn't notice

https://github.com/millejoh/emacs-ipython-notebook/blob/3d16ccf62af8d61a7b7d01e9d792f97a26e6ca54/lisp/ein-worksheet.el#L48

before, so I stopped EIN and fully restarted Emacs, and now undo works as expected (although I'm not quite sure why I need to include that `setq` line in my `.emacs` if the variable defaults to `t`). Thanks!!

**Comment by yefeiyu** [comment]
I repaired this problem by disable `;;(global-set-key (kbd "C-/") 'delete-other-windows)`
The global key of `C-/` conflict with `EIN`'s own.

**Comment by alcome1614** [comment]
Can you please elaborate more on this:  ` (let ((undo-binding....` ?
I still have not been able to solve this problem and apparently I don't have the function `ein:worksheet-undo-setup`
