### ISSUE TITLE
Error opening jupyter notebook

### ISSUE THREAD

**Issue by dov** [millejoh/emacs-ipython-notebook#340]
After pulling master today I can no longer open a notebook in ein. It fails with the messages (in *Messages*):

ein: [info] Unknown event: status_busy\.Kernel
ein: [info] Unknown event: execution_count\.Kernel
ein: [info] Unknown event: status_idle\.Kernel
ein: [info] Opened notebook list at http://127.0.0.1:8888 with path .

**Comment by dov** [comment]
Sorry, not sure what happened, but I don't think it is related to the latest pull...

**Comment by millejoh** [comment]
Still having problems? Looks like EIN couldn't start a session and/or connect to the running kernel. Are you able to open the notebooklist buffer and browse through your notebook hierarchy? When you try to open a notebook what is the output in the console where the jupyter server is running?

**Comment by dov** [comment]
Everything is fine after I changed my jupyter configuration and disabled XSRF.

```
c.NotebookApp.disable_check_xsrf = True
```
With XSRF I couldn't couldn't connect. In any case, the wording of this issue is too vague and not reproducible, so I'm closing it.
