### ISSUE TITLE
Support jupyter cell tags

### ISSUE THREAD

**Issue by martibosch** [millejoh/emacs-ipython-notebook#341]
Jupyter 5.0 allows defining a set of cell tags that can be useful for certain tools such as `nbconvert` or `papermill` (more info: https://www.i-programmer.info/news/216-python/10663-jupyter-notebook-5-adds-cell-tagging.html)

In Jupyter's web UI it looks like:
![selection_131](https://user-images.githubusercontent.com/5831581/46460635-cf453b00-c7bc-11e8-860e-aee6c9d5e0af.png)

and this is how it looks in the source ipynb file
``  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "autoscroll": false,
    "collapsed": false,
    "ein.hycell": false,
    "ein.tags": "worksheet-0",
    "slideshow": {
     "slide_type": "-"
    },
    "tags": [
     "parameters"
    ]
   },
   "outputs": [],
   "source": [
    "lulc_csv_fname = 'AREA_NOAS04_72_171129.csv' # TODO: fname vs uri (and DATA_DIR)\n",
    "t_snapshot_col = 'AS18_72'"
   ]
  },
``

I believe this feature should be supported in EIN :)

**Comment by peterewills** [comment]
I second this! I would love to have support for tags. We use papermill to generate parametrized notebooks at work and the lack of tags in EIN make it a bit clunky for me.

**Comment by dickmao** [comment]
I'm afraid this won't be worked on until I decide to support papermill (unlikely).
