### ISSUE TITLE
`ein:content-query-hierarchy*` chokes on large hierarchies

### ISSUE THREAD

**Issue by millejoh** [millejoh/emacs-ipython-notebook#345]
Writing this down so I don't forget when I go to bed in 5 minutes.

This is most probably a Windows only issue, but on a large, nested noteobok hierarchy emacs will generate "Too many open files" errors. The solution is probably to use semaphores, something that appears to be provided by [concurrent](https://github.com/kiwanami/emacs-deferred/blob/master/concurrent.el).

**Comment by dickmao** [comment]
It would be instructive to checkout a previous commit and call `ein:notebooklist-open-notebook-global` from a notebooklist buffer on the same big directory.  The asynchronous code was not intended to do any more file opening than the old synchronous code.

Please reference the PR for relief.

**Comment by millejoh** [comment]
Actually, this problem has existed for some time, though not exactly in this form. I had just forgotten about it until your recent updates. So, my true sincere thanks! You've helped me remember and provided some inspiration for a solution (fingers crossed).

I'm still wrapping my head around ecukes, but it would be nice to build some stress tests for ein into the test suite at some point.
