### ISSUE TITLE
Regression: cannot connect buffer to a notebook

### ISSUE THREAD

**Issue by alendit** [millejoh/emacs-ipython-notebook#347]
11c2245c4 introduced a typo at [ein-connect.el:192](https://github.com/millejoh/emacs-ipython-notebook/blob/master/lisp/ein-connect.el#L192): it should read `ein:aif (get-buffer buffer-or-name)` (i.e. a space between `get-buffer` and `buffer-or-name`).

**Comment by dickmao** [comment]
Thank you, I have added a test for such compile errors.
