### ISSUE TITLE
ob-ein: Content list call failed with status error

### ISSUE THREAD

**Issue by jackkamm** [millejoh/emacs-ipython-notebook#355]
I am trying to use ob-ein, following the example in the [docs](http://millejoh.github.io/emacs-ipython-notebook/#org-mode-integration).

However, when I try to edit the SRC block with `C-c '` (`org-edit-special`), or when I try to execute the SRC block with `C-c C-c`, I get the following error message in `*Messages* buffer`:
```
ein: [error] Content list call http://localhost:8888/api/contents/Untitled.ipynb failed with status error.
```
and in `*ein:log-all*` buffer:
```
[verbose] Error thrown: (error http 403) @#<buffer foo.org>
[error] Kernelspc query call failed with status error. @#<buffer foo.org>
[info] Opening notebook Untitled.ipynb... @#<buffer foo.org>
[verbose] Error thrown: (error http 403) @#<buffer foo.org>
[error] Content list call http://localhost:8888/api/contents/Untitled.ipynb failed with status error. @#<buffer foo.org>
[info] Opening notebook Untitled.ipynb... @#<buffer *Org Src foo.org[ ein ]*>
[verbose] Error thrown: (error http 403) @#<buffer *Org Src foo.org[ ein ]*>
[error] Content list call http://localhost:8888/api/contents/Untitled.ipynb failed with status error. @#<buffer *Org Src foo.org[ ein ]*>
```
and in the jupyter notebook server console terminal:
```
[W 23:01:59.262 NotebookApp] Forbidden
[W 23:01:59.263 NotebookApp] 403 GET /api/contents/Untitled.ipynb (127.0.0.1) 0.69ms referer=None
```

In addition, Emacs hangs until I quit with `C-g`.

I am using Emacs 26.1 on Ubuntu 18. Note that other parts of ein work fine (e.g. using the notebook buffer) -- only the org functionality is broken. Please let me know if there is any other info that would be useful for debugging.

UPDATE:

The problem goes away when I disable authentication in jupyter like so:
```
jupyter notebook --no-browser --NotebookApp.token=''
```
So it appears to be an authentication issue in ob-ein.

**Comment by millejoh** [comment]
Thanks for the report. I've noticed similar behavior. If I try executing again after breaking with `C-g` the execution will work. I also believe the issue doesn't occur if you first open the session notebook from the notebooklist buffer.

Does code execution work for you if you try either of the above?

My first thought with the issue that I am seeing is that EIN is trying to execute the code in the session notebook before it finishes opening the notebook and starting a new session, though I am not sure it explains the behavior you see with things working once authentication is disabled.

**Comment by millejoh** [comment]
Prior to executing the code block in org are you sure you have you called `ein:notebooklist-login` and entered the authorization token?

FYI so far I have been unable to reproduce. I typically run jupyter via `M-x ein:jupyter-server-start`. I always have authentication enabled and have not run into authentication issues with the ob-ein features.

**Comment by jackkamm** [comment]
Yes, I am sure I have called `ein:notebooklist-login`, and using the normal notebook buffers works fine. Only when trying to use org does it break.

I am starting the jupyter server with `jupyter notebook --no-browser` in a separate terminal, have you tried to reproduce in this case?

I can confirm that when starting jupyter via `M-x ein:jupyter-server-start` then ob-ein works fine. However I am mainly interested in running jupyter sever remotely, not within emacs.

**Comment by dickmao** [comment]
I presume you are using 0.14.1.  You would need to have a preexisting "Untitled.ipynb" sitting in the root directory of your notebook server for things to proceed.  I can't comment what should happen after that, like what behavior should be expected after `C-c '`

**Comment by jackkamm** [comment]
So, this weekend I updated to Ubuntu 18.10 and also updated all my emacs packages. Since then I can no longer reproduce this bug so I'm closing it.
