### ISSUE TITLE
weird message on connection loss

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#356]
Every now and then I see a huge message in the Echo area, something like this:
```
ein: [error] Error (error Not enough arguments for format string) on websocket #1=#s(websocket open #17=#s(ein:$websocket #1# ... nil ein:kernel--ws-closed-callback ... ... nil nil) #[... \305!	>\204\306\307\302D"\210\310H\305
!>\204"\306\307\311
D"\210
\312H\211\205?\313\305
!>\204;\306\307\311
D"\210
\314H"*\207 [ws cl-struct-websocket-tags websocket cl-struct-ein:$websocket-tags it type-of signal wrong-type-argument 2 ein:$websocket ...] 7] #[... \306!	>\204\307\310\305D"\210\311H\306
!>\204!\307\310\312
D"\210
\311H\306
!>\2046\307\310\313
D"\210
\311H\211\205[\205[\314\306
!>\204W\307\310\313
D"\210
\315H#+\207 [ws cl-struct-websocket-tags frame cl-struct-websocket-frame-tags packet websocket type-of signal wrong-type-argument 2 ...] 8] #[... \305!	>\204\306\307\302D"\210\310H\305
!>\204"\306\307\311
D"\210
\312H\211\205@\313
\305
!>\204<\306\307\311
D"\210
\314H#*\207 [ws cl-struct-websocket-tags websocket cl-struct-ein:$w
```
My knee jerk reaction has always been "okay, connection loss" and `M-x ein:notebook-reconnect-kernel` seemed to fix the problem.
However, the message `Not enough arguments for format string` seems to indicate a bug in ein.
I set `ein:debug` to `t` to no effect, but `M-x ein:dev-start-debug` results in a `*Backtrace*`:
```
Debugger entered--Lisp error: (websocket-closed . #s(websocket-frame :opcode text :pa
  signal(websocket-closed #s(websocket-frame :opcode text :payload "{\"header\":{\"ms
  websocket-send(#s(websocket :ready-state open :client-data #s(ein:$websocket :ws #1
  websocket-send-text(#s(websocket :ready-state open :client-data #s(ein:$websocket :
  ein:websocket-send(#s(ein:$websocket :ws #s(websocket :ready-state open :client-dat
  ein:websocket-send-shell-channel(#s(ein:$kernel :url-or-port "https://datasci-1.cle
  ein:kernel-execute(#s(ein:$kernel :url-or-port "https://datasci-1.clearme.com:8888"
  apply(ein:kernel-execute #s(ein:$kernel :url-or-port "https://datasci-1.clearme.com
  #f(compiled-function (cell kernel code &rest args) #<bytecode 0x446171e9>)(#<ein:co
  apply(#f(compiled-function (cell kernel code &rest args) #<bytecode 0x446171e9>) (#
  #f(compiled-function (cl-cnm cell kernel code &rest args) #<bytecode 0x4098ebd5>)(#
  apply(#f(compiled-function (cl-cnm cell kernel code &rest args) #<bytecode 0x4098eb
  #f(compiled-function (&rest args) #<bytecode 0x40f20dd1>)(#<ein:codecell ein:codece
  apply(#f(compiled-function (&rest args) #<bytecode 0x40f20dd1>) #<ein:codecell ein:
  ein:cell-execute-internal(#<ein:codecell ein:codecell-408ffa50> #s(ein:$kernel :url
  #f(compiled-function (cell) #<bytecode 0x446171bd>)(#<ein:codecell ein:codecell-408
  apply(#f(compiled-function (cell) #<bytecode 0x446171bd>) #<ein:codecell ein:codece
  #f(compiled-function (cl-cnm cell) #<bytecode 0x4098fbc9>)(#f(compiled-function (&r
  apply(#f(compiled-function (cl-cnm cell) #<bytecode 0x4098fbc9>) #f(compiled-functi
  #f(compiled-function (&rest args) #<bytecode 0x446297ed>)(#<ein:codecell ein:codece
  apply(#f(compiled-function (&rest args) #<bytecode 0x446297ed>) #<ein:codecell ein:
  ein:cell-execute(#<ein:codecell ein:codecell-408ffa50>)                            
  ein:worksheet-execute-cell(#<ein:worksheet ein:worksheet-40f9461c> #<ein:codecell e
  funcall-interactively(ein:worksheet-execute-cell #<ein:worksheet ein:worksheet-40f9
```

**Comment by millejoh** [comment]
I've update this logging call to note be quite so verbose, as there really is no need to dump the entire websocket structure when an error is occurred. I'm not sure if it will help track down what is happening, but it will at least clean up the log a bit. When you see this error again let me know what gets printed out.

**Comment by sam-s** [comment]
What I see now is
```
ein: [info] Starting channels WS: "wss://datasci-1.clearme.com:8888/api/kernels/d41c0a98-0ce6-460b-95d3-1b679270e1cb/channels?session_id=a766ffbc-badd-43b4-a29f-b973ac1e3ef9"
ein: [error] Error (wrong-type-argument ein:$websocket nil) on websocket action on-close (ws:wss://datasci-1.clearme.com:8888/api/kernels/d41c0a98-0ce6-460b-95d3-1b679270e1cb/channels?session_id=a766ffbc-badd-43b4-a29f-b973ac1e3ef9).
```

**Comment by millejoh** [comment]
One question - are these happening on notebooks that are open for long periods in emacs? If so, have you tried setting `ein:enable-keepalive` to T? I dimly recall an issue with cookies expiring in long running sessions, though not sure if that is related to what you are seeing.

**Comment by sam-s** [comment]
Yes, my notebooks are open for a long time; I will try setting `ein:enable-keepalive` to `t`.
BTW, I just got another
```
ein: [error] Error (error Not enough arguments for format string) on websocket action on-message (ws:wss://datasci-1.clearme.com:8888/api/kernels/d41c0a98-0ce6-460b-95d3-1b679270e1cb/channels?session_id=a766ffbc-badd-43b4-a29f-b973ac1e3ef9).
```

**Comment by dickmao** [comment]
I can't comment on the dying websockets, but regarding `Not enough arguments for format string`, I am wondering if your websocket library files are unabridged and the latest.  Mine are in a directory called `~/.emacs.d/elpa/websocket-20171113.2045`.

**Comment by millejoh** [comment]
The emacs websocket package is some solid code. I think it more likely the error is occurring somewhere in the bowels of ein's code and the exception is just being caught as it bubbles up into the websocket callback and ... I'll stop my analogy right there.

This is probably happening somewhere in ein's notification system, which I still don't fully understand, and probably being triggered by the connection going stale and disconnecting. I see similar errors when my laptop goes to sleep then wakes up, but have yet to figure out a way to gracefully recover. My fingers are crossed that `ein:notebooklist-enable-keepalive` will keep this from happening. You may have to play around with the setting for `ein:notebooklist-keepalive-refresh-time` to make this work.

Or its entirely possible something else is happening and this won't work at all.

**Comment by sam-s** [comment]
`Not enough arguments for format string` is a coding error rather than network failure (or something like that).
I think `ein:log` should report such errors in `*Backtrace*` rather that as a message.

**Comment by sam-s** [comment]
`Not enough arguments for format string` was fixed by 35f06bab.

**Comment by dickmao** [comment]
Shot in half-dark.  Please try making this change https://github.com/dickmao/emacs-ipython-notebook/pull/5/commits/235eea16b528369bedf4205c40239c21d27e5dad 

I never tested connecting notebooks to ipython.  I'm not sure what that workflow looks like (Is your buffer really 866,000 characters?)

**Comment by sam-s** [comment]
Yes, my notebooks are rather large. They are playgrounds - I don't through anything away until I am confident it's junk.

I am still getting 
```
ein: [info] WS action [(error show stopper ((80444 . 80465) (

Execution pending

. 80444) (#<marker at 80465 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (80379 . 80444) (t . 0) nil (65076 . 65097) (

Execution pending

. 65076) (#<marker at 80465 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (65024 . 65076) 62798 nil (65024 . 65045) (

Execution pending

. 65024) (#<marker at 80465 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (64970 . 65024) (t . 0) nil (64970 . 64991) (

Execution pending

. 64970) (#<marker at 80465 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (64903 . 64970) 62798 nil (64903 . 64924) (

Execution pending

. 64903) (#<marker at 80465 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (64836 . 64903) nil (64836 . 64857) (

Execution pending

. 64836) (#<marker at 80465 in *ein: https://datasci-1.clearme.com:8888/training-301.
ein: [info] WS action [(error show stopper ((80503 . 80524) (

Execution pending

. 80503) (#<marker at 80524 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (80444 . 80503) (t . 0) (80444 . 80465) (

Execution pending

. 80444) (#<marker at 80524 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (80379 . 80444) (t . 0) nil (65076 . 65097) (

Execution pending

. 65076) (#<marker at 80524 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (65024 . 65076) 62798 nil (65024 . 65045) (

Execution pending

. 65024) (#<marker at 80524 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (64970 . 65024) (t . 0) nil (64970 . 64991) (

Execution pending

. 64970) (#<marker at 80524 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (64903 . 64970) 62798 nil (64903 . 64924) (

Execution pending

. 64903) (#<marker at 80524 in *ein: https://datasci-1.clearme.com:8888/training-

ein: [info] WS action [(error show stopper ((80559 . 80580) (

Execution pending

. 80559) (#<marker at 80580 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (80503 . 80559) (t . 0) nil (80503 . 80524) (

Execution pending

. 80503) (#<marker at 80580 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (80444 . 80503) (t . 0) (80444 . 80465) (

Execution pending

. 80444) (#<marker at 80580 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (80379 . 80444) (t . 0) nil (65076 . 65097) (

Execution pending

. 65076) (#<marker at 80580 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (65024 . 65076) 62798 nil (65024 . 65045) (

Execution pending

. 65024) (#<marker at 80580 in *ein: https://datasci-1.clearme.com:8888/training-301.ipynb*> . -21) (64970 . 65024) (t . 0) nil (64970 . 64991) (

Execution pending

. 64970) (#<marker at 80580 in *ein: https://datasci-1.clearme.com:8888/trainin
```
I am using `"0.15.0"` from `elpa/ein-20181105.315`.

**Comment by dickmao** [comment]
By the way, if it's important enough to you, if you can show me a minimum working example of the bug, that would greatly increase the probability of a fix.

**Comment by sam-s** [comment]
Indeed, `undo` is largely broken, especially that execution kills all undo history of the cell.
(I _hope_ undo is per-cell).
I am not sure how I can create an MRE, since I don't even know what the message means.

**Comment by millejoh** [comment]
I don’t think the size of the notebook is a factor as I see similar errors occurring with small notebooks. Finding a reproducible scenario has been a challenge, however, which is why I have kept silent so far.

What I can see is that the error’s are mostly benign. They do not put the notebook buffer into an inconsistent state, but they are an abrupt interruption.

Maybe it would help if you could explain why you wrote this test case and what you are trying to communicate with the error message. M

John

**Comment by dickmao** [comment]
For years execution and other whole-cell operations used to kill all the undo history, but as of ad8408d, that should no longer be the case.

I agree that the notebook size is not a factor as 80k is not too big (but the preceding example with 800k is).

The undo accounting depends on a set cardinality constraint between the `undo-list` and the `%which-cell%` ledger associating actions to undo's.  It's tough code to follow (at least for me, and I wrote it).

**Comment by dickmao** [comment]
Ah, it looks like that `Execution pending` message is coming from `ein:timestamp`, and from a brief search of Issues, it looks like you two are the only to use it?  I had to explicitly `require ein:timestamp` to get that "Execution pending" message.  Yes, requiring that `ein:timestamp` completely breaks undo, making ad8408d no better than the commit before it.

**Comment by dickmao** [comment]
I have updated the comment in #339 to say the following:

> Undo is only ever suppose to undo keystrokes in the "input area". In the default color scheme, these are characters in the "brown" areas. If undo should ever undo things in the prompt or output areas, leaving the cursor in a weird place (what tkf called "messing up the buffer"), this is a bug and should be reported.
