### ISSUE TITLE
Quick try fails

### ISSUE THREAD

**Issue by kidmose** [millejoh/emacs-ipython-notebook#36]
After running into another issue I try to follow the *Quick try* without my own `~/.emacs.d` to investigate if I caused the problem myself. 
I find that the *Quick try* method fails to open a new notebook, required to test for the initial issue. 

Any advise on what ["I did"|"went"|"is"] wrong?

## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Steps to reproduce the problem

1. Start `ipython notebook` (3.0.0)
2. Run 'Quick try"

    git clone git://github.com/millejoh/emacs-ipython-notebook.git
    cd emacs-ipython-notebook/
    lisp/zeroein.el

3. Select *[New Notebook]*

## Expected output

A new notebook

## Your EIN configuration (in .emacs.d/init.el or somewhere else)

None (zeroein.el)

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`): 3.0.0

2. How do you start IPython? (e.g., `ipython notebook --port 9999`): ipython notebook

3. What is your IPython notebook port number or URL?: 8888

## Additional information (if any)

emacs \*Messages\* : 

    ein: [info] Opened notebook list at 8888 with path 
    ein: [info] Creating a new notebook at ...
    ein: [info] New notebook. Port: 8888, Path: 
    ein: [info] Creating a new notebook ()... Done.
    ein: [info] Opening notebook Untitled3.ipynb...
    ein: [info] Reading nbformat4 notebook.
    ein: [info] Worksheet Untitled3.ipynb is ready
    ein: [info] Opened notebook list at 8888 with path 
    ein: [info] Kernel started: 5acfc06a-48cb-45c6-89b5-e02ea091d8ed
    ein: [info] Starting channels WS: "ws://127.0.0.1:8888/api/kernels/5acfc06a-48cb-45c6-89b5-e02ea091d8ed/channels?session_id=5b48f585-3a03-4bca-89b2-1130bb8aeaec"
    error in process filter: condition-case: Error response received from websocket server
    error in process filter: Error response received from websocket server

ipython notebook output: 

    $ ipython notebook
    [I 14:53:42.069 NotebookApp] Using existing profile dir: u'/home/kidmose/.ipython/profile_default'
    [I 14:53:42.072 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
    [I 14:53:42.083 NotebookApp] Serving notebooks from local directory: /home/kidmose/git-reps/nalm/machine-learning
    [I 14:53:42.083 NotebookApp] 0 active kernels 
    [I 14:53:42.083 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
    [I 14:53:42.083 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    
    (process:21215): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
    [I 14:53:58.600 NotebookApp] Creating new notebook in 
    [I 14:53:58.719 NotebookApp] Kernel started: 5acfc06a-48cb-45c6-89b5-e02ea091d8ed
    [W 14:53:58.994 NotebookApp] Blocking Cross Origin WebSocket Attempt.  Origin: kidmose.eng.au.dk, Host: 127.0.0.1
    [W 14:53:58.995 NotebookApp] 403 GET /api/kernels/5acfc06a-48cb-45c6-89b5-e02ea091d8ed/channels?session_id=5b48f585-3a03-4bca-89b2-1130bb8aeaec (127.0.0.1) 264.62ms referer=None

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7)
 of 2014-03-07 on lamiak, modified by Debian"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux  3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
"
  :lsb-release
  "No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 17.1 Rebecca
Release:	17.1
Codename:	rebecca
")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.3.7a43f34"
	   :source-dir "/home/kidmose/emacs-ipython-notebook/lisp/")
 :lib
 ((:name "websocket"
	 :path "~/emacs-ipython-notebook/lib/websocket/websocket.el"
	 :featurep t
	 :version-var websocket-version
	 :version "0.93.1")
  (:name "request"
	 :path "~/emacs-ipython-notebook/lib/request/request.el"
	 :featurep t
	 :version-var request-version
	 :version "0.2.0alpha1")
  (:name "auto-complete"
	 :path "~/emacs-ipython-notebook/lib/auto-complete/auto-complete.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "mumamo"
	 :path "~/emacs-ipython-notebook/lib/nxhtml/util/mumamo.el"
	 :featurep t
	 :version-var mumamo:version
	 :version "0.91")
  (:name "auto-complete"
	 :path "~/emacs-ipython-notebook/lib/auto-complete/auto-complete.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "popup"
	 :path "~/emacs-ipython-notebook/lib/popup/popup.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "fuzzy"
	 :path "~/emacs-ipython-notebook/lib/fuzzy/fuzzy.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "pos-tip"
	 :path "~/emacs-ipython-notebook/lib/pos-tip/pos-tip.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "python"
	 :path "~/emacs-ipython-notebook/lib/python/python.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "markdown-mode"
	 :path "~/emacs-ipython-notebook/lib/markdown-mode/markdown-mode.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "smartrep"
	 :path "~/emacs-ipython-notebook/lib/smartrep/smartrep.el"
	 :featurep nil
	 :version-var nil
	 :version nil)))
```

**Comment by millejoh** [comment]
Looks like you need to update websockets. EIN needs version 1.3 to work - if you don't mind using MELPA or el-get those are probably the easiest/best way to get ein running.

Doing a `git submodule update` might also fix this.

**Comment by kidmose** [comment]
`git submodule update` or `cd lib/websockets && checkout master` doesn't seem to help (Issue remains)

After closing emacs and rerunning `list/zeroein.el`,  `ein:dev-bug-report-template` still says websocket is version 0.93.1 and websocket submodule is put back to: 

     /home/.../websocket $ git log -1
    commit b65328cc09e7c802ae29142ec5e7fa1f18ecacf1
    Author: Andrew Hyatt <ahyatt@gmail.com>
    Date:   Sun Sep 2 23:56:07 2012 -0400
    
        Made the max number of bytes transimssible 2^29 - 1 instead of 2^32 - 1.
        
        This is the maximum positive value an elisp integer can have on 32 bit
        machines.

If I understand things right (which I might very well **not**) then `list/zeroein.el`fails because is fetches an old version of websockets. 
I'll see if I can fix this and provide a pull request to fix. 

I appreciate you suggestion to use MELPA or el-get, but shouldn't the 'quick try' method work out of the box-like?

Said it before, but it can't be said to often: Thanks for your effort :)

**Comment by kidmose** [comment]
Updating `lib/websocket` doesn't solve it. 
Still no new notebook buffer appearing when activating *[New Notebook]*. 
It stays at the notebook list buffer and produces the following messages: 

    For information about GNU Emacs and the GNU system, type C-h C-a.
    `flet' is an obsolete macro (as of 24.3); use either `cl-flet' or `cl-letf'.
    (lambda (elem) ...) quoted with ' rather than with #'
    Blocking call to accept-process-output with quit inhibited!! [2 times]
    ein: [info] Opened notebook list at 8888 with path 
    ein: [info] Creating a new notebook at ...
    ein: [info] New notebook. Port: 8888, Path: 
    ein: [info] Creating a new notebook ()... Done.
    ein: [info] Opening notebook Untitled1.ipynb...
    ein: [info] Reading nbformat4 notebook.
    ein: [info] Worksheet Untitled1.ipynb is ready
    Making mumamo-bug-3467-w14 local to  *temp* while let-bound!
    Tested for Bug 3467 => PASSED
    ein: [info] Kernel started: 88b3b499-6401-4675-a750-963021c6ee17
    ein: [info] Starting channels WS: "ws://127.0.0.1:8888/api/kernels/88b3b499-6401-4675-a750-963021c6ee17/channels?session_id=426efa21-7e9a-4bdd-94db-e383e0e82b69"
    ein: [info] Opened notebook list at 8888 with path 
    ein: [info] Unknown event: status_busy\.Kernel
    ein: [info] Unknown event: status_idle\.Kernel
    ein: [info] Unknown event: status_busy\.Kernel
    ein: [info] Unknown event: status_idle\.Kernel
    ein: [info] Unknown event: execution_count\.Kernel

And ipython:

     /home/kidmose $ ipython notebook
    [I 10:38:04.771 NotebookApp] Created profile dir: u'/home/kidmose/.ipython/profile_default'
    [I 10:38:04.775 NotebookApp] Writing notebook server cookie secret to /home/kidmose/.ipython/profile_default/security/notebook_cookie_secret
    [I 10:38:04.775 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
    [I 10:38:04.786 NotebookApp] Serving notebooks from local directory: /home/kidmose
    [I 10:38:04.786 NotebookApp] 0 active kernels 
    [I 10:38:04.786 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
    [I 10:38:04.786 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    
    (process:8377): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
    [I 10:38:27.366 NotebookApp] Creating new notebook in 
    [I 10:38:27.369 NotebookApp] Writing notebook-signing key to /home/kidmose/.ipython/profile_default/security/notebook_secret
    [I 10:38:27.489 NotebookApp] Kernel started: 88b3b499-6401-4675-a750-963021c6ee17

Change in debug template:

    (:version "0.3.a7e9e7f"
    	   :source-dir "/home/kidmose/emacs-ipython-notebook/lisp/")
     :lib
     ((:name "websocket"
    	 :path "~/emacs-ipython-notebook/lib/websocket/websocket.el"
    	 :featurep t
    	 :version-var websocket-version
    	 :version "1.3")

**Comment by kidmose** [comment]
Can the proposed solution (Using MELPA or el-get) be used in the quick try?

**Comment by millejoh** [comment]
Think I finally figured this out. I've updated the repository so the submodules will point to the right version of websocket and added ein-mumamo as a submodule. Try updating and let me know if this works for you.

**Comment by kidmose** [comment]
Works for me - thanks :+1:
