### ISSUE TITLE
Fail to open directory in notebooklist

### ISSUE THREAD

**Issue by xavierr** [millejoh/emacs-ipython-notebook#364]
https://github.com/millejoh/emacs-ipython-notebook/blob/ab8f881bff5f12d97143fd5be05158cc9dc90acc/lisp/ein-notebooklist.el#L727

When using directory widget and going down more than one directory, the fact that `directory-file-name` removes slash creates wrong string for path. The issue is solved (for me) if I replace the function `directory-file-name` with `file-name-as-directory`

**Comment by dickmao** [comment]
Thank you.  Our test only checked one directory level down, not two.

**Comment by millejoh** [comment]
Thank you both... Github automagically closed the issue since I accepted the PR, but if for some reason troubles continue don't hesitate to let us know!
