### ISSUE TITLE
Add command "execute all above"

### ISSUE THREAD

**Issue by dov** [millejoh/emacs-ipython-notebook#367]
Description of use case: A couple of times it has happened that I have executed a long list of cells in a fastai course notebook, only to discover that my GPU is caught in another running python instance. Since python cannot recover from such an error I have to restart (after killing the "other" process) the kernel and redo the evaluations. Execute all above, would make this much faster.

**Comment by mfrasca** [comment]
I have been looking for some shortcut, and my first guess was C-c C-r, that would reset the cell execution count, then execute everything in sequence.  the `ein:worksheet-execute-all-cell` comes close, but it doesn't reset the count and it doesn't reformat the markdown.
