### ISSUE TITLE
Proposal: Integrate interactive debugger (Debugger mode)

### ISSUE THREAD

**Issue by kidmose** [millejoh/emacs-ipython-notebook#37]
I'm trying to use the python debugger (`pdb` or ideally `ipdb`) and run into some issues: 

### Expected:
Inserted and executed `import pdb; pdb.set_trace()` and expected to get a `*gud*` buffer (Debugger mode). 

### Experienced:
`StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.`

### Code:

    In [1]:
    import pdb; pdb.set_trace()
    
    --Call--
    > /usr/local/lib/python2.7/dist-packages/IPython/core/displayhook.py(222)__call__()
    -> def __call__(self, result=None):
    
    
    Truncated Traceback (Use C-c C-x to view full TB):
    /usr/local/lib/python2.7/dist-packages/IPython/kernel/zmq/kernelbase.pyc in raw_input(self, prompt)
        644         if not self._allow_stdin:
        645             raise StdinNotImplementedError(
    --> 646                 "raw_input was called, but this frontend does not support input requests."
        647             )
        648         return self._input_request(prompt,
    
    StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

### Proposal:
Given that it is feasible: 
Present a buffer in Debugger mode running the debugger.

**Comment by millejoh** [comment]
This is definitely on my wishlist, along with an object inspector. Maybe the
most direct path to doing this is supporting raw_input messages.

I was also thinking as a first step to at least get better support for walking
through and inspecting traceback objects, which means first I need to better
support object inspection. Not a lot of time at the moment, but patches are
always welcome!

**Comment by kidmose** [comment]
With my very limited lisp knowledge it seems a daunting task, but knowing that it's in line with your ideas I'll have a look at it and get back with any relevant results.

**Comment by millejoh** [comment]
I have very basic support of this working on the stdin-channels branch. Check it out and let me know what you think.
