### ISSUE TITLE
No module named 'ein'

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#374]
I get .a stream of these messages in the echo area and `*Messages*`:
```
ein: [error] ein:completions--prepare-oinfo: ("[0;31m---------------------------------------------------------------------------[0m" "[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)" "[0;32m<ipython-input-108-865058fe65ee>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0m__import__[0m[0;34m([0m[0;34m'ein'[0m[0;34m)[0m[0;34m.[0m[0mprint_object_info_for[0m[0;34m([0m[0mmaster_df[0m[0;34m.[0m[0mInputLexID[0m[0;34m.[0m[0mvar[0m[0;34m)[0m[0;34m[0m[0m
[0m" "[0;31mModuleNotFoundError[0m: No module named 'ein'")
```
how do I avoid this?
thanks!

**Comment by millejoh** [comment]
Looks like Python is complaining that it can't find `ein.py`. I think @dickmao commented on a similar issue earlier. After opening a websocket connection to a running kernel at some point `ein` should be calling `ein:pytools-add-sys-path`.

Few things to check:

 1. Do you have an `ein.py` file in your ein installation directory?
 2. What is the value of `ein:source-dir`?
 3. In python does the path to ein show up in the `sys.path` variable?

**Comment by sam-s** [comment]
`ein:source-dir ` is `/Users/ssteingold/.emacs.d/elpa/ein-20181029.1316/` and I do have `ein.py` there.
the python is running on a remote box without an `ein` installation.

**Comment by dickmao** [comment]
A recent change exposes autocompletion errors that were previously swallowed.
https://github.com/millejoh/emacs-ipython-notebook/blob/ab10680acb7908313505fd6a76f9210e59fb9dc0/lisp/ein-completer.el#L161-L162
Maybe I shouldn't have exposed them.  Are you overriding `ein:completion-backend` to use company?  I'd be curious to know if autocompletion ever worked for you.

**Comment by sam-s** [comment]
I do set `ein:completion-backend` to `ein:use-company-backend`.
It was never usable.
Emacs would always freeze when it was trying to create a completion list.
Then it would offer me completing options - but if I selected one, it would insert it while completely messing up the cell being edited.
I also get errors when the point is at the beginning of a line.
It might be a good idea to disable completion...

**Comment by dickmao** [comment]
Ok.  Then you should just remove that customization.  It will default to the original `auto-complete` which -- if you're like me -- may still be undesirable, but at least you shouldn't get the errors.

**Comment by millejoh** [comment]
Exposing the errors is actually something of a blessing in disguise because now I can see more clearly, though not completely clearly, what is causing the errors.

A lot of it seems to be the pytools code not correctly catching exceptions, or trying to complete against magic or incomplete object names.

I give myself 50/50 odds for figuring out a fix.

John

**Comment by sam-s** [comment]
these errors really DO slow me down - it would be nice to be able to silence them on demand.
also, it seems that trying to load local python code from a remote notebook is a bug.

**Comment by millejoh** [comment]
Okay, there will still be an initial (potentially long) delay as the cache is being built, but performance for the company completion backend overall should be much improved. I also realized that the errors occur when a kernel restarts, as the pytools code would be lost each time this happens. Hopefully that will no longer occur. Let me know how things go!

**Comment by millejoh** [comment]
The flickering is ein building the oinfo cache - i.e. calling `__ein_print_object_info_for` in the kernel for each completion candidate. The flickering is good, I think - it means latency for talking to the kernel is minimal and the calls are completing quickly. As you work you should see less and less of the flickering. The only issue is that the cache is not preserved between sessions, but I'm thinking of a way to implement that. Probably something along the line of keeping a crude db of the oinfo data, associated per kernelspec.

**Comment by dickmao** [comment]
Flickering is no longer an issue.
