### ISSUE TITLE
How do I reconnect?

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#377]
My notebooks run on a remote server on VPN.
Thus a lot of times I am not connected to the server.
The server runs very long commands, and restarting the kernel is always a disaster, to be avoided at all costs.
This morning I reconnected to the VPN and tried to reconnect my notebooks to the server using `M-x ein:notebook-reconnect-kernel RET` and I am asked to restart the kernel!!!
Then I see 
```
‘ein:notebook-reconnect-kernel’ is an obsolete command (as of 0.14.2); use ‘ein:notebook-restart-kernel-command’ instead.
```
in `*Messages*`.
What is going on?!

**Comment by sam-s** [comment]
this appears to be due to d62194479740ee9d1c192726cef55cf89f010539 by @dickmao.

**Comment by sam-s** [comment]
Moreover the kernel in question (i.e., the python process on the remote server) is still running (at 100% CPU), and I want to see the output it has produced over night.

**Comment by millejoh** [comment]
One thing to try - delete the notebook buffer and go back to the notebooklist buffer. If you reopen the notebook from the notebooklist buffer it should (at least in the old days) try to connect to the still running kernel.

**Comment by sam-s** [comment]
thanks, I got 
```
Debugger entered--Lisp error: (args-out-of-range #s(ein:$kernel :url-or-port "https://datasci-1.clearme.com:8
  ein:kernelinfo-setup-hooks(#<ein:kernelinfo ein:kernelinfo-47456f34>)                                      
  ein:kernelinfo-new(#s(ein:$kernel :url-or-port "https://datasci-1.clearme.com:8888" :events #<ein:events ei
  ein:notebook-open--callback(#s(ein:$notebook :url-or-port "https://datasci-1.clearme...." :notebook-id nil 
  apply(ein:notebook-open--callback (#s(ein:$notebook :url-or-port "https://datasci-1.clearme.com:88..." :not
  #f(compiled-function (&rest args2) #<bytecode 0x49b8f001>)(#s(ein:$content :url-or-port "https://datasci-1.
  ein:content-query-contents--success("https://datasci-1.clearme...." "getwit.ipynb" #f(compiled-function (&r
  apply(ein:content-query-contents--success ("https://datasci-1.clearme.com:88..." "getwit.ipynb" #f(compiled
  #f(compiled-function (&rest args2) #<bytecode 0x46035425>)(:data (:name "getwit.ipynb" :path "getwit.ipynb"
  apply(#f(compiled-function (&rest args2) #<bytecode 0x46035425>) (:data (:name "getwit.ipynb" :path "getwit
  apply(apply #f(compiled-function (&rest args2) #<bytecode 0x46035425>) (:data (:name "getwit.ipynb" :path "
  request--safe-apply(#f(compiled-function (&rest args2) #<bytecode 0x46035425>) (:data (:name "getwit.ipynb"
  request--callback(#<killed buffer> :type "GET" :timeout 60.0 :parser ein:json-read :sync nil :complete #f(c
  apply(request--callback #<killed buffer> (:type "GET" :timeout 60.0 :parser ein:json-read :sync nil :comple
```
and an older version of the notebook.
could be worse, I guess.
however,  this is not a very good option.

**Comment by dickmao** [comment]
[Sorry] I hadn't fully understood the notion of kernel reconnects, or that it was even possible.

I reinstated the functionality in #378 with some very light testing, so perhaps more turbulence.
