### ISSUE TITLE
apply-partially lambda

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#383]
A common coding pattern in EIN appears to be `(apply-partially (lambda (....) ...) ...)` which can be trivially simplified to a single `lambda` expression - which is both simpler and more readable.
Before I submit a PR "fixing" it, I wonder if I am missing something.
So, why are you using this relatively complex paradigm?
(just as a background - I have been doing lisp for 20+ years, so I am perfectly comfortable with functional programming; moreover, `(apply-partially #'foo ...)` looks, indeed, perfectly normal to me).

**Comment by dickmao** [comment]
It's a lexical versus dynamic scoping issue, one which I trust you are familiar.  For better or worse, I have replaced many 
```
(lexical-let (foo foo) 
  (setq callback (lambda () foo)))
``` 
constructs with 
```
(setq callback (apply-partially (lambda (foo*) foo*) foo))
```
Perhaps I am missing something, so please show me the simplification.

**Comment by sam-s** [comment]
thanks - but wouldn't it be better to make all files lexical rather than make some variables lexical?

**Comment by dickmao** [comment]
We are starting to enter flamewar territory.  elisp is (controversially) dynamic-let by default, and I personally prefer assuming the default and not having to verify there's a file-local variable saying lexical-let lurking above.

**Comment by sam-s** [comment]
I personally prefer CL (which is lexical), and, observing that most emacs lisp files these days do declare `-*- lexical-binding:t -*-`, I assume lexical bindings unless explicitly specified (which, I guess, explains my question in the first place).
I am surely not interested in a flame war ;-)
thanks for your explanation!

**Comment by millejoh** [comment]
Already closed, but my 2c are that lexical scoping makes it easier to reason about and debug code, especially when the code isn't yours. I'm not about to enforce any particular style, though, so long as everyone is willing to own the code they write. Carry on!
