### ISSUE TITLE
[Feature request] support open Org Mode file: link to .ipynb files

### ISSUE THREAD

**Issue by stardiviner** [millejoh/emacs-ipython-notebook#388]
I hope ein can add support for Org Mode link with `ein:filename.ipynb` to open .ipynb notebook file with current opened session, or auto create a new session if has no one.

Because ipynb files are shared over internet, save them and view them in session is useful. WDYT?
I know can open ipynb files manually. But it is not conviniently.

Here is an example: https://github.com/skeeto/elfeed/pull/206/files

**Comment by dickmao** [comment]
If I open a notebook in EIN, I can `org-store-link`.
Then I go to my org file and I can `org-insert-link`
Then I can `C-c C-o` on the inserted link, and it will take me to the notebook.
The functionality is still incomplete, however.  It won't auto create a new session.

**Comment by stardiviner** [comment]
I tested, it works for open the notebook. Like you said, it can't auto create a new session. Will ein support this? Or can use an elisp advice to improve this?
Like
```elisp
(defun ein:create-session-auto ()
  "Auto create a new session if detect no session exist."
  (if ()
      ))

(advice-add 'ein:org-open :before #'ein:create-session-auto)
```

**Comment by stardiviner** [comment]
I checked out your PR, seems great.

> attempt a new session to a simple notebook server without any cookie complications

What do you mean this? Can you descibe this more detailed?
If you mean a simple new session might lock of some features like code completion and other things. I think it is not I want.

I found the function used in my upper example:

```elisp
(defun ein:create-session-auto ()
  "Auto create a new session if detect no session exist."
  ;; `ein:jupyter-server-start'
  (unless (ein:jupyter-server-process)      ; return the emacs process object of our session.
    (ein:jupyter-server-start)))

(advice-add 'ein:org-open :before #'ein:create-session-auto)
```

**Comment by dickmao** [comment]
Yes, thank you for looking at the code.  `ein:jupyter-server-start` is the right function.

You'll see that my change in dickmao/emacs-ipython-notebook#9 for remote servers is very similar to https://github.com/millejoh/emacs-ipython-notebook/blob/f4aac8c951d0b4ba2eefb3af644a99084a72cd30/lisp/ein-process.el#L201-L208

For starting a local server, the appropriate changes should come from the same place, just a few lines down:
https://github.com/millejoh/emacs-ipython-notebook/blob/f4aac8c951d0b4ba2eefb3af644a99084a72cd30/lisp/ein-process.el#L210-L219

A simple new session will not *lack* "some features like code completion and other things." 
What do I mean by "cookie complications"?  Many public notebook servers do not use the standard token or password authentication -- instead they use cookie authentication.  EIN can handle cookies, but it requires another one or two-line change.

**Comment by stardiviner** [comment]
I see. Thanks. I will test your patch right now.

**Comment by stardiviner** [comment]
I tried the patch now.
When I have an already opened connection.
I got log:
```
11:47:45:257: [info] Login to http://127.0.0.1:8888 complete. @#<buffer emacs-ipython-notebook.org>
11:47:49:100: [verbose] Opened notebooklist at http://127.0.0.1:8888 @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
11:47:49:101: [warn] Notebook (http://127.0.0.1:8888 . simhash.ipynb) is pending open! @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
```
When I close the connection, open the link again, it failed. Here is the log:
```
11:49:05:203: [info] Process /home/stardiviner/.virtualenvs/python3.7/bin/jupyter killed http://127.0.0.1:8888 @#<buffer *ein:notebooklist http://127.0.0.1:8888*>
11:49:17:129: [error] Login to http://127.0.0.1:8888 failed @#<buffer emacs-ipython-notebook.org>
```

**Comment by stardiviner** [comment]
After applied your patch, I still can't let it auto create session.

**Comment by dickmao** [comment]
That doesn't look good.  Can you simply open a `.ipynb` file in EIN?  I find the fastest way to do that is `C-x C-f` the file.  Then `C-c C-z`.  This should prompt you to start a jupyter server.

If that works, perhaps you can try dickmao/emacs-ipython-notebook#9 again.

**Comment by stardiviner** [comment]
I have not found that I can press `C-c C-z` to launch jupyter server in `.ipynb` file before.

`ein:org-store-link` seems only store filename in current path. Does not support store link in other path files.
```
ipynb:(:url-or-port "http://127.0.0.1:8888" :name "simhash.ipynb")
```

I'm fine with this solution:
> That doesn't look good. Can you simply open a .ipynb file in EIN? I find the fastest way to do that is C-x C-f the file. Then C-c C-z. This should prompt you to start a jupyter server.

Thanks @dickmao

**Comment by dickmao** [comment]
You are correct... `ein:org-store-link` in `master` doesn't have enough information to start a session.  That is why I had added to dickmao/emacs-ipython-notebook#9 the following:

https://github.com/dickmao/emacs-ipython-notebook/blob/752783e36095d8e79eb96e311612b2a3381db969/lisp/ein-org.el#L97-L98

I am glad `C-c C-z` is enough for your purposes.  I will go ahead and submit dickmao/emacs-ipython-notebook#9 anyway after I add some tests.

**Comment by stardiviner** [comment]
Looks like you updated your PR since I viewed. I will take a chance to test this PR. I hope your PR can be merged too. And thank you for your work.

**Comment by stardiviner** [comment]
@dickmao I think you might should update the function docstring too. And may I ask you one question?, does it support store a notebook into any different path Org files? and support open any noetbook link in any different path Org files?
Just like variable `org-link-file-path-type` related cases, relative path, absolute path etc.

**Comment by dickmao** [comment]
dickmao/emacs-ipython-notebook#9 doesn't use `org-link-file-path-type` to store paths.  It uses its own custom logic to decide whether the stored link is a remote notebook or a local notebook, and if the latter, how to reconstruct the path to it.  I'm afraid the only way to really know if it works for you is to git clone my fork and `make install` from the `org-issue-388` branch.  Or you can just live with `C-c C-z` for now until I submit the PR.

**Comment by stardiviner** [comment]
`make install` requires `cask`, I will wait for this merged.

**Comment by dickmao** [comment]
The `ein-org.el` module is obsolesced.

**Comment by nakkaya** [comment]
@dickmao Was there a reason to make it obsolete? I was looking for a way to bookmark notebook files. Suggested solution in the issues was to use org-mode links to notebooks, but `ein-org.el` is removed. I got it working by taking bits from `ein-org.el` with no issues so far. Would a PR to add the capability back be acceptable?
