### ISSUE TITLE
unspecified dependency: 'f'

### ISSUE THREAD

**Issue by jefftrull** [millejoh/emacs-ipython-notebook#395]
Installing ein succeeds but errors of the form:

`Error: Cannot open load file: No such file or directory, f`

appear many times in the `*Compile-Log*` buffer for different `.el` files. Furthermore, when I try to begin by using `M-x ein:notebook-open` (or several other basic initial commands) the same error is printed in the minibuffer.

Things I have tried:
- starting clean with `emacs -q`
- removing all `.elc` files from my install dir (`~/.emacs.d/...`)
- running `M-x ein:dev-bug-report-template` (fails with an error about markdown-mode, which is installed - unclear what the issue is)

Although I could not run the bug report template I was able to run `ein:dev-show-sys-info`, which produced this:

```elisp
("EIN system info" :emacs-version "GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.23.2)\n of 2018-08-27, modified by Debian" :emacs-bzr-version nil :window-system x :emacs-variant nil :os
 (:uname "Linux jet-Oryx-Pro 4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux\n" :lsb-release "No LSB modules are available.\nDistributor ID:	Ubuntu\nDescription:	Ubuntu 18.10\nRelease:	18.10\nCodename:	cosmic\n")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend url-retrieve)
 :ein
 (:version "0.15.0-20181106.1910" :source-dir "/home/jet/.emacs.d/elpa/ein-20181106.1910/")
 :lib
 ((:name "websocket" :path "~/.emacs.d/elpa/websocket-20180423.16/websocket.el" :featurep t :version-var websocket-version :version "1.9")
  (:name "request" :path "~/.emacs.d/elpa/request-20170201.147/request.el" :featurep t :version-var request-version :version "0.3.0")
  (:name "auto-complete" :path "~/.emacs.d/elpa/auto-complete-20170125.245/auto-complete.el" :featurep t :version-var nil :version nil)
  (:name "auto-complete" :path "~/.emacs.d/elpa/auto-complete-20170125.245/auto-complete.el" :featurep t :version-var nil :version nil)
  (:name "popup" :path "~/.emacs.d/elpa/popup-20160709.1429/popup.elc" :featurep t :version-var popup-version :version "0.5.3")
  (:name "python" :path "/usr/share/emacs/25.2/lisp/progmodes/python.elc" :featurep t :version-var nil :version nil)))
```
I have attached [the compile log](https://github.com/millejoh/emacs-ipython-notebook/files/2560431/errors.txt) in case it helps.

**Comment by dickmao** [comment]
Please try

`package-install RET f`

https://github.com/rejeep/f.el

**Comment by jefftrull** [comment]
That fixed it :) Can 'f' be added to the dependency list with the appropriate version? I'm sure I won't be the last person...

**Comment by millejoh** [comment]
From what I can see, the dependency of `f` is coming from the testing code. I take it you are installing ein from github? Maybe doing a `cask install` from the install directory will help.

And to be 100% sure it's the testing code that is the culprit, can you try installing EIN from MELPA and confirm whether or not you see the same problems? Thanks!

**Comment by millejoh** [comment]
Okay, now I see where this is showing up:

```
$ grep "(f-.*" *.el
ein-notebooklist.el:            do (f-append-text line 'utf-8 (request--curl-cookie-jar)))))
ein-process.el:                            (if (f-file? fn) (f-parent fn) fn))
```

Not sure when those snuck in, but I'll make sure f is added to the ever growing list of ein dependencies. @dickmao's recent PR should do the trick.

**Comment by jefftrull** [comment]
Thanks! I'm excited to try EIN. Appreciate all the work you've put in.

**Comment by jefftrull** [comment]
Hi! Thanks for asking, but this is the melpa install.On Nov 8, 2018 8:00 AM, John Miller <notifications@github.com> wrote:From what I can see, the dependency of f is coming from the testing code. I take it you are installing ein from github? Maybe doing a cask install from the install directory will help.
And to be 100% sure it's the testing code that is the culprit, can you try installing EIN from MELPA and confirm whether or not you see the same problems? Thanks!
