### ISSUE TITLE
Cannot connect to server: (:bad-page 5435)

### ISSUE THREAD

**Issue by jefftrull** [millejoh/emacs-ipython-notebook#399]
I haven't been able to login to a running jupyter notebook server from Emacs yet. The error displayed in the minibuffer after the URL prompt is just "login failed". I am not prompted for the token. When I look at the logs the jupyter server has responded to the /login GET with a 200 status and the body `(:bad-page 5435) @#<buffer *Buffer List*>`, whatever that means. I saw nothing else of significance in the logs.

I tried deleting all the .elc files and starting with a clean config (emacs -q). No change observed. I have tried running the server both manually (`jupyter notebook --no-browser`) and via emacs (`M-x ein:jupyter-server-start`). My configuration is the same as in #395 . Any ideas?

**Comment by dickmao** [comment]
Can you copy and paste the buffer `*ein:log-all*`?  Thanks.

**Comment by jefftrull** [comment]
Here it is in its entirety:

`09:58:00:367: [error] Login to http://127.0.0.1:8888 failed @#<buffer pdk2notebooks>`

**Comment by dickmao** [comment]
Alas, you need `curl` on your system.  Instead of allowing the default `url-retrieve` http backend, we should probably error out and force the user to install curl.

**Comment by jefftrull** [comment]
Installing curl fixed my problem! Thanks!
