### ISSUE TITLE
Support languages other than python.

### ISSUE THREAD

**Issue by millejoh** [millejoh/emacs-ipython-notebook#40]
Jupyter now supports various backends, not just python. Can EIN do the same?

**Comment by kietdlam** [comment]
Just wondering what is the status of this? This would be really nice with Jupyter + IJulia.

**Comment by millejoh** [comment]
Short term, nothing much is going to happen here. Too busy with work at the moment. Long term I hope to look into this. Julia seems easy to set up so that may make for a good target for initial development.

PR's always welcome, of course.

**Comment by kietdlam** [comment]
Cool thanks, I'll take a stab at this.

**Comment by millejoh** [comment]
Only almost 7 months later have initial support for multiple kernels ala 6d66cc5a2efedf614b62f012fad2023c8b95189c. There is still work to be done here, but I'm going to close this out and document specific issues/needs as they come up.
