### ISSUE TITLE
Inline plot background color

### ISSUE THREAD

**Issue by DGalt** [millejoh/emacs-ipython-notebook#41]
I have been trying to figure out what attribute is setting the background for inline plots in EIN. The background for the plot seems to always take the default background color for my color theme, even though I'm changing the default background color for the major mode that it's contained in. I.e.:

    (defun switch-color ()
      "Switch default bg for ipython notebook."
      (face-remap-add-relative 'default '((:background "white"))))
    (add-hook 'ein:notebook-multilang-mode-hook 'switch-color)

This works for everything except for the inline plots that are generated.

I have also tried editing matplotlibrc, and have been able to change the coloring for different parts of the plot (ticks, axes, etc) with the exception of the background.

I don't know enough about how the plots are generated inline to figure out where they're inheriting their background color from. I've looking through the M-x customize-group options for ein, but haven't been able to find anything that affects the inline plot background.

**Comment by DGalt** [comment]
title change

**Comment by millejoh** [comment]
Believe this is actually an issue with IPython, see ipython/ipython#7964. I
think once 3.2 is released this should go away. When I get a chance I will check
on the 3.x branch and confirm if this is working again or not.

**Comment by maxhgerlach** [comment]
I work around this problem by having this code in one of the first cells. "savefig.facecolor" is the rc param responsible for the background of inline plots.
```python
import matplotlib as mpl
mpl.rcParams["figure.facecolor"] = "white"
mpl.rcParams["axes.facecolor"] = "white"
mpl.rcParams["savefig.facecolor"] = "white"
```

**Comment by millejoh** [comment]
FYI things are much improved in IPython 3.2, though you have to install from source since 3.2 has yet to be officially released.

**Comment by DGalt** [comment]
So will the function in the OP now work as expected with 3.2?

**Comment by millejoh** [comment]
Yes - IPython was forcing the alpha on the background for the plots, causing undesired/unexpected behavior. You can see the details at ipython/ipython#7964, which was closed back in April.

**Comment by Lenbok** [comment]
Hmm, I'm getting the black background issue with:
````
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
IPython 5.1.0 -- An enhanced Interactive Python.
````
Using the workaround from @maxhgerlach makes things visible again, but I'm not sure why these new versions are having the problem in the first place.

**Comment by millejoh** [comment]
EIN works by inserting an image that is generated by the inline backend from matplotlib. So trying to adjust faces in emacs is not going to work. You will need to fiddle with the rcParams in Python to get the axes and tick colors inverted. 

John
