### ISSUE TITLE
RFE: what is being run?

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#411]
As you know, my notebooks tend to be large.
I find it hard to find out what is being run at the moment.
It would be nice if there were a way to jump to the cell being executed now.
Additionally, if more cells are pending execution (marked with `In [*]:`) it would be nice to be able to visit them in order.
Ideally, there should be a textual indicators in the buffer (e.g., `Execution pending #1` &c).

Please note that the current textual indicators (including `Execution pending`) are unreliable.
E.g., in a notebook running right now, the data on the server is no longer synced with the Emacs buffer, so the cell which is in fact being executed is marked with `Last executed 2018-11-25T13:13:28 in 16614.0s` and `In [ ]:`. When I add a dummy cell with `print(1)` and hit `C-c C-c`, is  _is_ marked appropriately (`In [*]:` and `Execution pending`).

**Comment by millejoh** [comment]
Well, I think I have a partially solution to your request. See the new commands `ein:worksheet-jump-to-first-executing-cell` and `ein:worksheet-jump-to-next-executing-cell`. Note that "first" and "next" refer to the physical location of the executing cell, not their logical execution order. It will take some more thought on my part to get that working.

**Comment by sam-s** [comment]
Thanks, I tried it and got:
```
Debugger entered--Lisp error: (cl-no-applicable-method ein:cell-goto nil)                             
  signal(cl-no-applicable-method (ein:cell-goto nil))                                                 
  cl-no-applicable-method(#s(cl--generic :name ein:cell-goto :dispatches ((0 #s(cl--generic-generalize
  apply(cl-no-applicable-method #s(cl--generic :name ein:cell-goto :dispatches ((0 #s(cl--generic-gene
  #f(compiled-function (&rest args) #<bytecode 0x409678d9>)(nil)                                      
  apply(#f(compiled-function (&rest args) #<bytecode 0x409678d9>) nil nil)                            
  ein:cell-goto(nil)                                                                                  
  ein:worksheet-jump-to-first-executing-cell()                                                        
  funcall-interactively(ein:worksheet-jump-to-first-executing-cell)                                   
  call-interactively(ein:worksheet-jump-to-first-executing-cell record nil)                           
  command-execute(ein:worksheet-jump-to-first-executing-cell record)                                  
  execute-extended-command(nil "ein:worksheet-jump-to-first-executing-cell" nil)                      
  funcall-interactively(execute-extended-command nil "ein:worksheet-jump-to-first-executing-cell" nil)
```
