### ISSUE TITLE
Juputerhub cannot open notebook

### ISSUE THREAD

**Issue by dimitar-petrov** [millejoh/emacs-ipython-notebook#419]
I am unable to open a notebook from jupyterhub. It is able to connect but when I try to open a notbook the screen flickers and it spits a warning.

Here is the log from the ein:all buffer.

```
ein: [info] Jupyterhub: Response status: 400
ein: [info] Jupyterhub: Finding user: user
ein: [info] Jupyterhub: Found user: #s(ein:$jh-user user :json-false nil /user/user/ nil 2018-12-01T10:40:28.060274Z)
ein: [info] Jupyterhub: Found user? (#s(ein:$jh-user user :json-false nil /user/user/ nil 2018-12-01T10:40:28.060274Z))
ein: [info] Jupyterhub: Opening notebook at http://server:8000: 
REQUEST [error] Error (error) while connecting to http://server:8000/user/user/user/user/api.
ein: [warn] notebook version api not implemented
evil-forward-char: End of buffer
REQUEST [error] Error (error) while connecting to http://server:8000/user/user/user/user/api.
ein: [warn] notebook version api not implemented
evil-forward-char: End of line
command-execute: Buffer is read-only: #<buffer *ein:notebooklist http://server:8000*>
w is undefined
evil-backward-char: Beginning of buffer
Mark set
evil-line-move: End of buffer
Mark set
```

Which versions of jupyterhub, jupyterlab and notebook are supported?

**Comment by millejoh** [comment]
The code supporting jupyterhub sort-of worked over a year ago, but clearly bitrot has set in. @dickmao has a workaround that may work for you. See #239. I'm taking another stab at better jupyterhub support, but I keep getting distracted.

**Comment by millejoh** [comment]
@dimitar-petrov - give `ein:jupyterhub-connect` another try. Recent commits seem to have restored some functionality, at least where PAM authenticating servers are invovled.

**Comment by dickmao** [comment]
jupyterhub support is not on the docket.  Sorry.
