### ISSUE TITLE
Traceback: Jump to code

### ISSUE THREAD

**Issue by maxhgerlach** [millejoh/emacs-ipython-notebook#42]
When there's a Python error in a cell of a notebook, I can get a nice traceback with `C-c C-x`, but I cannot jump to the location of the error with `RET` at least if the error does not origin in some external file. The message is `File <ipython-input-87-7987bc9ea0c8> does not exist` or similar.

Looking at [the code](https://github.com/millejoh/emacs-ipython-notebook/blob/3c1131a558aaf74cf6b0d0c818d0b8e89aecb833/lisp/ein-traceback.el), this may not actually be supposed to work. Would it be hard to allow jumping to the line in a notebook buffer?

In any case, thanks a lot for keeping EIN alive!

**Comment by millejoh** [comment]
I believe the `input-<number>` tells you which cell generated the error. EIN has a way of jumping to a given cell, so with some magic I might be able to get this to work. I have been busy lately, but I working on ein is actually fun, so I will definitely try to implement this.

**Comment by maxhgerlach** [comment]
Yes, the decimal number definitely corresponds to the cell number. Is the hexadecimal part a hash of the notebook?

Anyway, this would be a very neat feature to have. :+1:

**Comment by millejoh** [comment]
Okay, with 75c5f36ceb16f0920d6e9f591de7d422d8ba8798 should be working.

**Comment by maxhgerlach** [comment]
Hi, 

I managed to try the latest version from Melpa (20150505.1922).

After pressing RET on a traceback entry, I now get messages "ein:cell-goto: No method definition: ein:cell-goto, (nil)", though.

My Emacs reports as "GNU Emacs 24.3.1 (i686-pc-linux-gnu, GTK+ Version 2.24.10) of 2014-01-30 on gerlach-VirtualBox".

**Comment by maxhgerlach** [comment]
d2681d8 works for me too, thanks! I added some code in the pull request to also go to the right line number within the cell.
