### ISSUE TITLE
ein:notebooklist-login using expired token, preventing me from logging in

### ISSUE THREAD

**Issue by jackkamm** [millejoh/emacs-ipython-notebook#420]
Since recent update to ein, I can no longer login to remote notebook servers I've forwarded to localhost:8888. After calling `ein:notebooklist-login`, I get a message that looks like:
```
Establishing session...failed.
```
Whereas before, I would have been prompted for a password token to login.

If I forward the server to a new port I've never used before (e.g. localhost:9999) then I am prompted for the password token as expected, and am able to login fine.

It appears like ein is now storing the token when logging in, and reusing it for future sessions at the same address. Is there any way to reset the token or disable this feature?

**Comment by dickmao** [comment]
Does the output of `jupyter notebook list` have an entry for `localhost:8888`?

**Comment by jackkamm** [comment]
No:
```
jack@jaheira:~ % jupyter notebook list
Currently running servers:
jack@jaheira:~ % 
```

**Comment by dickmao** [comment]
I'm afraid I can't mentally debug this.  It is very strange to me that 8888 doesn't work but 9999 does.  I trust you aren't running a jupyter from within emacs.

Copying the `*ein:log-all*` here would help a lot.  Even more helpful would be running `M-x ein:dev-start-debug`, manifesting the bug, and then copying the `*ein:log-all*` buffer here.

**Comment by jackkamm** [comment]
So I've managed to resolve this for myself. It turns out that while the minibuffer was displaying
```
Establishing session...failed.
```
One is still able to enter the password. Upon entering input to the keyboard, the minibuffer prompt does update itself to correctly display
```
Password for http://127.0.0.1:8888: ...
```
I was getting a bit confused though because, without any entering any input, the minibuffer prompt only displays `Establishing session...failed`, so at this point I would assume ein had failed and hit `C-g` to quit.

Anyways, sorry for the confusion -- I am able to enter in a password to login after all. It was just the way the minibuffer prompt was updating that was confusing me.

**Comment by dickmao** [comment]
Yes, thank you for pointing this out.  I actually already fixed this bug in a forthcoming change I'm making.  I was going to suggest it, but the 9999 counterexample made it seem like it was something else.
