### ISSUE TITLE
Cannot connect to notebook - status nil data nil

### ISSUE THREAD

**Issue by davidmascharka** [millejoh/emacs-ipython-notebook#425]
## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have

I'm unable to connect to a notebook, either through `ein:login` or through `ein:jupyter-server-start`. My logs are:

```
; ein:log-all
09:46:28:281: [debug] Login attempt #0 in response to nil from http://127.0.0.1:8889. @#<buffer *scratch*>
09:46:28:281: [debug] Currently at 0 simultaneous request calls. @#<buffer *scratch*>
09:46:28:295: [error] Login to http://127.0.0.1:8889 failed @#<buffer *scratch*>
09:46:28:295: [debug] ein:notebooklist-login--complete STATUS: nil DATA: nil @#<buffer *scratch*>
09:47:04:397: [info] Process /home/david/anaconda3/bin/jupyter hangup http://127.0.0.1:8889 @#<buffer *ein:log-all*>
```

```
; ein:jupyter-server-log
[D 09:46:27.750 NotebookApp] Searching ['/home/david', '/home/david/.jupyter', '/home/david/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 09:46:27.750 NotebookApp] Looking for jupyter_config in /etc/jupyter
[D 09:46:27.750 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 09:46:27.750 NotebookApp] Looking for jupyter_config in /home/david/anaconda3/etc/jupyter
[D 09:46:27.751 NotebookApp] Looking for jupyter_config in /home/david/.jupyter
[D 09:46:27.751 NotebookApp] Looking for jupyter_config in /home/david
[D 09:46:27.751 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 09:46:27.751 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 09:46:27.751 NotebookApp] Looking for jupyter_notebook_config in /home/david/anaconda3/etc/jupyter
[D 09:46:27.751 NotebookApp] Loaded config file: /home/david/anaconda3/etc/jupyter/jupyter_notebook_config.json
[D 09:46:27.751 NotebookApp] Looking for jupyter_notebook_config in /home/david/.jupyter
[D 09:46:27.752 NotebookApp] Loaded config file: /home/david/.jupyter/jupyter_notebook_config.py
[D 09:46:27.752 NotebookApp] Looking for jupyter_notebook_config in /home/david
[I 09:46:27.856 NotebookApp] The port 8888 is already in use, trying another port.
[D 09:46:27.858 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
        /etc/jupyter/jupyter_notebook_config.json
[D 09:46:27.858 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
        /usr/local/etc/jupyter/jupyter_notebook_config.json
[D 09:46:27.858 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
        /home/david/anaconda3/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
        /home/david/anaconda3/etc/jupyter/jupyter_notebook_config.json
[D 09:46:27.859 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
        /home/david/.jupyter/jupyter_notebook_config.json
[I 09:46:27.875 NotebookApp] JupyterLab extension loaded from /home/david/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 09:46:27.875 NotebookApp] JupyterLab application directory is /home/david/anaconda3/share/jupyter/lab
[I 09:46:27.876 NotebookApp] Serving notebooks from local directory: /home/david
[I 09:46:27.876 NotebookApp] The Jupyter Notebook is running at:
[I 09:46:27.876 NotebookApp] http://127.0.0.1:8889/?token=3dba2f0193c143a3965b9d098427b68e4462e5afeceab0c6
[I 09:46:27.876 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:46:27.876 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://127.0.0.1:8889/?token=3dba2f0193c143a3965b9d098427b68e4462e5afeceab0c6
```

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`): 7.0.1

2. How do you start IPython? (e.g., `ipython notebook --port 9999`): `jupyter notebook`

3. What is your IPython notebook port number or URL?: 8889

## Additional information
I'm running behind a proxy; I'm wondering if there's an additional setup involved, although I've been able to successfully run ein in the past with the exact same configuration on this same machine.

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 2.24.30)
 of 2018-10-30"
 :emacs-bzr-version "b9cbdd045f2d086390b3d0e4412ebac0b19aaead"
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux <my hostname> 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
"
  :lsb-release
  "No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
")
 :image-types
 (png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.15.0-20181203.1552"
           :source-dir "/home/david/.emacs.d/elpa/ein-20181203.1552/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/elpa/websocket-20180423.16/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.9")
  (:name "request"
         :path "~/.emacs.d/elpa/request-20181129.1138/request.elc"
         :featurep t
         :version-var request-version
         :version "0.3.0")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20170125.245/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20170125.245/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/elpa/popup-20160709.1429/popup.elc"
         :featurep t
         :version-var popup-version
         :version "0.5.3")
  (:name "python"
         :path "/usr/local/share/emacs/27.0.50/lisp/progmodes/python.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "python-mode"
         :path "~/.emacs.d/elpa/python-mode-20181008.1836/python-mode.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path "~/.emacs.d/elpa/markdown-mode-20181112.1529/markdown-mode.elc"
         :featurep t
         :version-var markdown-mode-version
         :version "2.4-dev")))
```

**Comment by dickmao** [comment]
> [I 09:46:27.876 NotebookApp] The Jupyter Notebook is running at:
> [I 09:46:27.876 NotebookApp] http://127.0.0.1):8889/?token=3dba2f0193c143a3965b9d098427b68e4462e5afeceab0c6

Thanks for running the diagnostic.  Do you know why there might be a right paren after the `127.0.0.1` and before the `:8889`?

**Comment by davidmascharka** [comment]
Oh whoops, I edited my hostname out of the logs; it originally said `http://(<my hostname> or 127.0.0.1):8889` and I just missed a paren. Sorry about that! I'll edit it now

**Comment by dickmao** [comment]
https://github.com/millejoh/emacs-ipython-notebook/blob/608058e07c60e78a44c9dd2aec2af1e7b8b74318/lisp/ein-notebooklist.el#L884

The symptoms you describe would happen if we got here.  It means the token wasn't enough and jupyter wanted another password.  If we didn't get here, then it's a real mystery.

I presume you in very vanilla-fashion launch an emacs and type `M-x ein:run` or `M-x ein:jupyter-server-start` and you get the symptoms above.  Is there something new about your jupyter install, possibly the jupyterlab extension that might prompt for password?

**Comment by davidmascharka** [comment]
That's the workflow I was using, yes. I've also run notebooks from the command line and tried logging in with `ein:notebooklist-login`. Specifying my port, I get `ein: [error] Login to http://127.0.0.1:8888 failed` with this log:

```
; ein:log-all
12:21:53:292: [debug] Login attempt #-1 in response to nil from http://127.0.0.1:8888. @#<buffer *scratch*>
12:21:53:292: [debug] Currently at 0 simultaneous request calls. @#<buffer *scratch*>
12:21:53:295: [error] Login to http://127.0.0.1:8888 failed @#<buffer *scratch*>
12:21:53:295: [debug] ein:notebooklist-login--complete STATUS: nil DATA: nil @#<buffer *scratch*>
```

I haven't updated my Python environment recently and I'm able to log in using my browser with just the token.

**Comment by dickmao** [comment]
> 12:21:53:292: [debug] Login attempt #-1 in response to nil from http://127.0.0.1:8888. @#<buffer *scratch*>

That is helpful as it rules out my earlier suspicion regarding passwords and suggests problems at the `curl` level (we use `curl` for all server interactions).  Unfortunately, to further diagnose, I would need to your help.  I'm asking:

1. launch emacs
2. `ein:dev-start-debug` (you might already be doing this)
3. `ein:run`
4. `M-: (switch-to-buffer request-log-buffer-name)`
5. Copy the resulting buffer here.

**Comment by Pfedj** [comment]
I had a similar error with run `M-x ein:jupyter-server-start` on Windows.
`
ein:[error] Login to http://127.0.0.1:8888 failed, error-thrown (error . exited abnormally with code 43), raw-header
`
Also I have  `C:\msys64\usr\bin`, `C:\Anaconda3\Library\bin`, in my system Path.
The issues was solved by setting  `C:\Anaconda3\Library\bin` on first in Path.
