### ISSUE TITLE
invalid Notebook JSON being saved from ein

### ISSUE THREAD

**Issue by flamingbear** [millejoh/emacs-ipython-notebook#43]
So after putting this together, it may just be that you don't support notebook 4 versions yet?  But here's a problem I'm seeing.  Let me know if I can help.

## Check list

- [X] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [X] Does IPython works from the web browser?
- [?] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [X] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have

Invalid JSON notebook errors.  When saving a notebook after doing a df.head() I get errors in my server console, and when I try to open the .ipynb file from a browser, I get an error "Notebook validation failed: Additional properties are not allowed (u'html' was unexpected): {....."

[E 14:50:32.727 NotebookApp] Notebook JSON is invalid: Additional properties are not allowed (u'html' was unexpected) ...<+ more>
full error here: https://gist.github.com/b74b22359497238f6de5

## Steps to reproduce the problem

1. start a new notebook and create a dataframe display the head()

```python
from pandas import Series, DataFrame
df =DataFrame( {'one' : Series([1., 2., 3.], index=['a', 'b', 'c']), 'two' : Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])})
df.head()
```
2. save dataframe inside ein. C-x C-s (ein:notebook-save-notebook-command)

3.  Open same ipython file from a browser.

## Expected output

No errors in the server window on save.

No errors when a file is opened from a browser after being saved in ein.

## Your EIN configuration (in .emacs.d/init.el or somewhere else)

lisp/zeroein.el

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):
```
$ ipython --version
3.1.0
```
2. How do you start IPython? (e.g., `ipython notebook --port 9999`):
```
ipython notebook --notebook-dir=. --ip=0.0.0.0
```
3. What is your IPython notebook port number or URL?:
```
8888
```
## Additional information (if any)

I am running under anaconda python.

```
savoie@Matts-MacBook-Air ~/Dropbox/projects/ein-test$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.11.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.6.2
     root environment : /Users/savoie/anaconda  (writable)
  default environment : /Users/savoie/anaconda
     envs directories : /Users/savoie/anaconda/envs
        package cache : /Users/savoie/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57)
 of 2015-04-18 on Matts-MacBook-Air.local"
 :emacs-bzr-version nil
 :window-system nil
 :emacs-variant nil
 :os
 (:uname
  "Darwin Matts-MacBook-Air.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
"
  :lsb-release nil)
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.3.edb0fd2"
	   :source-dir "/Users/savoie/projects/emacs-ipython-notebook/lisp/")
 :lib
 ((:name "websocket"
	 :path "~/projects/emacs-ipython-notebook/lib/websocket/websocket.el"
	 :featurep t
	 :version-var websocket-version
	 :version "1.3")
  (:name "request"
	 :path "~/projects/emacs-ipython-notebook/lib/request/request.el"
	 :featurep t
	 :version-var request-version
	 :version "0.2.0alpha1")
  (:name "auto-complete"
	 :path "~/projects/emacs-ipython-notebook/lib/auto-complete/auto-complete.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "mumamo"
	 :path "~/projects/emacs-ipython-notebook/lib/nxhtml/util/mumamo.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "auto-complete"
	 :path "~/projects/emacs-ipython-notebook/lib/auto-complete/auto-complete.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "popup"
	 :path "~/projects/emacs-ipython-notebook/lib/popup/popup.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "fuzzy"
	 :path "~/projects/emacs-ipython-notebook/lib/fuzzy/fuzzy.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "pos-tip"
	 :path "~/projects/emacs-ipython-notebook/lib/pos-tip/pos-tip.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "python"
	 :path "~/projects/emacs-ipython-notebook/lib/python/python.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "markdown-mode"
	 :path "~/projects/emacs-ipython-notebook/lib/markdown-mode/markdown-mode.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "smartrep"
	 :path "~/projects/emacs-ipython-notebook/lib/smartrep/smartrep.el"
	 :featurep nil
	 :version-var nil
	 :version nil)))
```

**Comment by millejoh** [comment]
fd6711c4e09615db9cc990cf7c6d30619c49a8c3 fixes this, sort of. I think this gets rid of the invalid json wanring, but the behavior still may not be completely what you expect as ein will prefer saving pretty-text over html if that is how you have `ein:output-type-preference` set in your configuration. I think by default it is `ein:output-type-prefer-pretty-text-over-html.`

**Comment by flamingbear** [comment]
This is a great quick fix. Thanks.
