### ISSUE TITLE
Autocomplete quirks with company backend

### ISSUE THREAD

**Issue by xelibrion** [millejoh/emacs-ipython-notebook#436]
Hi @millejoh, thanks for your work on this amazing package. 
I'm just setting up EIN in my Emacs and I'm experiencing some undesired behaviour.

Let's say I have imported a module in one cell
```
from sklearn import model_selection
```

If in another cell I try to invoke autocomplete after the dot
```
model_selection.
```

the typed expression gets replaced by the selected suggestion (*train_test_split* in this case)  instead of being appended. 

EXPECTED
```
model_selection.train_test_split
```

ACTUAL
```
train_test_split
```

Here's my configuration 
```
(use-package ein
  :pin melpa
  :config
  (setq ein:use-auto-complete t)
  (setq ein:complete-on-dot t)
  (setq ein:completion-backend 'ein:use-company-backend)
  (setq ein:use-auto-complete-superpack nil)
  (setq ein:use-smartrep nil)
)
```
I tried to look in logs in the debug mode, but haven't found anything that seemed useful. 
Using EIN *ein-20181213.1844*.

**Comment by xelibrion** [comment]
Funny enough, my work machine does not have the same problem despite sharing the same config. I'll try to figure out what's wrong with my home laptop.

**Comment by jcpetkovich** [comment]
I'm getting the same behaviour, although I can't quite nail down why. I tried the same configuration as @xelibrion and get the same result.

Stepping through it seems that `delete-region` here drops the prefix, and replaces it with `candidate` which is "train_test_split":
```elisp
(defun company--insert-candidate (candidate)
  (when (> (length candidate) 0)
    (setq candidate (substring-no-properties candidate))
    ;; XXX: Return value we check here is subject to change.
    (if (eq (company-call-backend 'ignore-case) 'keep-prefix)
        (insert (company-strip-prefix candidate))
      (unless (equal company-prefix candidate)
        (delete-region (- (point) (length company-prefix)) (point))
        (insert candidate)))))
```

**Comment by xelibrion** [comment]
I think I've got to the bottom of this. After spending a few hours with `edebug`, I came to a conclusion that the cause of this behaviour is how the company-mode works. 

In the method `company--insert-candidate` @jcpetkovich linked above, it is indeed the front end of company mode that performs the undesired action of removing the `model_selection.` prefix from the example above. This is the same prefix, that is the result of handling `prefix` command by `ein:company-backend`. 

The result of that command in the notebook is always `(ein:object-at-point)`, but unfortunately this is not what company expects (as far as I understand), as it does always delete the prefix. It makes perfect sense to delete the region if you complete `model_` -> 'model_selection', but if the prefix is not present in the list of candidates returned from the backend (as in our case), everything would break. This behaviour seems pretty unintuitive to me, would be great to hear what @dgutov thinks of it.

I also had a look at how `elpy` deals with it, and it looks like in their company-backend they use result of `(company-grab-symbol-cons "\\." 1)` expression as a prefix. The expression would return `model_` for `model_` -> 'model_selection' completion, and an empty string (which is not nil, so the backend will still be called by company-mode) for `model_selection.` -> `model_selection.train_test_split`, causing deletion of an empty region. 

Given the above, what are your thoughts on this bug @millejoh?

**Comment by dgutov** [comment]
> but if the prefix is not present in the list of candidates returned from the backend (as in our case), everything would break

Your prefix is wrong in this case, then.

Sounds like elpy has the right idea.

**Comment by dickmao** [comment]
Thank you for getting to the bottom of it --- it helps EIN when users help themselves.

It sounds like your completions are "BaseCrossValidator" instead of "model_selection.BaseCrossValidator".  Please confirm if this is true.

Also, I'd like to see your `company-backends`.  Please `M-: company-backends` from the notebook buffer.

Also, we want to inspect what the `matches` are from the server.  Before opening the notebook, type `M-x ein:dev-start-debug`, then try your `model_selection.` completion again.  Then switch-to-buffer the buffer that starts with `*websocket` (perhaps try `C-x b *web[TAB]`) and look for `"matches"`.

**Comment by xelibrion** [comment]
@dickmao yes, this is exactly right. 

This is my backends: 
```(ein:company-backend company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files (company-dabbrev-code company-gtags company-etags company-keywords) company-oddmuse company-dabbrev)```

This is the content object from `complete_reply`:
```
{"matches": ["BaseCrossValidator", "check_cv", "cross_val_predict", "cross_val_score", "cross_validate", "fit_grid_point", "GridSearchCV", "GroupKFold", "GroupShuffleSplit", "KFold", "learning_curve", "LeaveOneGroupOut", "LeaveOneOut", "LeavePGroupsOut", "LeavePOut", "ParameterGrid", "ParameterSampler", "permutation_test_score", "PredefinedSplit", "RandomizedSearchCV", "RepeatedKFold", "RepeatedStratifiedKFold", "ShuffleSplit", "StratifiedKFold", "StratifiedShuffleSplit", "TimeSeriesSplit", "train_test_split", "validation_curve"], "cursor_end": 16, "cursor_start": 16, "metadata": {"_jupyter_types_experimental": [{"start": 16, "end": 16, "text": "BaseCrossValidator", "type": "class"}, {"start": 16, "end": 16, "text": "check_cv", "type": "function"}, {"start": 16, "end": 16, "text": "cross_val_predict", "type": "function"}, {"start": 16, "end": 16, "text": "cross_val_score", "type": "function"}, {"start": 16, "end": 16, "text": "cross_validate", "type": "function"}, {"start": 16, "end": 16, "text": "fit_grid_point", "type": "function"}, {"start": 16, "end": 16, "text": "GridSearchCV", "type": "class"}, {"start": 16, "end": 16, "text": "GroupKFold", "type": "class"}, {"start": 16, "end": 16, "text": "GroupShuffleSplit", "type": "class"}, {"start": 16, "end": 16, "text": "KFold", "type": "class"}, {"start": 16, "end": 16, "text": "learning_curve", "type": "function"}, {"start": 16, "end": 16, "text": "LeaveOneGroupOut", "type": "class"}, {"start": 16, "end": 16, "text": "LeaveOneOut", "type": "class"}, {"start": 16, "end": 16, "text": "LeavePGroupsOut", "type": "class"}, {"start": 16, "end": 16, "text": "LeavePOut", "type": "class"}, {"start": 16, "end": 16, "text": "ParameterGrid", "type": "class"}, {"start": 16, "end": 16, "text": "ParameterSampler", "type": "class"}, {"start": 16, "end": 16, "text": "permutation_test_score", "type": "function"}, {"start": 16, "end": 16, "text": "PredefinedSplit", "type": "class"}, {"start": 16, "end": 16, "text": "RandomizedSearchCV", "type": "class"}, {"start": 16, "end": 16, "text": "RepeatedKFold", "type": "class"}, {"start": 16, "end": 16, "text": "RepeatedStratifiedKFold", "type": "class"}, {"start": 16, "end": 16, "text": "ShuffleSplit", "type": "class"}, {"start": 16, "end": 16, "text": "StratifiedKFold", "type": "class"}, {"start": 16, "end": 16, "text": "StratifiedShuffleSplit", "type": "class"}, {"start": 16, "end": 16, "text": "TimeSeriesSplit", "type": "class"}, {"start": 16, "end": 16, "text": "train_test_split", "type": "function"}, {"start": 16, "end": 16, "text": "validation_curve", "type": "function"}]}, "status": "ok"}
```
And the notebook server info:

```
The version of the notebook server is: 5.7.2

Current Kernel Information:
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.
```

**Comment by millejoh** [comment]
Interesting - when I step through `company--insert-candidate`, in my emacs the value for `candidate` includes the prefix. That is, `candidate` has the value `model_selection.train_test_split`. The value for `company-prefix` is `model_selection.`, so the code works as expected in my case.

Jupyter should return completion candidates that include the prefix, at least by my interpretation of the [documentation](https://jupyter-client.readthedocs.io/en/stable/messaging.html#completion). It would be good to know, as @dickmao commented, what actual matches are being returned by your Jupyter. You can do this as he suggested, or step through `ein:company-backend` and `ein:completions--find-cached-completion` and see what ein is storing in the oinfo cache.
