### ISSUE TITLE
Better use of vertical space, "in" "out"

### ISSUE THREAD

**Issue by data-coder** [millejoh/emacs-ipython-notebook#437]
It would be nice if we could hide "In" and "Out" lines, to better use vertical space.
![ein](https://user-images.githubusercontent.com/15821214/50340890-81a6b780-04fb-11e9-9569-bcb325d8bcd5.png)

**Comment by mfrasca** [comment]
I actually like their presence.  it shows the execution sequence.

**Comment by dickmao** [comment]
I'm afraid there are no plans to allow hiding `In [1]` and `Out[2]`.
