### ISSUE TITLE
Kernel hangs with cufflinks

### ISSUE THREAD

**Issue by ratnesh1729** [millejoh/emacs-ipython-notebook#438]
```
import pandas as pd
import cufflinks as cf
cf.go_offline()
```
-- If we have above imports and try to execute cell - the kernel and the whole emacs hangs. Only way to get out is to restart/kill emacs.

Let me know if we need more details. Doing above on Jupyter/browser does not hand anything and works smoothly.

Best,
Ratnesh

**Comment by millejoh** [comment]
[Cufflinks](https://plot.ly/ipython-notebooks/cufflinks/) is something of a wrapper around pandas and plotly. Plotly displays its graphs in the browser-based jupyter client using javascript, something which Emacs just simply does not grok. Something like [skewer](https://github.com/skeeto/skewer-mode) might work, but I just haven't had the time this past year to look much into implementing this support. I think a user did have some partial success - you might want to look at issue #65.

**Comment by dickmao** [comment]
Will only think about this if webkit integrates with emacs (unlikely).
