### ISSUE TITLE
Output from LIME is not shown

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#448]
Output from [`show_in_notebook`](https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20continuous%20and%20categorical%20features.html) is not shown in EIN (it does show in browser).
I have no idea how the above function works, the browser shows text (i.e., I can copy and paste it).

**Comment by millejoh** [comment]
That would be because `show_in_notebook` returns a bunch of javascript that ein unfortunately has no idea how to handle.
