### ISSUE TITLE
Error getting local tokens

### ISSUE THREAD

**Issue by dolorsitatem** [millejoh/emacs-ipython-notebook#449]
# Error
The error I am getting is:

> Error getting local tokens: (file-missing Searching for program No such file or directory jupyter) [2 times]

# Steps to reproduce
The steps to produce the error:

1. Activate virtual environment with jupyter installed in it
2. Start a jupyter notebook via `jupyter notebook`.  This opens the browser to `http://localhost:8888` and jupyter functions as expected.
3. Open Emacs
4. `M-x: ein:notebooklist-login`
5. Use the default URL or port (`[http://127.0.0.1:8888]`). 
6. Press Enter

I am not presented with the password prompt at all.

# Legwork

I've tried everything in [here](https://github.com/millejoh/emacs-ipython-notebook/issues/147), [here](https://github.com/millejoh/emacs-ipython-notebook/issues/154), [here](https://emacs.stackexchange.com/questions/30251/ein-failed-to-login-to-8888), and even [here](https://stackoverflow.com/questions/42648610/error-when-executing-jupyter-notebook-no-such-file-or-directory).

These include:

- Set a password via the setting for `c.NotebookApp.password` and instead of calling `ein:notebooklist-open` first call `ein:notebooklist-login`, supply the password, then call `ein:notebooklist-open`.

- Completely disable token authentication by setting both 'c.NotebookApp.token' and 'c.NotebookApp.password' to ''.

- Reinstalling jupyter

- Granting Emacs full access to the firewall
  
I've also made sure to do all of the above with `emacs -q`.

I am on a new install of Windows 10 with GnuEmacs 26.1 and EIN installed via MEPLA.  I have had success running EIN on Windows 7 and Debian, so I believe I've followed the steps correctly.  However, I could detail them precisely, if necessary.

# Desperate cry for help

I'm at complete loss for what's causing the error...

**Comment by dickmao** [comment]
The error means that `jupyter` is not in emacs's path.  It would be useful to know if a simple `ein:run` also fails in your setup.

As I don't use Windows I cannot reproduce.  As a workaround, you can try `customize-set-variable RET ein:jupyter-default-server-command` to the full path of `jupyter`, but that wouldn't explain why emacs cannot find `jupyter` in its path.

**Comment by millejoh** [comment]
I also say this is an issue with the path environment variable. Note that you haven't enjoyed all Windows truly has to offer until you try to set up a conda environment with pymc3 and then get it all working from a jupyter notebook.

Anyway, try starting emacs from the command line after activating the virtual environment that contains the jupyter executable. I think if you call `C-u M-x ein:notebooklist-login` it will force ein to prompt for a password.

Also you can go into system environment settings and add the jupyter executable to the user or system `PATH` variable.
