### ISSUE TITLE
multiple notebooks end up sharing single kernel.

### ISSUE THREAD

**Issue by flamingbear** [millejoh/emacs-ipython-notebook#45]
Not sure when this began, but I'm getting cross contamination with names 
(I guess it's going wrong after I do a restart of the kernel)  Sorry for the flurry of bug reports.

I am correct in thinking each notebook should have it's own kernel process.

Cheers, 
Matt

## Check list

- [X] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [X] Does IPython works from the web browser?
- [X] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [X] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have

kernels end up shared across notebooks leading to name collisions.

## Steps to reproduce the problem

1.  Start new notebook and set a variable
```
df = 'hello'
```
2. start second notebook try to print the variable
```
print df
```

3. restart kernel ein:notebook-restart-kernel-command

4. reload first notebook's cell
```
df = 'hello'
```

5. Try to print df from the second notebook.
```
print df
hello
```

6. profit

## Expected output

```sh
Truncated Traceback (Use C-c C-x to view full TB):
<ipython-input-5-ccf38de77676> in <module>()
----> 1 print df

NameError: name 'df' is not defined
```

I was under the impression that each sheet had it's own kernel and names shouldn't be cross contaminated across them.

## Your EIN configuration (in .emacs.d/init.el or somewhere else)

lisp/zeroein.el

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):
```
3.1.0
```

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):
```
ipython notebook --notebook-dir=. --ip=0.0.0.0
```
3. What is your IPython notebook port number or URL?:
```
8888
````

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57)
 of 2015-04-15 on savoie-laptop.ad.int.nsidc.org"
 :emacs-bzr-version nil
 :window-system nil
 :emacs-variant nil
 :os
 (:uname
  "Darwin savoie-laptop.ad.int.nsidc.org 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
"
  :lsb-release nil)
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.3.fd6711c"
	   :source-dir "/Users/savoie/Dropbox/projects/emacs-ipython-notebook/lisp/")
 :lib
 ((:name "websocket"
	 :path "~/Dropbox/projects/emacs-ipython-notebook/lib/websocket/websocket.el"
	 :featurep t
	 :version-var websocket-version
	 :version "1.3")
  (:name "request"
	 :path "~/Dropbox/projects/emacs-ipython-notebook/lib/request/request.el"
	 :featurep t
	 :version-var request-version
	 :version "0.2.0alpha1")
  (:name "auto-complete"
	 :path "~/Dropbox/projects/emacs-ipython-notebook/lib/auto-complete/auto-complete.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "mumamo"
	 :path "~/Dropbox/projects/emacs-ipython-notebook/lib/nxhtml/util/mumamo.el"
	 :featurep t
	 :version-var mumamo:version
	 :version "0.91")
  (:name "auto-complete"
	 :path "~/Dropbox/projects/emacs-ipython-notebook/lib/auto-complete/auto-complete.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "popup"
	 :path "~/Dropbox/projects/emacs-ipython-notebook/lib/popup/popup.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "fuzzy"
	 :path "~/Dropbox/projects/emacs-ipython-notebook/lib/fuzzy/fuzzy.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "pos-tip"
	 :path "~/Dropbox/projects/emacs-ipython-notebook/lib/pos-tip/pos-tip.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "python"
	 :path "~/Dropbox/projects/emacs-ipython-notebook/lib/python/python.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "markdown-mode"
	 :path "~/Dropbox/projects/emacs-ipython-notebook/lib/markdown-mode/markdown-mode.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "smartrep"
	 :path "~/Dropbox/projects/emacs-ipython-notebook/lib/smartrep/smartrep.el"
	 :featurep nil
	 :version-var nil
	 :version nil)))
```

**Comment by millejoh** [comment]
Can't believe I missed this. As far as I can tell this has been around since I added support for 3.x. Maybe not many people are using ein+ipython 3.x?

Latest commits should fix this and as an added bonus #44 has also been fixed.

Late now, must sleep. Hope this works for you.

**Comment by flamingbear** [comment]
Excellent!  This works for me now.  Thanks so much for the fast work!

**Comment by millejoh** [comment]
You caught me in a good moment - glad I could help.
