### ISSUE TITLE
Ipython won't open in browser upon startup

### ISSUE THREAD

**Issue by Krisselack** [millejoh/emacs-ipython-notebook#458]
In my current install EIN won't open the notebooklist in a browser session automatically. 

`

## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have
Ein won't open up in browser. Somehow in another version (Fedora) this worked fine. 
There are no error messages. When I click open in browser, it opens (after disabling Tokens in jupyterconfig (not ideal either)). 

## Steps to reproduce the problem

1. Open emacs 
2. M-x ein:run
3. Server starts in emacs. 

## Expected output
Also opening the notebook overview in browser. 

## Your EIN configuration (in .emacs.d/init.el or somewhere else)
(require 'ein)
(require 'ein-notebook)
(require 'ein-subpackages)

(setq ein:use-auto-complete t)
(setq ein:completion-backend 'ein:use-ac-jedi-backend)

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):
4.2.1 
2. How do you start IPython? (e.g., `ipython notebook --port 9999`):
ipython notebook 
3. What is your IPython notebook port number or URL?:
localhost:8888

## Additional information (if any)
After first install and on other system (Fedora 28), the notebook also opens in browser (without any tweaking). 

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
 of 2018-05-29"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux pinguin 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
"
  :lsb-release
  "No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.15.0-20190121.1354"
           :source-dir "/home/christian/.emacs.d/elpa/ein-20190121.1354/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/elpa/websocket-20180423.16/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.9")
  (:name "request"
         :path "~/.emacs.d/elpa/request-20181129.1138/request.elc"
         :featurep t
         :version-var request-version
         :version "0.3.0")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20170125.245/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/elpa/popup-20160709.1429/popup.elc"
         :featurep t
         :version-var popup-version
         :version "0.5.3")
  (:name "python"
         :path "/usr/share/emacs/26.1/lisp/progmodes/python.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path "~/.emacs.d/elpa/markdown-mode-20181229.1430/markdown-mode.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "helm"
         :path "~/.emacs.d/elpa/helm-core-20190122.549/helm.elc"
         :featurep t
         :version-var nil
         :version nil)))
```
`

**Comment by dickmao** [comment]
Please try:
1. `ein:run`
2. `M-x customize-group RET ein`
3. Find `Ein:Jupyter Server Args` and `DEL` the `--no-browser` string
4. `C-x C-s`
5. Restart emacs

**Comment by Krisselack** [comment]
Thank you very much, that did it! Apparently also the debug option was on.
