### ISSUE TITLE
Emacs hangs when opening notebook

### ISSUE THREAD

**Issue by rhstanton** [millejoh/emacs-ipython-notebook#46]
I haven't used EIN for a while, but it used to work fine. I just pulled the latest version and tried to open an existing notebook. ein:notebooklist-open works fine and shows the list of files as expected. However, when I click to open one of the notebooks, I get a message in the minibuffer saying "Entering debugger", and then Emacs hangs completely until I force it to quit.

If this is relevant, I'm using Emacs 24.5.1 and IPython 3.1 under OS X 10.10.3.

More info: When I try to create a new notebook, Emacs doesn't hang but I do get a readable dump from the debugger, which might be useful. I tried including it in this message, but github complains it's too long and it also doesn't seem to allow me to attach it as a zip or txt file. Do let me know if you'd like me to mail it to you.

**Comment by millejoh** [comment]
Yes, please do send it in an email. Can I also trouble you to run M-x ein:dev-bug-report-template then fill out and post the results here?

**Comment by rhstanton** [comment]
Here’s the debugger output when I try to open a new notebook. I’ve zipped it so it’s not quite so huge.

**Comment by rhstanton** [comment]
Here's the bug report:

## Description of the problem you have

When I try to open an existing notebook, ein:notebooklist-open works fine and shows the list of files as expected. However, when I click to open one of the notebooks, I get a message in the minibuffer saying "Entering debugger", and then Emacs hangs completely until I force it to quit.


## Steps to reproduce the problem

1.
2.
3.

## Expected output


## Your EIN configuration (in .emacs.d/init.el or somewhere else)

Here's what I can find:

(setq ein:notebook-set-buffer-file-name t)
(require 'ein-loaddefs)
(setq ein:use-auto-complete-superpack t)

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):

3.1.0

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):

ipython notebook

3. What is your IPython notebook port number or URL?:

8888

## Additional information (if any)


## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, Carbon Version 157 AppKit 1347.57)
 of 2015-04-20 on Richards-Mac-Pro.local"
 :emacs-bzr-version "f1161b7d871e4d022376649a0f74f5b4211c234c"
 :window-system mac
 :emacs-variant nil
 :os
 (:uname
  "Darwin Richards-Mac-Pro.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
"
  :lsb-release nil)
 :image-types
 (svg image-io imagemagick png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (svg image-io imagemagick png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.3.d2681d8-dirty"
           :source-dir
           "/Applications/MacPorts/EmacsMac.app/Contents/Resources/site-lisp/emacs-ipython-notebook/lisp/")
 :lib
 ((:name "websocket"
         :path
         "/Applications/MacPorts/EmacsMac.app/Contents/Resources/site-lisp/emacs-websocket/websocket.el"
         :featurep t
         :version-var websocket-version
         :version "1.4")
  (:name "request"
         :path "~/.emacs.d/el-get/request/request.elc"
         :featurep t
         :version-var request-version
         :version "0.2.0")
  (:name "auto-complete"
         :path "~/.emacs.d/el-get/auto-complete/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "auto-complete"
         :path "~/.emacs.d/el-get/auto-complete/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/el-get/popup/popup.elc"
         :featurep t
         :version-var popup-version
         :version "0.5.2")
  (:name "fuzzy"
         :path "~/.emacs.d/el-get/fuzzy/fuzzy.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "pos-tip"
         :path "~/.emacs.d/el-get/pos-tip/pos-tip.elc"
         :featurep t
         :version-var pos-tip-version
         :version "0.4.5")
  (:name "python"
         :path
         "/Applications/MacPorts/EmacsMac.app/Contents/Resources/lisp/progmodes/python.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "python-mode"
         :path
         "/Applications/MacPorts/EmacsMac.app/Contents/Resources/site-lisp/python-mode/python-mode.el"
         :featurep t
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path "~/.emacs.d/el-get/markdown-mode/markdown-mode.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "helm"
         :path
         "/Applications/MacPorts/EmacsMac.app/Contents/Resources/site-lisp/jmax/elpa/helm-20150315.1008/helm.elc"
         :featurep t
         :version-var nil
         :version nil)))
```

**Comment by millejoh** [comment]
As a temporary workaround you can comment out `(setq ein:notebook-set-buffer-name t)`. Not sure what I did to break this, but I will try to find out.

Note that if you are downloading from MELPA the (require 'ein-loaddefs) is unnecessary.
