### ISSUE TITLE
Selecting Python Version

### ISSUE THREAD

**Issue by Krisselack** [millejoh/emacs-ipython-notebook#460]
After reading the docs and screening all the options, I was not able to change ein's python kernel version. 
In EIN I am using 3.6.7 ("/usr/bin/python"), but my up-to date version is 3.7.1. Jupyter from CLI runs 3.7.1, Python (elpy) from emacs also runs 3.71. 
EIN-Version: 0.15.0
Emacs: 3.22.30

Setup in .emacs for selecting python Interpreter: 
`(setq python-shell-interpreter "/home/xyz/miniconda3/bin/python")
(setq elpy-rpc-python-command "/home/xyz/miniconda3/bin/python")
`
Where would I set the kernel version? Thanks.

**Comment by dickmao** [comment]
Pleaes check the output of `jupyter kernelspec list`.  I believe EIN will respect whatever that says.  You can google how to configure jupyter's kernels.

**Comment by Krisselack** [comment]
Thanks. It was a bit odd, as the jupyter command from CLI used a different kernel than EIN. I had an install of miniconda overriding my system python. As a "solution" I deleted miniconda and turned back to the old python3 in /usr/bin.

**Comment by dickmao** [comment]
I see.  While my suggestion didn't help, I do still believe EIN does not expose explicit configuration of python versions and such.
