### ISSUE TITLE
Scrolling for large tabular/text output 

### ISSUE THREAD

**Issue by Pfedj** [millejoh/emacs-ipython-notebook#465]
Hello.
Ein 20190204.1901, Emacs 26.1, windows 10.
I try to open notebook with a large dataset inside the output of a cell. Jupiter notebook is pretty show as 
![sample](https://user-images.githubusercontent.com/11408619/52327229-6d137580-29fc-11e9-8b5f-33909d7901fe.png)
In emacs I have uncomfortable latency scrolling experience for this.
Is there any solution for this?

**Comment by dickmao** [comment]
Emacs's latency on long lines is widely observed.  Please do a Google search for more information.

**Comment by millejoh** [comment]
Take a look at `M-x customize-variable RET ein:truncate-long-cell-output`.

My only suggestion is to set that variable to some number that is reasonable to you.
