### ISSUE TITLE
SageMath a Python "dialect"

### ISSUE THREAD

**Issue by malb** [millejoh/emacs-ipython-notebook#466]
Hi there, 

I'm using EIN for talking to a SageMath https://www.sagemath.org/ Jupyter notebook. 

With a current version of EIN SageMath cells are not recognised as Python. This is technically correct since Sage's language is a Python "dialect" (e.g. 2^3 is exponentiation). 

There is a sage-mode for Emacs but I'm at a loss how to tell EIN that it should e.g. syntax highlight code blocks using that major mode. 

Alternatively, if SageMath were to be treated as Python, that'd also work. Any suggestions?

**Comment by dickmao** [comment]
https://github.com/millejoh/emacs-ipython-notebook/blob/3e6c77b8a374cee04ddb88845338f0ed4109d015/lisp/ein-core.el#L190-L191

Perhaps change these lines to:
```
:language (let ((lang (plist-get (plist-get info :spec) :language)))
             (if (string= lang "sagemath") "python" lang))
```

**Comment by malb** [comment]
Thanks! 

Looks like this might be a bug in Sage, `lang` comes back as the empty string "".

**Comment by malb** [comment]
Hi, I've reported this issue to Sage and it seems indeed a bug there: https://trac.sagemath.org/ticket/27644 So I think on EIN's side nothing should be done for now. Thanks!
