### ISSUE TITLE
Notebook JSON is invalid: Additional properties are not allowed ('svg' was unexpected)

### ISSUE THREAD

**Issue by alexalekseyenko** [millejoh/emacs-ipython-notebook#467]
When Shapely is used to output an SVG, for instance:
```python
MultiPolygon(list(shapefile.geometry))
```

Jupyter Notebook throws the following error:

    [E 10:45:08.174 NotebookApp] Notebook JSON is invalid: Additional properties are not allowed ('svg' was unexpected)

        Failed validating 'additionalProperties' in execute_result:

        On instance['cells'][22]['outputs'][0]:
        {'data': {'text/plain': ['<shapely.geometry.multipolygon.MultiPolygon at '
                                '0xaa6bad240>']},
        'execution_count': 7,
        'metadata': {},
        'output_type': 'execute_result',
        'svg': '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www....'}

Which is in reference to the following cell (SVG attributes omitted):

    {
    "cell_type": "code",
    "execution_count": 7,
    "metadata": {
      "autoscroll": false,
      "collapsed": false,
      "ein.hycell": false,
      "ein.tags": "worksheet-0",
      "slideshow": {
      "slide_type": "-"
      }
    },
    "outputs": [
      {
      "data": {
        "text/plain": [
        "<shapely.geometry.multipolygon.MultiPolygon at 0xaa6bad240>"
        ]
      },
      "execution_count": 7,
      "metadata": {},
      "output_type": "execute_result",
      "svg": "<svg ... /></g></g></svg>"
      }
    ],
    "source": [
      "MultiPolygon(list(shapefile.geometry))"
    ]
    },

This also breaks in the browser.

However, when the call to Shapely is run in the browser, the validation error does not appear, and the corresponding cell looks like this (SVG attributes omitted):

    {
    "cell_type": "code",
    "execution_count": 9,
    "metadata": {
      "autoscroll": false,
      "ein.hycell": false,
      "ein.tags": "worksheet-0",
      "slideshow": {
      "slide_type": "-"
      }
    },
    "outputs": [
      {
      "data": {
        "image/svg+xml": [
        "<svg ... /></g></g></svg>"
        ],
        "text/plain": [
        "<shapely.geometry.multipolygon.MultiPolygon at 0xaa32f6320>"
        ]
      },
      "execution_count": 9,
      "metadata": {},
      "output_type": "execute_result"
      }
    ],
    "source": [
      "\n",
      "MultiPolygon(list(shapefile.geometry))\n"
    ]
    },

## System Info

Jupyter Notebook

```bash
$ jupyter notebook --version
5.7.4
```

EIN

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 26.1 (build 1, x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G1314))
 of 2018-05-28"
 :emacs-bzr-version nil
 :window-system ns
 :emacs-variant nil
 :os
 (:uname
  "Darwin <redacted> 16.7.0 Darwin Kernel Version 16.7.0: Sun Oct 28 22:30:19 PDT 2018; root:xnu-3789.73.27~1/RELEASE_X86_64 x86_64 i386 MacBookAir6,2 Darwin
"
  :lsb-release nil)
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.15.0-20190204.1901"
           :source-dir "/Users/<redacted>/.emacs.d/elpa/26.1/develop/ein-20190204.1901/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/elpa/26.1/develop/websocket-20180423.16/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.9")
  (:name "request"
         :path "~/.emacs.d/elpa/26.1/develop/request-20181129.1138/request.elc"
         :featurep t
         :version-var request-version
         :version "0.3.0")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/26.1/develop/auto-complete-20170125.245/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/elpa/26.1/develop/popup-20160709.1429/popup.elc"
         :featurep t
         :version-var popup-version
         :version "0.5.3")
  (:name "fuzzy"
         :path "~/.emacs.d/elpa/26.1/develop/fuzzy-20150730.337/fuzzy.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "pos-tip"
         :path "~/.emacs.d/elpa/26.1/develop/pos-tip-20150318.1513/pos-tip.elc"
         :featurep t
         :version-var pos-tip-version
         :version "0.4.6")
  (:name "python"
         :path "/usr/local/Cellar/emacs-plus/26.1/share/emacs/26.1/lisp/progmodes/python.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path "~/.emacs.d/elpa/26.1/develop/markdown-mode-20181229.1430/markdown-mode.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "helm"
         :path "~/.emacs.d/elpa/26.1/develop/helm-core-20190122.549/helm.elc"
         :featurep t
         :version-var nil
         :version nil)))
```

**Comment by millejoh** [comment]
Looks like two things are happening here.

1) EIN is not setting the right MIME type for svg, it should be "image/svg+xml". That is easily enough fixed.
2) The output returned by shapely is not processed correctly by EIN and it is ending up in the wrong place when exporting the cell to json. This will be a little more challenging to track down, especially considering the unholy mess that is that part of the code (all fault for that is mine, by the way).

**Comment by millejoh** [comment]
Assuming this is working for you now, but feel free to reopen if not.
