### ISSUE TITLE
Results in Org-mode

### ISSUE THREAD

**Issue by erdogdu** [millejoh/emacs-ipython-notebook#468]
In Org-mode, if the results are reported in multiple lines, then re-executing that block overwrites only the first line in the results. For example, after three executions (runs) of the following block, I get
`#+name: test`
`#+begin_src ein :session 8888/temp.ipynb`
`np.zeros(18)`
`#+end_src`
`#+RESULTS: test`
`: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., # this is from run 3`
 `      0.]) # from run 3`
`       0.]) # from run 2, didn't get overwritten because in second line`
`       0.]) # run 1, didn't get overwritten because in second line`
`

A solution to this issue is using drawers. But then each time I execute a block, drawer is auto-collapsed. That is,

`#+name: test`
`#+begin_src ein :session 8888/temp.ipynb :results drawer`
`np.zeros(18)`
`#+end_src`
`#+RESULTS: test`
`:RESULTS:...  #need to use tab here, or bind opening drawers to another key`

Is there a solution to either or both of these issues?

**Comment by millejoh** [comment]
I see this too, but I'm not entirely sure what is causing this behavior, nor what is the right format to send results back to org babel to avoid this. Other than going the `:results drawer` route you can also try `:wrap ein_result` or `:wrap example` or whatever name suits your needs. Note that ob-ipython seems to take a somewhat similar route.

**Comment by millejoh** [comment]
Fixed in PR #470 - but let me know if you still have problems with multi-line outputs in org.
