### ISSUE TITLE
Seeking help configure EIN for Windows 10

### ISSUE THREAD

**Issue by troisquatre** [millejoh/emacs-ipython-notebook#473]
## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [ ] Does IPython works from the web browser? NOTE: I typically use Jupyter notebooks, and haven't tried IPython.
- [ ] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have
I'm using Windows 10, an OS I'm admittedly not familiar with. In Windows, I'm attempting to use Jupyter within Emacs witout success. I'd like to avail your help to resolve this problem.

When I run: `ein:jupyter-server-start`, it asks me for `Notebook directory`. As I attempt to start the jupyter server from the relevant directory, i.e., `c:/Users/digby/Projects_d_20181226/`, it automatically suggests the same directory. When I hit return, I get the following error: ` Wrong type argument: stringp, nil`.

Please note that I have *not* been able to use IPython from the browser, but have been regularly using Jupyter notebook from the Microsoft Edge browser.

## Steps to reproduce the problem

1. Launch emacs 
2. Navigate to directory with notebook
3. Run: `ein:jupyter-server-start`

## Your EIN configuration (in .emacs.d/init.el or somewhere else)
;; package
(require 'package)
(add-to-list 'package-archives
	     '("melpa" . "http://melpa.milkbox.net/packages/") t)
(add-to-list 'package-archives
 	     '("marmalade" . "http://marmalade-repo.org/packages/"))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (when no-ssl
    (warn "\
Your version of Emacs does not support SSL connections,
which is unsafe because it allows man-in-the-middle attacks.
There are two things you can do about this warning:
1. Install an Emacs version that does support SSL and be safe.
2. Remove this warning from your init file so you won't see it again."))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives (cons "gnu" (concat proto "://elpa.gnu.org/packages/")))))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(package-initialize)

(custom-set-variables
 '(package-selected-packages
   (quote
    (package+ markdown-mode+ requirejs smartrep python-mode markdown-mode ipython-shell-send jupyter request-deferred tornado-template-mode ipython ein))))
(custom-set-faces
 )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(require 'ein)
(require 'ein-notebook)
(require 'ein-subpackages)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; (defun ipython ()
;;     (interactive)
;;     (term "/usr/bin/ipython"))

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):7.2.0

2. How do you start IPython? (e.g., `ipython notebook --port 9999`): None. BUT, when I launch Jupyter, I run: `jupyter notebook`

3. What is your IPython notebook port number or URL?: Not sure. Refer point above.

## System info:

```cl
("EIN system info"
 :emacs-version "GNU Emacs 26.1 (build 1, x86_64-w64-mingw32)
 of 2018-05-30"
 :emacs-bzr-version "07f8f9bc5a51f5aa94eb099f3e15fbe0c20ea1ea"
 :window-system w32
 :emacs-variant nil
 :os
 (:uname nil
	 :lsb-release nil)
 :image-types
 (svg png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (svg png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend url-retrieve)
 :ein
 (:version "0.15.0-20190222.1528"
	   :source-dir "c:/Users/dipparthi/AppData/Roaming/.emacs.d/elpa/ein-20190222.1528/")
 :lib
 ((:name "websocket"
	 :path "~/.emacs.d/elpa/websocket-20180423.16/websocket.elc"
	 :featurep t
	 :version-var websocket-version
	 :version "1.9")
  (:name "request"
	 :path "~/.emacs.d/elpa/request-20181129.1138/request.elc"
	 :featurep t
	 :version-var request-version
	 :version "0.3.0")
  (:name "auto-complete"
	 :path "~/.emacs.d/elpa/auto-complete-20170125.245/auto-complete.elc"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "popup"
	 :path "~/.emacs.d/elpa/popup-20160709.1429/popup.elc"
	 :featurep t
	 :version-var popup-version
	 :version "0.5.3")
  (:name "python"
	 :path
	 "c:/Users/dipparthi/MyEmacsInstallation/share/emacs/26.1/lisp/progmodes/python.elc"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "python-mode"
	 :path "~/.emacs.d/elpa/python-mode-20181223.1933/python-mode.elc"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "markdown-mode"
	 :path "~/.emacs.d/elpa/markdown-mode-20181229.1430/markdown-mode.elc"
	 :featurep t
	 :version-var markdown-mode-version
	 :version "2.4-dev")
  (:name "smartrep"
	 :path "~/.emacs.d/elpa/smartrep-20150509.230/smartrep.elc"
	 :featurep nil
	 :version-var nil
	 :version nil)))
```

**Comment by dickmao** [comment]
At some point you will need to install `curl`, but we should first address the `Wrong type argument, stringp, nil`.  That is almost certainly a bug.  Could you help us by starting emacs anew and running:

1.  `ein:dev-start-debug`
2.  Reproduce the steps to get the error.

Then copy the resulting backtrace here.

**Comment by troisquatre** [comment]
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-exists-p(nil)
  ein:jupyter-server-start(nil "c:/Users/dipparthi/Projects/CAS/AssessmentDashboard_Dj_20190226/" nil (lambda (buffer url-or-port) (pop-to-buffer buffer)))
  funcall-interactively(ein:jupyter-server-start nil "c:/Users/dipparthi/Projects/CAS/AssessmentDashboard_Dj_20190226/" nil (lambda (buffer url-or-port) (pop-to-buffer buffer)))
  call-interactively(ein:jupyter-server-start record nil)
  command-execute(ein:jupyter-server-start record)
  execute-extended-command(nil "ein:jupyter-server-start" "ein:jupyter-server-sta")
  funcall-interactively(execute-extended-command nil "ein:jupyter-server-start" "ein:jupyter-server-sta")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)


    On ‎Tuesday‎, ‎26‎ ‎February‎ ‎2019‎ ‎18‎:‎23‎:‎59‎ ‎CET, dickmao <notifications@github.com> wrote:  
 
 
At some point you will need to install curl, but we should first address the Wrong type argument, stringp, nil. That is almost certainly a bug. Could you help us by starting emacs anew and running:
   
   - ein:dev-start-debug
   - Reproduce the steps to get the error.

Then copy the resulting backtrace here.

**Comment by dickmao** [comment]
Thanks, I believe it's because emacs cannot find jupyter.  Please try:

```
M-: (executable-find "jupyter")
```
#474 aims to avoid the `Wrong argument stringp nil` error in favor of a less cryptic one.

**Comment by millejoh** [comment]
Late to the party as usual, but yes, this very much looks like an issue with finding the jupyter executable.

@troisquatre, where is your `jupyter.exe` located on your system and what is the setting for `ein:jupyter-default-server-command`? On Windows I recommend setting that variable to the full path to the jupyter executable.

Note that IPython != Jupyter, although EIN's documentation somewhat treats them the same still (though that is really a historical artifact that needs to be corrected at some point). IPython these days refers to either the command line Python client or the kernel implementation that can be managed by a jupyter server.

**Comment by troisquatre** [comment]
`M-: (executable-find "jupyter")` didn't work on my Emacs, and was becoming a bit of an exercise to make it work. So, I simply searched for `jupyter.exe` on my computer and here are the results:
`C:\Users\dipparthi\AppData\Local\Continuum\anaconda3\envs\py37\Scripts`
`C:\Users\dipparthi\AppData\Local\Continuum\anaconda3\pkgs\jupyter_core-4.4.0-py37_0\Scripts`
`C:\Users\dipparthi\AppData\Local\Continuum\anaconda3\Scripts`

Not sure if this is relevant, but here's how I use Jupyter within a browser:
1. Run `anaconda prompt`
2. In `anaconda prompt`, I execute: 
  a. `activate py37`
  b. `cd <directory_of_my_notbook>`
  c. `jupyter notebook`
3. This opens `Microsoft Edge` by itself, and the notebook works fine therein.

**Comment by millejoh** [comment]
Right, so you can do one of two things that I can think of:

1. `M-x customize-variable RET ein:jupyter-default-server-command` and set it to the exact path to the `jupyter.exe` executable, which looks to be `C:\Users\dipparthi\AppData\Local\Continuum\anaconda3\envs\py37\Scripts\jupyter.exe`.
2. From the command prompt activate the environment containing the jupyter executable (probably something like `conda activate py37`) and then- and this is important- *start emacs from the same command prompt*. Do not launch emacs from the desktop or star menu; it will not know about the activated environment.

You can also start jupyter from the command prompt and then use `ein:notebooklist-login` to open up the ein notebooklist browser.

**Comment by troisquatre** [comment]
The first approach works! 

There's this notification:
`ein: [info] Failed to save notebook!`

But, I suppose this is a different can of worms? 

In any case, thanks a ton! You all have been very helpful and super quick!

**Comment by troisquatre** [comment]
> ein: [info] Failed to save notebook!

Should I create a new "issue" for the aforementioned problem?

**Comment by LingxiangYu** [comment]
Hi, 
I have the similar issue. However, when I tried the first approach `M-x customize-variable`, I couldn't see ein in the list. Could you please let me know the other way that I can add `ein:jupyter-default-server-command`?

**Comment by yatsky** [comment]
> > ein: [info] Failed to save notebook!
> 
> Should I create a new "issue" for the aforementioned problem?

I had the same problem with saving notebooks. By removing some of the seemingly long outputs I was able to save the notebooks without any problem. This is just a workaround as you might still want the output...

**Comment by troisquatre** [comment]
> I had the same problem with saving notebooks. By removing some of the seemingly long outputs I was able to save the notebooks without any problem. This is just a workaround as you might still want the output...

Not sure how you removed the seemingly long outputs. Can you elaborate, or better yet, can you include relevant commands?

**Comment by yatsky** [comment]
> > I had the same problem with saving notebooks. By removing some of the seemingly long outputs I was able to save the notebooks without any problem. This is just a workaround as you might still want the output...
> 
> Not sure how you removed the seemingly long outputs. Can you elaborate, or better yet, include relevant commands?

`C-c C-k` to kill/delete the cell. Like I said, I did not need the cells so I just deleted them. You might still want them so try `C-c C-e` which toggles the output of the cell.
