### ISSUE TITLE
Proxy server settings leads to error

### ISSUE THREAD

**Issue by ema2159** [millejoh/emacs-ipython-notebook#476]
I am able to use EIN in my home with no error whatsoever but when I try to use it at work (where the only difference is that I have to set a certain proxy configuration) I get the following error:
`08:46:25:021: [error] Login to http://127.0.0.1:8888 failed, error-thrown (error http 403), raw-header HTTP/1.1 403 Forbidden
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Content-Length: 606
`
The notebook starts correctly and I have access to it through the browser, but I'm unable to use EIN. What could be the error?

**Comment by dickmao** [comment]
#464 is likely the same issue.  Unfortunately, EIN hardcodes the so-called loopback address `127.0.0.1`.  This is probably a bug.

I would try:
```
nc -lk 8888 (in one terminal)
curl -v http://127.0.0.1:8888 (in another terminal)
```
If that fails, you would need to get your hands dirty by replacing all occurrences of `127.0.0.1` with something your work env allows.

**Comment by cwitte** [comment]
I've had the same problem, it doesn't appear to be a problem with curl but rather with emacs not setting the NO_PROXY environment variable. I posted more info and a work around in bug #464 , see https://github.com/millejoh/emacs-ipython-notebook/issues/464#issuecomment-475484396
