### ISSUE TITLE
Regression: company-completion interacts badly with other modes

### ISSUE THREAD

**Issue by malb** [millejoh/emacs-ipython-notebook#478]
I'm now seeing "Company: backend ein:company-backend error "No kernel related to the current buffer." with args (candidates Foo)" I believe this is caused by https://github.com/millejoh/emacs-ipython-notebook/pull/477

**Comment by millejoh** [comment]
It's not much of a real solution, but I can at least try to keep ein from ruining your day with this error message.

**Comment by malb** [comment]
Thanks! This does the trick.
