### ISSUE TITLE
Retire auto-complete

### ISSUE THREAD

**Issue by dickmao** [millejoh/emacs-ipython-notebook#482]
tkf's integration of the matsuyama auto-complete was never quite correct.  It manages some semblance of correctness under python2, but is completely broken under python3.

EIN claims four different completion backends of dubious utility and user adoption, only one of which is tested.

Seeking approval to default `ein:completion-backend` to `ein:use-none-backend`, and support a single alternative `ein:use-company-backend`.

**Comment by millejoh** [comment]
I agree with your logic. I am concerned there are some users out there who might find the change abrupt and disconcerting so I would hope the community can provide some feedback before going forward with completely removing the auto-complete backend. In the meantime I support defaulting to `ein:use-none-backend`, but not removing any of the auto-complete code (just yet, at least).

Note that while opening an issue here does alert the 800 some individuals who have graced this project with their stars, [MELPA](https://melpa.org/#/ein) reports there are at least 64,000 downloads (!) of this package. Though I am unsure exactly how MELPA calculates that metric it does imply there are far more users out there than are monitoring here on github.

Perhaps the path forward is to start raising 'deprecated' warnings when the auto-complete backend is disabled and in a few months or so remove the option completely depending on the responses we get.

**Comment by seagle0128** [comment]
I agree to removing `auto-complete` from the dependencies, since `company-mode` is better and all are optional. `auto-complete` is just another option, not necessary.

**Comment by seagle0128** [comment]
@dickmao Sorry for comment here. But I didn't see `auto-complete` is removed from the dependencies according to the commits above.

**Comment by dickmao** [comment]
> Is it really retired?

Deprecated.  As requested by the package maintainer, the auto-complete code remains resident in memory so that it can be manually activated.

**Comment by seagle0128** [comment]
@dickmao Thanks for reply! IMO it's better removing `auto-complete` from the dependencies, and enable the related functionalities after activating `auto-complete-mode`, like `company-mode`.
