### ISSUE TITLE
ein with clojure kernel doesn't render output correct

### ISSUE THREAD

**Issue by keesterbrugge** [millejoh/emacs-ipython-notebook#484]
Hi,
 I'm trying out the iclojure kernel, but something goes wrong. It goes wrong in exactly the same way with jupyter and jupyter-lab. 

I start jupyter-lab in the terminal, make a connection using `ein:notebooklist-open`. From there I make a iclojure notebook. 

This is how its rendered in emacs
```
In [5]:
(map inc [2 3])
Out [5]:
[2m([22m3 4[2m)[22m
```

in the browser, however it does look correct. 

![Screenshot 2019-03-13 at 19 12 52](https://user-images.githubusercontent.com/6086439/54303776-0cabc100-45c4-11e9-9a64-ebc2375bba7a.png)

This is the content of the ipynb file
```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "autoscroll": false,
    "collapsed": false,
    "ein.hycell": false,
    "ein.tags": "worksheet-0",
    "slideshow": {
     "slide_type": "-"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\u001b[2m(\u001b[22m3 4\u001b[2m)\u001b[22m\n"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "(map inc [2 3])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "autoscroll": false,
    "collapsed": false,
    "ein.hycell": false,
    "ein.tags": "worksheet-0",
    "slideshow": {
     "slide_type": "-"
    }
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "IClojure",
   "language": "iclojure",
   "name": "iclojure"
  },
  "language_info": {
   "file_extension": ".clj",
   "mimetype": "text/x-clojure",
   "name": "clojure",
   "version": "1.10.0"
  },
  "name": "Untitled2.ipynb"
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

```
Do you have any ideas how I get the output to render correctly with ein? 

Cheers

**Comment by dickmao** [comment]
> Do you have any ideas how I get the output to render correctly with ein?

Add an ANSI escape code filter to EIN's `text/plain` rendering pipeline?
It seems odd that iclojure would add such color codes to `text/plain` but perhaps that is *de rigeur* now for jupyter kernels.
