### ISSUE TITLE
`wrong-type-argument` after call `ein:notebooklist-new-notebook-with-name`

### ISSUE THREAD

**Issue by kenkangxgwe** [millejoh/emacs-ipython-notebook#485]
## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have

After I called `ein:notebooklist-new-notebook-with-name`, it gave the message that 

```
ein: [warn] No recorded kernelspecs for 8888
helm-M-x: Wrong type argument: ein:$notebooklist, nil
```

So I opened the debugger and the `*BackTrace*` buffer shown that
```
Debugger entered--Lisp error: (wrong-type-argument ein:$notebooklist nil)
  signal(wrong-type-argument (ein:$notebooklist nil))
  ein:notebooklist-new-notebook-with-name("test" "default" 8888)
  funcall-interactively(ein:notebooklist-new-notebook-with-name "test" "default" 8888)
  call-interactively(ein:notebooklist-new-notebook-with-name record nil)
  command-execute(ein:notebooklist-new-notebook-with-name record)
  helm-M-x(nil #("ein:notebooklist-new-notebook-with-name" 0 39 (match-part "ein:notebooklist-new-notebook-with-name")))
  funcall-interactively(helm-M-x nil #("ein:notebooklist-new-notebook-with-name" 0 39 (match-part "ein:notebooklist-new-notebook-with-name")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

## Steps to reproduce the problem

1. <kbd>M-x</kbd> `ein:jupyter-server-start`
2. <kbd>M-x</kbd> `ein:notebooklist-new-notebook-with-name`

## Your EIN configuration (in .emacs.d/init.el or somewhere else)

I use default config from [Spacemacs](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/ipython-notebook).

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):
    6.2.1

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):  
<kbd>M-x</kbd> `ein:jupyter-server-start`

3. What is your IPython notebook port number or URL?:  
http://127.0.0.1:8888

## Additional information (if any)

I have looked at #464, but I did not set up any proxy.

## System info:

```cl
("EIN system info"
 :emacs-version "GNU Emacs 26.1 (build 1, x86_64-w64-mingw32)
 of 2018-05-28"
 :emacs-bzr-version "ae330c90e2cb41554c42a9d0154a00e084d5bb04"
 :window-system w32
 :emacs-variant nil
 :os
 (:uname nil
         :lsb-release nil)
 :image-types
 (svg png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (svg png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.15.0-20190209.1936"
           :source-dir "c:/Users/kenkangxgwe/.emacs.d/elpa/develop/ein-20190209.1936/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/elpa/develop/websocket-20180423.16/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.9")
  (:name "request"
         :path "~/.emacs.d/elpa/develop/request-20181129.1138/request.elc"
         :featurep t
         :version-var request-version
         :version "0.3.0")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/develop/auto-complete-20170125.245/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/elpa/develop/popup-20160709.1429/popup.elc"
         :featurep t
         :version-var popup-version
         :version "0.5.3")
  (:name "fuzzy"
         :path "~/.emacs.d/elpa/develop/fuzzy-20150730.337/fuzzy.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "pos-tip"
         :path "~/.emacs.d/elpa/develop/pos-tip-20150318.1513/pos-tip.elc"
         :featurep t
         :version-var pos-tip-version
         :version "0.4.6")
  (:name "python"
         :path "d:/Programs/msys64/mingw64/share/emacs/26.1/lisp/progmodes/python.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path "~/.emacs.d/elpa/develop/markdown-mode-20181229.1430/markdown-mode.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "helm"
         :path "~/.emacs.d/elpa/develop/helm-core-20190205.1337/helm.elc"
         :featurep t
         :version-var nil
         :version nil)))
```

**Comment by dickmao** [comment]
Sorry about this.  Thanks for reporting a real bug.

**Comment by kenkangxgwe** [comment]
It seems the problem continues. I am still getting the same message
```
ein: [warn] No recorded kernelspecs for 8888
helm-M-x: Wrong type argument: ein:$notebooklist, nil
```

**Comment by dickmao** [comment]
Please go into directory `M-: (ein:source-dir)`, and ensure the change made in #486 is there.

**Comment by kenkangxgwe** [comment]
There's no such a function or variable called `(ein:source-dir)`

**Comment by dickmao** [comment]
> There's no such a function or variable called `(ein:source-dir)`

Sorry, `M-: ein:source-dir`

**Comment by kenkangxgwe** [comment]
Ok, I checked my the file under the `ein:source-dir`, which is `~/.emacs.d/elpa/develop/ein-20190315.1546/ein-notebooklist.el:434`. It had already been the latest version:
```elisp
(list url-or-port kernelspec name)))
```

**Comment by dickmao** [comment]
I get a similar error when I didn't first `ein:run` or `ein:login`.

This command should not return nil

`M-: (ein:notebooklist-list-get (ein:url 8888))`

Otherwise, I'm afraid I cannot diagnose your problem.
