### ISSUE TITLE
can't undo 

### ISSUE THREAD

**Issue by littlehome-eugene** [millejoh/emacs-ipython-notebook#489]
## Problem description
on opening *.ipynb file, I see `Warning (ein): Disabling undo for undo-tree-undo`
and I can't undo 

 ## Steps to reproduce the problem
 open a file and edit it

 C-_ for undo-tree-undo

 Debugger entered--Lisp error: (error "No undo information in this buffer")
   signal(error ("No undo information in this buffer"))
   error("No undo information in this buffer")
   (progn (error "No undo information in this buffer"))
   (if (eq buffer-undo-list t) (progn (error "No undo information in this buffer")))
   undo-tree-undo(nil)
   funcall-interactively(undo-tree-undo nil)
   call-interactively(undo-tree-undo nil nil)
   command-execute(undo-tree-undo)

 
 ## System info:

 ```cl
 ("EIN system info"
  :emacs-version
  "GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511))
  of 2018-05-31"
  :emacs-bzr-version nil
  :window-system nil
  :emacs-variant nil
  :os
  (:uname
   "Darwin eugenekimui-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
 "
   :lsb-release nil)
  :notebook
  "You are using pip version 9.0.1, however version 19.0.3 is available.
 You should consider upgrading via the 'pip install --upgrade pip' command.
 "
  :ipython "7.2.0
 "
  :image-types
  (png gif tiff jpeg xpm xbm pbm)
  :image-types-available
  (png gif tiff jpeg xpm xbm pbm)
  :request
  (:backend curl)
  :ein
  (:version "0.15.0-20190310.228"
            :source-dir "/Users/eugenekim/.emacs.d/elpa/ein-20190310.228/")
  :lib
  ((:name "websocket"
          :path "~/.emacs.d/elpa/websocket-20180422.1716/websocket.elc"
          :featurep t
          :version-var websocket-version
          :version "1.9")
   (:name "request"
          :path "~/.emacs.d/elpa/request-20170131.1747/request.elc"
          :featurep t
          :version-var request-version
          :version "0.3.0")
   (:name "auto-complete"
          :path "~/.emacs.d/elpa/auto-complete-1.5.1/auto-complete.elc"
          :featurep t
          :version-var nil
          :version nil)
   (:name "popup"
          :path "~/.emacs.d/elpa/popup-0.5.3/popup.elc"
          :featurep t
          :version-var popup-version
          :version "0.5.3")
   (:name "python"
          :path "/Applications/Emacs.app/Contents/Resources/lisp/progmodes/python.elc"
          :featurep t
          :version-var nil
          :version nil)
   (:name "markdown-mode"
          :path "~/.emacs.d/elpa/markdown-mode-2.3/markdown-mode.elc"
          :featurep t
          :version-var markdown-mode-version
          :version "2.3")
   (:name "helm"
          :path "~/.emacs.d/elpa/helm-core-2.8.7/helm.elc"
          :featurep t
          :version-var nil
          :version nil)))
 ```

**Comment by dickmao** [comment]
Hi, that is expected behavior (undo is disabled for spacemacs).  Your re-raising of the issue, however, has suggested a more elegant way to deal with the spacemacs `undo-tree` versus `undo` issue #451, which I implement in #490.  We don't test spacemacs, so your mileage may vary.

**Comment by littlehome-eugene** [comment]
umm system info says ` :emacs-version
 "GNU Emacs 26.1 ` , Is it the same as spacemacs? I thought not..

**Comment by dickmao** [comment]
#490 disables `undo-tree` mode for EIN buffers, so at the very least the warning `Disabling undo` should not appear (regardless of spacemacs).

**Comment by mfrasca** [comment]
I was about to open an issue on `undo`, I'm not sure if I should.  I'm in GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian.  I notice that undo is sometimes funny: I split a cell, the content above the marker goes in the above cell, and I stay in the current one, with less content. I realize I did not want to split the cell at all, I undo, and the content from the above cell moves into the current one, but the above cell does not disappear.

now, after hitting the above problem a couple of times, EIN is telling me there's no undo information in the buffer, and a very long warning, starting with:
```
Error (ein): Undo failure diagnostic (nil (47433 . 47516) (service = next(services_iter)
    service_description = service.get('description') . 47421) nil (47421 . 47503) (service = next(services_iter)
    service_description = service.get('description')
```

**Comment by dickmao** [comment]
EIN's undo implementation affects only entered text.  It cannot "undo" any cell-level actions.  If you add a cell via `C-c C-b` or `C-c C-a`, undo will not delete the added cell.  This is confusing to everyone, and there is no relief in sight.

The `Undo failure diagnostic` is a bug.  If EIN's limitations have not already deterred you, please file a `M-x ein:dev-bug-report-template` so that we can know all the details.

**Comment by mfrasca** [comment]
I'm not deterred, I'm too much used to emacs as to consider anything else.  I hope you have the force to continue developing this!  and I might contribute, for example handling the issues I'm opening myself, but I need pointers into some technical documentation.
