### ISSUE TITLE
Text is read-only: when hitting end of cell

### ISSUE THREAD

**Issue by mfrasca** [millejoh/emacs-ipython-notebook#498]
I'm editing a cell, deleting text.  I want to delete a few trailing lines in the cell, so I go on the first line I want to delete, and start hitting `C-k`, in my mind expecting seeing each line first turn empty then disappear, at every subsequent `C-k` activation.

for example, here I want to delete the trailing line, which I added just to check the value.
![image](https://user-images.githubusercontent.com/122869/55246189-aef9b480-5212-11e9-937b-187868749457.png)

this goes as expected up to the last line in the cell, where again I would expect the line to disappear and either: (1) see my cursor jump to the end of the preceding line (this is a safe option, since any subsequent `C-k` would be expected to have no effect at all), or (2) see my cursor jump to the beginning of the following cell, but then I have to be careful not to keep invoking the kill.

what really happens is that the line stays there, the cursor jumps to the next line outside the editable cells, and I get the error `Text is read-only`.

![image](https://user-images.githubusercontent.com/122869/55246244-cfc20a00-5212-11e9-9d5d-888e9da43a6e.png)

if I keep "killing" text while outside the editable cells, it has no effect on the content of the buffer, it tells me that the "Text is read-only", but my cursor keeps jumping further in the buffer, which I don't find disturbing, but a bit surprising.

**Comment by millejoh** [comment]
This is something of a known (#58) issue which probably pre-dates my involvement with the package. Looking at the code, there are a lot of `\n`'s being inserted with the `read-only` property. I can only assume tkf's motivation in doing this was to maintain a notebook-like appearance to the buffer. There might be a better way now.

I think most of the code responsible for this is in `ein-cell.el`.

**Comment by mfrasca** [comment]
I don't manage to find clues in the code, my affinity with lisp is limited.

can you catch this case:
user hits kill while the point is at `(ein:cell-input-pos-max cell)`
if the previous character is a line break, remove it and update point.
otherwise do nothing.

but a "do nothing" is possibly better.

I don't know what to look for, in the code.
