### ISSUE TITLE
documentation: inline images versus python pop-ups?

### ISSUE THREAD

**Issue by rebcabin** [millejoh/emacs-ipython-notebook#50]
When trying the opening sample, the very first one under https://github.com/millejoh/emacs-ipython-notebook where it says "screenshot," I get the graphics in a popup window and not inside emacs.  The popup window is a hateful thing because it takes me out of emacs and then I have to touch the mouse to dismiss it and I've blown my mental cache & lost the advantages of using emacs.  I looked around a long time for some info in the docs to address this, and didn't find any.  If I end up figuring out how to fix this, I'll put it in the wiki. But because it may be something that will bite other beginners, may I suggest a word about it in the documentation. 

(EDIT: I found out that i need to say

    %pylab inline
    def plotnormal ...

and that the emacs background color should not be black (i'll try to fix that problem)

the documented example

    from pylab import plot

does not work for me: python barfs with 

    Truncated Traceback (Use C-c C-x to view full TB):
    <ipython-input-7-8618f02f2b7e> in <module>()
    ----> 1 from pylab import plot

    ImportError: cannot import name plot

and I don't know why

**Comment by millejoh** [comment]
Pylab is depcrecated in IPython 2.x. Recommended way of doing inline plots is:

```python

import matplotlib.pyplot as plt

%matplotlib inline.
```

I need to update that image...

**Comment by rebcabin** [comment]
The following works great

    In [1]:
    import matplotlib.pyplot as plot
    from numpy import random
    %matplotlib inline

    In[2]:
    def plotnormal():
        return plt.plot (random.randn (1000), random.randn (1000), 'o', alpha=0.3)
    plotnormal ()

**Comment by dickmao** [comment]
Please consult the FAQ in README.

**Comment by EvanMath** [comment]
> Please consult the FAQ in README.

Thank you, I just saw it just after I wrote the post yesterday. Works fine.
