### ISSUE TITLE
behaviour of C-up and C-down to mimic python-mode

### ISSUE THREAD

**Issue by mfrasca** [millejoh/emacs-ipython-notebook#501]
when editing Python scripts, I make huge use of C-up and C-down.  it lets me move between blocks of code, and I obviously make use of blank lines precisely because I know how C-up and C-down behave in correspondence of these blank lines.

I'm using blank lines in my notebooks too, and I wish EIN to acknowledge their presence.

what happens now is that I can only jump one cell at a time.

the most surprising in the 'one cella at a time' behaviour though is when I am in the middle of a cell, press on C-up, and I land at the beginning of the **previous** cell.

**Comment by millejoh** [comment]
Yes, currently ein only knows how to move to the beginning of a cell (maybe that can be fixed, though). I think if you enabled `ein:polymode` you might get back some of the behavior you are looking for, at least while inside a python cell.

**Comment by dickmao** [comment]
Sorry, the C-up and C-down shall remain cell-up and cell-down, not block-up and block-down.
