### ISSUE TITLE
stopping a notebook brings me to beginning of buffer

### ISSUE THREAD

**Issue by mfrasca** [millejoh/emacs-ipython-notebook#503]
when stopping a notebook from the notebooklist, the editor flashes as if it reloads the buffer, and brings the point back to the top of the buffer.
```
 [Open] ------ [Delete] : Untitled.ipynb                                      31/03/19
 [Open] [Stop] [Delete] : Untitled1.ipynb                                     31/03/19
 [Open] ------ [Delete] : Untitled2.ipynb                                     02/04/19
```
I would rather see the point stay at the same position, i.e.: where the `[Stop]` turns into `------`.

**Comment by millejoh** [comment]
This is a bug - ein should restore the point on a notebooklist refresh, but thanks to callback heck it isn't happening as expected. Let me see if I can fix that.

**Comment by millejoh** [comment]
Is behavior post PR a bit better for you?

**Comment by mfrasca** [comment]
it works fine!  thank you!

**Comment by mfrasca** [comment]
it works for `[Open]` and for `[Close]`, but not when I open a `[Dir]`.  or is it "as designed"?  I wish it would put the point at the first entry of the new directory, not at the beginning of the buffer.

also, if I use the mouse to select `[Dir]`, or `[Open]`, it beeps all the time, giving as message: `insert-for-yank: Buffer is read-only: #<buffer *ein:notebooklist http://127.0.0.1:8888*>`

when it opens a notebook, it does not mark it as running (it does not show the `[Stop]` button), I have to refresh the buffer.

while the `[Stop]` isn't yet showing, I refresh the notebooklist, and my point moves a few characters back to the start of the buffer.  I suppose because it does not take into account the added content, in my case `[Open][Close] : *ein: http://127.0.0.1:8888/RainData.ipynb*`

**Comment by millejoh** [comment]
1. Getting your `[Dir]` behavior working is a bit more complicated than I would like to contemplate at the moment, but I'll definitely accept it as an RFE. Might be doable as a hook on `ein:notebooklist-render--finish`.

2. I am unable to reproduce your error with mouse-1. Are you sure it is bound to `(mouse-set-point)` and that that function has no hooks or defadvice's?

3. The notebook should (and once did) refresh after selecting `[Open]`, so that is a bug. I'll take a look at a fix.

4. Bug, and you are spot on for the reason. Not sure there is an easy fix, though.

**Comment by mfrasca** [comment]
1. I'll open a new bug RFE

2. how do I check that?

4. what about counting chars from the end?

**Comment by millejoh** [comment]
`C-h k` then click. And I think it should say that <down-mouse-1> is bound to widget-button-click, among other things. This is what my config says:

```
There were several key-sequences:

  <down-mouse-1> at that spot runs the command widget-button-click
  <mouse-1> at that spot runs the command mouse-set-point

They're all described below.



<down-mouse-1> at that spot runs the command widget-button-click (found in
ein:notebooklist-mode-map), which is an interactive compiled Lisp function.

It is bound to <down-mouse-1>, <down-mouse-2>.

(widget-button-click EVENT)

Invoke the button that the mouse is pointing at.



<mouse-1> at that spot runs the command mouse-set-point (found in global-map),
which is an interactive compiled Lisp function.

It is bound to <mouse-1>.

(mouse-set-point EVENT &optional PROMOTE-TO-REGION)

Move point to the position clicked on with the mouse.
This should be bound to a mouse click event type.
If PROMOTE-TO-REGION is non-nil and event is a multiple-click, select
the corresponding element around point, with the resulting position of
point determined by ‘mouse-select-region-move-to-beginning’.

[back]
```

**Comment by mfrasca** [comment]
I checked with C-h k, got something practically equal to yours, and I can't reproduce the behaviour any more.  I have one more report about non-ipynb files, I'll open it separately.  I should leave this one open, you see when all component issues are solved.  thank you.
