### ISSUE TITLE
broken completion after typing (

### ISSUE THREAD

**Issue by abderrahim** [millejoh/emacs-ipython-notebook#506]
When I type `(` as in `tf.keras.layers.Dense(`, I get completions like `tf.keras.layers.Dense%%!`, which don't make any sense. I scrolled the list and it seems it is trying to replace the `(` with all possible completions of an empty string.

This is all with the default settings. I don't know if this is caused by an interaction with another package I have installed, will try to test with nothing installed.

I'm using 0.15.0 from melpa-stable.

**Comment by dickmao** [comment]
I could not reproduce this.  Typing `tf.keras.layers.Dense(` did not trigger auto-complete for me.

**Comment by millejoh** [comment]
You can turn off ein's custom, hacky company backend by setting `ein:completion-backend` to `ein:use-none-backend`. You can also toggle `ein:polymode` to enable polymode support and get better autocompletion using whatever backend is configured for python-mode.

**Comment by millejoh** [comment]
The oinfo cache can get corrupted under certain circumstances. You can clean things up by calling `M-: (ein:completions--reset-oinfo-cache (get-kernel)` inside the notebook buffer.

**Comment by dickmao** [comment]
Echoing above, `M-x customize-group RET ein-completion` and set the backend to `ein:use-none-backend`, and restart emacs should do the trick.

Polymode is not available in melpa-stable or the 0.15.0 release.  Please install from melpa or github to get the latest/greatest.
