### ISSUE TITLE
How to disable dot completion

### ISSUE THREAD

**Issue by abderrahim** [millejoh/emacs-ipython-notebook#507]
Because of #506, I tried to disable company and auto-complete (`M-x company-mode` and `M-x auto-complete-mode`). (btw, it seems weird to me to enable both, don't they do the same thing).

The result is every time I type a dot, I get a `Complete:` prompt at the minibuffer. Looking at the documentation on how to disable it, i found an old changelog entry that mentions `ein:complete-on-dot`, but this variable is gone and its replacement is nowhere explained.

Using 0.15.0 from melpa-stable.

**Comment by millejoh** [comment]
See my comments in #506 for disabling ein's idiosyncratic completion backend.
