### ISSUE TITLE
error [Open]ing non-ipynb file already associated to buffer

### ISSUE THREAD

**Issue by mfrasca** [millejoh/emacs-ipython-notebook#515]
the `notebooklist` buffer shows directories, notebooks, but also "other" files.  if you click on `[open]` for a non-ipynb file, behaviour depends on whether the file is already being visited, or not.

if it's not yet being visited, that is if no buffer is associated to the file, it goes as expected: file opens and the new buffer is activated.

if the file `<filename>` is already visited, you get the message and question:
`A buffer is visiting /home/mario/'/ein:http:/127.0.0.1:8888:<filename>; proceed? (y or n)`

answering `y` activates a second buffer on the same file.

**Comment by mfrasca** [comment]
by the way: why not emulate `dired` behaviour?
`<enter>` to visit the file in the same window: `(dired-find-file)`;
`o` to visit the file in other window: `(dired-find-file-other-window)`.

**Comment by millejoh** [comment]
Because ein is designed to work with remotely running jupyter servers. Perhaps the right thing is to extend tramp to understand jupyter's REST API, but I am not equipped for such an undertaking at the moment.

**Comment by dickmao** [comment]
Integrating with dired does make a lot more sense.  Thanks.
