### ISSUE TITLE
Some Error and warning during installation

### ISSUE THREAD

**Issue by Tantelitiana22** [millejoh/emacs-ipython-notebook#516]
Hi,
I have some error and warning that I put bellow during the installation  of ein from melpa. So, can anyone help me? 
Thank's

`
Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-ac.el at Sun Apr 14 07:50:53 2019
Entering directory ‘/home/tantely/.emacs.d/elpa/ein-20190404.2325/’
ein-ac.el:32:30:Error: Symbol’s value as variable is void: eieio-object-name-string

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-cell-edit.el at Sun Apr 14 07:50:53 2019

In end of data:
ein-cell-edit.el:269:1:Warning: the following functions are not known to be defined:
    ein:worksheet--get-buffer, ein:worksheet-get-current-cell,
    ein:notebook--get-nb-or-error, ein:worksheet--get-ws-or-error

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-cell-output.el at Sun Apr 14 07:50:53 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-cell.el at Sun Apr 14 07:50:53 2019
ein-cell.el:846:18:Warning: function ‘equalp’ from cl package called at
    runtime
ein-cell.el:1069:45:Warning: function ‘copy-list’ from cl package called at
    runtime

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-classes.el at Sun Apr 14 07:50:54 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-company.el at Sun Apr 14 07:50:54 2019

In ein:company-backend:
ein-company.el:76:52:Warning: reference to free variable ‘ein:connect-mode’

In ein:company--punctuation-check:
ein-company.el:104:52:Warning: function ‘subseq’ from cl package called at
    runtime

In end of data:
ein-company.el:125:1:Warning: the function ‘ein:worksheet-at-codecell-p’ is
    not known to be defined.

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-completer.el at Sun Apr 14 07:50:54 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-connect.el at Sun Apr 14 07:50:54 2019

In end of data:
ein-connect.el:415:1:Warning: the following functions are not known to be defined:
    ein:notebooklist-ask-path, ein:notebooklist-parse-nbpath,
    ein:notebook-opened-buffer-names, ein:notebook-buffer,
    ein:notebook-live-p, ein:notebook-execute-autoexec-cells,
    ein:worksheet-buffer-p

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-console.el at Sun Apr 14 07:50:54 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-contents-api.el at Sun Apr 14 07:50:54 2019
ein-contents-api.el:33:1:Warning: cl package required at runtime

In end of data:
ein-contents-api.el:528:1:Warning: the function ‘ein:notebook-to-json’ is not
    known to be defined.

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-core.el at Sun Apr 14 07:50:54 2019

In ein:byte-compile-ein:
ein-core.el:386:42:Warning: function ‘mapcan’ from cl package called at
    runtime

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-dev.el at Sun Apr 14 07:50:54 2019

In ein:dev-pop-to-debug-channels:
ein-dev.el:168:47:Warning: reference to free variable ‘ein:%notebook%’

In ein:dev-pop-to-debug-shell:
ein-dev.el:176:47:Warning: reference to free variable ‘ein:%notebook%’

In ein:dev-pop-to-debug-iopub:
ein-dev.el:184:47:Warning: reference to free variable ‘ein:%notebook%’

In ein:dev-notebook-plain-mode:
ein-dev.el:189:9:Warning: assignment to free variable ‘ein:notebook-modes’

In ein:dev-notebook-python-mode:
ein-dev.el:194:9:Warning: assignment to free variable ‘ein:notebook-modes’

In ein:dev-notebook-mumamo-mode:
ein-dev.el:199:9:Warning: assignment to free variable ‘ein:notebook-modes’

In ein:dev-notebook-multilang-mode:
ein-dev.el:204:9:Warning: assignment to free variable ‘ein:notebook-modes’

In ein:debug-notebook-to-json-buffer:
ein-dev.el:339:45:Warning: reference to free variable ‘ein:%notebook%’

In end of data:
ein-dev.el:351:1:Warning: the following functions are not known to be defined:
    ein:notebook-kill-all-buffers, ein:notebook-to-json

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-events.el at Sun Apr 14 07:50:54 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-file.el at Sun Apr 14 07:50:54 2019

In end of data:
ein-file.el:69:1:Warning: the following functions are not known to be defined:
    ein:notebooklist-parse-nbpath, ein:notebooklist-ask-path

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-helm.el at Sun Apr 14 07:50:54 2019

In ein:helm-export-source:
ein-helm.el:44:23:Warning: ‘helm-source’ is an obsolete variable (as of 25.1);
    use 'helm-source instead
ein-helm.el:44:9:Warning: ‘helm-source’ is an obsolete variable (as of 25.1);
    use 'helm-source instead

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-hy.el at Sun Apr 14 07:50:55 2019
ein-hy.el:26:1:Warning: cl package required at runtime

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-iexec.el at Sun Apr 14 07:50:55 2019
ein-iexec.el:28:1:Error: Symbol’s value as variable is void: eieio-object-name-string

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-inspector.el at Sun Apr 14 07:50:55 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-ipdb.el at Sun Apr 14 07:50:55 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-ipynb-mode.el at Sun Apr 14 07:50:55 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-jupyter.el at Sun Apr 14 07:50:55 2019

In ein:jupyter-server-conn-info:
ein-jupyter.el:92:60:Warning: function ‘search’ from cl package called at
    runtime

In end of data:
ein-jupyter.el:249:1:Warning: the following functions are not known to be defined:
    ein:notebook-opened-notebooks, ein:notebook-modified-p,
    ein:notebook-save-notebook, ein:notebook-close

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-jupyterhub.el at Sun Apr 14 07:50:55 2019

In ein:jupyterhub--query-server:
ein-jupyterhub.el:160:11:Warning: defsubst ‘ein:jupyterhub--query-server’ was
    used before it was defined

In ein:jupyterhub--query-user:
ein-jupyterhub.el:170:11:Warning: defsubst ‘ein:jupyterhub--query-user’ was
    used before it was defined

In ein:jupyterhub--query-login:
ein-jupyterhub.el:179:11:Warning: defsubst ‘ein:jupyterhub--query-login’ was
    used before it was defined

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-kernel.el at Sun Apr 14 07:50:55 2019

In ein:kernel-session-p--error:
ein-kernel.el:124:44:Warning: function ‘search’ from cl package called at
    runtime

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-kernelinfo.el at Sun Apr 14 07:50:55 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-kill-ring.el at Sun Apr 14 07:50:55 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-log.el at Sun Apr 14 07:50:55 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-multilang-fontify.el at Sun Apr 14 07:50:56 2019

In ein:mlf-font-lock-fontify-block:
ein-multilang-fontify.el:60:56:Warning: ‘font-lock-fontify-buffer’ is for
    interactive use only; use ‘font-lock-ensure’ or ‘font-lock-flush’ instead.

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-multilang.el at Sun Apr 14 07:50:56 2019
ein-multilang.el:32:1:Error: Symbol’s value as variable is void: eieio-object-name-string

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-node.el at Sun Apr 14 07:50:56 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-notebook.el at Sun Apr 14 07:50:56 2019
ein-notebook.el:55:1:Error: Symbol’s value as variable is void: eieio-object-name-string

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-notebooklist.el at Sun Apr 14 07:50:56 2019

In ein:notebooklist-refresh-related:
ein-notebooklist.el:358:54:Warning: reference to free variable
    ‘ein:%notebook%’

In ein:notebooklist-parse-nbpath:
ein-notebooklist.el:768:52:Warning: function ‘search’ from cl package called
    at runtime

In end of data:
ein-notebooklist.el:1027:1:Warning: the following functions are not known to be defined:
    ein:list-available-kernels, ein:notebook-buffer,
    ein:notebook-rename-command, ein:notebook-url-from-url-and-id,
    ein:notebook-opened-buffers, ein:notebook-get-opened-notebook,
    ein:notebook-opened-notebooks, ein:notebook-update-url-or-port

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-notification.el at Sun Apr 14 07:50:56 2019
ein-notification.el:209:75:Warning: reference to free variable
    ‘ein:%notebook%’

In ein:header-line-setup-maybe:
ein-notification.el:328:8:Warning: reference to free variable
    ‘ein:notebook-mode’

In end of data:
ein-notification.el:336:1:Warning: the following functions are not known to be defined:
    ein:notebook-opened-buffer-names, ein:list-available-kernels,
    ein:notebook-switch-kernel

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-org.el at Sun Apr 14 07:50:56 2019

In end of data:
ein-org.el:121:1:Warning: the following functions are not known to be defined:
    ein:notebook-worksheet-open-ith, ein:notebook-buffer,
    ein:worksheet-buffer-p, ein:notebook-worksheet-index

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-output-area.el at Sun Apr 14 07:50:56 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-pager.el at Sun Apr 14 07:50:56 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-process.el at Sun Apr 14 07:50:56 2019

In ein:process-dir-match:
ein-process.el:145:26:Warning: function ‘search’ from cl package called at
    runtime

In ein:process-path:
ein-process.el:163:70:Warning: function ‘subseq’ from cl package called at
    runtime

In ein:process-open-notebook*:
ein-process.el:187:88:Warning: function ‘subseq’ from cl package called at
    runtime

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-pseudo-console.el at Sun Apr 14 07:50:56 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-python.el at Sun Apr 14 07:50:57 2019
ein-python.el:31:1:Error: Symbol’s value as variable is void: eieio-object-name-string

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-pytools.el at Sun Apr 14 07:50:57 2019

In ein:pytools-jump-to-source-command:
ein-pytools.el:267:7:Warning: reference to free variable ‘poly-ein-mode’

In ein:pytools-jump-back-command:
ein-pytools.el:285:7:Warning: reference to free variable ‘poly-ein-mode’

In end of data:
ein-pytools.el:421:1:Warning: the following functions are not known to be defined:
    ein:notebook-buffer, ein:notebook-opened-notebooks,
    ein:notebook-to-json

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-query.el at Sun Apr 14 07:50:57 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-scratchsheet.el at Sun Apr 14 07:50:57 2019
ein-scratchsheet.el:29:1:Error: Symbol’s value as variable is void: eieio-object-name-string

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-shared-output.el at Sun Apr 14 07:50:57 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-skewer.el at Sun Apr 14 07:50:57 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-smartrep.el at Sun Apr 14 07:50:57 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-subpackages.el at Sun Apr 14 07:50:57 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-timestamp.el at Sun Apr 14 07:50:57 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-traceback.el at Sun Apr 14 07:50:57 2019

In end of data:
ein-traceback.el:199:1:Warning: the following functions are not known to be defined:
    ein:worksheet-get-cells, ein:notebook-buffer

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-utils.el at Sun Apr 14 07:50:57 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-websocket.el at Sun Apr 14 07:50:57 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein-worksheet.el at Sun Apr 14 07:50:57 2019
ein-worksheet.el:37:1:Error: Symbol’s value as variable is void: eieio-object-name-string

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ein.el at Sun Apr 14 07:50:57 2019

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/ob-ein.el at Sun Apr 14 07:50:57 2019

In end of data:
ob-ein.el:289:1:Warning: the following functions are not known to be defined:
    org-element-property, ein:notebook-get-opened-notebook

Compiling file /home/tantely/.emacs.d/elpa/ein-20190404.2325/poly-ein.el at Sun Apr 14 07:50:57 2019
poly-ein.el:2:1:Error: Symbol’s value as variable is void: eieio-object-name-string

`

**Comment by dickmao** [comment]
Your emacs does not seem to know about `eieio-object-name-string` which was introduced in emacs 24.4.  Please refer to the README.md to ensure a compatible version of emacs.

**Comment by Tantelitiana22** [comment]
I use emacs 24.5.1 and after I switch to 25.3.50.2 but I got the same error and warning despite that. It's sames that EIN is tested on GNU Emacs versions 25.1 in the README.md .Normaly EIN is supposed to work in emacs 24.5.1 if it work in emacs 24.4 and emacs 25.1 but it's not the case for me when I was in emacs 24.5.1.

**Comment by dickmao** [comment]
Oh, this sounds problematic.  Can you try:
```
M-: (require 'eieio)
M-: (fboundp 'eieio-object-name-string)
```
The second command should return `t`

**Comment by Tantelitiana22** [comment]
I don't know if I did it right but I put the two lines You suggest above in my  .emacs files, and after I reinstall EIN in my emacs 24.5.1 for testing but I get another error as you can see in the picture bellow.
![EIN_ERROR](https://user-images.githubusercontent.com/39998513/56095768-792a2080-5ee0-11e9-880c-2fbbae274f2e.png)

**Comment by dickmao** [comment]
Version 24.5 is not going to work.  Also, those two lines are not meant for your `.emacs`.  They are meant to be executed in emacs,  `M-:` means hold down Alt Shift and press ":"

If you decide to upgrade to version 25.3, please first delete `/home/tantely/.emacs.d/elpa/cl-generic-*` and `/home/tantely/.emacs.d/elpa/eieio-*`, and reinstall `ein`.  If that doesn't work your `/home/tantely/.emacs.d/elpa` may still contain incompatible libraries from emacs 24.5.

**Comment by Tantelitiana22** [comment]
Finaly, I am going to keep using emacs 24.5 because other package are not supported yet by emacs 25.3.When  I try to enter the command lines above the second line return t as expected. And after removing and reinstalling ein I got the same error as before in emacs 24.5 .

**Comment by dickmao** [comment]
> Version 24.5 is not going to work.

Thanks for your interest in EIN.  Hope you come back when you upgrade your emacs.

**Comment by millejoh** [comment]
No guarantees, but  [v0.13.0](https://github.com/millejoh/emacs-ipython-notebook/tree/v0.13.0) or [v0.12.8](https://github.com/millejoh/emacs-ipython-notebook/tree/v0.12.8) might work with emacs 24.x. Check the [releases](https://github.com/millejoh/emacs-ipython-notebook/releases) page for downloadables.

You will need to ensure you have all dependencies installed and that your `load-path` points to the `lisp` directory in the emacs-ipython-notebook project. I can't recall the exact magic incantation to load those older versions, but I think doing `(require 'ein-jupyter)` is a good place to start.

**Comment by Tantelitiana22** [comment]
Finally I found a solution to make ein work. As I have all the time an error how said: Symbol's value as variable is void:eieio-object-name-string. I remove and reinstall polymode, and then it work now. 
I think the version of my polymode was not good, and now after reinstalling I got the right version. 

Thank you all for your help.

**Comment by dickmao** [comment]
> Finally I found a solution to make ein work. As I have all the time an error how said: Symbol's value as variable is void:eieio-object-name-string.

Under version 24.x or 25.x?  If 24.x, your kung fu is powerful, indeed.  I personally could not get things to compile under 24.5.1.
