### ISSUE TITLE
Cannot login when start notebook server form terminal with token authentication

### ISSUE THREAD

**Issue by objectc** [millejoh/emacs-ipython-notebook#520]
Running jupyter notebook locally. Starting the server with _ein:jupyter-server-start_ works. Staring the server from the terminal, if the token authentication is disabled, just log in with the default URL and everything also works fine. However, I cannot finish the authentication when the token is enabled.  I'm confused with the URL logic here. If I choose the default URL, there is no token or password prompt and I get 403 forbidden error directly. If I add "/?token=xxx" into the default, it seems Ein will turn it into"/?token=xxx/login" automatically and require me the token or password again. After I input the token, I will get HTTP 405  error. What's the specific URL should be when the token is enabled?

**Comment by dickmao** [comment]
From https://github.com/millejoh/emacs-ipython-notebook/issues/464#issuecomment-475484396

```
M-x customize-group RET request
Request Curl Options:
INS String: --noproxy
INS String: 127.0.0.1
C-x C-s
M-x ein:stop
M-x ein:run
```
If that doesn't work, please refer to README for self-diagnostics.

**Comment by dickmao** [comment]
Please disregard my above suggestion.

Start the server from terminal with token enabled.
Ensure `jupyter notebook list --json` emits good output.
`M-x ein:login` again, and reproduce the error.  Now,
```
M-: (ein:crib-running-servers)
```
Should be something like ("http://127.0.0.1:8888")
```
M-: (ein:notebooklist-token-or-password (first (ein:crib-running-servers)))
```
Should return the longwinded token (but it doesn't).
If you really want to make this work, you may need to invest self-diagnosing effort via the README instructions.
