### ISSUE TITLE
Open a list of the *.ipynb files in ein

### ISSUE THREAD

**Issue by Pfedj** [millejoh/emacs-ipython-notebook#521]
Suppose i have a list of files `*.ipynb`: `my/list-nb`.  For simplification lets say they are located in one directory `my/list-np-path`. I would like to open them in ein. 
How can i do it? 
Thank you in advance.

**Comment by dickmao** [comment]
```
(lexical-let* ((my/list-np-path ".")
               (callback (lambda (_buffer url)
                           (dolist (file
                                    (directory-files my/list-np-path nil "\\.ipynb"))
                             (ein:notebook-open url file)))))
  (ein:jupyter-server-start
   (executable-find ein:jupyter-default-server-command)
   my/list-np-path nil
   callback))
```

**Comment by Pfedj** [comment]
Hello. Your code works very well. Thank you.
There are restrictions in regard to the quantity of open notebooks (25 units). when opening more there is a message `Creating pipe too many open files` and only 25 notebooks can be opened. I would like to  open more than 25

**Comment by dickmao** [comment]
> I would like to open more than 25

You're doing it wrong.  The "notebook" ethos is about playing with an idea, not bulk processing.

**Comment by Pfedj** [comment]
I don't use all opened notebooks for work. I would like to have the possibility to search in all my notebooks. See my issue [issues/523](https://github.com/millejoh/emacs-ipython-notebook/issues/523). 
I have found easy decision but it works not properly and in unstable way. I need some help. I decided that I would just copy notebooks in boofers and could search in buffer. 
I have a function for copying all notebooks in buffers. It works.

```
 (defun my-copy-buffer (buf)
   (let* ((old-buf (buffer-name buf))
          (new-buf (f-base old-buf)))
     (switch-to-buffer old-buf)
     (get-buffer-create new-buf)
     (kill-ring-save (point-min) (point-max))
     (switch-to-buffer new-buf)
     (yank)))

(defun ein-to-buffers()
  (let ((temp-list (seq-filter (lambda (x)
                                 (string-prefix-p "*ein: http" (buffer-name x)))
                               (buffer-list))))
    (mapcar 'my-copy-buffer temp-list )))
```
I want to go through all my notebooks in circle and open 10 notebooks in server, copy them and close:
```
(defun my-ein-open-ipynb(list-nb)
  (lexical-let* ((nb-list list-nb)
                 (my/list-np-path "~/jupyter/")
                 (callback (lambda (_buffer url)
                             (dolist (file nb-list)
                               (ein:notebook-open url file)))))
    (ein:jupyter-server-start
     (executable-find ein:jupyter-default-server-command)
     my/list-np-path nil
     callback)))

(defun my-ein-open()
  (dotimes (i (/ (length my-nb-rel) 10))
    (let ((list-nb (cl-subseq my-nb-rel (+ (* i 10) 1) (+ (* i 10) 10)  )))
      ;(call-process (my-ein-open-ipynb list-nb))
     ;(run-with-idle-timer 30 nil (my-ein-open-ipynb list-nb))
      (my-ein-open-ipynb list-nb)
      (run-with-idle-timer 30 nil #'ein-to-buffers)
      (run-with-idle-timer 60 nil #'ein:stop))))
```
My problem now is that i need to wait downloding all notebooks before copy them and close. Is there any function that returns that all notebooks downloaded? Can I avoid call ( ein:stop) to close all notebooks automatically without putting ("y,n")?

**Comment by Pfedj** [comment]
I have found the solution. Now previously I use pandoc  for conversion from ipynb to md (plain text). So now I do not need to download these files. In anycase this solution works and issue should be closed.
