### ISSUE TITLE
Search in the list of open notebooks

### ISSUE THREAD

**Issue by Pfedj** [millejoh/emacs-ipython-notebook#523]
I would like to have the possibility in regard to all the open notebooks. There is `helm-multi-swoop-all` , `ivy (swiper-all)`, `multi-occur-in-matching-buffers` etc. But every thing works only for one notebook which is located in active buffer.
Is there any other decision for that?

**Comment by millejoh** [comment]
@pfedj, see the new function `ein:notebook-jump-to-opened-notebook` and let me know if that was what you were looking for.

Note that you can a list of all opened notebooks using the functions `ein:notebook-opened-buffers` and `ein:notebook-opened-buffer-names`.

**Comment by Pfedj** [comment]
This is not exactly what I have been searching. However I found these functions very useful for me. In regard to my question initially I did it incorrectly. Now I have found the solution. Now previously I use ```pandoc```  for conversion from ipynb to md (plain text) and have easy multi search.

Thank you. Should be closed.
