### ISSUE TITLE
The screen does not scroll up when I stay at the last line press C-c C-c

### ISSUE THREAD

**Issue by yefeiyu** [millejoh/emacs-ipython-notebook#527]
<img width="1617" alt="roll副本" src="https://user-images.githubusercontent.com/4845104/57577083-c4b0f980-74a1-11e9-8473-b8779db5db72.png">

**Comment by dickmao** [comment]
I am curious about the output of the following:
```
M-: (frame-parameter nil 'background-mode)
M-: (frame-parameter nil 'display-type)
M-: (face-attribute 'ein:cell-input-area :background)
```

**Comment by yefeiyu** [comment]
> I am curious about the output of the following:
> 
> ```
> M-: (frame-parameter nil 'background-mode)
> M-: (frame-parameter nil 'display-type)
> M-: (face-attribute 'ein:cell-input-area :background)
> ```
I modified the background color of material-theme, you can find it here:
https://github.com/yefeiyu/emacs-material-theme

**Comment by millejoh** [comment]
Note that `C-c C-c` is normally bound to `ein:worksheet-execute-cell`. This evalutes the cell, but does not move the point. If you want the buffer to scroll down you should instead press `M-RET`, which is normally bound to `ein:worksheet-execute-cell-and-goto-next`. This will advance the point to the next cell and cause the window to scroll, if needed.

**Comment by yefeiyu** [comment]
Now I use `C-l` roll cursor.
