### ISSUE TITLE
feature request: don't kill kernel with C-x+k

### ISSUE THREAD

**Issue by jackkamm** [millejoh/emacs-ipython-notebook#53]
I have a remote notebook I access through ssh tunnel. When I open the notebook through my browser (Chrome), the ipython kernel will persist even if I close the tab/browser. I find this extremely useful for loading large data files, going and doing something else, then coming back and inspecting the data after it is loaded.

In ein, I've found that closing the window through C-x+k shuts down the kernel, which interferes with my workflow. I would like to request that C-x+k not shut down the kernel.

While submitting this issue I did discover a workaround: closing emacs with C-x+c will not shut down the kernel. Still I think it would be preferable if closing the buffer mimicked the behavior of closing a tab in the browser.

Thanks for all the work on ein, it is a really great & useful package. ipython notebooks are awesome, but having to write code in browser is very annoying -- being able to do so in emacs is a game changer for me.

**Comment by millejoh** [comment]
Yes - I think this was actually how ein was originally meant to work, but I changed the behavior in my zealousness. I will work on reverting.

**Comment by millejoh** [comment]
Okay - 0cf283a43b394cd324f150e9f90332f9b833af79 should bring back this functionality, plus a little extra. Let me know if that works for you.

If you want to kill a kernel/session you can do it from the notebooklist or via C-c C-q from an opened notebook buffer.

**Comment by jackkamm** [comment]
Works for me! Can confirm C-x+k no longer kills kernel, and C-c C-q kills kernel and buffer. Thanks so much!
