### ISSUE TITLE
Lisp error: (void-function ein:ml-lang-setup-python3)

### ISSUE THREAD

**Issue by tenspd137** [millejoh/emacs-ipython-notebook#530]
I was using a version from 2018 installed from melpa and upgraded to the current version 20190511.1231.  I noticed that when I open a new notebook from emacs, it no longer switched to the buffer - I had to manually, and things like C-c C-c were no longer bound.  I ran ein:dev-start-debug and above is where the backtrace took me.  If I start a new python3 notebook in a web browser, log out, and open it in emacs, then it tells me the kernel is unknown, please click and select - if I do that, it fails and then behaves as if I just created it in emacs as I previously described, the debugger again says ml-lang-setup-python3 is void.  Unfortunatley, I don't know how to roll back to compare, but I do know the version before upgrading was 2018xxxx.xxxx - maybe release 0.14 or 0.14.1?  Before that, we are in 2017.  Hope it can get fixed.  Thanks!

![image](https://user-images.githubusercontent.com/2739062/57830237-b814f580-776e-11e9-8769-ad91ae492551.png)

**Comment by dickmao** [comment]
Run `jupyter kernelspec list` and locate the python3 `kernel.json`.  I expect it to be misspecified --- it might say `"language": "python3"` instead of `"language": "python"`.

**Comment by tenspd137** [comment]
Yup - that was it.....  thank you!
