### ISSUE TITLE
How to get beginning-of-cell or end-of-cell?

### ISSUE THREAD

**Issue by yefeiyu** [millejoh/emacs-ipython-notebook#532]
As well know, M-< get beginning-of-buffer, M-> get end-of-buffer.
Now we wanna get beginning-of-cell, How can I do?

**Comment by millejoh** [comment]
Getting to the beginning of the cell is easy - either `ein:worksheet-goto-next-input` or `ein:worksheet-goto-prev-input` will do the trick. Unfortunately there is currently no analogue for going to the ending of cell. Makes a good feature request, though.

**Comment by millejoh** [comment]
My mistake - there are functions to move to the beginning and end of cell input, see `ein:worksheet-beginning-of-cell-input` and `ein:worksheet-end-of-cell-input`. In `ein:notebook-multilang-mode` these are bound to `beginning-of-defun-function` and `end-of-defun-function`. That means calling `beginning-of-defun` and `end-of-defun` should move the point around mostly as you would except.

If you have `ein:polymode` enabled then the movement behavior will be based on what `python-mode` provides, which may not be what you are looking for. If you want to get this behavior back then I think you could do the following:

```emacs-lisp
(add-hook 'poly-ein-mode-hook (lambda () (setq-local beginning-of-defun-function 'ein:worksheet-beginning-of-cell-input)))
(add-hook 'poly-ein-mode-hook (lambda () (setq-local end-of-defun-function 'ein:worksheet-end-of-cell-input)))
```

**Comment by yefeiyu** [comment]
I find the way.
use C-M-a and C-M-e can get the result.
It's meaning is `beginning-of-defun-raw' and 'end-of-defun'.
