### ISSUE TITLE
ein with spacemacs errors

### ISSUE THREAD

**Issue by cdegroot** [millejoh/emacs-ipython-notebook#538]
I'm trying to use EIN to login to an already running notebook using `M-x ein:login`. This results in 

```
Eager macro-expansion failure: (error "Don’t know how to make a localized variable an alias") [2 times]                                             
```

in the "*Messages*" buffer.Trying to debug the issue seems to be impossible: `M-x ein:dev-start-debug` with then `M-x ein:login` results in 

```
ein:ac-setup-maybe: Symbol’s value as variable is void: ein:notebook-mode                                                                           
```

in "*Messages*" and subsequently most actions (like trying to execute anything through M-x, showing the buffer list) don't do anything but showing

```
Symbol’s value as variable is void: ein:notebook-mode                                                                                              
```

on the status line so I can't get to any debug info. Recompining EIN gives a ton of warnings (lots about references to undefined variables) and one error:

```
Compiling file /home/cees/.emacs.d/elpa/ein-20190522.149/ein-company.el at Fri May 24 12:05:33 2019                                                 
ein-company.el:31:1:Error: Don’t know how to make a localized variable an alias          
```

That error is on a line doing a `require` so I'm - not an Elisp specialist - a tad stuck here.

Emacs 25.2.2 (default Ubuntu 18.04) package, Spacemacs just updated so current as of today.

**Comment by dickmao** [comment]
#508 is very similar.  I would like to know two things: 1) the exact directory name of `/home/cees/.emacs.d/elpa/polymode*` and the contents of `/home/cees/.emacs.d/elpa/polymode*/polymode-pkg.el`.  Once you record that info, try deleting the directory and reinstalling EIN.

**Comment by cdegroot** [comment]
Install is through my Spacemacs config, in its `dotspacemacs-additional-packages` setting. Spacemacs takes care of the rest. 

Polymode is `polymode-20190508.1847`.  Contents of `polymode-pkg.el`:

```
(define-package "polymode" "20190508.1847" "Extensible framework for multiple major modes"
  '((emacs "25"))
  :keywords
  '("languages" "multi-modes" "processes")
  :authors
  '(("Vitalie Spinu"))
  :maintainer
  '("Vitalie Spinu")
  :url "https://github.com/vitoshka/polymode")
;; Local Variables:
;; no-byte-compile: t
;; End:
```

I'm gonna clean out `ein` now and restart Spacemacs and see whether that gives me a compile log. Otherwise I'll do a forced recompile and paste that here.

**Comment by dickmao** [comment]
Thank you.  The answers to 1 and 2 are correct.  So I look forward to answer 3.

**Comment by cdegroot** [comment]
Spacemacs output: https://gist.github.com/cdegroot/d80cb52c0e770e9135a3674289c6bd4b - after doing this, I get back stuck in the `Symbol’s value as variable is void: ein:notebook-mode` error when trying to do
pretty much anything. Gist with the forced recompile will follow next.

**Comment by cdegroot** [comment]
`byte-force-recompile` the melpa/ein.... directory: https://gist.github.com/cdegroot/18886fbb3b6a8afd6bacafde4de7dc26

**Comment by cdegroot** [comment]
(hmm... I was going through #508 and noticed https://github.com/millejoh/emacs-ipython-notebook/issues/508#issuecomment-479888144 - I don't have a `cl-generic` melpa package installed, nor anything in `/usr/share/{emacs,emacs25}`. In any case, removing the rest and retrying lands me in the same spot)

**Comment by dickmao** [comment]
What does `/home/cees/.emacs.d/elpa/cl-*` look like?  (Correct answer is none).
When `M-x find-library RET cl`, does it show a file that is `/usr/share/emacs/25.2/lisp/emacs-lisp/cl.el.gz`? (Correct answer is yes).

If you answer correctly on both, then I'm afraid I cannot help you.  I tried an install on spacemacs, emacs-version 25.1, ubuntu 16.04, and I didn't see your issues.

Not for nothing, but my EIN experience on spacemacs is truly impoverished.  So even if you get it to work, I think you'd be disappointed.

**Comment by cdegroot** [comment]
Yeah, both on the mark. Nothing in elpa, but in /usr/share it's there (I looked for `cl.el`, not for `cl.el.gz`, so couldn't find it). Last ditch attempt: clean out ~/.spacemacs and rebuild the whole thing. 

(not relevant to the issue report, but since you bring it up - why is the EIN experience on spacemacs impoverished?)

**Comment by dickmao** [comment]
> why is the EIN experience on spacemacs impoverished?

We only run our tests on GNU Emacs.  As you can tell from your own experience, EIN is not programmed robustly enough to handle variations, slight or otherwise.  In other words, everything needs to be perfect.  One glaring deficiency under spacemacs is undo functionality.  It just doesn't work --- partly because of spacemacs's insistence on `undo-tree` but other reasons as well.

**Comment by cdegroot** [comment]
Thanks. I cleaned out every last transient Spacemacs file and it still happened so something is broken around Spacemacs (or any of the myriad packages I have installed) and I am not Elisp-savvy enough to figure it out, I'm afraid. 

For now, I'm gonna setup a separate user with a clean `init.el` instead - Evil and EIN should be all I need to have something nicer to me than a web-based notebook UI :)

Sorry I couldn't be more useful in analyzing this and thanks for the quick responses!

**Comment by dickmao** [comment]
Evil also uses `undo-tree` which EIN will eventually fail on.

**Comment by cdegroot** [comment]
Yikes. Why can't I ever have nice things? ;-). Thanks for the heads-up.

**Comment by millejoh** [comment]
The `ipython-notebook` layer probably needs to be updated (note: I am not the guy who originally wrote that code, either), but I do regularly use ein under spacemacs. @dickmao is correct that undo is somewhat broken in `undo-tree`. At seemingly random times it will generate some scary looking error messages which probably mean undo information is being lost, but otherwise the rest of ein functions just fine.

For an idea check out this [gist](https://gist.github.com/millejoh/8632402a11384a3a0949fa350a1a271b). It needs work, but so far I have found it usable.

**Comment by jbharat** [comment]
I dont use spacemacs. I have my own config with evil. I would love to use ein. Is there a way to get ein working with just evil without depending on spacemacs?

**Comment by dickmao** [comment]
EIN under evil should "mostly" work.  EIN will automatically turn off undo-tree which causes problems.  If you turn on polymode, however, all bet are off (undo-tree cannot be turned off in that case and undo won't work).

**Comment by jbharat** [comment]
I am working on a config for ein with evil bindings. I will post it here once I am done.
