### ISSUE TITLE
EIN doesn't generate `language` metadata

### ISSUE THREAD

**Issue by peterewills** [millejoh/emacs-ipython-notebook#540]
If I generate a notebook with a single markdown cell containing the text `test` first in EIN (called `test.ein.ipynb`) then in the browser UI (called `test.browser.ipynb`) I see the following diff (`M-x diff RET test.ein.ipynb RET test.browser.ipynb RET`):

```
diff -u ~/test.browser.ipynb ~/test.ein.ipynb
--- ~/test.browser.ipynb	2019-05-24 16:39:54.000000000 -0700
+++ ~/test.ein.ipynb	2019-05-24 16:40:22.000000000 -0700
@@ -2,7 +2,12 @@
  "cells": [
   {
    "cell_type": "markdown",
-   "metadata": {},
+   "metadata": {
+    "ein.tags": "worksheet-0",
+    "slideshow": {
+     "slide_type": "-"
+    }
+   },
    "source": [
     "test"
    ]
@@ -11,21 +16,9 @@
  "metadata": {
   "kernelspec": {
    "display_name": "Python 3",
-   "language": "python",
    "name": "python3"
   },
-  "language_info": {
-   "codemirror_mode": {
-    "name": "ipython",
-    "version": 3
-   },
-   "file_extension": ".py",
-   "mimetype": "text/x-python",
-   "name": "python",
-   "nbconvert_exporter": "python",
-   "pygments_lexer": "ipython3",
-   "version": "3.6.8"
-  }
+  "name": "test.ein.ipynb"
  },
  "nbformat": 4,
  "nbformat_minor": 2
```
So, EIN doesn't include some metadata that the browser UI does. I can fix this by opening the notebook in the browser, and saving. The thing that is actually causing problems for me is that the missing `metadata.kernelspec.language` parameter causes [papermill](https://papermill.readthedocs.io/en/latest/) to bonk when I try and run my EIN-generated notebook.

Is this intended behavior? Is there something I can do to ensure that all the relevant metadata gets written to notebooks written in EIN?

**Comment by dickmao** [comment]
> the missing `metadata.kernelspec.language` parameter

Its absence is probably a bug -- although [the file format](https://nbformat.readthedocs.io/en/latest/format_description.html) intones that all metadata is arbitrary.  I have made a PR to make EIN's treatment of metadata less surprising ("language" will be there).
