### ISSUE TITLE
Autocomplete + EIN = slow sadness sometimes.

### ISSUE THREAD

**Issue by flamingbear** [millejoh/emacs-ipython-notebook#55]
Since you're looking at semi-related EIN things I thought I'd toss this out there.
## Check list
- [X] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [X] Does IPython works from the web browser?
- [X] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [X] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)
## Description of the problem you have

Autocomplete doesn't play nicely with long arrays containing long strings.
## Steps to reproduce the problem
1. take this sample cell and execute it:

```
longstring = '****************************************************************************************'
shortstring = '***'
shortarray = [shortstring + str(x) for x in range(12000)]
longarray = [longstring + str(x) for x in range(12000)]
```
1. next If you type slowly into another cell:

```
shortarray[3]
```

and execute, it returns reasonably fast.
1. If you type slowly into a third cell:

```
longarray[3]
```

it takes a noticeable (multi seconds, more than ten) amount of time to return.

If you go to another buffer and copy `longarray[88]` and paste that into a cell, it returns immediately.

If you turn off autocomplete, none of these behaviors happen.
## Expected output

I expect accessing an array element to be fast regardless of the length of data inside of the array.
## Your EIN configuration (in .emacs.d/init.el or somewhere else)

zeroein.el
## Your IPython configuration
1. What is your IPython version? (run `ipython --version`):
   3.1.0
2. How do you start IPython? (e.g., `ipython notebook --port 9999`):
   ipython notebook --notebook-dir=. --ip=0.0.0.0
3. What is your IPython notebook port number or URL?:
   8888
## System info:

``` cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57)
 of 2015-04-18 on Matts-MacBook-Air.local"
 :emacs-bzr-version nil
 :window-system nil
 :emacs-variant nil
 :os
 (:uname
  "Darwin Matts-MacBook-Air.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
"
  :lsb-release nil)
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.3.93b449b-dirty"
       :source-dir "/Users/savoie/projects/emacs-ipython-notebook/lisp/")
 :lib
 ((:name "websocket"
     :path "~/projects/emacs-ipython-notebook/lib/websocket/websocket.el"
     :featurep t
     :version-var websocket-version
     :version "1.3")
  (:name "request"
     :path "~/projects/emacs-ipython-notebook/lib/request/request.el"
     :featurep t
     :version-var request-version
     :version "0.2.0alpha1")
  (:name "auto-complete"
     :path "~/projects/emacs-ipython-notebook/lib/auto-complete/auto-complete.el"
     :featurep t
     :version-var nil
     :version nil)
  (:name "mumamo"
     :path "~/projects/emacs-ipython-notebook/lib/nxhtml/util/mumamo.el"
     :featurep t
     :version-var mumamo:version
     :version "0.91")
  (:name "auto-complete"
     :path "~/projects/emacs-ipython-notebook/lib/auto-complete/auto-complete.el"
     :featurep t
     :version-var nil
     :version nil)
  (:name "popup"
     :path "~/projects/emacs-ipython-notebook/lib/popup/popup.el"
     :featurep t
     :version-var nil
     :version nil)
  (:name "fuzzy"
     :path "~/projects/emacs-ipython-notebook/lib/fuzzy/fuzzy.el"
     :featurep nil
     :version-var nil
     :version nil)
  (:name "pos-tip"
     :path "~/projects/emacs-ipython-notebook/lib/pos-tip/pos-tip.el"
     :featurep nil
     :version-var nil
     :version nil)
  (:name "python"
     :path "~/projects/emacs-ipython-notebook/lib/python/python.el"
     :featurep t
     :version-var nil
     :version nil)
  (:name "markdown-mode"
     :path "~/projects/emacs-ipython-notebook/lib/markdown-mode/markdown-mode.el"
     :featurep nil
     :version-var nil
     :version nil)
  (:name "smartrep"
     :path "~/projects/emacs-ipython-notebook/lib/smartrep/smartrep.el"
     :featurep nil
     :version-var nil
     :version nil)))
```

**Comment by millejoh** [comment]
Thanks for the report!

I too have noticed that sometimes cells will take an inordinate amount of time to execute. If I go back and re-execute the cell with the busy `[*]` the code will immediately return.

I think what may be happening is that the code is executing and returning quickly, but Emacs is missing messages from the ipython kernel, so thinks the kernel is still executing. Great theory, but not exactly sure how to go about debugging. Think I will need lots of coffee for this one...

**Comment by flamingbear** [comment]
Just as another data point.  Re-executing the cell does not return immediately in my case.  Sorry.  I was hoping that would be a workaround.

**Comment by flamingbear** [comment]
So I thought I posted this today, but I can't find it.  I know you're not looking into this right now, but I might have found a clue. 

```
- ...                                                            3842  61%
   Automatic GC                                                  3819  61%
 + #<lambda 0x307fd065fecc770c>                                     9   0%
 + #<compiled 0x40d54879>                                           4   0%
 + #<compiled 0x40c244d7>                                           4   0%
 + #<lambda 0x307fd065fecc770c>                                     1   0%
 + #<lambda 0x307fd065fecc770c>                                     1   0%
 + #<lambda 0x307fd065fecc770c>                                     1   0%
 + #<lambda 0x307fd065fecc770c>                                     1   0%
 + #<lambda 0x307fd065fecc770c>                                     1   0%
 + #<lambda 0x307fd065fecc770c>                                     1   0%
+ #<compiled 0x4060a85d>                                         1240  19%
+ request--curl-callback                                          399   6%
+ timer-event-handler                                             344   5%
+ command-execute                                                 222   3%
+ redisplay_internal (C function)                                 210   3%
+ ac-handle-post-command                                            2   0%
```

If I increase `gc-cons-threshold` and do about the same thing it takes much less time and I don't see a lot of garbage collection happening.

```
+ #<compiled 0x44865f5d>                                          773  28%
+ request--curl-callback                                          498  18%
+ ...                                                             458  16%
+ timer-event-handler                                             353  12%
+ command-execute                                                 340  12%
+ redisplay_internal (C function)                                 304  11%
+ flycheck-display-error-at-point-soon                              1   0%
+ flycheck-perform-deferred-syntax-check                            1   0%
```

I'm not sure if you want to close this, but it seems like it's likely somewhere else?
my fix was 
`(setq gc-cons-threshold 100000000)`
Thanks
Matt

**Comment by arthurl** [comment]
Thanks @flamingbear, your suggestion works great for me!

However, this also increases the time needed for garbage collection. While this trade off is great for EIN, it's not good for everything else, because now Emacs periodically stalls for a few seconds. Is there a way to increase `gc-cons-threshold` only in active EIN buffers, and automatically revert to the default value outside EIN buffers?

**Comment by flamingbear** [comment]
Sorry I don't.  Maybe someone else can help.
