### ISSUE TITLE
ein:jupyter-server-start problem with command jupyter-notebook 

### ISSUE THREAD

**Issue by brittAnderson** [millejoh/emacs-ipython-notebook#552]
I am using archlinux and I have a command `juptyer-notebook` to start notebooks. This works fine from the terminal and emacs/ein can connect via login, but the command `ein:jupyter-server-start` always times out and fails (similar to what was described in issue #248). I believe the problems is the text string "notebook" being inserted in the function `ein:jupyter-server--run`. If I manually change "notebook" to "" on line 68 of ein-jupyter.el and recompile it works fine. However, this is not a general solution (because it breaks for those using `jupyter` ) and I am not elisp competent enough to write a patch to check if the juptyer command has the word "notebook" in it and then alter the string accordingly.

**Comment by dickmao** [comment]
Do you have `ein:jupyter-default-server-command` customized to `jupyter-notebook`?
If so, I would remove it from your `.emacs` or `init.el`.

**Comment by brittAnderson** [comment]
I do have it customized because I don't have the `jupyter` command in my case; only the `jupyter-notebook` one. `jupyter-notebook --version` is 5.7.8, but `jupyter --version` gives command not found.
