### ISSUE TITLE
callback for ein:kernel-restart-session

### ISSUE THREAD

**Issue by Nephyrin** [millejoh/emacs-ipython-notebook#554]
Minor request: While making a "restart session and execute autoexec cells" bind, I ran into some awkwardness due to `ein:kernel-restart-session` not exposing a callback.

I end up with the below, but the direct-manipulation of `ein:events-trigger` makes it seem like this is fragile and perhaps going past functions the user is expected to call directly.

```elisp
(defun neph-ein-restart-and-autoexec ()
  (interactive)
  ;; This inlines ein:kernel-restart-session since it doesn't take a callback.
  (ein:aif ein:%notebook%
      (let ((kernel (ein:$notebook-kernel it)))
        (ein:kernel-delete-session
         kernel
         (lambda (kernel)
           (ein:events-trigger (ein:$kernel-events kernel) 'status_restarting.Kernel)
           (ein:kernel-retrieve-session kernel 0
                                        (lambda (kernel)
                                          (ein:events-trigger (ein:$kernel-events kernel)
                                                              'status_restarted.Kernel)
                                          (ein:notebook-execute-autoexec-cells ein:%notebook%))))))
    (message "Not in notebook buffer")))
```

As a side-request, having a native `ein:notebook-restart-session-and-execute-autoexec-cells` and maybe `ein:notebook-restart-session-and-execute-all-cells` would be nice helpers -- the latter of which matches the "restart kernel and run all" the jupyter webui exposes.

Edit: clarified wording

**Comment by dickmao** [comment]
"autoexec" cells are no longer available.  The only supported and documented batch execution is manual `C-u C-c C-c` (ein:worksheet-execute-all-cells, ein:worksheet-execute-all-cells-above, ein:worksheet-execute-all-cells-below).
