### ISSUE TITLE
Attach to an opened terminal  

### ISSUE THREAD

**Issue by AlphaAlgorithms** [millejoh/emacs-ipython-notebook#558]
Upon reading through the docs, I did not find how to connect to a web Terminal opened in Jupyter  notebook.

ein: console-open is not set for a terminal

version: 26.2 on Ubuntu 18.10

**Comment by dickmao** [comment]
https://github.com/millejoh/emacs-ipython-notebook/issues/519#issuecomment-488294558

**Comment by millejoh** [comment]
Actually, I'm not entirely sure I understand what you mean by "web terminal". Do you mean connecting to a console via the `jupyter console` command? Notwithstanding @dickmao 's comments, EIN does support this via the `ein:console-open` command, but you have to call it from within an opened notebook and you have to set the `ein:console-executable` variable to point to your jupyter executable. Note that @dickmao is correct in that this functionality is not well tested, so there are no guarantees how it will work under varying emacs configurations.

You may also have to do some magic with the `ein:console-security-dir` and `ein:console-args` variables, but I can get the console to work on my setup simply by setting `ein:console-executable` to the absolute path of the jupyter executable.

**Comment by AlphaAlgorithms** [comment]
No, it is just working. ein:console-security-dir etc.

**Comment by millejoh** [comment]
"It's just not working" does not help me track down the problem. Without reproducing your issue there is no hope of fixing it.

Does `jupyter console` work from the command line?

Are you trying to connect over a remote connection? `ein:console-open` only works on local jupyter instances as it depends on calls to the `jupyter console` command.

Also, I am still not clear what you mean by "web terminal" - link to jupyter documentation or example would be helpful.

**Comment by AlphaAlgorithms** [comment]
wow, thank  you  for your patient response.  the web terminal is the created terminal from Jupyter notebook. On Jupyter's new button, there are options of Text file, Folder and Terminal.

**Comment by millejoh** [comment]
Thank you - okay I think I understand now. You are trying to open a [system shell](https://jupyterlab.readthedocs.io/en/stable/user/terminal.html)  on whatever system the jupyter notebook server is running on.

The bad news is that ein does not directly support this. The good news is that ein doesn't need to as Emacs offers a number of solutions that are far better. For accessing a remote machine I would take the time to understand [TRAMP](https://www.gnu.org/software/tramp/). For local shell access there are several options, [eshell](https://www.masteringemacs.org/article/complete-guide-mastering-eshell), [shell](https://www.gnu.org/software/emacs/manual/html_node/emacs/Interactive-Shell.html), [ansi-term](https://www.emacswiki.org/emacs/AnsiTerm) and others I probably don't know about.
