### ISSUE TITLE
autocomplete suggesstions not showing

### ISSUE THREAD

**Issue by xorb0ss** [millejoh/emacs-ipython-notebook#569]
Arch 5.1.16, emacs 26.2, latest EIN version on MELPA

For some reason I can't actually see the auto-complete suggestions. I've played around with some of the variables in `ein` but can't get it to work, or maybe not the right ones

Having run `ein:dev-start-debug` and `C-c C-i` to force the autocomplete, I can see the server sending back the appropriate suggestions, but nothing actually shows for me in the notebook:

```
[WS] Received: ~{"header": {"msg_id": "57e26cfe-efd0e4057cbce424df3c7795", "msg_type": "complete_reply", "username": "xxxx", "session": "3b3f50a3-89e3a0fa9c055f5a212b93dc", "date": "2019-07-10T12:11:35.363902Z", "version": "5.3"}, "msg_id": "57e26cfe-efd0e4057cbce424df3c7795", "msg_type": "complete_reply", "parent_header": {"msg_id": "4779bfb8-0bf2-43e7-98d6-096af022139c", "username": "xxxx", "session": "465c081f-3215-4dc8-98b3-a411e710fc30", "version": "5.0", "date": "2019-07-10T13:11:35+01:00", "msg_type": "complete_request"}, "metadata": {}, "content": {"matches": ["pause", "pcolor", "pcolormesh", "phase_spectrum", "pie", "pink", "plasma", "plot", "plot_date", "plotfile", "plotting", "polar", "prism", "psd", "pylab_setup"], "cursor_end": 5, "cursor_start": 4, "metadata": {"_jupyter_types_experimental": [{"start": 4, "end": 5, "text": "pause", "type": "function"}, {"start": 4, "end": 5, "text": "pcolor", "type": "function"}, {"start": 4, "end": 5, "text": "pcolormesh", "type": "function"}, {"start": 4, "end": 5, "text": "phase_spectrum", "type": "function"}, {"start": 4, "end": 5, "text": "pie", "type": "function"}, {"start": 4, "end": 5, "text": "pink", "type": "function"}, {"start": 4, "end": 5, "text": "plasma", "type": "function"}, {"start": 4, "end": 5, "text": "plot", "type": "function"}, {"start": 4, "end": 5, "text": "plot_date", "type": "function"}, {"start": 4, "end": 5, "text": "plotfile", "type": "function"}, {"start": 4, "end": 5, "text": "plotting", "type": "function"}, {"start": 4, "end": 5, "text": "polar", "type": "function"}, {"start": 4, "end": 5, "text": "prism", "type": "function"}, {"start": 4, "end": 5, "text": "psd", "type": "function"}, {"start": 4, "end": 5, "text": "pylab_setup", "type": "function"}]}, "status": "ok"}, "buffers": [], "channel": "shell"}
```

The above is the output of running autocomplete on `matplotlib.pyplot`

**Comment by millejoh** [comment]
The auto-complete backend has not gotten much attention in some time. The company backend works a bit better, if that is an option for you. Or you could enable `ein:polymode` and let whatever completion backend `python-mode` is configured for on your setup do the heavy lifting.

Nevertheless I will see if I can reproduce the issue. If you are comfortable with debugging you can try instrumenting the function `ein:completer-finish-completing-ac` and `ein:completer-choose` and see what is happening in those functions, if they are being called at all.

**Comment by xorb0ss** [comment]
Thanks, I've enabled `ein:polymode` and that works fine. Any performance issues or hiccups it can cause?

**Comment by millejoh** [comment]
I have not played with it too much, but no, performance seems just fine.
