### ISSUE TITLE
curl --data-binary parameter causing 401/403 under Windows?

### ISSUE THREAD

**Issue by millejoh** [millejoh/emacs-ipython-notebook#571]
Given some of the recent issues some (myself included) have hadwith ein not working under windows in seemingly random ways (see #568 for one example) I am taking some time to document my investigations. Apparently the combination of emacs+curl+windows causes problems jupyter with token and xsrf authentication enabled. Currently on my setup (Windows 10+emacs 26.2 and most recent versions of ein and dependencies) this manifests as 403 responses to login requests, though it has also manifested as failing to start kernel sessions.

A request call to login typically looks like the following on my windows setup:

```
/ProgramData/chocolatey/bin/curl.exe --silent --include --location --compressed --cookie "c:/Users/E341194/.emacs.d/.cache/request/curl-cookie-jar" --cookie-jar "c:/Users/E341194/.emacs.d/.cache/request/curl-cookie-jar" --write-out "\n(:num-redirects %{num_redirects} :url-effective %{url_effective})" --noproxy 127.0.0.1 --trace-ascii c:/Users/E341194/AppData/Local/Temp/curl-trace --data-binary @c:/Users/E341194/AppData/Local/Temp/emacs-requestD41420 --header "X-XSRFTOKEN: 2|ef4f28b0|305ea349fe1509f3b069986e403bf5b5|1562976067" http://127.0.0.1:8888/login
```

If I login from WSL/Ubuntu to a notebook server running on the Windows side the curl call looks a bit different:

```
curl --silent --include --location --compressed --cookie /home/millejoh/.emacs.d/.cache/request/curl-cookie-jar --cookie-jar /home/millejoh/.emacs.d/.cache/request/curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --request GET --header X-XSRFTOKEN: 2|6cb9af0e|f665a1664b563ce55e909bc28c2624ff|1558204019 http://127.0.0.1:8888/api/sessions
```

Finally, if I login from WSL/Ubuntu to a notebook server running under WSL/Ubuntu the curl call looks almost the same as the corresponding Windows curl call:

```
curl --silent --include --location --compressed --cookie /home/millejoh/.emacs.d/.cache/request/curl-cookie-jar --cookie-jar /home/millejoh/.emacs.d/.cache/request/curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --data-binary @/tmp/emacs-requestrngiDy --header X-XSRFTOKEN: 2|6cb9af0e|f665a1664b563ce55e909bc28c2624ff|1558204019 http://127.0.0.1:8889/login
```

If I remove the `--data-binary` option when calling curl from inside eshell I get a 302 response, which is what we want. Per the [curl documentation](https://curl.haxx.se/docs/manpage.html#--data-binary), --data-binary just POSTs the contents of the specified file.

I wonder if the issue is due to improper encoding of the temporary file that request writes out to when passed a `:data` parameter in the call to `request`.

**Comment by dickmao** [comment]
I appeciate the value of journalling one's thoughts and reflections, but if we are serious about Windows support, the proper first step is to get appveyor going for a subset of the ecukes tests.  This I acknowledge is ~40 man-hours of work just to get a baseline WSL, never mind the additional man-hours of fine-tuning and non-WSL Windows.

Otherwise, it's all just half-measures and non-permanance.  Whatever you discover now may not be true days later.  Travis has helped us detect breaking changes to outside emacs libraries and jedi.

**Comment by millejoh** [comment]
As you wish... Check [this](https://ci.appveyor.com/project/millejoh/emacs-ipython-notebook/builds/26050247) out. Should we ever meet the first round of drinks is on me...

Note the issue I'm monologue-ing on here may not be so easily caught in Appveyor as I suspect it is being caused by 1) some weird corporate mandated network security policy, or 2) anti-virus software. Note that I tend to blame AV for any weird, unexpected behavior on Windows.

**Comment by dickmao** [comment]
Great, although we were [at this state in October](https://github.com/millejoh/emacs-ipython-notebook/pull/357#issuecomment-431633270) with the unit tests.

I find speculation about "weird corporate security" and/or what can be caught by testing unproductive until the testing is implemented.  Thanks for listening and making the effort!

**Comment by millejoh** [comment]
On Windows this issue appears to be related to not specifying a User-Agent in the header. Local testing is generating positive results. Results with CI on appveyor is less positive - login and notebooklist commands work, but something is happening when ein tries to POST a request to create a new notebook. Error presents as a JSON encoding error in the notebook server, even though JSON on the emacs/curl side looks to be well-formed. Note that I cannot recreate the error on my local setup. If I can reliably recreate I'll document in a new issue.
