### ISSUE TITLE
Trying to kill last line of cell produces error

### ISSUE THREAD

**Issue by cpaulik** [millejoh/emacs-ipython-notebook#58]
Trying to kill the last line of a cell, or the only line in a cell results in the error 
`Text is read-only: #<buffer *ein: 8888/Untitled0.ipynb*>`

**Comment by autosquid** [comment]
and jump to to head in first line of cell is not working property too  (`^` is evil mode)

**Comment by millejoh** [comment]
Note that the same error message is displayed when you try to kill beyond any text on the last line of a cell. The end effect is that nothing happens, which I think is the right behavior for the most part, though having an error message is annoying. What do you think should be correct behavior? Is there a way for emacs to determine when killing text whether the cursor is on a blank line?

At the very least getting rid of the error message would be nice. I am not entirely sure, though, how one would go about suppressing the error message. I will try to research this a bit more when I have time.

I don't use evil mode, but I will see if I can understand what is happening with the jump to head.

**Comment by cpaulik** [comment]
I think that the correct behavior is to kill the selected text if it is not read-only. 
The error message is helpful in my opinion, at least one knows then that something is wrong. If nothing happens I would be quite confused.

**Comment by autosquid** [comment]
if the last cell contains some text, the "correct" behavior is to clear its text.

**Comment by justmytwospence** [comment]
Any evil operator that "touches" the read-only parts of the buffer will fail. This includes but is not limited to:

- any line operator (`dd`, `cc`, etc) on the last line of a cell
- any paragraph operator that touches the edges of the cell (`dap`, `dip`, `cap`, `cip`, etc)
- probably lots more

Not sure if there's any way around this, it would be great if there was.

**Comment by aldanor** [comment]
Wondering if anyone has been able to solve this? It would be great if trying to kill the last would just clear it, which would probably also enable all evil operators like `dd` and `S` that currently fail.

**Comment by ileixe** [comment]
Is this issue resolved? I still have the same issue with the latest.

**Comment by sergiolib** [comment]
Same here! The issue persists. It is very unpleasant.
