### ISSUE TITLE
How to use LSP with ein

### ISSUE THREAD

**Issue by hnisonoff** [millejoh/emacs-ipython-notebook#580]
The documentation suggests the ability to use lsp with ein when ein:polymode is set to t. However, I have been unable to get any python lsp functionality. Has this been tested in anyway?

**Comment by Knowledge91** [comment]
Is there a way to use LSP with ein? I tried to follow (reddit)[https://www.reddit.com/r/emacs/comments/cotwf1/lspmode_within_emacs_ipython_notebook/], but without success.
