### ISSUE TITLE
ein:notebook-open-in-browser does not provide token

### ISSUE THREAD

**Issue by costrouc** [millejoh/emacs-ipython-notebook#584]
Possibly a PR that I would like to open. Often times I like interacting with notebooks in emacs but then I encounter a widget that I need to interact with in a browser. When I call `ein:notebook-open-in-browser` it asks for a token. Is there a way for `ein` to provide the token with the url request? If there is not a way currently I would be interested in making a PR out of this.

**Comment by millejoh** [comment]
You should take a look at functions `ein:jupyter-server-conn-info` and `ein:crib-token`. The first will work if you started jupyter from ein (i.e. by using `ein:run`), while the second should work more generally so long as you have a locally running instance of jupyter.

Making your suggestion work with remote connections will take a bit more work; you will have to store the token somewhere safe (maybe the ein:$notebooklist struct?) that you can access when needed.

**Comment by dickmao** [comment]
`ein:notebook-open-in-browser` is no longer available.  Sorry.

**Comment by OldIMP** [comment]
sad to hear that :( Any reason for that? Any recommendation for the fastest way to open the notebook in a browser? Thx!

**Comment by eeshugerman** [comment]
best way i've found is `jupyter notebook list` in shell/term/vterm and then `link-hint-open-link-at-point` (`SPC x o` in spacemacs)
