### ISSUE TITLE
Folding markdown headers?

### ISSUE THREAD

**Issue by indigoviolet** [millejoh/emacs-ipython-notebook#585]
One common pattern in Jupyter notebooks is to use markdown headers to organize sections of the notebook. It would be pretty nice to be able to use some folding in ein buffers, similar to https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/collapsible_headings/readme.html. Have you considered this?

**Comment by millejoh** [comment]
It is a good suggestion and something I had given it some thought in the past, but these days I get all that functionality - and more - using org-mode buffers and [ob-ein](http://millejoh.github.io/emacs-ipython-notebook/#org-mode-integration-ob-ein) source blocks.

As my primary use of python is data analysis I find org buffers much more amenable for generating and maintaining reports. I still use notebook buffers to quickly prototype code, which I then embed into the org buffer. Finally I can use pandoc to generate Word documents that I can easily share with the rest of my team. Org has richer markup and cross-referencing than markdown and, for me at least, has a much easier to use export system.

If you or someone else wants to submit a PR implementing folding in the notebook buffer I would be happy to accept, but this is not something I plan on working on in the near future. Just too busy with real world issues, I am afraid.

**Comment by indigoviolet** [comment]
Thank you for the explanation. I agree that org buffers are better at this and I would use ob-ein for reports that I'm the exclusive user of, but unfortunately I tend to have to collaborate with or use Jupyter notebooks from people who have not seen the light :) 

I don't believe there is a way to go back and forth between Jupyter and org/ob-ein; also, there are still some features of Jupyter that are not supported in org/ob-ein, such as widgets and interactive plots. 

I don't have enough understanding of the workings of ein or a code folding package to quickly knock this out, but will consider looking into it. Thanks again for ein!
