### ISSUE TITLE
Installation of ob-ein breaks org-mode 

### ISSUE THREAD

**Issue by smartmic** [millejoh/emacs-ipython-notebook#586]
I could successfully install and use ob-ein on Emacs 26.3 (ein-20190813.2156). But when I restart emacs and try to open an .org file, the whole file mode is broken showing this message:

    File mode specification error: (error Recursive load /usr/local/share/emacs/26.3/lisp/org/org.elc /usr/local/share/emacs/26.3/lisp/org/org-element.elc /home/martin/.emacs.d/elpa/ein-20190813.2156/ob-ein.elc /usr/local/share/emacs/26.3/lisp/org/org.elc /usr/local/share/emacs/26.3/lisp/org/org-element.elc /home/martin/.emacs.d/elpa/ein-20190813.2156/ob-ein.elc /usr/local/share/emacs/26.3/lisp/org/org.elc /usr/local/share/emacs/26.3/lisp/org/org-element.elc /home/martin/.emacs.d/elpa/ein-20190813.2156/ob-ein.elc /usr/local/share/emacs/26.3/lisp/org/org.elc /usr/local/share/emacs/26.3/lisp/org/org-element.elc /home/martin/.emacs.d/elpa/ein-20190813.2156/ob-ein.elc /usr/local/share/emacs/26.3/lisp/org/org.elc

I am using the builtin org version.

**Comment by alaskamike** [comment]
You could try rebuilding your .elc files:

Quit emacs and then run these commands:
cd /usr/local/share/emacs/
rm -r *.elc
cd ~/.emacs.d
rm -r *.elc
and then restart emacs.

**Comment by smartmic** [comment]
I deleted the *.elc files in ``/usr/local/share/emacs/26.3/lisp/`` but this did not help (or recompile) anything, instead, the recursive load error gets propagated to different resources now:

    insert-file-contents: Recursive load: "/usr/local/share/emacs/26.3/lisp/jka-compr.el.gz", "/usr/local/share/emacs/26.3/lisp/jka-compr.el.gz", "/usr/local/share/emacs/26.3/lisp/jka-compr.el.gz", "/usr/local/share/emacs/26.3/lisp/jka-compr.el.gz", "/usr/local/share/emacs/26.3/lisp/jka-compr.el.gz", "/usr/local/share/emacs/26.3/lisp/auth-source.el.gz", "/usr/local/share/emacs/26.3/lisp/url/url-parse.elc", "/usr/local/share/emacs/26.3/lisp/url/url-handlers.elc", "/usr/local/share/emacs/26.3/lisp/emacs-lisp/package.elc

**Comment by alaskamike** [comment]
Do you have a copy of ein-20190813.215?  What I would do is delete the ein
folder in your ~/.emacs.d/elpa, restart emacs (which should allow emacs to
recreate elc's from el's), and then copy the  ein-20190813.2156folder into
elpa.  I did this for ein-20190318.1601 a few months ago and that worked
for me.

**Comment by smartmic** [comment]
Well, I could not exactly follow your suggestions but fixed the issue with a complete reinstallation and cleanup of configuration. Thank you anyhow!
