### ISSUE TITLE
Images displying in a fragmented manner

### ISSUE THREAD

**Issue by coolsidd** [millejoh/emacs-ipython-notebook#587]
The images in ein don't display properly.

![Screenshot_2019-09-04_20-45-06](https://user-images.githubusercontent.com/8058854/64268213-4f3bce00-cf55-11e9-9e2f-9db148eeb9a2.png)

I am using [doom-emacs](https://github.com/hlissner/doom-emacs)

**Comment by alaskamike** [comment]
I'm noticing that your plot has multiple lines.  When I plot (in org-mode)
the plot is on a single line.

**Comment by coolsidd** [comment]
> I'm noticing that your plot has multiple lines. When I plot (in org-mode) the plot is on a single line.

You are correct, the plot spans across multiple lines, but I believe that should be the case (?).

The problem is solved if I change the plot size or fix the plot size according to dpi. But for small sizes, the error persists
```python
num_of_simulations = 100000
num_bins = 100
fig, ax = plt.subplots(1,len(num_of_convolutions), figsize=(18, 9),dpi=80)
sim = (np.random.random((np.max(num_of_convolutions), num_of_simulations))-0.5)*2
sims = []
for i in range(len(num_of_convolutions)):
    sims.append(np.sum(sim[:num_of_convolutions[i]], axis=0))
    print("Sdev for {} convs is {}".format(num_of_convolutions[i], np.std(sims[i])))
    ax[i].hist(sims[i], bins=num_bins, density=False)
    ax[i].set_title("Conv {}".format(num_of_convolutions[i]))
plt.show()
```

![Screenshot_2019-09-06_16-15-34](https://user-images.githubusercontent.com/8058854/64422576-05242b00-d0c2-11e9-914c-9d3d1c353435.png)

and this will low size
``` python
fig, ax = plt.subplots(1,len(num_of_convolutions), figsize=(18, 4),dpi=80)
```
![Screenshot_2019-09-06_16-18-39](https://user-images.githubusercontent.com/8058854/64422708-546a5b80-d0c2-11e9-8cee-6c86a688dd82.png)

Note that increasing does not cause overlap
```python
fig, ax = plt.subplots(1,2, figsize=(25, 25),dpi=50)
st_line = [(x,x) for x in range(20)]
ax[0].plot(st_line)
st_line.reverse()
ax[1].plot(st_line)
plt.show()
```
![Screenshot_2019-09-06_16-27-34](https://user-images.githubusercontent.com/8058854/64423236-a19afd00-d0c3-11e9-9414-e5244ef5635d.png)


Of course, decreasing the size of the plots makes it **worse**.

**Comment by millejoh** [comment]
It looks like you have `ein:slice-image` set to `T`. The lines should go away if you set that to 'NIL'. I dimly recalling having this issue a few years ago, but unfortunately don't recall if I discovered why it was happening.

**Comment by Jimflip** [comment]
I'm seeing the same problem.

Previously using spacemacs and ein, with ein:slice-image set to T, moved over to Doom, which has ein:slice-image set to T as default.

Same notebook/images, now render ugly.

SImply setting that value to false isn't a great solution, as when scrolling without it the experiance is janky to the point of confusion.

**Comment by Jimflip** [comment]
I've worked around it not by modifying the dpi, but rather the aspect ratio of the figsize, I've noticed a y value < 8 causes problems also.

Note this doesn't happen on all graph (or at least some seem more susceptible to it than others), for example horizontal bar graphs have lots of probs, vertical none.

**Comment by dickmao** [comment]
I was dismayed to see doom apply [an overlay](https://github.com/hlissner/doom-emacs/blob/db7a37d888ee6f4dfa3d738598d7c4a1b8026d2d/modules/tools/ein/config.el) much as spacemacs [also does](https://github.com/syl20bnr/spacemacs/blob/26b8fe0c317915b622825877eb5e5bdae88fb2b2/layers/%2Blang/ipython-notebook/packages.el).

These overlays were last meaningfully changed years ago and many changes to EIN have transpired since then.  We sadly cannot vouch for doom or spacemacs despite their popularity as they're completely off our testing radar.

**Comment by millejoh** [comment]
@coolsidd - I've tried playing with various settings of figsize and dpi, but so far I am unable to recreate the striped visual artifacts. I tried using your code, but there is something not right with it - it won't execute in the test notebook I have set up.

There might be something particular in your configuration that is causing this (or fixing it in mine). I'd take a look at the version of matplotlib you are using; I am using 3.1.1. Filling out `ein:dev-bug-report-template` would be a first step towards generating a reproducible test case.

**Comment by coolsidd** [comment]
@millejoh Sorry for the delay. Setting `ein:slice-image` to `nil` fixed the issue. There is a "FIXME" pointing to [this issue](https://github.com/tkf/emacs-ipython-notebook/issues/94) along with an "EXPERIMENTAL" tag. 
`.. FIXME: ROWS and COLS must be determined dynamically by measuring
      the size of iamge and Emacs window`

https://github.com/millejoh/emacs-ipython-notebook/blob/0c207dfac1a3adcee7592d7d28200d86b0478fb1/lisp/ein-cell.el#L152-L162

The culprit in doom is the line 16 of [this file](https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/ein/config.el#L16)
https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/ein/config.el#L10-#L17

I'll close this soon.
