### ISSUE TITLE
Recursive ‘require’ for feature ‘org’ error

### ISSUE THREAD

**Issue by kjschanney** [millejoh/emacs-ipython-notebook#588]
Hi,
I updated my Arch Linux yesterday. After the update, I am unable to add (ein . t) as org-babel-load-languages. Whenever I add (ein . t) to the list of babel languages I get the following error.

`(Spacemacs) Error in dotspacemacs/user-config: Recursive ‘require’ for feature ‘org’`

The error will go if I remove (ein . t). It was working fine before the update. 

I am using spacemacs develop branch (0.300.0@26.3) and emacs version 26.3

Any help?

**Comment by millejoh** [comment]
I can't even come close to recreating this issue based on the information you have provided, so my only suggestion is to completely delete all your installed packages (i.e. everything under `~/.emacs.d/elpa/`) and let spacemacs download and rebuild everything from scratch.
