### ISSUE TITLE
Add support for Wolfram Language / Mathematica for Jupyter

### ISSUE THREAD

**Issue by entropy43** [millejoh/emacs-ipython-notebook#589]
Wolfram has recently made a pretty cool [Jupyter integration](https://github.com/WolframResearch/WolframLanguageForJupyter) which permits a user to have a fairly full-featured interface with the Wolfram Language via Jupyter notebook.

The typical use case here is that this solution allows one to host their Wolfram / Mathematica kernels on a remote machine (ie on AWS / GCP etc) and then connect a Jupyter notebook via the usual methods instead of a "regular" Wolfram notebook. 

As this is a live feature for regular Jupyter notebooks (though not lab -- yet) it would be great to have support for WolfLang / Mathematica in EIN.

I'd love to be able to contribute to this effort but not sure where to start?

How can we get this going?

**Comment by dickmao** [comment]
I would try following directions [here](https://github.com/WolframResearch/WolframLanguageForJupyter/blob/master/README.md), then [here](https://github.com/millejoh/emacs-ipython-notebook/blob/master/README.rst).

**Comment by entropy43** [comment]
Thanks @dickmao 

I have already successfully installed the Kernel and it is already accessible (and usable) as per those links via a regular jupyter notebook:

![image](https://user-images.githubusercontent.com/25653220/65925698-354ab980-e435-11e9-9619-7339a49eb2e3.png)

It is also visible to EIN:

![image](https://user-images.githubusercontent.com/25653220/65925729-54e1e200-e435-11e9-94fe-a6d71092835d.png)

But when I try to start a new notebook, I get the error

`ein: [error] ein:ml-lang-setup: kernelspec language ’Wolfram-Language’ unsupported`

![image](https://user-images.githubusercontent.com/25653220/65925752-7216b080-e435-11e9-801d-f5ec894ef196.png)

My issue is how can we add Wolfram Language to the "quiver" of supported languages in EIN (given EIN can already see the installed Wolfram Kernel)

In terms of language support, emacs already has [wolfram-mode](https://github.com/kawabata/wolfram-mode) to assist with syntax highlighting, ac etc.

It's really just a case of how we support the kernel inside EIN. Thoughts @millejoh ? 

Also ccing Wolfram engineer @arnoudbuzing who often keeps a helpful eye on such efforts

**Comment by dickmao** [comment]
Good, now you need to turn on polymode as explained in the README.

**Comment by entropy43** [comment]
Thanks -- this permits opening a notebook

![image](https://user-images.githubusercontent.com/25653220/65926573-341b8b80-e439-11e9-9da2-7c9976ee04f8.png)

but then get this error:

`Warning (ein): pm:get-span: no major mode for kernelspec language 'Wolfram-Language`

And, irrespective of whether any input is entered, then Kernel then dies

![image](https://user-images.githubusercontent.com/25653220/65926588-4eee0000-e439-11e9-968a-355fa1e928bf.png)

**Comment by dickmao** [comment]
We're in partially charted waters at this point.  The kernel requiring reconnect looks bad.

If you haven't installed kawabata/wolfram-mode, that's required for this to work.

We've gotten julia notebooks to work under polymode without having to hardcode anything.  Wolfram may have quirks that require tweaking.  It's doable by someone like me, but could be quite painful for you.

**Comment by dickmao** [comment]
A fellow @fedeinthemix hardcoded wolfram in #545 .  I frown upon such hardcoding, but that may be the only viable route as polymode may require expert fiddling.

**Comment by entropy43** [comment]
Ok, the good news is that this "works"

![image](https://user-images.githubusercontent.com/25653220/65927543-73e47200-e43d-11e9-8cfe-a76ba7f5be9e.png)

The bad news is that it throws a language kernelspec warning every character you type:

![image](https://user-images.githubusercontent.com/25653220/65927608-b017d280-e43d-11e9-96fd-6fb105435622.png)

I'm assuming that there's probably a relatively simple fix to link `wolfram-mode` to be the major mode in this case?

I really appreciate your help on this, @dickmao !

**Comment by dickmao** [comment]
Yes, try adding this to your `.emacs` or `init.el`:
```
(add-to-list 'auto-mode-alist '("\\.Wolfram-Language$" . wolfram-mode))
```

**Comment by entropy43** [comment]
Ahh, perfect.... this works a treat:

![image](https://user-images.githubusercontent.com/25653220/65928379-14886100-e441-11e9-99f6-d1913c55e7bb.png)

Thank you so much, @dickmao ! Super helpful. I will mark this as closed for now.

**Comment by tangw** [comment]
@entropy43 Would you mind if I ask how you got the inline image shown properly in the wolfram mode?

PS: I've followed the instructions to turn on ein:output-area-inlined-images and setup mailcap-user-mime-data. I've also tried an example plot in Python and R kernel, respectively, and they both worked.
