### ISSUE TITLE
No Syntax highlighting 

### ISSUE THREAD

**Issue by tbrodbeck** [millejoh/emacs-ipython-notebook#599]
I installed ein once in spacemacs and in doom emacs. (I am a emacs newbie and did not understand how to install it in default emacs yet). In both emacs configurations there is simply no Syntax highlighting inside a python cell, the text is just pure white. (numbers are orange in doom emacs though)

The highlighting in default python files works. 

Even though I did not want to use emacs unconfigured, I can try again to install ein on stock emacs, then I will update this post.

**Comment by millejoh** [comment]
EIN is not well tested in the doom and spacemacs environments. I use spacemacs, but not the ipython-notebook layer. Instead I install a local copy of ein from github and set up my environment by running `cask emacs`. I think a few others have had success getting spacemacs+ein to work; you might want to search through all opened and closed issues for references to spacemacs.

The installation instructions in the README should be enough to get you going in a vanilla emacs installation.

I would also try enabling `ein:polymode` and restarting emacs. Again, there are some useful pointers spread about this project's opened and closed issues if you run into any problems.
