### ISSUE TITLE
Setting `case-fold-search` to `nil` breaks ein.

### ISSUE THREAD

**Issue by gahag** [millejoh/emacs-ipython-notebook#600]
How to reproduce:
- `(setq case-fold-search nil)`
- Try to open any notebook.

Error message:
> ein: [info] WS action [(websocket-invalid-header Incorrect handshake from websocket: is this really a websocket connection?)] on-open

**Comment by millejoh** [comment]
Definitely reproducible. The break seems to be occurring in `websocket-verify-headers` in the websocket package. I'll ping that package maintainer and in the meantime I'll see if I can devise a temporary workaround.

**Comment by gahag** [comment]
Thanks a lot for working on this! EIN is great by the way, thanks for the awesome work.
