### ISSUE TITLE
Command jupyter not found or not executable

### ISSUE THREAD

**Issue by tbouiller** [millejoh/emacs-ipython-notebook#601]
I installed ein via MELPA and averything worked fine, but then I closed emacs and when I reoppened it next time and tried to run ein by doing M-x `run:ein` I get this error message : 
 `Command jupyter not found or not executable`
It's pretty weird because everything was working fine just before and I cannot find any similar issues.
The debugger outputs this but I don't get what's not working
`Debugger entered--entering a function:
* ein:run(nil "~/.emacs.d/elpa/ein-20191012.1337/" nil #f(compiled-function (buffer url-or-port) #<bytecode 0x17d66d9>))
  funcall-interactively(ein:run nil "~/.emacs.d/elpa/ein-20191012.1337/" nil #f(compiled-function (buffer url-or-port) #<bytecode 0x17d66d9>))
  call-interactively(ein:run record nil)
  command-execute(ein:run record)
  execute-extended-command(nil "ein:run" "ein:run")
  funcall-interactively(execute-extended-command nil "ein:run" "ein:run")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
  recursive-edit()
  debug()
  funcall-interactively(debug)
  call-interactively(debug record nil)
  command-execute(debug record)
  execute-extended-command(nil "debug" "debug")
  funcall-interactively(execute-extended-command nil "debug" "debug")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
`

**Comment by entropy43** [comment]
Not to be facetious but I’m assuming you have installed Jupyter already and
you’re able to open a notebook in your browser? (ie `$ jupyter notebook`
from your terminal).

Can you see if you can try the indirect method of opening a notebook in
your browser (per the command line instruction above) and then see if you
can get things running in emacs with:

`M-x ein:notebooklist-login`

This will then prompt you to specify the port your Jupyter notebook is
running on (should be 8888 by default) and, depending on platform and
version, then perhaps ask you for the key / password.

**Comment by tbouiller** [comment]
Ah yes I should have metionned it but jupyter notebook does run normally in the browser, but I tried what you said and it does work by running a notebook beforehand and loging in into emacs. It's just a bummer that I cannot launch one directly in emacs

**Comment by millejoh** [comment]
This behavior is [mostly](http://millejoh.github.io/emacs-ipython-notebook/#running-a-jupyter-notebook-server-from-emacs) described in the documentation. The variable you want to look at is [`ein:jupyter-default-server-command`](http://millejoh.github.io/emacs-ipython-notebook/#ein:jupyter-default-server-command).

I suggest you set that variable to the absolute path to your jupyter executable (explicit is better than implicit).

**Comment by tbouiller** [comment]
So i've tried setting different variables for `ein:jupyter-default-server-command`,  and omitting  `ein:jupyter-server-use-subcommand` but it seems that whatever I throw in, the command does not get recognised, which is troubling because it was working at some point.

**Comment by millejoh** [comment]
What happens if you try to call `jupyter notebook` from inside `ansi-term` (or other equivalent)? Other places to look for clues would be the `*ein:log-all*` and `*ein:jupyter-server*` buffers.
