### ISSUE TITLE
Sudden change in appearance: only text is highlighted

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#602]
I updated ein using elpa this morning and now the notebooks look like this:
![image](https://user-images.githubusercontent.com/1596894/66942072-3b848c80-f016-11e9-9b0b-d4fe67b8f9ba.png)
before the whole lines if the `in` cells had colored background, now only code text does.

is this change documented anywhere?

**Comment by millejoh** [comment]
I don't see any changes to the default faces in any recent commits. They aren't documented in any great detail anywhere, but there are a number of customizable variables for cell appearance. You can find those by a call to `M-x customize-apropos RET ein:cell RET`.

**Comment by xor-xor** [comment]
Not sure if related, but I had something similar after `(setq ein:polymode t)` (and restarting Emacs, which is required for this setting) - i.e. `In[]` and `Out[]` widgets - not the actual cells - lost their usual background/highlight in a freshly opened notebook, but it came back after executing their respective cells. That was on `v0.16.1`, if I remember correctly - haven't checked this with the higher versions yet.
