### ISSUE TITLE
problem with running `cask exec ecukes`

### ISSUE THREAD

**Issue by xor-xor** [millejoh/emacs-ipython-notebook#604]
Hi,

I was trying to catch up with recent developments of EIN, so as a first step, I tried to run tests on the current master. `make dist` and `make quick` passed fine, but I've got this error on the second part of `make test-int` (`cask exec ecukes --reporter magnars`) - the output shown below is with `--debug` added:
```
debug-on-error=t websocket-debug=t websocket-callback-debug-on-error=t ein:debug=t ein:log-level=debug ein:log-message-level=verbose
  signal(json-readtable-error ...)
  json-read()
  json-read-from-string("/bin/bash: jupyter: command not found\n")
  (let ...)
  (alist-get ...)
  (let* ...)
  (setq ...)
  (lambda ...)()
  funcall(...)
  -each(... ...)
  ecukes-hooks-run(...)
  ecukes-hooks-run-setup()
  ecukes-run(...)
  (let ...)
  ecukes-cli/run("features")
  apply(ecukes-cli/run ...)
  commander--handle-command(nil)
  commander-parse(...)
  (if ...)
  eval-buffer(#<buffer  *load*> ...)
  load-with-code-conversion(#1="/Users/xor-xor/code/_other/emacs-ipython-notebook/.cask/26.3/elpa/ecukes-20190822.2127/ecukes-cli.el" ...)
  load("/Users/xor-xor/code/_other/emacs-ipython-notebook/.cask/26.3/elpa/ecukes-20190822.2127/ecukes-cli.el" ...)
  command-line-1(...)
  command-line()
  normal-top-level()
JSON readtable error: 47
```
I'm not quite sure what is the problem here - is it `jupyter: command not found`, or `JSON readtable error: 47`, or something else? I know about `JUPYTER_TESTING_COMMAND` env var, but it seems that ecukes doesn't (?) rely on it.

**Comment by millejoh** [comment]
It's the jupyter note found, most likely. What happens if you try to execute `jupyter notebook` from the command line you are running `cask exec ecukes` from? The tests work best if `jupyter` is in your executable path.

Also you will want to install R and Julia, otherwise some of the ecukes tests will fail

**Comment by xor-xor** [comment]
Yep, that was it. Thanks!
