### ISSUE TITLE
ein fails to connect to an ssh portforwarded server

### ISSUE THREAD

**Issue by dov** [millejoh/emacs-ipython-notebook#61]
## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have

When connecting to a remote server by ssh and portforwarding of the ipython port, the ipython server refuses to accept commands as it complains of `WARNING | Blocking Cross Origin WebSocket Attempt.  Origin: grower, Host: 127.0.0.1`. 

## Steps to reproduce the problem

1. Start ipython on a remote server with `ipython notebook --no-browser`
2. ssh to the remote server with local port forwarding `ssh -L8888:localhost:8888`
3. Open ein and connect to `localhost:8888`
4. Open a notebook or create a new notebook

## Expected output

ein should connect to a kernel.

Note that in contrast connecting through filefox to `localhost:8888` works as expected.

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):

2.3.1

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):

ipython notebook --no-browser --port 8888

3. What is your IPython notebook port number or URL?:

localhost:8888

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.5.1 (i686-redhat-linux-gnu, GTK+ Version 3.16.2)
 of 2015-04-22 on buildhw-10.phx2.fedoraproject.org"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux grower 4.0.5-300.fc22.i686+PAE #1 SMP Mon Jun 8 16:37:42 UTC 2015 i686 i686 i386 GNU/Linux
"
  :lsb-release
  "LSB Version:	:core-4.1-ia32:core-4.1-noarch:cxx-4.1-ia32:cxx-4.1-noarch:desktop-4.1-ia32:desktop-4.1-noarch:languages-4.1-ia32:languages-4.1-noarch:printing-4.1-ia32:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 22 (Twenty Two)
Release:	22
Codename:	TwentyTwo
")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.3"
           :source-dir "/home/dov/git/dov-env/emacs/ein/lisp/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/el-get/websocket/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.1")
  (:name "request"
         :path "~/.emacs.d/el-get/request/request.elc"
         :featurep t
         :version-var request-version
         :version "0.2.0")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-1.4/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "mumamo"
         :path "~/.emacs.d/el-get/nxhtml/util/mumamo.elc"
         :featurep t
         :version-var mumamo:version
         :version "0.91")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-1.4/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/elpa/popup-0.5/popup.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "fuzzy"
         :path "~/.emacs.d/elpa/fuzzy-0.1/fuzzy.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "python"
         :path "/usr/share/emacs/24.5/lisp/progmodes/python.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "python-mode"
         :path "~/git/dov-env/emacs/python-mode.el"
         :featurep t
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path "~/.emacs.d/el-get/markdown-mode/markdown-mode.elc"
         :featurep t
         :version-var markdown-mode-version
         :version "1.8.1")))
```

**Comment by millejoh** [comment]
Do you know what version of Tornado the remote ipython is using? Version prior to 4.0 had issues with EIN. Also can you try updating emacs-websocket to 1.3?

**Comment by dov** [comment]
Thanks! Updating websocket to 1.3 or 1.4 indeed solved the problem! Closing the bug.
