### ISSUE TITLE
Modify default output width in notebook buffer

### ISSUE THREAD

**Issue by vale46** [millejoh/emacs-ipython-notebook#610]
The width for displayed **output** in a notebook buffer is set to 80 characters. How do I override/customize this default to display wider text/tables without the forced line break and wrapping?

Setting ein:truncate-lines-on impacts only the **input** lines in a notebook buffer.

Running Emacs 26.1 on W10 box.

**Comment by millejoh** [comment]
I will need to see the code that is triggering this behavior on your system as I am not seeing this on my setup.

```python
s = '.'*120
print(s)
```

Results in a single line of output of 120 .'s long. For the most part, printing cell output devolves into calls to `insert` without any fill-text-like calls. Multiple lines of output can be truncated via the variable `ein:truncate-long-cell-output`, but this code also does not do any text filling.

On the Python side there is the config variable [`PlainTextFormatter.max_width`](https://ipython.readthedocs.io/en/stable/config/options/terminal.html#configtrait-PlainTextFormatter.max_width). You might play with that and see if it results in different output.

**Comment by vale46** [comment]
Tried your suggestion, which prints the width of the emacs  frame and wraps if needed. My issue is likely related to Python as you mentioned. In my case, it happens when I print a pandas dataframe which is more than 80 characters wide causing last 2 columns to wrap. Here's a simple example

`import pandas as pd
mpg = pd.read_html("https://alliance.seas.upenn.edu/~cis520/wiki/index.php?n=Lectures.DecisionTrees", header=0)[0]
print(mpg)`

**Comment by vale46** [comment]
Setting [pandas.set_option('expand_frame_repr', False)](https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html) fixes the dataframe output wrapping. Thanks for your tips in helping get to my solution.
