### ISSUE TITLE
plots not working, inline or otherwise

### ISSUE THREAD

**Issue by notuntoward** [millejoh/emacs-ipython-notebook#615]
I'm able to start ein with `ein:run`, and in the resulting notebook, I can examine variable contents and see the result of python print().  

But I can't see plots.  For example,  the result of typing `C-c C-c` in:

```
In [1]:
#%matplotlib inline
import numpy as np
from matplotlib import pyplot as plt
plt.plot(np.arange(10), np.arange(10))
#plt.show()
```

is that I get the output:

```
Out [1]:
[<matplotlib.lines.Line2D at 0x2076a60be10>]
```
but no plot is displayed, either in a popup window, a browser tab, or inline.  If I try to force it to display or be inline, by uncommenting any combination of the commented lines in the input cell above, I still don't see a plot.

There were no error messages when running the cells above, nor during the installation of ein with the lines:

```
(use-package ein
  :ensure t
  :commands (ein:notebooklist-open))
```

This is on Windows 10, emacs 26.2, the latest emacs packages from melpa, and the latest python packages from Anaconda.

How can I debug this?

**Comment by yatsky** [comment]
I can run your code without a problem. Did you set up EIN correctly?
Do you have the following in your .emacs.d?
```
(require 'ein)
(require 'ein-notebook)
(require 'ein-subpackages)
```

**Comment by millejoh** [comment]
My first thought is that your emacs isn't configured to display the image types that jupyter is returning (this was surprisingly common with emacs builds for Windows at one point). Can you send the output of calling `M-x ein:dev-bug-report-template`?

**Comment by notuntoward** [comment]
Thanks for the responses.

@yatsky, I wasn't using the require statements because I'm initializing it with use-package.  However, just to be sure, I added the require statements: the plot still doesn't appear.

@millejoh, bug template report attached...

[eindevbug.txt](https://github.com/millejoh/emacs-ipython-notebook/files/3837660/eindevbug.txt)

**Comment by millejoh** [comment]
You definitely won't see inline plots if you don't first call `%matplotlib inline`, but I cannot reproduce your problem. The README and CONTRIBUTING documents have some basic instructions on how to debug ein. Start with a call to `ein:dev-start-debug` before you start or connect to a jupyter server then check the various logs via `ein:log-pop-to-{X}` where X is one of `all-buffer` or `request-buffer` and also via `ein:pop-to-debug-channels` to debug the websocket connection.

**Comment by notuntoward** [comment]
I looked at the two logs and the pop-to- channel but didn't see anything I could identify as a problem.  However, sometime when running these things, I saw the following message in the terminal where I started emacs:

`request--curl-sync: semaphore never called`

Is that suspicious to anyone?

**Comment by notuntoward** [comment]
It turns out that adding `highlight-indent-guides-mode` or `outline-minor-mode` to `prog-mode-hook` breaks EIN inline image display (see code at end).  I'd like to keep these two useful minor modes so the best thing would be if EIN just worked with them.  But otherwise, could you suggest how I can suppress them just for EIN?

And one other thing:  When I start juputer notebook or jupyter lab, I don't have to type a password (I followed the instructions in the jupyter docs in order to prevent this).  But in EIN, I have to type a password every time.  Can I prevent that?

The lines in .emacs file that break EIN inline images:

```
(use-package outshine
  :diminish outline-mode
  :diminish outline-minor-mode
  :config
  (add-hook 'outline-minor-mode-hook 'outshine-mode)
  (add-hook 'prog-mode-hook 'outline-minor-mode)
  (bind-keys
   :map outline-minor-mode-map
   ("<backtab>" . outshine-cycle-buffer)))
  
(use-package highlight-indent-guides
  :config
  (add-hook 'prog-mode-hook 'highlight-indent-guides-mode)
  (setq highlight-indent-guides-method 'character))
```

**Comment by notuntoward** [comment]
Update:  If do `(setq ein:polymode t)` before `ein:run`, then neither `outshine-minor-mode` nor `highlight-indent-guides-mode` break inline plots. I don't quite understand why but it works.

I'll leave this open in case you're interested in documenting this somehow.

**Comment by dickmao** [comment]
`ein:polymode` is now default `t`.
