### ISSUE TITLE
Blocking call to accept-process-output with quit inhibited!! when trying to start a new notebook

### ISSUE THREAD

**Issue by prayner** [millejoh/emacs-ipython-notebook#62]
This is with emacs 24.4.50 and ipython
ipython 3.2.0
with ein-20150704.650  on a fedora 20 x86_64 system.

ein:notebooklist-open works fine to bring up
IPython 2 Notebook list

 | [Home] |

[New Notebook] [Reload List] [Open In Browser]
Followed by a stack of directories.

Clicking on the new notebook link (with the return key rather than
mouse if that matters) yields the following in the *messages* buffer:
ein: [info] Creating a new notebook at ...
ein: [info] New notebook. Port: 8888, Path: 
ein: [info] Creating a new notebook ()... Done.
ein: [info] Opening notebook untitled4/untitled4...
ein: [error] Content list call http://127.0.0.1:8888/api/notebooks/untitled4%2Funtitled4 failed with status error.
Blocking call to accept-process-output with quit inhibited!! [2 times]
ein: [info] Opened notebook list at 8888 with path 

Using ein:junk-open
produces pretty much the same thing.

**Comment by millejoh** [comment]
I notice that you are running ipython 3.2.0, but the notebooklist is saying IPython 2. Try one (or both) of the following:

 1. Call `ein:force-ipython-version-check`
 2. Restart emacs.

Let me know if that does anything for you.

**Comment by prayner** [comment]
Both of those worked. That's probably a useful tip to add to the
installation documentation.
thanks again
Peter

-- 
Peter Rayner
Leader, Clean Air and Urban Landscapes NESP hub.
room 343 
School of Earth Sciences, University of Melbourne, 3010, Vic, Australia
tel: work: +61 (0)3 8344 9708; fax: +61 (0)3 8344 7761 
mobile +61 402 752 379, skype: petermorag 
mail-to: prayner@unimelb.edu.au
google scholar profile <http://scholar.google.com.au/citations?user=H3up71wAAAAJ&hl=en>
