### ISSUE TITLE
How to provide `ein:jupyter-server-start` with another URL to use for connect/login than the one the `jupyter notebook` command outputs

### ISSUE THREAD

**Issue by halloleo** [millejoh/emacs-ipython-notebook#621]
I have configured Jupyter on my machine with teh name  `jupnode` to be accessible from other machines (e.g. I set `c.NotebookApp.ip = '0.0.0.0'`). Therefore `jupyter notebook` outputs on start-up the full local domain of the server (e.g.:

    [I 12:28:21.656 NotebookApp] http://jupnode.local:8989/

However for some network/DNS reasons (which I cannot change) http://jupnode.local is on `jupnode` itself  not accessible, only `http://localhost` and `127.0.0.1` work.

So my question is: How can I configure `ein:jupyter-server-start` (running in Emacs on `jupnode`) to start Jupyter but not to parse out the URL from the command output, but use `127.0.0.1:8989` instead?

**Comment by millejoh** [comment]
You can call `ein:login` and then manually specify the host - you may need to manually enter the security token, however.

**Comment by halloleo** [comment]
True, but then I cannot use EIN's facility to start up the server.

**Comment by millejoh** [comment]
Good point. Took some digging to find, but can you try setting the [`--NotebookApp.custom_display_url`](https://jupyter-notebook.readthedocs.io/en/stable/config.html)  parameter in your call to `ein:run`? The relevant elisp variable is `ein:jupter-server-args`.
