### ISSUE TITLE
Can't undo any changes even after (setq with ein:worksheet-enable-undo t)

### ISSUE THREAD

**Issue by halloleo** [millejoh/emacs-ipython-notebook#626]
When I open a notebook in EIN I cannot undo anything in the cells. Instead I get the error message

    user-error: No undo information in this buffer

I have seen #338; that;s why I add the following:

(**A**) In the `*Warnings*` buffer I get `Warning (ein): Disabling undo for set-mark-command`.

(**B**)  I tried to set explicitly `(setq ein:worksheet-enable-undo t)`, closed the notebook, restarted the server, reopened the notebook and added a new cell wit new content, but no avail: On `M-x undo` I still get `user-error: No undo information in this buffer`.

(**C**) I tried to switch the cell type to markdown, but that doesn't make any difference to the undo behaviour.

What can I do?

**Comment by millejoh** [comment]
Sorry, it is going to be difficult to help without a reliable way of recreating this problem. I suggest you start with a vanilla configuration (i.e. no custom code except for whatever is needed to load ein) and see if the problem persists. Then start incrementally introducing parts of your custom configuration and see where things start to break.

**Comment by vale981** [comment]
I have the same odd problem. It always crops up after `C-k`ing the last line in a cell.

**Comment by dickmao** [comment]
Please follow `M-x ein:dev-bug-report-template`
