### ISSUE TITLE
emacs freezes when calling ein:worksheet-toggle-slide-type in combination with markdown cell type

### ISSUE THREAD

**Issue by P-Takenaka** [millejoh/emacs-ipython-notebook#629]
As described in the title. Emacs freezes after calling ein:worksheet-toggle-slide-type while the cell has type markdown.

EIN version: 0.16.2.2
Emacs version: 26.3

**Comment by dickmao** [comment]
`ein:worksheet-toggle-slide-type` is no longer available (and thus won't cause you the freeze).
