### ISSUE TITLE
"[info] WS action" messages spamming when running notebook in the background

### ISSUE THREAD

**Issue by veprbl** [millejoh/emacs-ipython-notebook#630]
Following messages appear when I switch away from a notebook that is running and producing output:
```
ein: [info] WS action [(error ein:worksheet--unshift-undo-list 1886 != 1896)] on-message (ws://127.0.0.1:8888/api/kernels/########-####-####-####-############/channels?session_id=#########-#####-####-#####-############)
```
This is distracting. I also remember that in older versions of ein it used to trigger the bug, the one when undo used to stop working randomly.

### Steps to reproduce:
1. Run jupyter-notebook (python 3.7)
2. Start emacs with ein (I move ~/.emacs.d away to not include my configuration)
3. M-x ein:notebooklist-login, http://127.0.0.1:8888, paste the key
4. Open new notebook, add a cell with the following code:
```python
while True:
    print(1)
```
5. Execute (C-c C-c), observe "1"s appearing in the output
6. Switch to a different buffer. Since we want to see the error, let's switch to `*Messages*`
7. Wait few minutes without touching anything
8. Messages start popping up

### System:
* GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.12)
* Should work with any version of ein, I had this issue with ein from melpa for over year now. I can reproduce the issue on the current master (7f66b95a733e28aa400ea6116bdc4fd330e1a45f)

**Comment by veprbl** [comment]
On my real work configuration with real notebooks I get a slightly different message:
```
ein: [info] WS action [(wrong-type-argument sequencep t)] on-message (ws://127.0.0.1:8888/api/kernels/########-####-####-####-############/channels?session_id=########-####-####-####-############)
```
From emacs I use ido-mode, TRAMP plus some minor extensions like multiple cursors, some syntax highlighting not relevant to python.

**Comment by millejoh** [comment]
Thank you for this. The error is very repeatable, though maybe a bit difficult to understand. I've jiggered the code which seems to have made this go away. The only question now is if I have broken everything else in the process...
