### ISSUE TITLE
Error (ein): Undo failure diagnostic

### ISSUE THREAD

**Issue by bvborisov** [millejoh/emacs-ipython-notebook#631]
Hi,

I installed the latest release of ein: `20191201.1831` and I get the following error when I try `C-_` i.e. undo:

```
Error (ein): Undo failure diagnostic (nil (1282 . 1283) nil (1270 . 1282) nil (1269 . 1270) nil (1248 . 1269) nil (10 . 1238) (t . 0)) (8450f 8450f 8450f) | 8
```

I can provide more information if this is not enough.

Thanks,
Bilyan

**Comment by millejoh** [comment]
I am going to guess that you use undo-tree? EIN has known issues with that pacakage - unfortunately it has been very difficult to develop a repeatable test case that generates the issue. If you can get the error to reliably occur please post it here. Thanks.

**Comment by dickmao** [comment]
Please follow `M-x ein:dev-bug-report-template`
