### ISSUE TITLE
Error when I want to save the notebook

### ISSUE THREAD

**Issue by linwaytin** [millejoh/emacs-ipython-notebook#632]
Hi,

Every save-related command gives me this:

```elisp
ein:notebook-enable-autosaves: Wrong type argument: ein:$notebook, nil
```
and I cannot save notebooks.

Does anyone have similar issue?

**Comment by millejoh** [comment]
I, unfortunately, am not seeing this. Well, unfortunate in that that means I have no idea why you are having this issue and I am not.

Posting the results of calling `M-x ein:dev-bug-report-template` would be a start in tracking this down. The next step would be to call `M-x ein:dev-start-debug` before you start up a jupyter server and open a notebook, then look at the contents of the `*ein:log-all*` buffer.
