### ISSUE TITLE
ihaskell_emacs_error: kernel spec haskell not supported

### ISSUE THREAD

**Issue by zeta-00** [millejoh/emacs-ipython-notebook#636]
normally ihaskell works with ein(emacs ipython notebook) in emacs,
but for some reason now when i run ein i got get this error message:
kernel spec, haskell not supported? why is this and how to i fix this?

Debugger entered--Lisp error: (error "ein:notebook-open--callback: notebook instantiation failed")
  signal(error ("ein:notebook-open--callback: notebook instantiation failed"))
  error("ein:notebook-open--callback: notebook instantiation failed")
  ein:notebook-open--callback(#s(ein:$notebook :url-or-port "http://127.0.0.1:8888" :notebook-id nil :notebook-path "Untitled63.ipynb" :kernel #s(ein:$kernel :url-or-port "http://127.0.0.1:8888" :path "Untitled63.ipynb" :kernelspec #s(ein:$kernelspec :name "haskell" :display-name "Haskell" :resources (:kernel\.js "/kernelspecs/haskell/kernel.js" :logo-64x64 "/kernelspecs/haskell/logo-64x64.svg") :spec (:argv ("/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/bin/ihaskell" "kernel" "{connection_file}" "--ghclib" "/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/lib/ghc-8.6.5" "+RTS" "-M3g" "-N2" "-RTS") :env nil :display_name "Haskell" :language "haskell" :interrupt_mode "signal" :metadata nil) :language "haskell") :events #<ein:events ein:events> :api-version 5 :session-id "42a7b244-c4e7-4127-91df-b7dec4d3c970" :kernel-id nil :shell-channel nil :iopub-channel nil :websocket nil :base-url "/api/kernels" :kernel-url nil :ws-url nil :stdin-activep nil :username "username" :msg-callbacks #<hash-table equal 0/65 0x11ef5c9> :oinfo-cache #<hash-table equal 0/65 0x123b895> :after-start-hook ((ein:pytools-load-safely . #2)) :after-execute-hook nil) :kernelinfo nil :kernelspec #s(ein:$kernelspec :name "haskell" :display-name "Haskell" :resources (:kernel\.js "/kernelspecs/haskell/kernel.js" :logo-64x64 "/kernelspecs/haskell/logo-64x64.svg") :spec (:argv ("/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/bin/ihaskell" "kernel" "{connection_file}" "--ghclib" "/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/lib/ghc-8.6.5" "+RTS" "-M3g" "-N2" "-RTS") :env nil :display_name "Haskell" :language "haskell" :interrupt_mode "signal" :metadata nil) :language "haskell") :pager "*ein:pager http://127.0.0.1:8888/Untitled63.ipynb*" :dirty nil :metadata nil :notebook-name "Untitled63.ipynb" :nbformat 4 :nbformat-minor 2 :events #<ein:events ein:events> :worksheets (#<ein:worksheet ein:worksheet>) :scratchsheets nil :api-version 5 :autosave-timer nil :checkpoints nil :q-checkpoints nil) #f(compiled-function (&rest args2) #<bytecode 0x12a2661>) t #s(ein:$content :url-or-port "http://127.0.0.1:8888" :notebook-version 5 :name "Untitled63.ipynb" :path "Untitled63.ipynb" :type "notebook" :writable t :created "2019-12-11T16:16:44.775535Z" :last-modified "2019-12-11T16:16:44.775535Z" :mimetype nil :raw-content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :session-p nil :checkpoints nil))
  apply(ein:notebook-open--callback (#s(ein:$notebook :url-or-port "http://127.0.0.1:8888" :notebook-id nil :notebook-path "Untitled63.ipynb" :kernel #s(ein:$kernel :url-or-port "http://127.0.0.1:8888" :path "Untitled63.ipynb" :kernelspec #s(ein:$kernelspec :name "haskell" :display-name "Haskell" :resources (:kernel\.js "/kernelspecs/haskell/kernel.js" :logo-64x64 "/kernelspecs/haskell/logo-64x64.svg") :spec (:argv ("/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/bin/ihaskell" "kernel" "{connection_file}" "--ghclib" "/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/lib/ghc-8.6.5" "+RTS" "-M3g" "-N2" "-RTS") :env nil :display_name "Haskell" :language "haskell" :interrupt_mode "signal" :metadata nil) :language "haskell") :events #<ein:events ein:events> :api-version 5 :session-id "42a7b244-c4e7-4127-91df-b7dec4d3c970" :kernel-id nil :shell-channel nil :iopub-channel nil :websocket nil :base-url "/api/kernels" :kernel-url nil :ws-url nil :stdin-activep nil :username "username" :msg-callbacks #<hash-table equal 0/65 0x11ef5c9> :oinfo-cache #<hash-table equal 0/65 0x123b895> :after-start-hook ((ein:pytools-load-safely . #4)) :after-execute-hook nil) :kernelinfo nil :kernelspec #s(ein:$kernelspec :name "haskell" :display-name "Haskell" :resources (:kernel\.js "/kernelspecs/haskell/kernel.js" :logo-64x64 "/kernelspecs/haskell/logo-64x64.svg") :spec (:argv ("/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/bin/ihaskell" "kernel" "{connection_file}" "--ghclib" "/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/lib/ghc-8.6.5" "+RTS" "-M3g" "-N2" "-RTS") :env nil :display_name "Haskell" :language "haskell" :interrupt_mode "signal" :metadata nil) :language "haskell") :pager "*ein:pager http://127.0.0.1:8888/Untitled63.ipynb*" :dirty nil :metadata nil :notebook-name "Untitled63.ipynb" :nbformat 4 :nbformat-minor 2 :events #<ein:events ein:events> :worksheets (#<ein:worksheet ein:worksheet>) :scratchsheets nil :api-version 5 :autosave-timer nil :checkpoints nil :q-checkpoints nil) #f(compiled-function (&rest args2) #<bytecode 0x12a2661>) t #s(ein:$content :url-or-port "http://127.0.0.1:8888" :notebook-version 5 :name "Untitled63.ipynb" :path "Untitled63.ipynb" :type "notebook" :writable t :created "2019-12-11T16:16:44.775535Z" :last-modified "2019-12-11T16:16:44.775535Z" :mimetype nil :raw-content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :session-p nil :checkpoints nil)))
  #f(compiled-function (&rest args2) #<bytecode 0x1230f69>)(#s(ein:$content :url-or-port "http://127.0.0.1:8888" :notebook-version 5 :name "Untitled63.ipynb" :path "Untitled63.ipynb" :type "notebook" :writable t :created "2019-12-11T16:16:44.775535Z" :last-modified "2019-12-11T16:16:44.775535Z" :mimetype nil :raw-content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :session-p nil :checkpoints nil))
  ein:content-query-contents--success("http://127.0.0.1:8888" "Untitled63.ipynb" #f(compiled-function (&rest args2) #<bytecode 0x1230f69>) :data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x11f392d>) :success #f(compiled-function (&rest args2) #<bytecode 0x11f394d>) :error #f(compiled-function (&rest args2) #<bytecode 0x11f396d>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :response #11) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Wed, 11 Dec 2019 16:16:44 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Wed, 11 Dec 2019 16:16:44 GMT\nEtag: \"cc51b31fb711b9c9c493ff0ae3991ec86bf25aa0\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil))
  apply(ein:content-query-contents--success ("http://127.0.0.1:8888" "Untitled63.ipynb" #f(compiled-function (&rest args2) #<bytecode 0x1230f69>) :data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x11f392d>) :success #f(compiled-function (&rest args2) #<bytecode 0x11f394d>) :error #f(compiled-function (&rest args2) #<bytecode 0x11f396d>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :response #13) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Wed, 11 Dec 2019 16:16:44 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Wed, 11 Dec 2019 16:16:44 GMT\nEtag: \"cc51b31fb711b9c9c493ff0ae3991ec86bf25aa0\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil)))
  #f(compiled-function (&rest args2) #<bytecode 0x11f394d>)(:data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x11f392d>) :success #f(compiled-function (&rest args2) #<bytecode 0x11f394d>) :error #f(compiled-function (&rest args2) #<bytecode 0x11f396d>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :response #8) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Wed, 11 Dec 2019 16:16:44 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Wed, 11 Dec 2019 16:16:44 GMT\nEtag: \"cc51b31fb711b9c9c493ff0ae3991ec86bf25aa0\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil))
  apply(#f(compiled-function (&rest args2) #<bytecode 0x11f394d>) (:data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x11f392d>) :success #f(compiled-function (&rest args2) #<bytecode 0x11f394d>) :error #f(compiled-function (&rest args2) #<bytecode 0x11f396d>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :response #10) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Wed, 11 Dec 2019 16:16:44 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Wed, 11 Dec 2019 16:16:44 GMT\nEtag: \"cc51b31fb711b9c9c493ff0ae3991ec86bf25aa0\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil)))
  apply(apply #f(compiled-function (&rest args2) #<bytecode 0x11f394d>) (:data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x11f392d>) :success #f(compiled-function (&rest args2) #<bytecode 0x11f394d>) :error #f(compiled-function (&rest args2) #<bytecode 0x11f396d>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :response #11) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Wed, 11 Dec 2019 16:16:44 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Wed, 11 Dec 2019 16:16:44 GMT\nEtag: \"cc51b31fb711b9c9c493ff0ae3991ec86bf25aa0\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil)))
  request--safe-apply(#f(compiled-function (&rest args2) #<bytecode 0x11f394d>) (:data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x11f392d>) :success #f(compiled-function (&rest args2) #<bytecode 0x11f394d>) :error #f(compiled-function (&rest args2) #<bytecode 0x11f396d>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :response #10) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Wed, 11 Dec 2019 16:16:44 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Wed, 11 Dec 2019 16:16:44 GMT\nEtag: \"cc51b31fb711b9c9c493ff0ae3991ec86bf25aa0\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil)))
  request--callback(#<killed buffer> :type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x11f392d>) :success #f(compiled-function (&rest args2) #<bytecode 0x11f394d>) :error #f(compiled-function (&rest args2) #<bytecode 0x11f396d>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :response #s(request-response :status-code 200 :history nil :data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x11f392d>) :success #f(compiled-function (&rest args2) #<bytecode 0x11f394d>) :error #f(compiled-function (&rest args2) #<bytecode 0x11f396d>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :response #23) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Wed, 11 Dec 2019 16:16:44 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Wed, 11 Dec 2019 16:16:44 GMT\nEtag: \"cc51b31fb711b9c9c493ff0ae3991ec86bf25aa0\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil))
  apply(request--callback #<killed buffer> (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x11f392d>) :success #f(compiled-function (&rest args2) #<bytecode 0x11f394d>) :error #f(compiled-function (&rest args2) #<bytecode 0x11f396d>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :response #s(request-response :status-code 200 :history nil :data (:name "Untitled63.ipynb" :path "Untitled63.ipynb" :last_modified "2019-12-11T16:16:44.775535Z" :created "2019-12-11T16:16:44.775535Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled63.ipynb" :done-p nil :settings #3 :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Wed, 11 Dec 2019 16:16:44 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Wed, 11 Dec 2019 16:16:44 GMT\nEtag: \"cc51b31fb711b9c9c493ff0ae3991ec86bf25aa0\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil)))
  request--curl-callback(#<process request curl> "finished\n")

**Comment by millejoh** [comment]
The traceback isn't being too useful here, I am afraid. You might try reinstalling ein, or calling `M-x ein:byte-compile-ein` followed by `M-X ein:dev-reload`. If neither of those commands are available then you need to evaluate `(require 'ein-dev)`.

**Comment by zeta-00** [comment]
I executed the above instructions and ihaskell is still not working(same error: ihaskell kernel not supported), also i am getting another error when running:  ein:byte-compile-ein  :

mapc: Removing old name: Read-only file system, /nix/store/4ydrcx5rm9pca8p6x9lld0fy1d63p2v2-emacs-packages-deps/share/emacs/site-lisp/elpa/ein-20191020.1934/ein-ac.elc

So is there a workaround i can do to get around this? also is this a problem with ein or ihaskell? when I posted this same issue on the ihaskell project in github they told me that this is a problem related to ein so i need to come here instead?

**Comment by millejoh** [comment]
Okay, think I figured this out after an extended saga of getting ihaskell to work under WSL (which it does, quite well in fact, if anyone cares).

EIN multilang mode does not support haskell (yet), but if you enable polymode by setting `ein:polymode`  to `t` then you should be able to load your notebook.

**Comment by zeta-00** [comment]
after adding:  (setq ein:polymode t) to my .emacs file, i am finally able to open an ihaskell notebook without getting that error: kernel spec haskell not supported, which is good but now i am stuck at: kernel reconnecting, i changed the port number from 8888 to 9999, but i am still stuck at that kernel reconnecting message, at this point i have no idea what to do next to connect to the haskell kernel?

**Comment by zeta-00** [comment]
this might be a nix problem now so i posted the issue in ihaskell as well: https://github.com/gibiansky/IHaskell/issues/1132

**Comment by zeta-00** [comment]
thanks for the help, ein is a useful tool, go ahead and close this issue, the people in ihaskell helped me fix the problem i had on the nix end:  https://github.com/gibiansky/IHaskell/issues/1132

**Comment by millejoh** [comment]
Glad everything worked out! Good luck using the tool.
