### ISSUE TITLE
Server notebook list is empty, can't connect to any notebook

### ISSUE THREAD

**Issue by dov** [millejoh/emacs-ipython-notebook#64]
## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have

With the latest ipython on Fedora, ein:notebooklist-open no longer returns a list of available notebooks.

The received emacs buffer output is:

    IPython 2 Notebook list

     | [Home] |

    [New Notebook] [Reload List] [Open In Browser]

Reload doesn't do anything.

## Steps to reproduce the problem

1. Get latest emacs-ipython-notebook version

shell> git config --get remote.origin.url
git://github.com/tkf/emacs-ipython-notebook.git
shell> git log --oneline -1
0bbe7ad Be more friendly in `ein:notebooklist-open`

2. Start ipython server

shell>  ipython notebook --no-browser

3. Run ./lisp/zeroein.el to connect to the new server.

## Expected output

I expect to get a list of notebooks matching the notebooks that are seen when accessing the server in a web browser. The actual result is no notebooks at all.

## Your EIN configuration (in .emacs.d/init.el or somewhere else)

Used zeroin.

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):

> ipython --version
2.0.0-dev

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):

ipython notebook --no-browser

3. What is your IPython notebook port number or URL?:

Default, i.e. 8888

## Additional information (if any)

Tornado version: 3.2.dev2

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.5.1 (i686-redhat-linux-gnu, GTK+ Version 3.16.2)
 of 2015-04-22 on buildhw-10.phx2.fedoraproject.org"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux grower 4.0.6-300.fc22.i686+PAE #1 SMP Tue Jun 23 14:22:22 UTC 2015 i686 i686 i386 GNU/Linux
"
  :lsb-release
  "LSB Version:	:core-4.1-ia32:core-4.1-noarch:cxx-4.1-ia32:cxx-4.1-noarch:desktop-4.1-ia32:desktop-4.1-noarch:languages-4.1-ia32:languages-4.1-noarch:printing-4.1-ia32:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 22 (Twenty Two)
Release:	22
Codename:	TwentyTwo
")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.7.0bbe7ad"
	   :source-dir "/space/pub-repos/emacs-ipython-notebook/lisp/")
 :lib
 ((:name "websocket"
	 :path "/space/pub-repos/emacs-ipython-notebook/lib/websocket/websocket.el"
	 :featurep t
	 :version-var websocket-version
	 :version "1.3")
  (:name "request"
	 :path "/space/pub-repos/emacs-ipython-notebook/lib/request/request.el"
	 :featurep t
	 :version-var request-version
	 :version "0.2.0alpha1")
  (:name "auto-complete"
	 :path "/space/pub-repos/emacs-ipython-notebook/lib/auto-complete/auto-complete.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "mumamo"
	 :path "/space/pub-repos/emacs-ipython-notebook/lib/nxhtml/util/mumamo.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "auto-complete"
	 :path "/space/pub-repos/emacs-ipython-notebook/lib/auto-complete/auto-complete.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "popup"
	 :path "/space/pub-repos/emacs-ipython-notebook/lib/popup/popup.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "fuzzy"
	 :path "/space/pub-repos/emacs-ipython-notebook/lib/fuzzy/fuzzy.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "pos-tip"
	 :path "/space/pub-repos/emacs-ipython-notebook/lib/pos-tip/pos-tip.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "python"
	 :path "/space/pub-repos/emacs-ipython-notebook/lib/python/python.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "markdown-mode"
	 :path "/space/pub-repos/emacs-ipython-notebook/lib/markdown-mode/markdown-mode.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "smartrep"
	 :path "/space/pub-repos/emacs-ipython-notebook/lib/smartrep/smartrep.el"
	 :featurep nil
	 :version-var nil
	 :version nil)))
```

**Comment by dov** [comment]
I downgraded ipython to version 2.3.1 and I then get the expected list of notebooks. Unfortunately I still fail to access the notebooks due to some websocket problem. :-(

**Comment by millejoh** [comment]
You need to upgrade tornado to v4.0+ (I should really update the checklist someday) as earlier versions have problems with websockets.

Sorry for the slow reply.

**Comment by dov** [comment]
Thanks! Ein is in indeed working with the tornado vs 4.2.
