### ISSUE TITLE
Support for xeus-cling

### ISSUE THREAD

**Issue by tlkahn** [millejoh/emacs-ipython-notebook#644]
How can I make EIN (orgmode) work with xeus-cling? I added the following pair to Ob EIN languages and it seems not to work:

<img width="306" alt="Screen Shot 2020-01-20 at 11 32 32 AM" src="https://user-images.githubusercontent.com/335719/72696840-a9da6d00-3b78-11ea-8dcc-5595498d1a2f.png">

My src block looks like:

```
#+NAME: 38C89913-7AC7-405A-928E-4D0806236476
#+begin_src ein-Cpp17 :session localhost:8889 :results raw drawer 
cout << filesystem::current_path();
#+end_src
```

My jupyter kernels (xcpp1x installed through xeus-clint):

```
Available kernels:
  pycharm-5b5121ec    ...
  python3             ...
  xcpp11              ...
  xcpp14              ...
  xcpp17              ...
  c                   ...
```

**Comment by millejoh** [comment]
First step is to get just a bit more info. When you try to execute the source code block does what does the `*ein:shared-output*` buffer look like, and does ein produce any interesting looking messages in the `*ein:log-all*` buffer?

**Comment by tlkahn** [comment]
Sure. Based on the above config, in *Messages* buffer I saw:

`org-babel-execute-src-block: No org-babel-execute function for C++17!`

I dipped into the code for a little and struggled to find this in `ein-multilang.el`:

```
(defun ein:ml-lang-setup-python ()
  "Presumably tkf had good reasons to choose only these forms from `python-mode'."
  (setq-local mode-name "EIN[Py]")
  (setq-local comment-start "# ")
  (setq-local comment-start-skip  "#+\\s-*")
  (setq-local parse-sexp-lookup-properties t)
  (setq-local indent-line-function
              (apply-partially #'ein:ml-indent-line-function #'python-indent-line-function))
  (setq-local indent-region-function
              (apply-partially #'ein:ml-indent-region #'python-indent-region))
  (set-syntax-table python-mode-syntax-table)
  (set-keymap-parent ein:notebook-multilang-mode-map python-mode-map))

(defun ein:ml-lang-setup-clojure () ...
```
I tried to add the code below (though I'm sure more work is required):

```
(defun ein:ml-lang-setup-C++17 ()
  "Presumably tkf had good reasons to choose only these forms from `C++-mode'."
  (setq-local mode-name "EIN[C++]")
  (setq-local comment-start "// ")
  (setq-local comment-start-skip  "////+\\s-*")
  (setq-local parse-sexp-lookup-properties t)
  (setq-local indent-line-function
              (apply-partially #'ein:ml-indent-line-function #'C++-indent-line-function))
  (setq-local indent-region-function
              (apply-partially #'ein:ml-indent-region #'C++-indent-region))
  (set-syntax-table C++-mode-syntax-table)
  (set-keymap-parent ein:notebook-multilang-mode-map C++-mode-map))
```
It seems I can send the code to the kernel now (step 1.` ein:connect-to-notebook` step 2: `ein:connect-eval-region`) will send the code to kernel and execute the code. But the rest part I don't know how to proceed... Please help.

**Comment by tlkahn** [comment]
After adding the code, In *ein:log-all*, I see:

`Command sent to the kernel: %run "/Users/yongguo/Desktop/ai/model_zoo.org" @#<buffer model_zoo.org>`. 

Before the code, there is nothing there.

After the code, In *ein:shared-output*, I saw: 

`Unknown magic line function %run`

Before the code, there was nothing.

**Comment by dickmao** [comment]
> I tried to add the code below (though I'm sure more work is required):

It's nice you made this effort to extend ein:multilang, but as you're well aware, a lot more has to change.

I maintain an EIN fork at https://github.com/dickmao/emacs-ipython-notebook which I've verified to work with xeus-cling.  Note that `printf("hello, world")` does not yield the desired string since org-babel only captures results, not stdout.  C-c C-c of just the constant string `"hello, world"` gets you what you want.  C-c C-c of `strlen("hello, world")` returns 12.

In addition to using the EIN fork, you will need to add:
```
(custom-set-variables
 '(ob-ein-languages
   (quote
    (("ein" . python)
     ("ein-python" . python)
     ("ein-R" . R)
     ("ein-r" . R)
     ("ein-julia" . julia)
     ("ein-C++17" . C++17))))
 '(polymode-mode-name-aliases
   (quote
    ((elisp . emacs-lisp)
     (el . emacs-lisp)
     (bash . sh-mode)
     (C++17 . c++)))))
```
or something similar to accommodate your three C++ kernels.

**Comment by millejoh** [comment]
@tlkahn - with the lastest few commits you should be able to get xeus-cling with ein-multilang both in the notebook and in babel source blocks, but let me know if you continue to have problems.

**Comment by tlkahn** [comment]
Thanks fo much for such quick solution. Kudos to you both @dickmao, @millejoh. You guys are heros!
