### ISSUE TITLE
Error after ein update

### ISSUE THREAD

**Issue by vale46** [millejoh/emacs-ipython-notebook#646]
Hi - updated EIN (to version 20200104.1609) a few mins ago, but upon restart (tried both ein:run and C-x C-o in a .ipynb buffer), but see the error message:

Appreciate your help on this!

`16:40:56:483: [info] Login to http://127.0.0.1:8888 complete. @#<buffer *ein:log-all*>
16:40:56:604: [warn] notebook version currently unknowable @#<buffer *ein:log-all*>
16:40:56:737: [verbose] Retry kernelspecs #0 in response to 200 @#<buffer *ein:log-all*>
16:40:56:862: [verbose] Retry kernelspecs #1 in response to 200 @#<buffer *ein:log-all*>
16:40:56:982: [verbose] Retry kernelspecs #2 in response to 200 @#<buffer *ein:log-all*>
16:40:57:110: [error] ein:query-kernelspecs--error http://127.0.0.1:8888: ERROR json-readtable-error DATA (92) @#<buffer *ein:log-all*>
16:40:57:111: [warn] No recorded notebook version for http://127.0.0.1:8888 @#<buffer *ein:log-all*>
16:40:57:243: [verbose] Retry sessions #0 in response to 200 @#<buffer *ein:log-all*>
16:40:57:592: [verbose] Retry content-query-contents #0 in response to 200 @#<buffer *ein:log-all*>
16:40:58:092: [warn] No recorded notebook version for http://127.0.0.1:8888 @#<buffer *ein:log-all*>
16:40:58:493: [verbose] Retry sessions #1 in response to 200 @#<buffer *ein:log-all*>
16:40:59:497: [verbose] Retry content-query-contents #1 in response to 200 @#<buffer *ein:log-all*>
16:41:00:535: [warn] No recorded notebook version for http://127.0.0.1:8888 @#<buffer *ein:log-all*>
16:41:00:552: [verbose] Retry sessions #2 in response to 200 @#<buffer *ein:log-all*>
16:41:01:379: [verbose] Retry content-query-contents #2 in response to 200 @#<buffer *ein:log-all*>
16:41:02:883: [warn] No recorded notebook version for http://127.0.0.1:8888 @#<buffer *ein:log-all*>
16:41:03:022: [error] ein:content-query-sessions--error http://127.0.0.1:8888: ERROR json-readtable-error DATA (92) @#<buffer *ein:log-all*>
16:41:03:316: [error] ein:content-query-contents--error http://127.0.0.1:8888/ REQUEST-STATUS parse-error DATA (92) @#<buffer *ein:log-all*>
`

**Comment by vale46** [comment]
debug log below....

`17:10:31:331: [info] ein:jupyter-server--run: c:/Users/xxx.yyy/anaconda3/Scripts/jupyter.exe notebook --notebook-dir=c:/notebook/dir/ --debug --no-browser @#<buffer *scratch*>
17:10:36:518: [debug] Login attempt #0 in response to nil from http://127.0.0.1:8888. @#<buffer *scratch*>
17:10:36:664: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:37:141: [info] Login to http://127.0.0.1:8888 complete. @#<buffer *scratch*>
17:10:37:142: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:37:144: [debug] ein:notebooklist-login--complete STATUS: 200 DATA: (:bad-page nil) @#<buffer *scratch*>
17:10:37:266: [debug] ein:query-notebook-version--complete STATUS: 200 DATA: nil @#<buffer *scratch*>
17:10:37:266: [warn] notebook version currently unknowable @#<buffer *scratch*>
17:10:37:268: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:37:393: [verbose] Retry kernelspecs #0 in response to 200 @#<buffer *scratch*>
17:10:37:395: [debug] Race! (ein:query-kernelspecs http://127.0.0.1:8888) nil @#<buffer *scratch*>
17:10:37:395: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:37:397: [debug] ein:query-kernelspecs--complete STATUS: 200 DATA: nil @#<buffer *scratch*>
17:10:37:519: [verbose] Retry kernelspecs #1 in response to 200 @#<buffer *scratch*>
17:10:37:520: [debug] Race! (ein:query-kernelspecs http://127.0.0.1:8888) nil @#<buffer *scratch*>
17:10:37:521: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:37:522: [debug] ein:query-kernelspecs--complete STATUS: 200 DATA: nil @#<buffer *scratch*>
17:10:37:650: [verbose] Retry kernelspecs #2 in response to 200 @#<buffer *scratch*>
17:10:37:651: [debug] Race! (ein:query-kernelspecs http://127.0.0.1:8888) nil @#<buffer *scratch*>
17:10:37:652: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:37:653: [debug] ein:query-kernelspecs--complete STATUS: 200 DATA: nil @#<buffer *scratch*>
17:10:37:784: [error] ein:query-kernelspecs--error http://127.0.0.1:8888: ERROR json-readtable-error DATA (92) @#<buffer *scratch*>
17:10:37:785: [warn] No recorded notebook version for http://127.0.0.1:8888 @#<buffer *scratch*>
17:10:37:786: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:37:788: [debug] ein:query-kernelspecs--complete STATUS: 200 DATA: nil @#<buffer *scratch*>
17:10:37:789: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:38:342: [verbose] Retry sessions #0 in response to 200 @#<buffer *scratch*>
17:10:38:845: [debug] Race! (content-query-sessions http://127.0.0.1:8888) nil @#<buffer *scratch*>
17:10:38:846: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:38:848: [debug] ein:query-sessions--complete STATUS: 200 DATA: nil @#<buffer *scratch*>
17:10:38:849: [verbose] Retry content-query-contents #0 in response to 200 @#<buffer *scratch*>
17:10:39:369: [warn] No recorded notebook version for http://127.0.0.1:8888 @#<buffer *scratch*>
17:10:39:371: [debug] Race! (content-query-contents http://127.0.0.1:8888 ) nil @#<buffer *scratch*>
17:10:39:371: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:39:373: [debug] ein:query-contents--complete STATUS: 200 DATA: nil @#<buffer *scratch*>
17:10:39:381: [verbose] Retry sessions #1 in response to 200 @#<buffer *scratch*>
17:10:40:383: [debug] Race! (content-query-sessions http://127.0.0.1:8888) nil @#<buffer *scratch*>
17:10:40:383: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:40:385: [debug] ein:query-sessions--complete STATUS: 200 DATA: nil @#<buffer *scratch*>
17:10:40:468: [verbose] Retry content-query-contents #1 in response to 200 @#<buffer *scratch*>
17:10:40:496: [verbose] Retry sessions #2 in response to 200 @#<buffer *scratch*>
17:10:41:999: [debug] Race! (content-query-sessions http://127.0.0.1:8888) nil @#<buffer *scratch*>
17:10:41:999: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:42:001: [debug] ein:query-sessions--complete STATUS: 200 DATA: nil @#<buffer *scratch*>
17:10:42:001: [warn] No recorded notebook version for http://127.0.0.1:8888 @#<buffer *scratch*>
17:10:42:003: [debug] Race! (content-query-contents http://127.0.0.1:8888 ) nil @#<buffer *scratch*>
17:10:42:003: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:42:005: [debug] ein:query-contents--complete STATUS: 200 DATA: nil @#<buffer *scratch*>
17:10:42:399: [verbose] Retry content-query-contents #2 in response to 200 @#<buffer *scratch*>
17:10:43:902: [warn] No recorded notebook version for http://127.0.0.1:8888 @#<buffer *scratch*>
17:10:43:904: [debug] Race! (content-query-contents http://127.0.0.1:8888 ) nil @#<buffer *scratch*>
17:10:43:904: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|c527a043|27de1b4afe448cd6f292456a0d84d572|1574284236 @#<buffer *scratch*>
17:10:43:906: [debug] ein:query-contents--complete STATUS: 200 DATA: nil @#<buffer *scratch*>
17:10:43:907: [error] ein:content-query-sessions--error http://127.0.0.1:8888: ERROR json-readtable-error DATA (92) @#<buffer *scratch*>
17:10:43:908: [debug] ein:query-sessions--complete STATUS: 200 DATA: nil @#<buffer *scratch*>
17:10:44:338: [error] ein:content-query-contents--error http://127.0.0.1:8888/ REQUEST-STATUS parse-error DATA (92) @#<buffer *scratch*>
17:10:44:338: [debug] ein:query-contents--complete STATUS: 200 DATA: nil @#<buffer *scratch*>
`

**Comment by dickmao** [comment]
I would reinstall EIN with melpa latest.  When reporting bugs, please fill out `M-x ein:dev-bug-report-template`, and copy here.  It's hard to diagnose "failure to launch" issues such as yours without all the versioning info.
