### ISSUE TITLE
ein-20200202.218 is missing ein-timestamp

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#650]
File `ein-timestamp` is missing from `ein-20200202.218` installed from elpa.

**Comment by dickmao** [comment]
This was an undocumented feature for 1-2 users.  I'd ask that you keep a copy of `ein-timestamp.el` in your `load-path` for your personal use.

**Comment by sam-s** [comment]
IMHO, this is not a reasonable approach. @millejoh - is this your official position now?!
