### ISSUE TITLE
ein-20200202.218: cannot search in data

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#652]
`C-s` in output data resumes a search from input cells.
it is impossible to start a new search from the output data

**Comment by dickmao** [comment]
I have added to the README instructions on how to disable your personal configuration which is almost certainly causing this strange behaviour.

**Comment by sam-s** [comment]
I am sorry, I don't see anything there.
Could you please copy the text into this ticket?
Thanks.

**Comment by dickmao** [comment]
`emacs -Q -f package-initialize`

**Comment by sam-s** [comment]
I don't think the problem is with my settings.
When search takes one from input to output cell, the mode changes and since isearch is a mode, the mode change screws the mode up.

**Comment by dickmao** [comment]
I'm afraid you're going to have to spell out the exact sequence of events, or ideally produce a gif video, like this.
![search](https://user-images.githubusercontent.com/7578770/73885088-2a65c280-4835-11ea-94cc-f4a4c662c30f.gif)

**Comment by sam-s** [comment]
wow! how do you make that?!
