### ISSUE TITLE
cell-input-area color ugly in new version of emacs 27 and emacs 28

### ISSUE THREAD

**Issue by yefeiyu** [millejoh/emacs-ipython-notebook#654]
The cell-i-a's background color which defined in `customize-face, ein:cell-input-area` changes only with input characters, not by cell's region.

**Comment by dmille** [comment]
I'm having the same issue. This is what it looks like:

![image](https://user-images.githubusercontent.com/959823/74047902-19d15b80-499f-11ea-9acf-5738d48f9bd9.png)

This is GNU Emacs 28.0.50

**Comment by dickmao** [comment]
Not for nothing, but you might try `plt.style.use('dark_background')` to get your axes labels to become visible.

**Comment by zsxh** [comment]
Changes in Emacs 27.1

** New face attribute ':extend' to control face extension at EOL.
The new face attribute ':extend' controls whether to use the face for
displaying the empty space beyond end of line (EOL) till the edge of
the window.  By default, this attribute is non-nil only for 'region',
'secondary-selection', 'hl-line' and some faces of Diff and Ediff
modes; any other face that crosses end of line will not affect the
display of the empty space at EOL.  This is to make Emacs behave more
like other GUI applications with respect to displaying faces that
cross line boundaries.

Themes that redefine faces should add a non-nil ':extend' attribute to
the above-mentioned faces, to keep the behavior of the default face
definitions.

``` elisp
(with-eval-after-load 'ein-cell
    (set-face-extend 'ein:cell-input-area t))
```

**Comment by yefeiyu** [comment]
> ```emacs-lisp
> (with-eval-after-load 'ein-cell
>     (set-face-extend 'ein:cell-input-area t))
> ```

Thank you very much, it's resolved.

**Comment by dmille** [comment]
> Not for nothing, but you might try `plt.style.use('dark_background')` to get your axes labels to become visible.

Thanks for the tip! Yeah I'll do that
