### ISSUE TITLE
Can't show plot image inline, always shows it in browser

### ISSUE THREAD

**Issue by Loutine** [millejoh/emacs-ipython-notebook#656]
Thanks for this amazing package, but I found some problem when trying to plot image by using matplotlib.I can't get the image in cell but always get it in browser,and show me some error information.
`Wrong type argument: ein:$kernelspec, nil: defaulting language to python [3 times]`
`error in process sentinel: Text is read-only [2 times]`
![ArcoLinux_2020-02-05_20-18-48](https://user-images.githubusercontent.com/33801505/73841106-cf43c800-4854-11ea-8a56-5b2868432014.png)
but it's no problem to use it in stable version (0.16)
How can i solve this, if i need to config some settings for this?

**Comment by dickmao** [comment]
I have modified the README to say:
```
M-x customize-group RET ein
Ein:Output Area Inlined Images
```
