### ISSUE TITLE
No way to set slide attributes from ein

### ISSUE THREAD

**Issue by dov** [millejoh/emacs-ipython-notebook#66]
A ipynb notebook may be converted to a reveal slideshow through `ipython nbconvert --to slides`. This option uses the slide attributes that are available through the browser client through **Cell Toolbar: SlideShow** and by setting the Slide type of some cells to **Slide**. But these attributes are not available through the ein interface, and it is therefore not possible to create a notebook that is to be used for a slide show in ein.

**Comment by dov** [comment]
Here is a small script around that I wrote to get around the problem the slide conversion problem. It recognizes header level 1, either from cell type or from the first line of markdown, and inserts a new slide. After this script has been called, there is no problem to run the `ipython nbconvert --to slides` on the resulting json.

```python
#!/usr/bin/python

import sys,os
import json

argp = 1

filename = sys.argv[argp] if argp < len(sys.argv) else 'Test.ipynb' 

tree = json.load(open(filename))
if not 'metadata' in tree:
  tree['metadata'] = {
  "celltoolbar": "Slideshow",
  }

for ws in tree['worksheets']:
  for cell in ws['cells']:
    if not 'metadata' in cell or cell['metadata'] is None:
      cell['metadata'] = {}

    if ((cell['cell_type'] == 'markdown'
         and cell['source'][0].startswith('# '))
        or (cell['cell_type'] == 'heading' and cell['level']==1)):
        cell['metadata']['slideshow'] = {
         "slide_type": "slide"
        }

    # Fill in outputs with metadata
    if 'outputs' in cell:
      for out in cell['outputs']:
        if not 'metadata' in out or out['metadata'] is None:
          out['metadata'] = {}

fixed_filename = filename.replace('.ipynb','-fixed.ipynb')
open(fixed_filename,'w').write(json.dumps(tree,indent=2))
```

**Comment by millejoh** [comment]
Thanks for the script - I think it will only work with IPython 2.x notebooks, though. In 3.x the developers got rid of notebook worksheets.

There is no reason why EIN can't directly support those - other than my availability to implement something. The summer has been unexpectedly busy for me, but I will look into implementing this capability at some point

**Comment by Konubinix** [comment]
IIUC, the idea is to conserve the metadata in the notebook cells. In the method ein:cell-to-nb4-json, we can see that the metadata of each cell is overwritten with 
```json
{
  "collapsed": true,
  "tags": [
    "worksheet-0"
  ]
}
```
The proper implementation, IMHO, would be to store the metadatas in the class ein:textcell and give them back in the saving process.

My two cents :-)
