### ISSUE TITLE
Plots are not showing (no viewer method found in mailcap)

### ISSUE THREAD

**Issue by rileyf0** [millejoh/emacs-ipython-notebook#663]
Since upgrading to the most recent version of ein on Melpa, I've been unable to render any plots.  I get an error message that says `ein: [warn] ein:cell-append-mime-type: no viewer method found in mailcap`.  I get the same message whether I have `%matplotlib inline` or not.  

For example,
```
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
a = 50000
k = 20
c = -2
p0 = np.linspace(30, 50, 5)
q0 = np.random.poisson(a * p0 ** c)

%matplotlib inline
plt.plot(p0, q0)
```

This returns the following as usual but no plot:
```
[<matplotlib.lines.Line2D at 0x11d3c6410>]
```

Here is my section of my init with ein:
```
(require 'ein)
(require 'ein-notebook)
(setq ein:use-auto-complete t)
(setq ein:completion-backend 'ein:use-ac-jedi-backend)
(setq ein:use-auto-complete t)
```

**Comment by dickmao** [comment]
Please refer to FAQ section of README.
