### ISSUE TITLE
Ein:stop does not stop kernel on Windows

### ISSUE THREAD

**Issue by 2old2randr** [millejoh/emacs-ipython-notebook#666]
Signals are sent to the kernel process but this doesn’t seem to stop the kernel under Windows 10. Older versions of the code had a special branch for windows in ein:Jupiter-server-stop that has been removed.

**Comment by dickmao** [comment]
Commit 6121536 

The most celebrated answer in https://github.com/jupyter/notebook/issues/2844 is to dash-nine the pid on Win10.  Please let me know if that works since I don't have a Win10 setup.

**Comment by 2old2randr** [comment]
Yes, this seems to work. Thank you.
