### ISSUE TITLE
Ein complains that it cannot find ein-multilang.el

### ISSUE THREAD

**Issue by zjp** [millejoh/emacs-ipython-notebook#667]
As the title says, Ein has been complaining that it cannot find ein-multilang.el when it starts up. I see a previous commit on 7 January (5de0c8b) removes the library.

Strangely, the only results I get from `rg multilang` in the elpa/ein directory are a couple docstrings in ein-worksheet.el that reference ein:notebook-multilang-mode. 

For now, it doesn't appear to affect usage (a buffer just pops up with the complaint) but I'll come back and edit this post if something interesting happens.

**Comment by dickmao** [comment]
I would delete the results of `(file-expand-wildcards (expand-file-name "ein*"
package-user-dir))` and reinstall.

You can be more assured of normalcy when `(mapcar #'package-desc-dir (cdr
(assq 'ein package-alist)))` returns a single directory that looks like
`ein.20200215.xxx`.

Also ensure you don't have rogue `ein` require lurking in your `.emacs` or `init.el`.
