### ISSUE TITLE
Autocomplete repeats pre-typed expression

### ISSUE THREAD

**Issue by justmytwospence** [millejoh/emacs-ipython-notebook#67]
Say I have the following code:

```
import numpy as np
np.
```

The completer will then open and I will choose something, say `Inf`. The code that gets filled in then looks like this:

```
import numpy as np
np.np.Inf
```

This happens for all completions, when complete-on-dot is enabled and also when it is not and completion is manually invoked using `C-c C-i`. 

This renders autocompletion completely unusable for me - any ideas?

**Comment by millejoh** [comment]
How do you have autocomplete configured in your init.el file? What is the setting for`ein:use-auto-complete-superpack`? I don't know this part of the code as well as others, but my guess is that this is a configuration issue.

I have Jedi installed and `ein:use-auto-complete-superpack` set to T and unfortunately don't see this behavior.

**Comment by flamingbear** [comment]
I've seen this before with company-mode rather than autocomplete.  But I'll let @justmytwospence respond.

**Comment by justmytwospence** [comment]
Here's the potentially relevant bits of my config:

```
(use-package auto-complete
  :ensure t
  :ensure pos-tip
  :diminish auto-complete-mode
  :init
  (setq ac-use-menu-map t)
  :config
  (global-auto-complete-mode))

(use-package ein
  :ensure t
  :commands
  (ein:notebooklist-open)
  :init
  (setq ein:use-smartrep t)
  :config
  (add-hook 'ein:connect-mode-hook 'ein:jedi-setup))

(use-package jedi
  :ensure t
  :init
  (setq jedi:complete-on-dot t)
  :config
  (add-hook 'python-mode-hook 'jedi:setup))
```

**Comment by millejoh** [comment]
Nothing looks out of the ordinary there - my only thought is to double check that you have set either `ein:use-auto-complete` or `ein:use-auto-complete-superpack` to T. EIN wraps some of the ac functions depending on how these variables are set.

**Comment by maxhgerlach** [comment]
I have the same issue. The problem appears when auto-complete-mode is *not* turned on and instead some other built-in ipython completion is used. I would really like to disable that completion mechanism altogether because it is really disruptive.

Sadly I can't leave auto-complete mode on constantly because occasionally it slows down EIN to a crawl, making it painful just to enter code.

**Comment by maxhgerlach** [comment]
Here is a hacky work-around in my `init.el` to avoid the completion prompt if `auto-complete-mode` is not on.

```elisp
(defun my-ein-dot-function ()
  (interactive)
  (if (bound-and-true-p auto-complete-mode)
      (ein:notebook-complete-dot)
    (self-insert-command 1)))           ;problem remains: cannot insert many dots this way...

(define-key ein:notebook-mode-map (kbd ".") 'my-ein-dot-function)
```

I haven't found out yet how to deal with the universal argument `C-U` here...

**Comment by maxhgerlach** [comment]
The previous hack did not actually work correctly in `init.el`. This seems to do it:

```elisp
(defun my-ein-dot-function ()
  (interactive)
  (if (bound-and-true-p auto-complete-mode)
      (ein:notebook-complete-dot)
    (self-insert-command 1)))           ;problem remains: cannot insert many dots this way...

(defun define-key-for-my-ein-dot-function ()
  (interactive)
  (define-key ein:notebook-mode-map (kbd ".") 'my-ein-dot-function)
  (define-key ein:notebook-multilang-mode-map (kbd ".") 'my-ein-dot-function))

(add-hook 'ein:notebook-mode-hook
          'define-key-for-my-ein-dot-function)
```

What is the proper way to change key bindings for EIN?

**Comment by millejoh** [comment]
More than six months late, but behold 261576f94bb6eddc566c9d7aa557bf7cd20a2c05! I am very embarrassed it so long to figure out what in the end was a 15 minute fix. Sorry about that.
