### ISSUE TITLE
Files missing for manual install instructions ?

### ISSUE THREAD

**Issue by balbirthomas** [millejoh/emacs-ipython-notebook#672]
I am trying to build a simple Debian package for myself, by following the manual install instructions which state "Put Emacs lisp `ein*.el` files and the Python file `ein_remote_safe.py` in a directory defined in your load-path."  

However there seems to be no `ein_remote_safe.py` in the current git master branch. Where does this need to be obtained from ?

Also in trying to follow the minimal suggested configuration of
```
(require 'ein)
(require 'ein-notebook)
(require 'ein-subpackages)
```
I run into another problem that `ein-subpackages.el` seems to be missing. Again I would be grateful for a clarification on how it needs to be installed. 

I also tried manual install and packaging with the [unmaintained](https://github.com/tkf/emacs-ipython-notebook) branch. Even though the simple manual packaging worked however it failed to connect to jupyter sever, because of [this](https://github.com/tkf/emacs-ipython-notebook/issues/153) issue. I noticed `ein-subpackages.el` is available in this repository though. Is it still compatible ?

**Comment by dickmao** [comment]
Any information at https://github.com/tkf/emacs-ipython-notebook is obsolete.

An appeal to hide that repo from Google results has already been made at https://github.com/tkf/emacs-ipython-notebook/issues/205.

Please refer to this repo's [README](https://github.com/millejoh/emacs-ipython-notebook/blob/master/README.rst) for install instructions.

**Comment by balbirthomas** [comment]
Thanks for heads up. README indeed does not mention those missing dependencies. The Debian package works well without them and was quite easy to package with dh-make-elpa.

The documentation I was referring to, which mentions those missing dependencies was https://millejoh.github.io/emacs-ipython-notebook/  which links to this git repository.

**Comment by balbirthomas** [comment]
Thanks for heads up. [README](https://github.com/millejoh/emacs-ipython-notebook/blob/master/README.rst) indeed does not mention those missing dependencies. The Debian package works well without them and was quite easy to package with `dh-make-elpa`. 

The documentation I was referring to, which mentions those missing dependencies was https://millejoh.github.io/emacs-ipython-notebook/  which links to this git repository.

**Comment by dickmao** [comment]
> https://millejoh.github.io/emacs-ipython-notebook/

Also largely obsolete.  I'd stick to the README to get 90% of what you need to know, and `C-h m` for the rest.
