### ISSUE TITLE
visual-line-mode toggles on and off when you enter markdown cell

### ISSUE THREAD

**Issue by jgarvin** [millejoh/emacs-ipython-notebook#677]
If you have visual line mode enabled, markdown cells are wrapped only when the cursor is inside the cell. As soon as you move the cursor outside the cell the wrapping goes away. This causes a lot of weird jitter when you scroll through a notebook, and also makes it hard to navigate with relative line numbering.

**Comment by dickmao** [comment]
Thanks for reporting.  d2a11cd
