### ISSUE TITLE
sympy equation output visibility

### ISSUE THREAD

**Issue by seregaxvm** [millejoh/emacs-ipython-notebook#678]
Sympy equations are rendered as black text on transparent background. It does not look very well with dark themes:
![image](https://user-images.githubusercontent.com/26824900/75673713-a0bede80-5c94-11ea-8bcf-1e2b8f44308c.png)
Maybe there could be something done to increase visibility of such output?

**Comment by dickmao** [comment]
This is outside the scope of EIN.

On my [solarized theme](https://ethanschoonover.com/solarized/), sympy rendered light on dark out of the box.
![sin](https://user-images.githubusercontent.com/7578770/75675377-0ee3b100-5c55-11ea-95bf-b6fa359b05e5.png)

For whatever reason sympy cannot figure out you're on a dark background.  You can hammer it with `init_printing(forecolor='White')` but that's not ideal.  Either way, EIN has no control over this.

**Comment by dickmao** [comment]
Also, a recent commit d2a11cd disables display-line-numbers-mode causing line numbers to jarringly disappear and reappear described in #616.

**Comment by seregaxvm** [comment]
> On my solarized theme, sympy rendered light on dark out of the box.

I used `solarized-zenburn` theme.
