### ISSUE TITLE
ein:notebooklist-open does not navigate backwards

### ISSUE THREAD

**Issue by rambalachandran** [millejoh/emacs-ipython-notebook#68]
Hi,
I'm using ein (installed from melpa) in Emacs along with ipython 2.4.1. I can open the ipythonfiles with ein:notebooklist-open. However, when I try to navigate back to higher level directories, I get the following error

> widget-before-change: Text is read-only: "Attempt to change text outside editable field"
> ein: [error] Content list call http://127.0.0.1:8888/api/contents>/%2FDocumentsmyCodesbitbucketReposionictransportworkflow failed with status error.

**Comment by millejoh** [comment]
Make sure you are only selecting text between brackets (i.e. '[' and ']') in the notebooklist buffer. It also looks like an escaping problem in ein's code for IPython 2.x. There are enough subtle differences between 2.x and 3.x that it has been a challenge maintaining compatibility.

**Comment by rambalachandran** [comment]
I'm chosing the text that gets highlighted. Its not a showstopper but its a bit of nagging issue. I hope you can find time to fix it.
