### ISSUE TITLE
wrong command versions in menubar

### ISSUE THREAD

**Issue by seregaxvm** [millejoh/emacs-ipython-notebook#682]
Menubar and keymap have different command versions binded. For example, typing `C-h k C-c C-l` shows doc for `ein:worksheet-clear-output-km` function while typing `C-h k` and then clicking `EIN Notebook->Cell/Code->Discard all output` shows doc for `ein:worksheet-clear-all-output`. This does not affect functionality of ein, but because of this keybinding tips are not showing in the menubar.

**Comment by dickmao** [comment]
Thanks for reporting the bug.  53ab1c3
