### ISSUE TITLE
What happened to completion?

### ISSUE THREAD

**Issue by bcclaywell** [millejoh/emacs-ipython-notebook#689]
I've been trying to follow along with the docs for getting ein set up, in particular [here](http://millejoh.github.io/emacs-ipython-notebook/#subpackages) for getting company set up for completion, and as far as I can tell these variables don't even exist anymore (and a grep through the repository confirms that). Is there updated documentation on how to get completion working, has that feature been removed entirely, or am I missing something? Thanks!

**Comment by dickmao** [comment]
BC> I've been trying to follow along with the docs for getting ein set up

The millejoh.github.io documentation is several iterations stale.  The
maintainer of it (@millejoh) would do well to retire those pages as the README
supplies 90% of important information and its brevity makes it much easier to
keep *au courant*.

**Comment by bcclaywell** [comment]
So does that mean EIN no longer supports autocompletion via e.g. company?

**Comment by dickmao** [comment]
Technically yes, but morally no.  EIN now delegates all language-specific functionalities such as autocompletion to individual [program modes](https://www.gnu.org/software/emacs/manual/html_node/emacs/Program-Modes.html).  So if you've set up company for python, then EIN via the [polymode mechanism](https://github.com/polymode/polymode) lets that flow through  (for python in particular, we recommend elpy as referenced in the README).
