### ISSUE TITLE
No autocomplete suggestion for packages

### ISSUE THREAD

**Issue by ashkan-leo** [millejoh/emacs-ipython-notebook#690]
I can't see autocomplete suggestions for packages.
When I import something and type dot, EIN doesn't show stuff inside the package or class.
The python keywords (assert, etc.) are auto completed.
In python-mode, I use lsp-mode to get this functionality to work. Is there anyway to make this work in EIN as well?

**Comment by dickmao** [comment]
I've only ever used elpy.  I've never used lsp-mode, so I suspect it won't work with EIN (rarely does anything work with EIN out of the box without someone first tweaking it).

As a minimal reproducible example, I know under elpy something like
```
import numpy as np
np.
```
will bring up a completions popup after a pause.  I understand elpy's completions to not be as snappy or intelligent as some other libraries.

I have no plans to integrate lsp-mode and am closing this issue.  I am purposely avoiding the phrase "PRs welcome" as that has effectively been the kiss of death, and I'm a superstitious fellow.  Thanks for your interest, nonetheless.
