### ISSUE TITLE
LaTeX support through Texfrag

### ISSUE THREAD

**Issue by balbirthomas** [millejoh/emacs-ipython-notebook#691]
Hi,

If I am not mistaken emacs-ipython-notebook does not support LaTeX preview in mardown cells. I came across [Texfrag](https://github.com/TobiasZawada/texfrag) recently, which is intended to support LaTeX preview in non LaTeX modes. Is this (or anything similar), something that can be integrated into emacs-ipython-notebook for out of the box support for LaTeX preview. 
By LaTeX preview I mean the ability to view typeset LaTeX output within emacs, without the need to export the IPython notebook to other formats such as HTML or PDF.

Thank you for maintaining this fantastic package.
regards

**Comment by dickmao** [comment]
LaTeX rendering is listed as one of "Projects."  I have no plans to work on it.  My first attempt at it failed quite badly and so I'm somewhat leery of a reattempt.  I suspect the final solution, should it ever get that far, will not need any third-party packages like Texfrag.
