### ISSUE TITLE
A lot functions were deleted without clear reason, and documentation is old

### ISSUE THREAD

**Issue by c02y** [millejoh/emacs-ipython-notebook#695]
I was reading documentation from https://millejoh.github.io/emacs-ipython-notebook/#notebook, and notice a lot functions such as `ein:edit-cell-xx` are unavailable, and the keyword I found in the current repo is only https://github.com/millejoh/emacs-ipython-notebook/blob/master/doc/source/index.rst#advanced-editing file, no definitions found. Then I search them in the git log/history, and found that a commit(https://github.com/millejoh/emacs-ipython-notebook/commit/59540e54d90fce46664f9d66d6d0d8ec1a924cce) deleted a lot files including the files containing the definitions of `ein:edit-cell-xx`, but it didn't tell the reason.

So why were they deleted? And the documentation is old.

**Comment by dickmao** [comment]
Earlier requests for @millejoh to retire his documentation below:

https://github.com/millejoh/emacs-ipython-notebook/issues/689#issuecomment-600339594
https://github.com/millejoh/emacs-ipython-notebook/issues/672#issuecomment-590000815

Please refer to [README](https://github.com/millejoh/emacs-ipython-notebook/blob/master/README.rst) and `C-h m` for usage.
