### ISSUE TITLE
M-x customize-group ein error in Emacs 27.0.90 and 28.050

### ISSUE THREAD

**Issue by exp2ipi** [millejoh/emacs-ipython-notebook#697]
M-x customize-group ein throws an error and displays a corrupted buffer with half the options missing or displaying strings "UNITIALIZED, you should not see this".

The error is: (void-variable ein:jupyter-default-server-command)

**Comment by dickmao** [comment]
I have created a new label "emacs-27" for issues like yours.  Please refer to the FAQ in the README about EIN's treatment of pre-release versions of emacs.

**Comment by leoalekseyev** [comment]
Emacs 27 is in beta and the release is coming reasonably soon. Many people are switching to it due to much improved workflows with LSP due to native JSON parsing. So it would be reasonable to not punt testing against 27.090 until too long. If I can be of help testing/debugging let me know.

**Comment by goktug97** [comment]
I've realized that some of the variables are set when the ein:markdown mode is initialized so I've set my config like this;

```lisp
  (add-hook 'ein:markdown-mode-hook
            (lambda ()
              (progn 
                (setq ein:output-area-inlined-images t)
                (set-face-background 'ein:cell-input-area "black"))))
```
and it works.
