### ISSUE TITLE
We need to update watching name "object_info_request" of  ein:ac-request-document-for-selected-candidate

### ISSUE THREAD

**Issue by lijinhui** [millejoh/emacs-ipython-notebook#70]
For IPython 3.x:

"Changed in version 5.0: object_info_request renamed to inspect_request". See https://ipython.org/ipython-doc/dev/development/messaging.html

We need to update ein:ac-set-document too.

Thanks.

**Comment by millejoh** [comment]
I think ein supports this better now, but you will need to let me know if you are seeing the expected behavior or not.
