### ISSUE TITLE
cannot send message to a closed websocket

### ISSUE THREAD

**Issue by FalseProtagonist** [millejoh/emacs-ipython-notebook#704]
### Environment
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.3
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.1.2
jupyter lab      : 1.2.6
nbconvert        : 5.6.1

emacs version: 0.200.13@28.0.50
ein version: 20200425

### Bug description
Connecting to a remote jupyter server on http (not https) using ein:login, can enumerate files and open non-notebook files, opening a notebook causes some infinite loop over the lines listed in the Emacs log, crashing Emacs. Sometimes the notebook eventually opens with a dead kernel.

### Emacs Log
ein: [info] WS action [(wrong-type-argument ein:$websocket nil)] on-close (ws://zimablue.com:80/api/kernels/256875a8-6aec-4955-ae66-3ab2803c7356/channels?session_id=8aeb4a0a-f87a-40a7-803f-bb73b72357ee)
error in process filter: websocket-send: Cannot send message to a closed websocket: #s(websocket-frame pong "c6417ed01bdc0ae3ef32ae4894fd03\">
    <meta http-equiv=\"" nil t)

### Jupyter Log
[W 14:02:43.870 LabApp] 403 GET /api/kernels/256875a8-6aec-4955-ae66-3ab2803c7356/channels?session_id=8aeb4a0a-f87a-40a7-803f-bb73b72357ee (41.36.114.134) 2.44ms referer=None
[W 14:02:44.130 LabApp] Couldn't authenticate WebSocket connection

**Comment by dickmao** [comment]
We make no assurances about unreleased versions of emacs.  Sorry.
