### ISSUE TITLE
How to change the listing order of jupyter notebook

### ISSUE THREAD

**Issue by yohey-uemura** [millejoh/emacs-ipython-notebook#705]
Hi all,

I would like to change the order of the list in ein.
I use 'ein:notebooklist-open' and successfully show the list of notebooks.
The notebooks are sorted by Name in ascending order.
I would like to see them by "**Last modified**" in "**descending order**".
How can I edit my int file?

**Comment by dickmao** [comment]
```
M-x customize-group RET ein
Ein:Notebooklist Sort Field: Last modified
Ein:Notebooklist Sort Order: Descending
C-x C-s
```
Go to notebooklist buffer, and `C-c C-r`

Please avoid using `ein:notebooklist-open` (use `ein:run` or `ein:login` instead).  If you found that command from http://millejoh.github.io/emacs-ipython-notebook , please be aware that documentation is severely outdated.
