### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by cobacdavid** [millejoh/emacs-ipython-notebook#707]
Last command in a cell doesn't output its result in Out with `C-c C-c`. For example:

```python
a = 3
a
```  
I also get this in `Messages` buffer:
```
ein: [info] WS action [(void-variable type)] on-message (ws://127.0.0.1:8888/api/kernels/811110b0-994c-4721-8b7e-7eafb0ca4aff/channels?session_id=c0ad0ad5-3a9f-4589-83f4-b941826b5fb6)
```

**Comment by dickmao** [comment]
A baseline failure like this suggests an incomplete install.  There's not much I can recommend other than deleting and reinstalling (which I understand is beyond the reach of many emacs users).

Following the FAQ for reporting bugs might offer additional insights (although again, those steps may require a facility with UNIX beyond some users).
