### ISSUE TITLE
[Unable to install package] Websocket-1.3 is unavailable

### ISSUE THREAD

**Issue by CestDiego** [millejoh/emacs-ipython-notebook#71]
When using melpa this file https://github.com/millejoh/emacs-ipython-notebook/blob/master/lisp/ein-pkg.el hardcodes the version of `websocket` to use and one gets
```
Warning (emacs): Unable to activate package `ein'.
Required package `websocket-1.3' is unavailable
```

I think it is automatically generated by melpa right? so why keep it there? Also, maybe can we change it to 1.5 maybe?

**Comment by millejoh** [comment]
Thanks for catching this - it looks like ein has disappeared from MELPA; I hope this is the reason why. I just pushed a commit updating ein-pkg to require websocket 1.5.

**Comment by CestDiego** [comment]
@millejoh I think you should consider openning an issue on MELPA

**Comment by millejoh** [comment]
Figured it out, I think. MELPA does `git submodule update --init --recursive` and subsequently fails for some reason when trying to download nxhtml, saying 'Unable to checkout 'f3ee292f8d2849cc89ba9c50e7c4bbfbf100daef' in submodule path 'lib/nxhtml'`. I ran into this problem before, but can't remember what I did to solve it.

**Comment by millejoh** [comment]
FIxed, wIth a scorched-earth policy when it comes to nxhtml. Not sure how many people this will affect, but at least ein is back up in MELPA.
