### ISSUE TITLE
Saving despite 'Text is read-only'.

### ISSUE THREAD

**Issue by dotmilk** [millejoh/emacs-ipython-notebook#710]
Uncertain as to why this message appears in my mini buffer when saving:
` ein:notebook-save-notebook: Saving despite 'Text is read-only'.`

Would like to keep it from happening if possible.

**Comment by dickmao** [comment]
Please check `C-h v before-save-hook`.  A function sitting in that hook is triggering the `Text is read-only`, and EIN is merely saying "I observed this error, but I'm going to try to save anyway."

**Comment by dotmilk** [comment]
Thank you. That was indeed it.
