### ISSUE TITLE
emacs-ipython-notebook conflicts with tabbars

### ISSUE THREAD

**Issue by Volker-Weissmann** [millejoh/emacs-ipython-notebook#715]
Hello, 
If you install ein and any tabbar that I tried (e.g. https://github.com/manateelazycat/awesome-tab) and you switch to a ein buffer, you won't see the tabbar.

Is there a way to fix this?

**Comment by dickmao** [comment]
Both ein and awesome-tab seek to annex the [header line slot](https://www.gnu.org/software/emacs/manual/html_node/elisp/Header-Lines.html#Header-Lines), of which there is and can only be one.
