### ISSUE TITLE
Push stable versions to melpa-stable.

### ISSUE THREAD

**Issue by bastibe** [millejoh/emacs-ipython-notebook#72]
This is as simple as adding a git-tag with a version number (`x.y[.z]`).

I'd much rather update EIN every time a new major version comes out than for every commit.

**Comment by millejoh** [comment]
Tag added and looks like ein is now appearing on melpa-stable - hope what I tagged is stable enough for your use.

**Comment by bastibe** [comment]
Perfect! It works beautifully!
