### ISSUE TITLE
problems with ihaskell's auto-completion:

### ISSUE THREAD

**Issue by zeta-00** [millejoh/emacs-ipython-notebook#720]
@millejoh @dickmao , hello again, so i finally got ihaskell up and running with ein and it works great, the only problem i'm having is getting ihaskell's kernel's built-in functionality like auto-completion and all of it's other features working, ihaskell's kernel comes built-in with the messaging protocol:

https://github.com/gibiansky/IHaskell/issues/1175

anyways, according to ein's documentation( http://millejoh.github.io/emacs-ipython-notebook/#ein:completion-backend ), i need to use company-mode to communicate with ihaskell's kernel to use it's build-in functionality, but after setting company-mode up with company-ghci, ihaskell breaks and stops working, here's my .emacs code i use for ihaskell and ein:

;;------------------------------------------------------------------
;; haskell-mode configuration:
(with-eval-after-load 'company
  (push 'company-ghci company-backends))

(add-hook 'haskell-mode-hook 'company-mode)
(add-hook 'haskell-mode-hook 'interactive-haskell-mode)
(add-hook 'haskell-interactive-mode-hook 'company-mode)
(add-hook 'haskell-mode-hook 'haskell-indentation-mode)
;;------------------------------------------------------------------
;; emacs-ipython-notebook configuration:
(setq ein:polymode t)
(setq ein:completion-backend 'ein:use-company-backend)
;;------------------------------------------------------------------

**Comment by zeta-00** [comment]
ghc-mod is outdated, so i don't know how i'm going to be able to communicate with the ihaskell kernel's built-in functionality?

**Comment by dickmao** [comment]
> anyways, according to ein's documentation( http://millejoh.github.io/emacs-ipython-notebook/#ein:completion-backend )

Our README indicates the aforementioned link has been stale for several iterations of the code, and [several requests for its retirement](https://github.com/millejoh/emacs-ipython-notebook/issues/695#issuecomment-609893084) have thus far been ignored.

> (setq ein:polymode t)
> (setq ein:completion-backend 'ein:use-company-backend)

If you're using a recent melpa commit, these lines do nothing.  You should remove them.

Haskell modes are outside the EIN's scope.  If you can get it working *outside* of EIN, then come back with a working example of how it doesn't work *inside* EIN.
