### ISSUE TITLE
Last execution time, and jump to error

### ISSUE THREAD

**Issue by indigoviolet** [millejoh/emacs-ipython-notebook#722]
I run `ein:worksheet-execute-all-cells-above` quite often. There are two (related) inconveniences:

1) Sometimes one of the cells in that list errors, but I'm scrolled to the "last" cell (ie. the cell above which I'm executing all) and don't realize. I have to notice that the kernel is no longer busy, then scroll up looking for a cell that errored. It would be nice for (a) there to be some more visible notice that an error has occured (b) for the worksheet to jump to that cell or for there to be a function to jump to it.

2) In general it would be nice to know which cells have been executed recently and which ones are from a while ago so that I can track dependencies between them. In the web ui, displaying "Last executed time" via an extension helps with this. 

I saw two previous issues #411  and #432 discussing something similar, but they have been closed - not sure what their status ended up as.

Thanks again for your work on ein, it's awesomely useful.

**Comment by dickmao** [comment]
> 1. ... one of the cells list errors

The browser notebook halts execution upon error, and https://github.com/dickmao/emacs-ipython-notebook/commit/d547048a5d7f3260d8a8828364b702a24d2d6f90 attempts to replicate that behavior.  Alas, introducing multiple threads breaks undo.  One unappealing solution is to block upon receiving `ein:worksheet-execute-all-cells`.  Jumping to the cell that errors only make sense if I were to go the blocking route, which I won't.

> 2. "Last executed time" via an extension helps with this.

https://github.com/millejoh/emacs-ipython-notebook/blob/old-master/lisp/ein-timestamp.el remained an unfinished feature of a discontinued version of EIN.  You are welcome to dig it out, but it requires manual integration and potentially breaks things.
