### ISSUE TITLE
wrong type argument stringp nil when trying to open a notebook

### ISSUE THREAD

**Issue by exp2ipi** [millejoh/emacs-ipython-notebook#724]
I was working in a notebook when the worksheet window simply disappeared (the buffer apparently got killed). After that, trying to re-open the notebook keeps throwing an error (see screenshot), and the messages buffer says 
`ein: [info] Notebook 100_Numpy_random.ipynb is already open`, however that buffer definitely does not exist.

When I eval `(ein:notebook-get-opened-notebook "http://127.0.0.1:8888" "100_Numpy_random.ipynb")`, I get back a message saying `Apparently a circular structure is being printed`

Restarting the jupyter server, killing ein buffers, etc. does not fix the problem.

![image](https://user-images.githubusercontent.com/338250/86108009-7c72e300-ba77-11ea-8a6b-9288382fb74e.png)

**Comment by dickmao** [comment]
EIN cannot account for a buffer that "simply disappears" (that is the real problem).

You can reset the state manually via `M-: (ein:notebook-tidy-opened-notebooks (ein:notebook-get-opened-notebook 8888 "100_Numpy_random.ipynb"))` but it's obviously easier to restart emacs.

For the future, please follow the README to report bugs.

If you can reproduce the disappearing buffer, please reopen.

**Comment by exp2ipi** [comment]
@dickmao it is not "obviously easier" to restart emacs for users who are used to weeks-long uptimes with 100s of buffers open. It is "obviously easier" to issue M-x commands in case ein misbehaves. If it can get into a bad state (which is FWIW I'm observing a lot), instructions on how to reset it should be added to the readme of FAQ.

I am currently observing that I am unable to kill a notebook buffer (exact behavior with #614 which was just closed with no investigation it appears). And yes, it appears that in order to kill that buffer I need to restart emacs. This is an extremely unfortunate behavior and tbh ruins this otherwise wonderful package.
