### ISSUE TITLE
ob-ein  fails to evaluate ein-python source block

### ISSUE THREAD

**Issue by exp2ipi** [millejoh/emacs-ipython-notebook#725]
Trying to execute the following block fails with `No org-babel execute function for ein-python`:

```
#+BEGIN_SRC ein-python
2 + 2
#+END_SRC
```

`org-babel-load-languages` is set to `((ein-python . t) (emacs-lisp . t) (ein . t))`

**Comment by dickmao** [comment]
Please follow the README to report bugs, and reopen the issue as necessary.
```
emacs -nw -Q -f package-initialize --eval "(setq debug-on-error t)" \
  --eval "(require 'ob-ein)" \
  --eval "(setq org-babel-load-languages '((ein . t)))" \
  foo.org
```
![alekseyev](https://user-images.githubusercontent.com/7578770/86114596-c0c2ab00-ba98-11ea-9d58-b20645700d68.gif)
