### ISSUE TITLE
Migrating from emacs-jupyter and using remote kernels

### ISSUE THREAD

**Issue by dangom** [millejoh/emacs-ipython-notebook#726]
Dear devs,

I am looking to replicate my previous emacs-jupyter setup with ein. I've been giving it a shot, but I'm missing some features which I believe ein implements, but I'm not aware how to use them.

- In emacs-jupyter, I'd connect to a remote kernel in org-mode by passing a `:session \ssh:remote` header arg. Emacs-jupyter takes care of opening the appropriate ssh tunnels and managing the connection from then on.
Is it possible to replicate this behaviour with ein?

- I've noticed that if I run `ob-ein`, I cannot switch to a REPL by using `C-c C-v C-z` because ein-python doesn't implement org-babel-initiate-session. Is there a workaround for that? Ideally one that works remotely as well :)

- What is the recommended workflow to use ein with standard python files and a REPL? Do I always have to go through a notebook server first?

Any pointers towards getting these issues sorted out would help me a lot, and I'd be glad to contribute with documentation once I get these things going.

Thank you in advance.

**Comment by dickmao** [comment]
1. No, the logic performed by emacs-jupyter to both instantiate and talk to "microkernels" is highly nontrivial and not at all implemented in EIN.

2. REPL is not a first-class citizen as it is for emacs-jupyter.  Rather it is manifest in what EIN calls the "shared output cell" that is largely hidden from public view.  It would be significant effort to have it plug into `C-c C-v C-z`.  Short answer is no.

3. Elpy is the way to go here.  No need for EIN which largely serves a student population whose teaching materials often (rather unfortunately) include ipynb files.
