### ISSUE TITLE
Good ways to start the notebook in a different directory?

### ISSUE THREAD

**Issue by jsigman** [millejoh/emacs-ipython-notebook#727]
Say that I want to run a notebook from a project root directory, but the `.ipynb` file exists in a subfolder. Is there a good way to start the kernel in a different folder?

Right now, I am changing the directory in the first cell of the notebook:

```python
import os
os.chdir('..')
```

If I try to start a notebook, `C-c C-o`, then select the project root directory, the notebook's home directory still starts inside the subfolder. Is there a good way to manage this so I can elegantly import from project modules?

Thanks

**Comment by dickmao** [comment]
I would think the shell behaviors of the notebook protocol are well outside EIN's scope.  I would google this.
