### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by jluttine** [millejoh/emacs-ipython-notebook#73]
I tried to use ein but I'm not able to get it working. Installation from melpa.org went fine with the instructions in the documentation, I think. I can use `M-x ein:<TAB>` to see all ein commands. But if I try to use any of the commands, I get the following kind of error:
```
Cannot open load file: no such file or directory, ein/lisp/ein-notebooklist
```
That is, nothing works. Any ideas what could be wrong?

**Comment by millejoh** [comment]
Jaako - what happens when you try `M-x ein:notebooklist-open`?

**Comment by jluttine** [comment]
I got it working by installing spacemacs and using ipython-notebook layer there. I'm not sure anymore did I try that particular command. I think I tried quite many that sounded useful but not sure about that. Anyway, this package works via spacemacs and it's great! :+1:
