### ISSUE TITLE
EIN doesn't give results when in org-mode and doesn't show plots in standard-mode

### ISSUE THREAD

**Issue by NicoloZorzetto** [millejoh/emacs-ipython-notebook#731]
Hello, I'm a MacOS Catalina, Emacs 26.3 and Org-mode 9.1.9 user.

I have tried to plot a graph both in the 'standard' EIN mode (using a notebook) and inside an org-block. This is the snippet that I've used:
```
import numpy, math, matplotlib.pyplot as plt
  %matplotlib inline
  x = numpy.linspace(0, 2*math.pi)
  plt.plot(x, numpy.sin(x))

print("Hello")
```
When inside a notebook the output is:
```
In [10]:-------------------------------------
  import numpy, math, matplotlib.pyplot as plt
  %matplotlib inline
  x = numpy.linspace(0, 2*math.pi)
  plt.plot(x, numpy.sin(x))

print("Hello")
--------------------------------------------
Hello
```
While inside an org-block this is the result:
```
#+NAME: 20722AC3-F5EA-46C3-9909-A05732392A76
#+BEGIN_SRC ein-python :session localhost :results output :exports both
  import numpy, math, matplotlib.pyplot as plt
  %matplotlib inline
  x = numpy.linspace(0, 2*math.pi)
  plt.plot(x, numpy.sin(x))

print("Hello")
#+END_SRC

#+RESULTS: 20722AC3-F5EA-46C3-9909-A05732392A76
: [....]

```
I was curious so I tried a snippet without plotting, sure enough when in a notebook this worked just fine but org-blocks seem to not want to collaborate.
**Notebook**
```
In [12]:----------------
print("Hello")
-----------------------
Hello
```
**Org-block**
```
#+NAME: 07F26158-7FCE-4731-A20C-84ED770D6694
#+BEGIN_SRC ein-python :session localhost :results output :exports both
print("Hello")
#+END_SRC

#+RESULTS: 07F26158-7FCE-4731-A20C-84ED770D6694
: [....]
```

Also this message comes up in the miniuffer every time I try to run the plotting snippet:
`ein: [warn] ein:cell-append-mime-type: no viewer method found in mailcap`
But when I try to run an org-block without plots this is the message:
`Code block evaluation complete. [2 times]`

This is everything related to EIN in my config:
`(package-install 'ein)`
I open notebooks by finding the one I want to visit via find-file and then pressing C-c C-o and for Org-mode just <s TAB and then complete with the flags(?) you can see in the snippets.

**Comment by NicoloZorzetto** [comment]
Ok installed `ob-ipython` (reccomend to ass as a dependency or merge the two or at least mention in the readme) and now it compiles when in org-mode and shows that a file has been produced but can't be shown as inline image. 
The standard notebook still gives no plot output, inline or as file. Am I missing something more?

**Comment by dickmao** [comment]
https://github.com/millejoh/emacs-ipython-notebook/issues/730#issuecomment-662079551 addresses `ein: [warn] ein:cell-append-mime-type: no viewer method found in mailcap`.

https://github.com/millejoh/emacs-ipython-notebook/issues/725#issuecomment-651701199 is a very basic test case for org blocks.  When you press `C-c C-c`, emacs is supposed to ask you where you want to start a jupyter server.  A likely explanation is you're `C-g` quitting out of that sequence.

**Comment by NicoloZorzetto** [comment]
Hello, mailcap is installed on my system. I am sure I am not pressing `C-g` but when I first press `C-c C-c` it doesn't ask me if I want to start a jupyter server, just if I want to evaluate the block

**Comment by dickmao** [comment]
Basic test case:

`emacs -nw -Q -f package-initialize --eval "(setq debug-on-error t)"   --eval "(require 'ob-ein)"   --eval "(setq org-babel-load-languages '((ein . t)))" --eval "(ein:dev-start-debug)" foo.org`

![zorzetto](https://user-images.githubusercontent.com/7578770/89123211-adda3680-d49b-11ea-9aeb-6f74cc54bdf9.gif)

**Comment by dickmao** [comment]
> Ok installed `ob-ipython`

ob-ipython has nothing to do with EIN.
