### ISSUE TITLE
Confused about README: "contrary to the prevailing documentation, which should be disregarded."

### ISSUE THREAD

**Issue by Noah-Huppert** [millejoh/emacs-ipython-notebook#732]
Hi, I am just setting up Ein 🤠  and got a little confused by the statement in the `README.md`:

> No require statements, e.g. (require 'ein), are necessary, contrary to the prevailing documentation, which should be disregarded.

Am I to understand that all of the documentation on `http://millejoh.github.io/emacs-ipython-notebook/` is to be disregarded? Or that just cases where the documentation website says `(require 'ein)` is needed should be ignored?

Adding to my confusion is the fact that documentation website it does not recommend `(require 'ein)` unless the MELPA installation didn't work.

**Comment by dickmao** [comment]
Please, @millejoh , if you're out there, please retire `http://millejoh.github.io/emacs-ipython-notebook`

Previous mentions:
https://github.com/millejoh/emacs-ipython-notebook/issues/695#issuecomment-609893084
https://github.com/millejoh/emacs-ipython-notebook/issues/705#issuecomment-625217810
