### ISSUE TITLE
EIN doesn't mark modified notebook buffers as modified

### ISSUE THREAD

**Issue by peterewills** [millejoh/emacs-ipython-notebook#733]
When I modify a notebook buffer, Emacs is not aware that the buffer has been modified. It therefore doesn't have any prompt when I close emacs with unsaved notebooks. It would be nice to have it so that if I try and close emacs without saving my notebooks, I get a prompt with an option to save.

I'm on version `ein-20200712.24`

**Comment by dickmao** [comment]
#525 had gone to some lengths to avoid this.  Reopen issue following FAQ for reporting bugs if the following basic test doesn't work.
```
emacs -nw -Q -f package-initialize --eval "(setq debug-on-error t)" --eval "(ein:dev-start-debug)"
```
![wills](https://user-images.githubusercontent.com/7578770/89532509-e5105680-d7bf-11ea-8ef2-e84567952b3c.gif)
