### ISSUE TITLE
What happened to ein:slice-image?

### ISSUE THREAD

**Issue by peterewills** [millejoh/emacs-ipython-notebook#735]
I see that `ein:slice-image` was removed by commit `9ac1bf6`, which from my log looks like a part of PR 59 (the closest downstream merge commit is ` 759c6ba - Merge pull request #59 from dickmao/dev`). If I check out the previous commit (`0ee5f01`) then `ein:slice-image` is still present.

I am just curious as to why it was removed. I tried looking at `https://github.com/millejoh/emacs-ipython-notebook/pull/59` but it directs me to issue 59, which seems unrelated. Perhaps I'm confused about something here.

(By the way - thanks for all your hard work maintaining EIN! It's a key part of my daily workflow, I really appreciate it.)

**Comment by dickmao** [comment]
`ein:slice-image` is an ill-advised hack dating back to https://github.com/tkf/emacs-ipython-notebook/issues/94 (the original repository).  It's not clear how or why anyone would notice its removal.

**Comment by peterewills** [comment]
I was using it to help smooth out the scrolling issues arising from large images - basically, the initially stated intent. Any particular reason to remove it? Asked another way, will I see problems if I add it back in myself?

**Comment by dickmao** [comment]
I had no confidence in `ein:slice-image` (particularly in light of https://github.com/hlissner/doom-emacs/issues/2545), which was neither documented nor tested.

I don't recommend manually adding it back in, but everyone's emacs is his own, and that is the overriding virtue of emacs.

Generally, I recommend leaving off `ein:output-area-inlined-images` (the default setting) and washing one's hands completely of the inherent complications scrolling images within emacs's display buffers, but that seems to be an unpopular choice.
