### ISSUE TITLE
using show-paren-mode makes unclosed parens in code cells move point to end of file

### ISSUE THREAD

**Issue by vwood** [millejoh/emacs-ipython-notebook#736]
using (show-paren-mode 1) and show-paren-style parenthesis (though I imagine others might do it too) means if I put the point just before an unclosed paren in a code cell, the point is moved to the very end of the file, or a "matching" paren in another code cell entirely (which was very disorienting until I figured out what was happening).

For context I'm using python notebooks.
 
The point shouldn't be moved at all, it makes editing difficult having a banned position for your cursor. I'll let you know if I find a workaround in the meantime.

**Comment by dickmao** [comment]
Yes!  Thank you for delineating the exact circumstances that reproduce the jarring "jump down" I've observed but never bothered to nail down.  Commit 8311830 attempts a fix.

EIN is getting dangerously close to usability!
