### ISSUE TITLE
401 when trying to ein:run in windows

### ISSUE THREAD

**Issue by JuanPabloMF** [millejoh/emacs-ipython-notebook#738]
[error] request--callback: peculiar error: 401
ein: [error] Login to http://127.0.0.1:8888 failed, error-thrown (error http 401), raw-header HTTP/1.1 401 Unauthorized
Server: TornadoServer/6.0.4
Content-Type: text/html; charset=UTF-8
Date: Fri, 07 Aug 2020 21:35:09 GMT
X-Content-Type-Options: nosniff
Content-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report
Content-Length: 9237

Emacs version: 26
WSL 2
Ubuntu 18.04

**Comment by dickmao** [comment]
`M-x ein:dev-start-debug`
`M-x ein:run [fail]`
`M-x ein:log-pop-to-all-buffer`
`C-x b RET *ein server*`

**Comment by JuanPabloMF** [comment]
Tried the sequence of commands, couldn't get much of it. Should I post the output on *ein-server* or can I show any more details about the configuration/error message?

**Comment by JuanPabloMF** [comment]
Fourth attempt and it worked!
