### ISSUE TITLE
Can't undo split/merge cells

### ISSUE THREAD

**Issue by jluttine** [millejoh/emacs-ipython-notebook#74]
After splitting or merging cells, undo doesn't do anything. It doesn't undo the split/merge but it doesn't undo any changes before that either.

**Comment by millejoh** [comment]
Do you have Ein:Worksheet Enable Undo set to full? I don't use this feature much since I am unfamiliar with the code and it carries the scary warning that it might corrupt to buffer. The code appears to at least try to record undo information for splitting and merging.

**Comment by millejoh** [comment]
Duplicate, moving to #151.  Maybe I will actually fix this time!
