### ISSUE TITLE
org-mode print not producing output

### ISSUE THREAD

**Issue by DJJ88** [millejoh/emacs-ipython-notebook#742]
Hello,

I cannot get the output of pring using ein-python in org-mode

  #+BEGIN_SRC ein-python :session http://127.0.0.1:8888/Untitled.ipynb :result raw
  print("3")
  #+END_SRC

On the other hand this works as expected

  #+NAME: 711f7857-da46-4895-9f52-8147ecd21a16
  #+BEGIN_SRC ein-python :session http://127.0.0.1:8888/Untitled.ipynb :result raw
    "3"
  #+END_SRC

  #+RESULTS: 711f7857-da46-4895-9f52-8147ecd21a16
  : '3'

Best regards,
Jeremie

Org mode version 9.3.7 (release_9.3.7-725-g7bc18e @ /home/djj/src/org-mode/lisp/) 
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2020-09-01
version on ein: 20200901.1226 installed from  melpa

**Comment by dickmao** [comment]
With `:results output`
```
#+begin_src ein :session localhost :results output                              
print("displayed value")                                                        
"returned value"                                                                
#+end_src                                                                       

#+RESULTS: 39fc35a9-73bc-4e31-8539-ec19161adb59
: displayed value                                                               
: 'returned value'
```

Without `:results output`
```
#+begin_src ein :session localhost                                              
print("displayed value")                                                        
"returned value"                                                                
#+end_src                                                                       

#+RESULTS: 39fc35a9-73bc-4e31-8539-ec19161adb59
: 'returned value'
```

1. `:result` is *prima facie* undocumented and possibly a no-op.  I would use `:results`.
2. We do not support unreleased versions of emacs (including 28.0.50)
3. I would avoid `:results raw` (or, in your case, `:result raw` which is ill-advised also for reason 1).
4. The semantics for `:results output` in conjunction with `:session` are described https://orgmode.org/manual/Results-of-Evaluation.html about halfway down the page.  The above example behavior should hew to that documentation.

**Comment by DJJ88** [comment]
Many thanks for your reply. It was a false alarm. Everything works as intended with :results

#+NAME: 33f9165b-967d-467d-8d20-0db4fa6fee46
#+BEGIN_SRC ein-python :session http://127.0.0.1:8888/Untitled.ipynb :results output
print("hello")
#+END_SRC

#+RESULTS: 33f9165b-967d-467d-8d20-0db4fa6fee46
: hello
