### ISSUE TITLE
login fails instead of asking for token

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#743]
`M-x ein:notebooklist-login` fails:

```
[error] request--callback: peculiar error: 401
ein: [error] Login to http://172.21.30.235:8080 failed, error-thrown (error http 401), raw-header HTTP/1.1 401 Unauthorized
Server: TornadoServer/6.0.4
Content-Type: text/html; charset=UTF-8
Date: Mon, 21 Sep 2020 16:57:14 GMT
X-Content-Type-Options: nosniff
Content-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report
Content-Length: 9237
```

I expected to be asked for a token.
chrome works fine.

**Comment by dickmao** [comment]
Restart from scratch.  `M-: (ein:notebooklist-token-or-password "http://172.21.30.235:8080")` should return nil, and if so, then `C-u C-M-x` on `ein:notebooklist-login-error` to set a breakpoint, then reproduce the error, then figure out why it's not hitting https://github.com/millejoh/emacs-ipython-notebook/blob/0416f72d4ca30c2541795f46971a2829e140a1c0/lisp/ein-notebooklist.el#L712

**Comment by sam-s** [comment]
`ein:notebooklist-token-or-password` returns a wrong token.
How do I reset it?

**Comment by dickmao** [comment]
My bad.  Pushed e03de47.  Thanks.
