### ISSUE TITLE
Text-read-only issues

### ISSUE THREAD

**Issue by Jerror** [millejoh/emacs-ipython-notebook#746]
I'm running spacemacs with ein-20200926.403. For some reason, after performing very few actions (running a copy cells or copying some text) ein stops letting me run cells and save notebooks with error "Text is read-only." The buffer is not read-only and the text is not read-only (aside from the very end of each code cell, of course.) Closing and reopening notebooks does not fix the issue. Neither does restarting kernels or stopping and restarting the ein session. Only restarting emacs fixes the problem, and the problems arises almost immediately once again, rendering ein completely unusable.

**Comment by dickmao** [comment]
This has been also been reported in #721.  I've been lax in investigating as the plaintiffs both here and there haven't followed the README instructions to report bugs.

**Comment by Jerror** [comment]
Sorry about that! I never expected to find bug report instructions in the FAQ, so I never looked.

Anyway, the instructions make testing on spacemacs impossible. I'll have to drop the -Q flag, but I could use a minimal .spacemacs file (the template that ships with spacemacs with the sole adjustment of adding the ipython layer.) Is that acceptable?

If you want spacemacs users to contribute to the development and testing of this package you'll want to come up with bug report instructions for spacemacs users. You can't run spacemacs without the init file and the spacemacs init file is not meant to be modified. All user configuration is done within the .spacemacs file.

**Comment by Jerror** [comment]
Thanks for pointing to the other thread. It solved the issue for me. My version of emacs had the bug in json-encode-string. I just installed an older version and the problem is resolved.

**Comment by dickmao** [comment]
Great.  Spacemacs, given all its baggage, is anathema to the clinical control of -Q.  Minimally though `ein:dev-bug-report-template`, as it automatically records your underlying version of emacs, is a _sina qua non_ starting point for discussion.  The template also forces users to at least give a thought to providing an minimum reproducible example (as opposed to a hand-wavy, high-level description of how to surface the bug).

**Comment by Jerror** [comment]
Got it! Thanks again. Love the way you write, by the way.
