### ISSUE TITLE
Cannot open notebook (adapted protocol version)

### ISSUE THREAD

**Issue by gmoutso** [millejoh/emacs-ipython-notebook#747]
I haven't used ein for a while. I fired it up and can succesfully create a notebook and run a cell. I cannot open though an open notebook. The server is running remotely and have an ssh port forward to it. It is a jupyterlab server. It happens with notebooks that log on the server
Adapting from protocol version 5.1 (kernel 8168f2fa-816a-411a-901b-3e9e2e0ab47e) to 5.3 (client).
It does not happen when I open a notebook created with another kernel.

The message is
```
[error] request--callback: peculiar error
```
Without debug the log has
```
12:03:51:089: [verbose] Retry content-query-contents #0 in response to nil @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
12:03:52:608: [verbose] Retry content-query-contents #1 in response to nil @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
12:03:54:633: [verbose] Retry content-query-contents #2 in response to nil @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
12:03:57:156: [error] ein:content-query-contents--error http://127.0.0.1:8889/drawdownchar/riskmeasures/rankriskcorr-Copy1.ipynb REQUEST-STATUS timeout DATA interrupt
 @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
```
with ein:dev-start-debug 
```
12:02:49:192: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|4a24028c|8cb26d755f7a3fa28c0636e625d0b493|1522089177 @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
12:02:50:249: [verbose] Retry content-query-contents #0 in response to nil @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
12:02:50:770: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|4a24028c|8cb26d755f7a3fa28c0636e625d0b493|1522089177 @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
12:02:50:772: [debug] ein:query-contents--complete STATUS: nil DATA: nil @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
12:02:51:776: [verbose] Retry content-query-contents #1 in response to nil @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
12:02:52:779: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|4a24028c|8cb26d755f7a3fa28c0636e625d0b493|1522089177 @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
12:02:52:781: [debug] ein:query-contents--complete STATUS: nil DATA: nil @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
12:02:53:827: [verbose] Retry content-query-contents #2 in response to nil @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
12:02:55:330: [debug] EIN:QUERY-PREPARE-HEADER: Found xsrf: 2|4a24028c|8cb26d755f7a3fa28c0636e625d0b493|1522089177 @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
12:02:55:332: [debug] ein:query-contents--complete STATUS: nil DATA: nil @#<buffer *ein:notebooklist http://127.0.0.1:8889*>
12:02:56:378: [error] ein:content-query-contents--error http://127.0.0.1:8889/drawdownchar/riskmeasures/rankriskcorr-Copy1.ipynb REQUEST-STATUS timeout DATA interrupt
 @#<buffer  *Minibuf-1*>
12:02:56:406: [debug] ein:query-contents--complete STATUS: nil DATA: nil @#<buffer  *Minibuf-1*>
```

jupyterlab 2.2.4
protocol version 5.1 or 5.3

**Comment by gmoutso** [comment]
However I can create a new notebook with the kernel that offends (the one that says adapting from protocol version...). That is, I can always create notebooks in ein whatever the kernel, but only open pre-existing ones when there was not protocol-version-adapting.

**Comment by dickmao** [comment]
> It happens with notebooks that log on the server
> Adapting from protocol version 5.1 (kernel 8168f2fa-816a-411a-901b-3e9e2e0ab47e) to 5.3 (client).

Your English and high-level descriptions make this hard to comprehend.  You use the word "kernel" in two contexts -- a running **_ipykernel_** driving "only open pre-existing [notebooks] when there was not protocol-version-adapting", and a **_kernelspec_** with which you "can always create notebooks in ein whatever the kernel."

If your flagging interest in ein can sustain it, perhaps you could present a minimum example that triggers the error with less potentially confusing prose as we don't share a common understanding of what "kernels" are.  Thanks for your interest.

**Comment by gmoutso** [comment]
As flagging as it may have been, your response has been conclusive to my interest. You are welcome.
