### ISSUE TITLE
Ein and Pyvenv not working?

### ISSUE THREAD

**Issue by Alf0nso** [millejoh/emacs-ipython-notebook#748]
I'm not sure if they are suppose to be compatible or not really, but when I start pyvenv and specify a virtual-env to work on, ein doesn't really recognize don't recognize does virtuenv... if I install a package on the virtual env I'm working on ein doesn't find him

**Comment by dickmao** [comment]
Virtualenv and conda generally confuse me.  I am unfamiliar with the whole pyenv enterprise, which I've not given a thought when developing EIN.

Unless I have your exact workflow as requested in the README, e.g., 

1. This is how I make my pyenv
2. These are the keystrokes I make in emacs
3. This is what I expect to happen

I am unmotivated to address.

**Comment by HumHongeKamyaab** [comment]
can check solution at #793

**Comment by Alf0nso** [comment]
Thanks :)
