### ISSUE TITLE
Close notebook list after opening a notebook?

### ISSUE THREAD

**Issue by jluttine** [millejoh/emacs-ipython-notebook#75]
Is it possible to open a notebook without having the notebook list staying in another window? If using `ein:notebooklist-open`, it opens in one of the other windows and the chosen notebook opens in the original window. But then the notebook list stays in the other window. Minor inconvenience. Do you know if it's possible to open the notebook list in the same window as the notebook will open or to have the notebook list buffer to close after choosing a notebook?

If I have only one window, the notebook list is opened in a new window and that window doesn't close after opening the notebook, so I'm left with two windows although I had only one previously.

Minor issues.. :)

**Comment by maxhgerlach** [comment]
I would also much prefer the notebooklist window to be replaced by the newly opened notebook! 

This often breaks my workflow because I frequently lose the window containing the second notebook I wanted to keep open..

**Comment by millejoh** [comment]
By default ein calls `pop-to-buffer` to bring up a newly opened notebook. My emacs-fu is really quite weak, but at the very least I am sure therein lies the issue you are seeing.

Also - note that you can call  `ein:notebooklist-open-notebook-global` to open a notebook without having to go back to the notebooklist buffer.

**Comment by maxhgerlach** [comment]
For now I mostly work around this issue by opening new frames for different notebooks.

**Comment by maxhgerlach** [comment]
> By default ein calls pop-to-buffer to bring up a newly opened notebook. My emacs-fu is really quite weak, but at the very least I am sure therein lies the issue you are seeing.

Thanks for the pointer, @millejoh! I think the best way to tune this behavior to one's liking is to make use of one of the packages that tweak how popped up windows are dealt with. [Shackle](https://github.com/wasamasa/shackle) works well for me. @jluttine, the behavior you were looking for (which I also prefer) can be had by this snippet in your `init.el`. 

```elisp
;;;; let's use package Shackle to prevent ein notebook buffers to pop
;;;; up in the "other window"
(require 'shackle)
(setq shackle-rules '(("\\`\\*ein: .+?\\.ipynb\\*\\'" :regexp t :same t)))
(shackle-mode)
```

It relies on the standard way EIN notebook buffers are named. Things like tracebacks will still pop up in a secondary window.
