### ISSUE TITLE
ANSI escape string not handled correctly?

### ISSUE THREAD

**Issue by hnisonoff** [millejoh/emacs-ipython-notebook#751]
Thank you very much for the great package. I am currently using it with Julia and I noticed that sometimes these escape codes show up when I print objects. Is this something that can be fixed? 
```
x = Dict("A" => [1,2], "B"=> [true, false])
DataFrame(x)
Out [11]:
2×2 DataFrame
│ Row │ A     │ B    │
│     │ [90mInt64[39m │ [90mBool[39m │
├─────┼───────┼──────┤
│ 1   │ 1     │ 1    │
│ 2   │ 2     │ 0    │
```

**Comment by dickmao** [comment]
Thanks for reporting this bug.  Commit bf1ca5b

**Comment by hnisonoff** [comment]
Thanks!
