### ISSUE TITLE
Worksheet only renders on the first installation with straight

### ISSUE THREAD

**Issue by jsigman** [millejoh/emacs-ipython-notebook#752]
I am encountering a strange issue.

My worksheet only renders on the first time that I run `ein` after an install with `straight.el`. If I restart emacs, it will properly start the jupyter kernel, but never start render the notebook, and I will be stuck with a json buffer forever.

It works again if I clear my `ein` install and re-install with `straight.el`. I am not sure what state information could even account for this difference, since it should be loading the same elisp files either way. When I toggle `debug-on-error`, it breaks with the following:

![image](https://user-images.githubusercontent.com/2373529/97308066-d1acde80-1836-11eb-891b-0fbeb3209f95.png)

**Comment by dickmao** [comment]
What do `M-: (featurep 'ein-core)` and `M-: (featurep 'ein-utils)` return?

Your emacs appears to know `ein:query-notebook-version--complete` which comes
from the former, but cannot resolve `ein:log` which comes from the latter, *but*
the former requires the latter, so it's not making sense.

**Comment by jsigman** [comment]
It returns `t` for both, and it returns them regardless of whether the notebook can successfully render.

**Comment by dickmao** [comment]
Doh, I meant `M-: (featurep 'ein-log)`.  This is almost certainly nil for you.  Somehow the autoload mechanism isn't traversing the dag of requires to pull in ein-log.el.

Please follow the README to report this potential bug.  If I can't reproduce it, I can't help you.

**Comment by jsigman** [comment]
I did try this, and it returns `(featurep 'ein-log) => t`, actually.

**Comment by dickmao** [comment]
Ah, that's good.  Otherwise, it'd be a harder problem.

Ah, it's not void-function, it's invalid-function (i am talking to myself).  that means, ein:log exists... it's just corrupted somehow.

**Comment by jsigman** [comment]
So I actually did fix it by changing `(defun ein:log ...)` to `(defmacro ein:log ...)`. I have no idea what the broader implications of this  are to the code base, but  it fixed it for me... Thought you might want to know

**Comment by dickmao** [comment]
This https://github.com/raxod502/straight.el/issues/451 looks somewhat related.

I wonder what `M-: (mapcar #'package-desc-dir (cdr (assq 'ein package-alist)))` says.  I suspect there is a rogue version of ein that foils the straight version in the bizarre way you're observing.

The emacs package situation is inexecrable.
