### ISSUE TITLE
Cannot change input method

### ISSUE THREAD

**Issue by matsievskiysv** [millejoh/emacs-ipython-notebook#753]
Cannot change input method in `ein` buffers.
Steps to reproduce:

1. Open emacs `emacs -q --eval '(package-initialize)'`
1. Connect to jupyter, create new notebook and open it
1. Type <kbd>asdf</kbd>
1. Change input method <kbd>M-x `set-input-method` russian-computer</kbd>
1. Notice that indicator in the bottom left of the buffer changed from `U` to `RUU`
1. Type <kbd>asdf</kbd>
1. Observe that the last 4 characters in buffer are `asdf` and not `фыва`

---
**Edit**
For some reason input method behaves normally when typing inside parenthesis. If in the example above change <kbd>asdf</kbd> to <kbd>(asdf)</kbd>, input would work as expected.

**Comment by dickmao** [comment]
It fails only when inserting at the end of the cell (if the cell is empty, then it fails at the beginning since in that case beginning and end are the same).  This looks hard.

**Comment by dickmao** [comment]
Reported https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44466

**Comment by dickmao** [comment]
If you compile your own emacs, you may want to pull in this latest fix:

https://github.com/emacs-mirror/emacs/commit/19da602991538e03648a82214cbb1bcc9a6ec14a
