### ISSUE TITLE
Display inline image when plotting in Wolfram language for Jupiter.

### ISSUE THREAD

**Issue by tangw** [millejoh/emacs-ipython-notebook#756]
It is great to see that the Wolfram language kernel can be added to Jupiter and is accessible in Emacs via EIN. But I cannot reproduce the same inline images display as shown in #589. I've enabled the options setting for inline images. It works for Python and R kernels. Could anyone share a little more details? Or shall it be considered as an issue?
![Screen Shot](https://user-images.githubusercontent.com/1703956/100518293-49339d80-3156-11eb-9535-60348a808f43.png)

**Comment by dickmao** [comment]
Thanks for reporting the bug.
