### ISSUE TITLE
Quick fix in documentation

### ISSUE THREAD

**Issue by BuddhiLW** [millejoh/emacs-ipython-notebook#764]
There is miss a "+" in "#+BEGIN_SRC ein-python (...)"

Ob-ein section,

Snippet:

#BEGIN_SRC ein-python :session localhost
  import numpy, math, matplotlib.pyplot as plt
  %matplotlib inline
  x = numpy.linspace(0, 2*math.pi)
  plt.plot(x, numpy.sin(x))
#+END_SRC

**Comment by dickmao** [comment]
Thanks.  Incidentally, refer to FAQ in the README.rst to render your julia plots.
