### ISSUE TITLE
Embedding Julia Plot Images on Notebook

### ISSUE THREAD

**Issue by BuddhiLW** [millejoh/emacs-ipython-notebook#765]
With the following code,
`` ssh
convert %s -background white -alpha remove -alpha off - | display -immutable
``
I could render the image. Perfect.

But, now, I would like to embed it on Emacs! I already have turned on the option
Ein:Output Area Inlined Images

What is the next step?

(Thanks for solving the rendering problem, btw. It already goes a long way)

**Comment by dickmao** [comment]
There is no next step.  If `C-h v RET ein:output-area-inlined-images` is `t`, then images render inside emacs.
