### ISSUE TITLE
outputs are not displayed

### ISSUE THREAD

**Issue by indigoviolet** [millejoh/emacs-ipython-notebook#767]
I've been finding that in some scenarios, no outputs are displayed in my ipynb notebook. By "output", I mean I type `2`, hit `C-c C-c` and expect to see `2` in the output area if things are working (as below), but the output area is empty.

![image](https://user-images.githubusercontent.com/114010/103380884-07707c80-4a9f-11eb-8dec-996c2a4fb76c.png)

If I `print()`  in the cell, that output is displayed as expected.

The things correlated to this are that cells that would previously display `<IPython.core.display.HTML object>` now render their HTML. I'm not exactly sure when this issue was introduced: I suspected it was introduced in https://github.com/millejoh/emacs-ipython-notebook/commit/a019ee3994585e4ed4700d2591d693fda3232616, but reverting to just before that didn't fix it either in my hands. When I reverted to https://github.com/millejoh/emacs-ipython-notebook/commit/02ab452227197b42b18fd9fa0ae006b1a893f5a9, I have not experienced the issue.

I can help with more information if you can suggest some investigation.

**Comment by dickmao** [comment]
Yes, I was waiting for someone to notice.  This line messed things up badly:

https://github.com/millejoh/emacs-ipython-notebook/commit/f1de0cff9458170e52ea5bf3cdc96f7a52a16ab7#diff-4b3057d0c60634ac3d31d8389266b67d17d6dcfa938b9a34c6a1886ca3ff9100R168

Sorry.
