### ISSUE TITLE
Strange `eldoc error: (text-read-only)' when create new Notebook

### ISSUE THREAD

**Issue by blldw** [millejoh/emacs-ipython-notebook#769]
I encounter the strange `eldoc error: (text-read-only)' when editing in a new created Notebook. For example, I want to type `import`, but the error occurs just after I had typed a single `i'. However, this error won't occur in another computer.  These two computers both run Ubuntu 18.04 OS, and use the same emacs configurations. Can I assure the error does not related with emacs and EIN configuration since EIN works well on other computers? If so, what could be the reason resulting my problem? 

P.S.: The error won't occur either if editing in an existing .ipynb file, which is not created through 'New Notebook' menu from ein:notebooklist buffer.

**Comment by dickmao** [comment]
eldoc is independent of EIN.  You need to `(setq debug-on-error t)` to get a backtrace.
