### ISSUE TITLE
Failed to autocompletion in Notebook buffer

### ISSUE THREAD

**Issue by blldw** [millejoh/emacs-ipython-notebook#770]
Please see the closed issue #769. I disabled eldoc mode, and I found the following error message after I typed a single character in some problematic notebook buffers:

Company: An error occurred in auto-begin
Text is read-only

However, after made a comparison with normal-working notebook buffer (which I mean the autocompletion work well), I found the label in buffer header different: "IP[y]: [python3]" vs. "IP[1]: [python3]".

does this information make sense? does "IP" mean "IPython"? Then what the 'y' and '1' mean?

Any help would be nice, thank you.

**Comment by dickmao** [comment]
IP[y] versus IP[1] is inconsequential.  "y" is the init state, "1" is the number of cells executed.

`Company: An error occured in auto-begin` comes from `company.el` line 1440.  Company, like eldoc, is independent of EIN.  As in #769 , the prescription remains the same.  `M-x toggle-debug-on-error` to get a backtrace.
