### ISSUE TITLE
Support autosave/checkpoint

### ISSUE THREAD

**Issue by YizhePKU** [millejoh/emacs-ipython-notebook#772]
Is there a way to save/restore a checkpoint?

Reading issue #222, I think ein used to have `ein:notebook-restore-to-checkpoint`. Is that feature still available?

This, plus no cell-level undo(issue #512), makes me really nervous when doing cell operations.

**Comment by dickmao** [comment]
>  As emacs users we both prefer and have the luxury of saving the old-school way, that is, when we explicitly C-x C-s. 

In #344 I argue the notion of checkpointing is a Web 2.0 phenomenon.  For most of computing history, programmers explicitly saved their work, and checked in "snapshots" to their version control.  I will concede that the webcentric jupyter "way of doing things" is truly terrible for git, especially if the notebook is being remotely served in which case it's impossible to check into version control.  I have no plans on bringing back the checkpointing.

No cell-level undo is a genuine problem.  You should be nervous.  Alas, again, I blame the deficiency on the jupyter "way of doing things."   Serious work should be done with traditional scripting and proper source control.  _Ad hoc_ EDA (exploratory data analysis) with jupyter is fine.

**Comment by dickmao** [comment]
To be clear, org-babel remains the only "sane" emacs solution for proper undo and proper source control.  Sadly it does not appeal to the youngest generation of statisticians accustomed to Web 2.0 precepts.

**Comment by YizhePKU** [comment]
Thanks for your reply.

After reading IPEP 15, I realize what I really need is not autosave(as supported by Jupyter Notebook), but backup-on-manual-save(as supported by Emacs itself). I'll try to figure out how to make it work with ein.

**Comment by dickmao** [comment]
I think you'll ultimately be disappointed by EIN and backups, but here's how to do what you propose (it's complicated because the backup needs to happen as a callback *after* jupyter saves to disk).

```
(defun my-backup-if-local (modified-p)
  (let ((buffer-file-name (concat (ein:jupyter-running-notebook-directory)
                                  (ein:$notebook-notebook-path (ein:get-notebook))))
        (buffer-backed-up (not modified-p)))
    (when (file-exists-p buffer-file-name)
      (backup-buffer))))

(add-function :override (symbol-function 'ein:notebook-save-notebook-command)
              (lambda (&rest _args)
                (interactive)
                (ein:notebook-save-notebook ein:%notebook%
                                            (apply-partially #'my-backup-if-local
                                                             (buffer-modified-p)))))
```

**Comment by YizhePKU** [comment]
Yeah, it doesn't work for remotely-served notebooks. Thanks anyways.
