### ISSUE TITLE
ipython-widgets/matplotlib guis are not being printed inline, onto the screen inside an ein notebook?

### ISSUE THREAD

**Issue by zeta-00** [millejoh/emacs-ipython-notebook#775]
Hello there,
I got ipython working great in ein, but I was wondering if there's a way to get it to print guis like ipython-widgets? I can't seem to get it to work, maybe i'm missing a front-end/dependeny? here's a similar issue: https://github.com/jupyter-widgets/ipywidgets/issues/2141 
here's the example that i'm using: https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Basics.html
If you could let me know if this is even possible, thanks!
I hope that I can get the printing of guis working in ein notebooks, so that I can use python packages like matplotlib and numpy!

**Comment by zeta-00** [comment]
Here's my reddit post that is a much more descriptive:

https://www.reddit.com/r/emacs/comments/l4dso4/emacsipythonnotebook_how_do_you_enable_ein_inline/

thanks in advance for the help!

**Comment by dickmao** [comment]
Even if EIN knew anything about js widgets, emacs itself wouldn't be able to render them.  [This enterprising youth](https://github.com/akirakyle/emacs-webkit), while nowhere near the point for serious consideration by the emacs maintainers, seems furthest along the path of having emacs become Web-2.0-aware.  I hope that effort never comes to fruition, not purely out of *schadenfreude*, but out of a personal desire for emacs not to become a web browser like, well, every popular text editor out there today.

This current issue as well as our previous interactions #708 strongly suggest you'd be happier using jupyter in a browser as the jupyter designers intended.
