### ISSUE TITLE
can't interrupt kernel with ob-ein

### ISSUE THREAD

**Issue by julian-urban** [millejoh/emacs-ipython-notebook#780]
I may just be ignorant about the relevant functionality or how to do it properly, but I'm currently unable to send interrupt commands to the ipython kernel from an org mode buffer. Right now I have to wait for the cell to finish executing or kill the process manually. `ein:notebook-kernel-interrupt-command` returns `Wrong type argument: ein:$notebook, nil`.

Unfortunately I haven't been able to find a lot of information on how to call ein functions from org mode. Can someone tell me if this is possible, and if so, how?

**Comment by dickmao** [comment]
One should not call ein functions from org mode.  As of 52fc726 `C-h m` should now show:
```
C-c C-v C-k     ob-ein-kernel-interrupt
```
which should not be confused with `C-c C-v k`.

Traditionally, I believe org-babel is purely synchronous so `C-g` would suffice.  I don't know how the prevailing asynchronous package [ob-async](https://github.com/astahlman/ob-async/issues/42) handles it.
