### ISSUE TITLE
Cursor warps to previous cell upon `next-line`

### ISSUE THREAD

**Issue by matsievskiysv** [millejoh/emacs-ipython-notebook#782]
`next-line` (kbd <kbd>↓</kbd>) doesn't always go to the next line when there're [overlays](https://www.gnu.org/software/emacs/manual/html_node/elisp/Overlays.html) in cell.

This is better illustrated by this video (only <kbd>↓</kbd> was pressed):
![ex](https://user-images.githubusercontent.com/26824900/107524730-26e2e500-6bc7-11eb-9b94-dc463384bdc3.gif)

---
ein version "20210202.217"
math overlays provided by [`math-preview`](https://melpa.org/#/math-preview)

**Comment by dickmao** [comment]
> This is better illustrated by this video

I don't know that it is.  It's not clear whether you're complaining about the cursor jumping from the left margin to the middle of the next line at word "[cellst]", or that you had to hit down-arrow multiple times to get it to go down.

I don't see any jumping or "stuck" down-arrow in the following equally ambiguous video.
![what](https://user-images.githubusercontent.com/7578770/107555625-64367b00-6ba5-11eb-9b79-4b5f03d1c4df.gif)

**Comment by matsievskiysv** [comment]
To clarify what was happening on the video:
1. Cursor was a the middle of the python cell
2. I repeatedly press <kbd>↓</kbd>
3. Cursor gets into markdown cell
4. Instead of continuing going down, it unexpectedly jumps in the middle of the previous python cell.

**Comment by dickmao** [comment]
Okay, in the initial example, you can understand why I thought the "jump back" was merely the gif cycling playback.

The second example with the inline image might be a known problem with emacs inlined images.  I don't have the exact debbugs number, but I know it's been widely reported in contexts like eww that trying to scroll past a large enough image results in annoying bounceback.

The initial example looks like a genuine EIN problem.  I couldn't reproduce it just now, but I don't disbelieve it's happening.

**Comment by dickmao** [comment]
I can reproduce it.

**Comment by matsievskiysv** [comment]
I'll try to create a genuine MWE

**Comment by dickmao** [comment]
Commit 069e54c attempts to mitigate the jumping.  EIN's treatment of overlays should remain suspect as I don't test them.

**Comment by dickmao** [comment]
Incidentally, you might want to configure your matplotlibrc for dark
backgrounds.  Here is my ~/.config/matplotlib/matplotlibrc.

```
# Set black background default line colors to white.

lines.color: white
patch.edgecolor: white

text.color: white

axes.facecolor: black
axes.edgecolor: white
axes.labelcolor: red
axes.prop_cycle: cycler('color', ['8dd3c7', 'feffb3', 'bfbbd9', 'fa8174', '81b1d2', 'fdb462', 'b3de69', 'bc82bd', 'ccebc4', 'ffed6f'])

xtick.color: white
ytick.color: white

grid.color: white

figure.facecolor: black
figure.edgecolor: black

savefig.facecolor: black
savefig.edgecolor: black

# from http://www.huyng.com/posts/sane-color-scheme-for-matplotlib/

patch.linewidth: 0.5
patch.facecolor: 348ABD  # blue
patch.antialiased: True

font.size: 10.0

axes.linewidth: 1
axes.grid: True
axes.titlesize: x-large
axes.labelsize: large
axes.axisbelow: True       # grid/ticks are below elements (e.g., lines, text)

xtick.direction: out
ytick.direction: out

grid.linestyle: -    # solid line
```

**Comment by chookity-pokk** [comment]
This still seems to be happening with the most up to date version of EIN (I installed it just a few days ago). Any time there's an image that's relatively small then it goes over just fine but if the image goes from the base of the cell to the end of the buffer then it always loops. On top of that, if you go in from below the image and get within about 5 lines it jumps the cursor to the top of the image.

I can get a GIF/Video of this if needed but it's basically the same as what you see above.
