### ISSUE TITLE
Symbol's value as variable is void: keymap

### ISSUE THREAD

**Issue by gyps** [millejoh/emacs-ipython-notebook#786]
Dear all,

I'd really like to use ein as I am using emacs for most of my tasks (even use it as my window manager with exwm). Unfortunately I get the error mentioned in the topics subject when I try to use ein (from melpa) or compile the git version of ein. Does anybody have any idea what could be the reason?

Thanks in advance,
Alex

PS: Im using Emacs 28.0.50 built from git

**Comment by dickmao** [comment]
The README stipulates unreleased versions of emacs are not supported.

Running `EMACS=emacs-28.0.50 make test-compile` on my git repo complains about a number of things, none of which are `Symbol's value as variable as void: keymap`, however.
