### ISSUE TITLE
Can't install - websocket issues?

### ISSUE THREAD

**Issue by smontanaro** [millejoh/emacs-ipython-notebook#788]
I tried to install ein, but after refreshing the contents and executing package-install, it bailed with this error message:

Need package ‘websocket-20191017.30’, but only 1.13.1 is available

I'm running:

GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-28

I found a closed issue which suggests the ein version in melpa-stable won't install but that it will from melpa-unstable:

https://github.com/millejoh/emacs-ipython-notebook/issues/597

Perhaps this should be mentioned in the install section of the docs.

**Comment by dickmao** [comment]
Alas I am a stickler for the tersest possible README.  The install section only mentions unstable melpa.  Adding a caveat regarding stable melpa would increase word count.

As for stable melpa as a general concept, I am reminded of John Updike's quote regarding Manhattanites.  Any emacs user with an ounce of ambition or curiosity will soon find that venue hopelessly obtuse.

**Comment by smontanaro** [comment]
> Alas I am a stickler for the tersest possible README. The install section
only mentions unstable melpa. Adding a caveat regarding stable melpa would
increase word count.
>
> As for stable melpa as a general concept, I am reminded of John Updike's
quote regarding Manhattanites. Any emacs user with an ounce of ambition or
curiosity will soon find that venue hopelessly obtuse.

I see no mention of unstable. Here
<https://github.com/smontanaro/emacs-ipython-notebook> it just says "melpa":

(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

If you jump through the Getting Started
<https://melpa.org/#/getting-started> link, it explicitly mentions using
stable:

To use the stable package repository <https://stable.melpa.org/> instead of
the default “bleeding-edge” repository, use this instead of "melpa":

As I try hard not to break my Emacs install, I tend to stick with stable.
It still seems to me that somewhere you should mention that ein in
melpa-stable won't install (at least for some combination of Emacs
versions/dialects).

Skip
