### ISSUE TITLE
Cannot install via oackage-install from MELPA

### ISSUE THREAD

**Issue by caedmon-kitty** [millejoh/emacs-ipython-notebook#789]
M-x package-install <RET> ein <RET> results in:

Need package ‘websocket-20191017.30’, but only 1.13.1 is available

**Comment by dickmao** [comment]
EIN is only available on melpa.org, not stable.melpa.org.

I am going to try to remove it from stable.melpa.org by annihilating all of EIN's git tags.  I may have to send a manual request to the melpa maintainer in addition to this (somewhat scorched-earth) action.

cf. #788

**Comment by caedmon-kitty** [comment]
Thank you.  I'll try to install it from melpa.
