### ISSUE TITLE
Adding minor modes, when opening notebook

### ISSUE THREAD

**Issue by zeneofa** [millejoh/emacs-ipython-notebook#79]
Hi,
Fairly new to emacs, so not sure in which of the ein*.el I should edit (or what line to add, for that matter), in order to have evil mode activated as a minor mode when I open a new notebook. Any advice?

(I know I can, M + x, then type evil-mode , but I would like to have that has default when I open a notebook, but only in the notebook, not when using notebooklist )

Thanks,
P

**Comment by millejoh** [comment]
I think what you want is to customize `ein:notebook-mode-hook`. Add something like `(add-hook 'ein:notebook-mode-hook 'evil-mode)` to your initialization file after loading ein.

**Comment by zeneofa** [comment]
Thanks, it worked, added the line you suggested to ein.el , just before `(provide 'ein)` .
