### ISSUE TITLE
popup.el (as from auto-complete) is horribly garbled in EIN

### ISSUE THREAD

**Issue by glyph** [millejoh/emacs-ipython-notebook#792]
I have Jedi configured to supply completions to `python-mode` buffers based on what virtual environment they're in.  Here's what it looks like in a normal buffer:

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/716529/111959850-38fc5100-8aac-11eb-9593-4e5681ce2323.png">

Now, this is what it looks like in EIN:

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/716529/111960180-a1e3c900-8aac-11eb-9d8a-5b4248ec9f92.png">

Additionally the auto-completion itself only works sporadically, the keyboard shortcuts for navigating the completion menu (up and down arrows, for example) instead start navigating the buffer without dismissing the popup.

I'm *pretty* sure this used to work (at least, I remember it working when I set it up a year or so ago), but I drop into EIN infrequently and so I'm not quite sure when it broke.

**Comment by findesgh** [comment]
I have similar problems using elpy and its company backend. Similarly believe I recall this working a while ago, can't do any testing atm, though, sorry.

**Comment by ioannis-vm** [comment]
I have the same problem. Just when I decided to reconfigure my workflow to be using ein t_t

**Comment by jacknashg** [comment]
the same issue encountered here...

**Comment by ioannis-vm** [comment]
> the same issue encountered here...
> 
> edit1: can walk around it by disable font-lock-mode, however, color highlighting is also "walk arounded".
> 
> edit2: the issue can be resolved by: (setq jit-lock-defer-time 0)
> although, dont't know why it works...

None of them works for me.

**Comment by jacknashg** [comment]
> > edit1: can walk around it by disable font-lock-mode, however, color highlighting is also "walk arounded".
> > edit2: the issue can be resolved by: (setq jit-lock-defer-time 0)
> > although, dont't know why it works...
> 
> None of them works for me.

found this: https://lists.gnu.org/archive/html/emacs-devel/2006-03/msg00828.html

it seems modifying jit-lock-defer-time won't take effect immediately, eithter by using setq or customize.
try this:
1. Customize jit-lock-defer-time to 1
2. restart Emacs
3. C-h v jit-lock-defer-time, to make sure its value is 1
4. C-h v jit-lock-defer-timer, to make sure its value is [nil 0 1 0 t jit-lock-deferred-fontify nil idle 0]
5. see if things go right in ein

**Comment by ioannis-vm** [comment]
Currently ein's `ein-completer.el` is mostly commented out, with a remark that it needs to be rewritten. Could this be the reason for the issues?

**Comment by dickmao** [comment]
Sorry about this.  It occurs to me now that #797 #796 describe the same [overlay fail](https://github.com/millejoh/emacs-ipython-notebook/commit/4179a27e9d5a02db1ee01a88ef11325be640be08).
