### ISSUE TITLE
Is ein:edit-cell-contents gone?

### ISSUE THREAD

**Issue by DawnFawn** [millejoh/emacs-ipython-notebook#799]
Please close this ticket if the answer is yet.

I have gotten started with ein again, but I can't seem to open a cell in a separate buffer, where I could use the primary language mode (python). I know I was able to do this previously, and old documentation references this.

Was this feature removed? Replaced?

Thanks all for the work on ein

**Comment by dickmao** [comment]
You should get primary language mode without having to open a separate buffer.  Supposably.
