### ISSUE TITLE
cannot run ein on windows 

### ISSUE THREAD

**Issue by shelper** [millejoh/emacs-ipython-notebook#80]
Installed the newest ipython (jupyter) 4.0 and when i run ein:notebooklist-open on a windows machine, i have ein: [error] Content list call http://127.0.0.1:8888/api/contents/ failed with status error.
and I run `emacs -Q -l lisp/zeroein.el`, got the same error, I use the same (basic) configuration on a mac and everything is fine. so i believe it is a bug in ein., then i turned on deug-on-error and I run `emacs -Q -l lisp/zeroein.el`,  i got the debug message as below:

Debugger entered--Lisp error: (wrong-type-argument listp %url_effective\))
  cdr(%url_effective\))
  (car (cdr (plist-member --cl-rest-- (quote :num-redirects))))
  (let* ((--cl-rest-- (request--curl-read-and-delete-tail-info)) (num-redirects (car (cdr (plist-member --cl-rest-- (quote :num-redirects))))) (url-effective (car (cdr (plist-member --cl-rest-- (quote :url-effective)))))) (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote (:num-redirects :url-effective :allow-other-keys))) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:num-redirects :url-effective)" (car --cl-keys--)))))) (goto-char (point-min)) (request--consume-100-continue) (if (> num-redirects 0) (progn (let* ((case-fold-search t) (--cl-var-- num-redirects)) (while (>= (setq --cl-var-- (1- --cl-var--)) 0) (request--consume-100-continue) (let ((response ...)) (request--clean-header response) (request--cut-header response) (setq history (cons response history)))) nil))) (goto-char (point-min)) (nconc (list :num-redirects num-redirects :url-effective url-effective :history (nreverse history)) (request--parse-response-at-point)))
  (progn (let* ((--cl-rest-- (request--curl-read-and-delete-tail-info)) (num-redirects (car (cdr (plist-member --cl-rest-- (quote :num-redirects))))) (url-effective (car (cdr (plist-member --cl-rest-- (quote :url-effective)))))) (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote ...)) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:num-redirects :url-effective)" (car --cl-keys--)))))) (goto-char (point-min)) (request--consume-100-continue) (if (> num-redirects 0) (progn (let* ((case-fold-search t) (--cl-var-- num-redirects)) (while (>= (setq --cl-var-- ...) 0) (request--consume-100-continue) (let (...) (request--clean-header response) (request--cut-header response) (setq history ...))) nil))) (goto-char (point-min)) (nconc (list :num-redirects num-redirects :url-effective url-effective :history (nreverse history)) (request--parse-response-at-point))))
  (let (history) (progn (let* ((--cl-rest-- (request--curl-read-and-delete-tail-info)) (num-redirects (car (cdr (plist-member --cl-rest-- ...)))) (url-effective (car (cdr (plist-member --cl-rest-- ...))))) (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq ... ...) (setq --cl-keys-- ...)) ((car ...) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:num-redirects :url-effective)" ...))))) (goto-char (point-min)) (request--consume-100-continue) (if (> num-redirects 0) (progn (let* ((case-fold-search t) (--cl-var-- num-redirects)) (while (>= ... 0) (request--consume-100-continue) (let ... ... ... ...)) nil))) (goto-char (point-min)) (nconc (list :num-redirects num-redirects :url-effective url-effective :history (nreverse history)) (request--parse-response-at-point)))))
  request--curl-preprocess()
  (save-current-buffer (set-buffer buffer) (request--curl-preprocess))
  (condition-case err (save-current-buffer (set-buffer buffer) (request--curl-preprocess)) ((debug error) (list :error err)))
  (let* ((--cl-rest-- (condition-case err (save-current-buffer (set-buffer buffer) (request--curl-preprocess)) ((debug error) (list :error err)))) (version (car (cdr (plist-member --cl-rest-- (quote :version))))) (code (car (cdr (plist-member --cl-rest-- (quote :code))))) (num-redirects (car (cdr (plist-member --cl-rest-- (quote :num-redirects))))) (history (car (cdr (plist-member --cl-rest-- (quote :history))))) (error (car (cdr (plist-member --cl-rest-- (quote :error))))) (url-effective (car (cdr (plist-member --cl-rest-- (quote :url-effective)))))) (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote (:version :code :num-redirects :history :error :url-effective :allow-other-keys))) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:version :code :num-redirects :history :error :url-effective)" (car --cl-keys--)))))) (request--curl-absolutify-location-history (plist-get settings :url) history) (progn (or (and (vectorp response) (>= (length response) 14) (memq (aref response 0) cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-status-code) (quote request-response))) (let* ((v response)) (aset v 1 code))) (progn (or (and (vectorp response) (>= (length response) 14) (memq (aref response 0) cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-url) (quote request-response))) (let* ((v response)) (aset v 6 url-effective))) (progn (or (and (vectorp response) (>= (length response) 14) (memq (aref response 0) cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-history) (quote request-response))) (let* ((v response)) (aset v 2 history))) (progn (or (and (vectorp response) (>= (length response) 14) (memq (aref response 0) cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-error-thrown) (quote request-response))) (let* ((v response)) (aset v 4 (or error (if (>= code 400) (progn (list ... ... code))))))) (apply (function request--callback) buffer settings))
  (progn (let* ((--cl-rest-- (condition-case err (save-current-buffer (set-buffer buffer) (request--curl-preprocess)) ((debug error) (list :error err)))) (version (car (cdr (plist-member --cl-rest-- (quote :version))))) (code (car (cdr (plist-member --cl-rest-- (quote :code))))) (num-redirects (car (cdr (plist-member --cl-rest-- (quote :num-redirects))))) (history (car (cdr (plist-member --cl-rest-- (quote :history))))) (error (car (cdr (plist-member --cl-rest-- (quote :error))))) (url-effective (car (cdr (plist-member --cl-rest-- (quote :url-effective)))))) (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote ...)) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:version :code :num-redirects :history :error :url-effective)" (car --cl-keys--)))))) (request--curl-absolutify-location-history (plist-get settings :url) history) (progn (or (and (vectorp response) (>= (length response) 14) (memq (aref response 0) cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-status-code) (quote request-response))) (let* ((v response)) (aset v 1 code))) (progn (or (and (vectorp response) (>= (length response) 14) (memq (aref response 0) cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-url) (quote request-response))) (let* ((v response)) (aset v 6 url-effective))) (progn (or (and (vectorp response) (>= (length response) 14) (memq (aref response 0) cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-history) (quote request-response))) (let* ((v response)) (aset v 2 history))) (progn (or (and (vectorp response) (>= (length response) 14) (memq (aref response 0) cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-error-thrown) (quote request-response))) (let* ((v response)) (aset v 4 (or error (if (>= code 400) (progn ...)))))) (apply (function request--callback) buffer settings)))
  (cond ((and (memq (process-status proc) (quote (exit signal))) (/= (process-exit-status proc) 0)) (progn (or (and (vectorp response) (>= (length response) 14) (memq (aref response 0) cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-error-thrown) (quote request-response))) (let* ((v response)) (aset v 4 (cons (quote error) event)))) (apply (function request--callback) buffer settings)) ((equal event "finished\n") (progn (let* ((--cl-rest-- (condition-case err (save-current-buffer ... ...) (... ...))) (version (car (cdr ...))) (code (car (cdr ...))) (num-redirects (car (cdr ...))) (history (car (cdr ...))) (error (car (cdr ...))) (url-effective (car (cdr ...)))) (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond (... ...) (... ...) (t ...)))) (request--curl-absolutify-location-history (plist-get settings :url) history) (progn (or (and (vectorp response) (>= ... 14) (memq ... cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-status-code) (quote request-response))) (let* ((v response)) (aset v 1 code))) (progn (or (and (vectorp response) (>= ... 14) (memq ... cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-url) (quote request-response))) (let* ((v response)) (aset v 6 url-effective))) (progn (or (and (vectorp response) (>= ... 14) (memq ... cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-history) (quote request-response))) (let* ((v response)) (aset v 2 history))) (progn (or (and (vectorp response) (>= ... 14) (memq ... cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-error-thrown) (quote request-response))) (let* ((v response)) (aset v 4 (or error ...)))) (apply (function request--callback) buffer settings)))))
  (let* ((buffer (process-buffer proc)) (response (process-get proc :request-response)) (symbol-status (progn (or (and (vectorp response) (>= (length response) 14) (memq (aref response 0) cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-symbol-status) (quote request-response))) (aref response 5))) (settings (progn (or (and (vectorp response) (>= (length response) 14) (memq (aref response 0) cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-settings) (quote request-response))) (aref response 8)))) (let ((level (request--log-level-as-int (quote debug))) (log-level (request--log-level-as-int request-log-level)) (msg-level (request--log-level-as-int request-message-level))) (if (<= level (max log-level msg-level)) (progn (let ((msg (format "[%s] %s" ... ...))) (if (<= level log-level) (progn (save-current-buffer ... ... ...))) (if (<= level msg-level) (progn (message "REQUEST %s" msg))))))) (let ((level (request--log-level-as-int (quote debug))) (log-level (request--log-level-as-int request-log-level)) (msg-level (request--log-level-as-int request-message-level))) (if (<= level (max log-level msg-level)) (progn (let ((msg (format "[%s] %s" ... ...))) (if (<= level log-level) (progn (save-current-buffer ... ... ...))) (if (<= level msg-level) (progn (message "REQUEST %s" msg))))))) (let ((level (request--log-level-as-int (quote debug))) (log-level (request--log-level-as-int request-log-level)) (msg-level (request--log-level-as-int request-message-level))) (if (<= level (max log-level msg-level)) (progn (let ((msg (format "[%s] %s" ... ...))) (if (<= level log-level) (progn (save-current-buffer ... ... ...))) (if (<= level msg-level) (progn (message "REQUEST %s" msg))))))) (let ((level (request--log-level-as-int (quote debug))) (log-level (request--log-level-as-int request-log-level)) (msg-level (request--log-level-as-int request-message-level))) (if (<= level (max log-level msg-level)) (progn (let ((msg (format "[%s] %s" ... ...))) (if (<= level log-level) (progn (save-current-buffer ... ... ...))) (if (<= level msg-level) (progn (message "REQUEST %s" msg))))))) (cond ((and (memq (process-status proc) (quote (exit signal))) (/= (process-exit-status proc) 0)) (progn (or (and (vectorp response) (>= (length response) 14) (memq (aref response 0) cl-struct-request-response-tags)) (error "%s accessing a non-%s" (quote request-response-error-thrown) (quote request-response))) (let* ((v response)) (aset v 4 (cons (quote error) event)))) (apply (function request--callback) buffer settings)) ((equal event "finished\n") (progn (let* ((--cl-rest-- (condition-case err ... ...)) (version (car ...)) (code (car ...)) (num-redirects (car ...)) (history (car ...)) (error (car ...)) (url-effective (car ...))) (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ... ... ...))) (request--curl-absolutify-location-history (plist-get settings :url) history) (progn (or (and ... ... ...) (error "%s accessing a non-%s" ... ...)) (let* (...) (aset v 1 code))) (progn (or (and ... ... ...) (error "%s accessing a non-%s" ... ...)) (let* (...) (aset v 6 url-effective))) (progn (or (and ... ... ...) (error "%s accessing a non-%s" ... ...)) (let* (...) (aset v 2 history))) (progn (or (and ... ... ...) (error "%s accessing a non-%s" ... ...)) (let* (...) (aset v 4 ...))) (apply (function request--callback) buffer settings))))))
  request--curl-callback(#<process request curl> "finished\n")

**Comment by millejoh** [comment]
I develop mostly on Windows and I have run into difficult to debug issues when request.el uses curl instead of url-retrieve. There are a few things to try:

1. Download from MELPA stable instead of using zeroein.el.
2. Configure request.el to use `url-retrieve` instead of `curl`.

If that still doesn't seem to be working could you send me the contents of *ein:log-all* and anything that looks useful from the terminal running Jupyter/IPython?

**Comment by shelper** [comment]
i think i found the reason, you need to install cygwin or similar tools so that there is a `curl.exe` in the path can be called by EIN, it maybe worth to put this into the documentation for windows users. 

thanks!
