### ISSUE TITLE
"peculiar error" on open

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#801]
I get 
```
[error] request--callback: peculiar error [4 times]
ein: [error] ein:content-query-contents--error http://dev-dsk-sdsg-1e-cfbb346a.us-east-1.amazon.com:8080/aps-split.ipynb REQUEST-STATUS timeout DATA interrupt: 2
```
when I click on `[Open]` in `notebooklist`.
The notebook is large (850k) with lots of charts; created by `ein` last week.
It opens just find in chrome.
Ein can create and open tiny notebooks.

`EIN version is 20210522.1036`

**Comment by dickmao** [comment]
Sounds like #779
