### ISSUE TITLE
How open current jupyter session in browser?

### ISSUE THREAD

**Issue by Katafotic** [millejoh/emacs-ipython-notebook#805]
Hi.

In my work, I needed to open Jupyter through a browser, for specific work with plots. It also allows me to see some dataframes in a more readable form. 

I have searched the documentation but did not find a command to reopen the file in the browser.

I switched to the browser and went to the localhost, but I need a token to connect. I don't know how to get it from emacs without creating a new jupyter session. 

Of course, I can open a terminal, turn on the environment, and run a `jupyter notebook list` to view the token. Or copy and paste URL from the buffer with jupyter server logs `ein:log-all`. But this is uncomfortable.

So, If you follow the way of customizing Emacs, than how I can get URL (i.e. token) for the Jupyter server via ein in emacs?

Thank You.

P.S.
I understand that 2 programs cannot work correctly with one file without frequent saving and reopening of the file. But the ability to briefly switch to the browser would really help me in my work.

**Comment by dickmao** [comment]
`M-: (ein:jupyter-server-conn-info)`
