### ISSUE TITLE
code compleation with ein-completer.el

### ISSUE THREAD

**Issue by haschka** [millejoh/emacs-ipython-notebook#807]
I'm on version 0.16.2.3 from melpa stable. 

After this last update I had serious troubles with the code completer and i saw that here in git the code seems to be completely removed. 

I took the version of the ein-completer.el from the commit below and replaced the code of version 0.16.2.3 after I tried hacking it myself and getting the errors away. 

https://github.com/millejoh/emacs-ipython-notebook/commit
/bcf1c2ac5538cd20a8cea87a071dcb16d64f0b38

I'm a huge fan of this feature and may be others are too. I do like to use elpy for this as it needs its own python environment in my home and pip installs packages, which I find a bit overkill as these functionality is already provided by the jupyter kernel. I also really do not understand why the same is true for jedi.el, even though I have jedi installed on my machine. Thus I really prefere and kind of depend on this feature.

As such I hope that this feature comes back and hope that in writing this issue I can help others reverting to "existed functionality".

my jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : not installed
ipython          : 7.25.0
ipykernel        : 5.5.4
jupyter client   : 6.1.12
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5

Thanks, Thomas

**Comment by dickmao** [comment]
I don't intend on bringing it back.  My expert opinion is remote completions are a very difficult thing to do tastefully.  Some will disagree.  Some will disagree my opinion is expert.

**Comment by haschka** [comment]
As far as I understand it jedi / elpy is also remote ( installing a code
completion server locally )

Maybe we can find a maintainer or someone who helps you out on this issue.

cheers,
- Thomas

**Comment by dickmao** [comment]
> As far as I understand it jedi / elpy is also remote ( installing a code completion server locally )

Correct, and most people find elpy/Jedi completion  unreliable.
