### ISSUE TITLE
Question: Does it work with mybinder?

### ISSUE THREAD

**Issue by genomorro** [millejoh/emacs-ipython-notebook#808]
Hi.

I'm very new with jupyter notebooks. Currently I'm working with Gitlab and mybinder.org, however, use my web browser as a text editor is not a good idea and json format is not very friendly.

Looking for a better solution, I'm a emacs user, I read some code in this repo but I don't know if it's possible EIN works with Mybinder or similar services (Colab, Cocalc or Datalore) because of login information.

Anybody has tried this kind of config? Thanks.

**Comment by dickmao** [comment]
I vaguely remember getting it to work with mybinder three years ago, but it wasn't straightforward, and I can only surmise things have progressed to have made it less so.

EIN is largely not usable with these heavy web-centric SaaS's like Colab, etc.  And by "usable" I mean "something that doesn't regularly frustrate you."  By that definition, though, most emacs things are not usable.
