### ISSUE TITLE
Switching between Python 2 and 3 with EIN / Jupyter notebook

### ISSUE THREAD

**Issue by DGalt** [millejoh/emacs-ipython-notebook#82]
Prior to the release of "jupyter notebook" (i.e. when it was still ipython notebook), I had 2 versions installed - ipython notebook and ipython2-notebook (the later being for Python 2.7, as my system default is Python 3). With this set up I could easily access either (or both) python3-ipython notebooks and python2-ipython notebooks using EIN within emacs. 

With the transition to Jupyter notebook, though, I can't seem to figure out how to switch between a python3 and python2 kernels. If I create a new python2 notebook through the browser interface and then close it / re-open it, EIN treats it as a python3 notebook. 

I use Pyenv to switch between python3 and 2 within emacs, which works fine for my ipython repl within emacs, but EIN doesn't respect that setting either. 

Am I missing some way to specify what install of python / python kernel EIN should be using? 

(sorry if that explanation is sort of convoluted, if it's not clear i can try to clarify more)

**Comment by millejoh** [comment]
Let me see if I understand - before you had two notebook servers running on different ports - one Python2 and one Python3. EIN  is fine working with multiple notebook servers, but as you noted in Jupyter you can specify which kernel to run in the web interface. EIN currently doesn't do that, it just runs the default kernel for the server.

This is certainly desirable behavior, though, so thanks for bringing up the topic. There have been requests in the past for EIN to support more than just the python kernel, so implementing kernel selection would certainly be a good first step. Now I just have to find some free time to look into this (easier said than done).

**Comment by DGalt** [comment]
Yes, that would be wonderful. 

In the meantime, should anyone else come across this issue, I did a little digging into the jupyter docs and found that when starting a jupyter notebook server the default kernel can be set using ```--MappingKernelManager.default_kernel_name="<Unicode>"```

so in my case I just have to do: 
```jupyter notebook --MappingKernelManager.default_kernel_name='python2'```

and now the server running on that port defaults to python2 and EIN works just fine for my python2 notebook.

**Comment by risantos** [comment]
Having ipython, ipython3 and jupyter installed, I found a similar issue few days ago.

I am using `jupyter notebook` and when a notebook is created within the browser, the default kernel of notebooks is python3 (as I have specified in my ipython_notebook_config.py)

When I `C-c C-r` , to restart the kernel inside emacs, the kernel is changed to Python2, and the only way to change it back to python3 is through the browser notebook.

>Yes, the ability to switch kernel for notebooks from within EIN would be wonderful.

Considering Jupyter's ability to use other kernels, this is a really useful feature, even so for a future "Emacs Jupyter Notebook"

**Comment by millejoh** [comment]
Just pushed 6d66cc5a2efedf614b62f012fad2023c8b95189c to master and it should be showing up on MELPA devel at any time. I haven't implemented switching kernels in a running notebook, but you can specify which kernel to use when creating new notebooks and EIN will respect if you change the kernel from the web interface. It's a bit late and I'm tired, so I hope that made some sense.

**Comment by DGalt** [comment]
Thanks for the update, much appreciated.

**Comment by vvkisil** [comment]
First, thanks for maintaining the EIN, it is a relief for a Emacs user to have this tool.
Back to my question: I have tried to find how to make Python3 the default kernel for newly created notebooks, but cannot see a suitable configuration option. Did I miss something. Of course it is not a big deal and can be selected manually each time. However, Python2 appears as the default in my sessions and I do not think many people are look for Python2 in these days.
