### ISSUE TITLE
ein:pytools-whos is not working

### ISSUE THREAD

**Issue by dvorak0** [millejoh/emacs-ipython-notebook#821]
I see the amazing ein:pytools-whos in documentation http://millejoh.github.io/emacs-ipython-notebook/#ein:pytools-whos.

But it's not working in my Emacs.

ein:pytools-jump-back-command is there, which I found implementation in https://github.com/millejoh/emacs-ipython-notebook/blob/master/lisp/ein-pytools.el.

I see no implementation for pytools-whos.

**Comment by dickmao** [comment]
> No require statements, e.g. ``(require 'ein)``, are necessary, contrary to the
`prevailing documentation`_, which should be disregarded.

https://github.com/millejoh/emacs-ipython-notebook/blob/1e42a2b26c2b113884170a94229c2743978e2dec/README.rst?plain=1#L12-L13

#813 #705 #695

**Comment by dvorak0** [comment]
Does that mean pytools-whos is diregarded?
