### ISSUE TITLE
Error While Starting a Notebook

### ISSUE THREAD

**Issue by emreds** [millejoh/emacs-ipython-notebook#822]
Hello, I am a newbie in emacs and I use doom emacs for starting. 
When I would like to start notebook with the `M-x ein:run` I have this error. 
Could you explain what is the problem? 

This is the error log:

```
evil-line-move: End of buffer [2 times]
ein: [info] ein:jupyter-server--run: /home/xxx/.local/bin/jupyter-notebook notebook --notebook-dir=/home/xxx/ --no-browser
ein: [warn] Jupyter server failed to start, cancelling operation
End of buffer
evil-line-move: End of buffer [2 times]
ein: [info] ein:jupyter-server--run: /home/xxx/.local/bin/jupyter-notebook notebook --notebook-dir=/home/xxx/xxx/ --no-browser
ein: [warn] Jupyter server failed to start, cancelling operation
C-c C-c is undefined [5 times]
```

Also, after I install the package with `M-x package-install`, `ein` commands are not appearing after the reload of emacs. I delete and reinstall the package to start again. 

I would really appreciate that if you could explain the reasons of those problems. 

Thank you.

**Comment by dickmao** [comment]
Try running `/home/xxx/.local/bin/jupyter-notebook notebook --notebook-dir=/home/xxx/ --no-browser` from the command line, and proceed from there.  Welcome to UNIX.  You have a very long and arduous journey ahead of you.

**Comment by emreds** [comment]
Thank you for the answer but, I would like to use this package and edit notebooks in emacs. Shouldn't the `ein:run` command run the notebook for me after I entered the path? Could you just tell me where is the mistake? Do I need to start notebooks then, connect them using this package. Is this what you mean?

**Comment by dickmao** [comment]
I'm always tell people their exact mistake if I know what it is.

ein cannot execute the command `/home/xxx/.local/bin/jupyter-notebook notebook
--notebook-dir=/home/xxx/ --no-browser`.  The only way to ascertain why is to
run that command from the shell.  It's not clear whether you know what a shell
is, so that's why I talked down to you about UNIX.

At this rate of progress, I suspect emacs and ein is not for you.  Both are
very fragile and suit people less interested in the destination than the
journey.

**Comment by emreds** [comment]
I guess we have a bit of miscommunication here. 
I couldn't find in the documentation about how to use `ein:run` then, I tried to find out how to use it and it just accepted the shell command as a `Server Command`. Then I thought it is trying to run the direct shell command in the back.
I wouldn't try to run ipython on emacs if I didn't interested in. 
It would be nice if you can just tell me how to do it, or send some documentation links.

**Comment by dickmao** [comment]
> I guess we have a bit of miscommunication here. I couldn't find in the documentation about how to use `ein:run` then, I tried to find out how to use it and it just accepted the shell command as a `Server Command`. Then I thought it is trying to run the direct shell command in the back.

Oh, we definitely have a miscommunication problem.  Describing technical issues in an economic but precise manner is difficult for a native English speaker, which it's clear you're not.

> It would be nice if you can just tell me how to do it

I want to be nice.  I want to "just tell you how to do it."  But it's not up to me.

**Comment by emreds** [comment]
Yes I am not native and I couldn't describe it well. With saying "just tell you how to do it." I meant how to use `ein:run`.
Okay.
