### ISSUE TITLE
Notebook won't save - ein:notebook-save-notebook-command-km

### ISSUE THREAD

**Issue by kanodiaayush** [millejoh/emacs-ipython-notebook#825]
I see the following on `C-x C-s` -- `ein:notebook-save-notebook-command-km: Unbound slot: ein:codecell, "#<ein:codecell ein:codecell-1ff03e6f2100>", input, oref`

I don't know how to fix it. I'm on doom emacs. This error starts popping from time to time and I don't know why.

**Comment by dickmao** [comment]
That looks bad.  I don't trust doom emacs for anything, so I'd start with migrating off that to normal emacs, or if that is time-prohibitive, to vscode.

**Comment by kanodiaayush** [comment]
> That looks bad. I don't trust doom emacs for anything, so I'd start with migrating off that to normal emacs, or if that is time-prohibitive, to vscode.

This is so sad :(
