### ISSUE TITLE
how to type C-c C-$?

### ISSUE THREAD

**Issue by xiaohan2012** [millejoh/emacs-ipython-notebook#827]
Hi,

What keys on the keyboard should I press to type the `C-c C-$`?

I tried `C-c C-Shift+4$` (assuming American keyboard layout), which gives `C-c 4 is undefined`

Thanks!

Han

**Comment by dickmao** [comment]
Try: `C-h k C-Shift-4`.  If that says `C-4 is undefined`, then I can't help you.

I admit this binding `C-c C-$` for showing the backtrace is lame.  It's never too early to learn how to remap keys if you're resigned to cohabitation with emacs.
