### ISSUE TITLE
Error is thrown when opening a notebook after ein:run:

### ISSUE THREAD

**Issue by zeta-00** [millejoh/emacs-ipython-notebook#829]
Greetings,

I installed the required tools to do Python/Jupyter coding in EIN, but, for some reason, after I run `ein:run` then press `[New Notebook]`, these errors get thrown:

`error in process sentinel: ein:insert-read-only: Wrong type argument: number-or-marker-p, t
error in process sentinel: Wrong type argument: number-or-marker-p, t`

It's been a while since I used EIN, so I'm not sure if I'm missing something in my .emacs config.
I installed all the required Python/Jupyter stuff with the nix package manager so there shouldn't be any issues there.

Anyways, here's my EIN config in my .emacs file:

;;-------------------------------------------------
(use-package ein
  :defer t
  :hook
  (ein-mode . elpy-mode)
  :config
  (setq ein:auto-save-on-execute t)
  (setq ein:output-area-inlined-images t)
  (setq ein:slice-image t)
  (setq ein:complete-on-dot t)
  (setq ein:polymode t)
  (setq ein:use-smartrep t)
  (setq ein:use-auto-complete t)
  :custom
  (ein:completion-backend 'ein:use-company-backend)
  (ein:truncate-long-cell-output t)
  (ein:auto-black-on-execute t)
  )
;;-------------------------------------------------
(use-package python-mode
  :defer t
  :hook
  (python-mode . company-mode)
  :config
  ;; emacs calculates line offset:
  (setq python-indent-guess-indent-offset t)
  ;; silence warnings while emacs calculates the line offset:
  (setq python-indent-guess-indent-offset-verbose t))
;;-------------------------------------------------
;; company-jedi setup:
(defun my/python-mode-hook ()
  (add-to-list 'company-backends 'company-jedi))

(add-hook 'python-mode-hook 'my/python-mode-hook)
;;-------------------------------------------------
(use-package elpy
  :defer t
  :config
  (elpy-enable)
  (elpy-company-backend)
  (elpy-get-info-from-shell)
  (setq python-shell-interpreter "ipython"
        python-shell-interpreter-args "-i --simple-prompt"))
;;-------------------------------------------------

**Comment by zeta-00** [comment]
When I run `jupyter-notebook` in a terminal, it opens in a web browser and works just fine, but, for some reason EIN is not working in Emacs.

**Comment by zeta-00** [comment]
(use-package eglot
  :defer t
  :hook
  (python-mode . eglot-ensure))

I have a hook to run `eglot-mode` whenever `python-mode` gets activated for a regular file, but I'm not sure if this is messing things up whenever I open  a `.ipynb` file with `EIN`.

**Comment by zeta-00** [comment]
Also, I'm using `treemacs` so I'm not sure if that's what is messing up EIN in Emacs.

**Comment by dickmao** [comment]
We never seem to get anywhere #806 #775 #723 #720 #709 #708 #642 #636.

The goal of data analysis is getting results, not fighting with your tools.  While I myself have not heeded my own advice, and have dedicated my waking hours to fighting emacs, I do not recommend that poor life choice to others.
