### ISSUE TITLE
Using Emacs's markdown-mode with EIN?

### ISSUE THREAD

**Issue by zeta-00** [millejoh/emacs-ipython-notebook#831]
Greetings,

I finally got EIN working nicely with Python and Elpy, but I'm not sure how to correctly setup emacs's markdown-mode to work with Jupyter notebooks in EIN.

Context:
My physics teacher assigned my class some Jupyter notebooks, so, when I open theme in EIN, things like plots are rendering nicely, but my issue has to do with markdown-mode.
When I open the Jupyter notebooks in a web browser, the browser's built-in markdown works correctly when displaying things like physics equations, but in EIN the markdown section is not displaying correctly.

Any tips on how to fix this?
I'm not sure if this is EIN related, or if this is more related to the markdown-mode package?

Reference links:

https://www.ibm.com/docs/en/watson-studio-local/1.2.3?topic=notebooks-markdown-jupyter-cheatsheet

https://www.emacswiki.org/emacs/MarkdownMode

https://leanpub.com/markdown-mode/read

Thanks in advance for the help.

**Comment by dickmao** [comment]
> Context: My physics teacher assigned my class some Jupyter notebooks

Ah, so you're still in high school.  Things make more sense now.

EIN's markdown mode is rather sus, and a largely untested bolt-on.

I wouldn't trust it to do the right thing beyond simple h1 headings.  Sorry.
