### ISSUE TITLE
change background color of highlighted text in traceback

### ISSUE THREAD

**Issue by xiaohan2012** [millejoh/emacs-ipython-notebook#833]
Hi,

In my traceback, the foreground color of text and the background one is so close that I cannot see the actual text.

A screenshot to demonstrate this:

<img width="707" alt="Screenshot 2022-04-01 at 14 48 52" src="https://user-images.githubusercontent.com/789353/161258039-875db694-6abc-4734-a69d-5b5361d24031.png">

Is there anyway to change the background color?

Thanks!

**Comment by wickedjargon** [comment]
place your caret over text with the bright background. `M-x customize-face`. modify the settings and save your changes for future sessions.

**Comment by dickmao** [comment]
We don't have control over ipython's ansi codes.  You could butcher ansi-color.el but that would be wrong.

I would google "change color ipython".
