### ISSUE TITLE
Please add an entry to FAQ on why WSL is needed for Windows

### ISSUE THREAD

**Issue by beetleb** [millejoh/emacs-ipython-notebook#836]
There are plenty of us who happily use vanilla Emacs on Windows without WSL. Some information on what aspect of EIN requires WSL would be helpful (e.g. what feature does it rely on that requires WSL). 

Also, is it a case of not having enough resources to support non-WSL Windows (i.e. could volunteers step up to add support?), or is it fundamentally designed to require WSL and it's not really a question of volunteers?

Main point: More information would be really helpful. Even a link to a prior issue that discusses this in detail.

**Comment by dickmao** [comment]
#819

**Comment by beetleb** [comment]
It doesn't really address most of what I was asking:

* What aspect of being in Windows is causing this?
* Is this something that *can* be solved but no one has put time into it, or is it fundamentally something that *cannot* be solved?

Another way of phrasing it:

If someone wants to volunteer to get it working in Windows, are they wasting their time because this is a known unfixable problem?

**Comment by dickmao** [comment]
>What aspect of being in Windows is causing this?

Your guess is as good as mine.
