### ISSUE TITLE
Interest in Github Sponsoring this project

### ISSUE THREAD

**Issue by hnisonoff** [millejoh/emacs-ipython-notebook#839]
I am a daily user of this package! Having the ability to work in jupyter while staying in emacs has been great. I would love to see this package continue to get developed and keep up with the jupyter ecosystem. I was curious if there was a way to sponsor crowdsource sponsoring developers to work on this package? I'd personally love to contribute and I imagine many other users would be as well.

**Comment by dickmao** [comment]
> I am a daily user of this package!

Really?  I'm amazed (not being hyperbolic).

> I was curious if there was a way to sponsor ... on this package?

That would be as simple as posting a feature request here, and saying you'd stake your lunch money.  I assume you lunch at *Le Bernardin*.

But truthfully, you'd do me more good by propagating the Good Word of emacs amongst your peers and colleagues thus marginally increasing the remote possibility that companies with deeper pockets might buy into the emacs ecosystem.

**Comment by hnisonoff** [comment]
Yes and I know plenty of other emacs + python people who regularly use this too. I actually have regular worries that one day this package will no longer work and I will have to completely change how I work haha. 

I am a graduate student so I make my own lunch but I would be happy to contribute a monthly sponsorship for two things:
1) General maintenance of the package to make sure it can keep working as the python + emacs ecosystems continue to grow
2) Jupyterlab support? 

I know the latter has been discussed and dropped but I thought perhaps if there was a sponsorship it would be worth the effort. Anyway, thanks for all the work you do on this package. It is appreciated.

**Comment by dickmao** [comment]
As a man of leisure, the last thing I'd want is so much as an inkling of a fiduciary obligation to keep EIN alive.  Perhaps someone else would accept your largesse.  Hopefully that person is github-watching this dialogue.

As for Jupyterlab, a good egg in #803 showed me EIN was actually compatible with it.

**Comment by jkn-coder** [comment]
Just want to back up hnisonoff here. I have become totally addicted to ein. Best tool I ever used. Especially connecting to a remote powerful jupyter server is really efficient. Ein has its small flaws, emacs cut and paste sometimes messes up, but I can live with that, since the remote server is just continuing even if I reboot my linux laptop.  And I have used matlab for a quarter of a century!  I am never going back.
Thanks!

**Comment by hnisonoff** [comment]
Yeah definitely not trying to pressure you or anyone else to work more on this but just wanted to say that I love the package and if having a sponsorship to help maintain it would be helpful I’d be happy to contribute.
