### ISSUE TITLE
save notebook in emacs on windows cause error

### ISSUE THREAD

**Issue by shelper** [millejoh/emacs-ipython-notebook#84]
so, i am using ein and opened a new notebook called untitled1.ipynb, but when i call function: `ein:notebook-save-notebook-command` to save the notebook, it saves file correctly as .json format, but if i call save-buffer, it saves pure text that appears in the buffer window. Then if I call `ein:notebook-save-notebook-command` again, this then cause some issue 'cus emacs revert the buffer to show literal texts in the json file, not the notebook layout anymore, would it be nicer to override `save-buffer` in ein:ml mode to call `ein:notebook-save-notebook-command` instead?

also i found if i have inline figures in the ein notebook buffer, and run ` ein:notebook-save-notebook-command`, i have error:
```bash
ein: [info] Writing notebook Untitled1.ipynb as nbformat 4.
ein: [error] Content list call http://127.0.0.1:8888/api/contents/Untitled1.ipynb failed with status error.
```

**Comment by millejoh** [comment]
With finger crossed, I think the image saving and error report should be fixed in current version in both MELPA stable and devel. I just pushed the tag, so it may take a while for MELPA to update.

C-x C-s should be bound to ein:notebook-save-command when ein:notebook-minor-mode is active. One solution would be to `defadvice` save-buffer - I will think about what that entails.

**Comment by shelper** [comment]
great！
my hack for the saving issue is to modify the original save-buffer function, i tried defadvice but failed.


```lisp
  ;;; my hack to calls ein:notebook-save-notebook-command when in ein mode
  (defun save-buffer (&optional arg)
    (interactive "p")
    (if (eq major-mode 'ein:notebook-multilang-mode)
        (ein:notebook-save-notebook-command)
      (let ((modp (buffer-modified-p))
            (make-backup-files (or (and make-backup-files (not (eq arg 0)))
                                   (memq arg '(16 64)))))
        (and modp (memq arg '(16 64)) (setq buffer-backed-up nil))
        (if (and modp (buffer-file-name))
            (message "Saving file %s..." (buffer-file-name)))
        (basic-save-buffer)
        (and modp (memq arg '(4 64)) (setq buffer-backed-up nil)))))

;;; advice /defadvice that fails
(defun save-ein()
    (if (eq major-mode 'ein:notebook-multilang-mode)
      (ein:notebook-save-notebook-command))))
(advice-add 'save-buffer :before #'save-ein)
```
