### ISSUE TITLE
Cell ID changes on save for every cell

### ISSUE THREAD

**Issue by natsirtguy** [millejoh/emacs-ipython-notebook#840]
The `id` field changes for every cell when I save the notebook. It looks like EIN is generating a new uuid every time I go to save. Presumably [this](https://github.com/millejoh/emacs-ipython-notebook/blob/master/lisp/ein-classes.el#L241) is where the new uuid is being generated.

This is primarily a problem when working with source control systems like `git`, because it looks like every cell changes with every commit.

**Comment by dickmao** [comment]
Source control is precisely why jupyter is a non-starter for **real work**, but I sympathize with the proletariat whose corporate overlords forego brick houses when straw ones will suffice until the next promotion.

I don't see an `id` field in my `.ipynb` files.  When I `C-x C-s` willy-nilly, a `diff` shows no changes to the `.ipynb` contents.

**Comment by vvkisil** [comment]
I have seen this issue with `id` tag and version control before as well, but now it gone. Probably the developers had recognised that it was a bad idea and had dropt it with some update. 

Off: I am using the opportunity to say "many thanks" to the developers for maintaining wonderful ein.

**Comment by natsirtguy** [comment]
I think Jupyter implemented the [cell ID JEP](https://jupyter.org/enhancement-proposals/62-cell-id/cell-id.html) relatively recently, is it possible you are using old versions of the notebook format somehow?

[Here's the reference json schema for the most recent notebook format](https://github.co/jupyter/nbformat/blob/main/nbformat/v4/nbformat.v4.5.schema.json) for reference.

Source control with Jupyter is definitely a pain, but there are some tools out there that make it bearable :-)

**Comment by dickmao** [comment]
In c629877 I attempted a quick, untested fix.  Sorry I can't be bothered to upgrade my jupyter to test it.

If that fails to keep your cell id's stable across sessions, I hope you can tweak the fix for the win.

**Comment by natsirtguy** [comment]
Hi @dickmao , thanks for this. It *almost* solved the problem, but the notebook wasn't saving the cell IDs that you now load into the cell objects. #850 fixes that, take a look if you get the chance.
