### ISSUE TITLE
tqdm progress bars show up on different lines

### ISSUE THREAD

**Issue by kanodiaayush** [millejoh/emacs-ipython-notebook#851]
```
from tqdm import tqdm
from time import sleep
for i in tqdm(range(0, 100), total = 500, desc="random"):
  sleep(.1)
```

When I try this, I do not get an updating progress bar on a single line. It prints every progress bar line on a new line. I am probably making a simple mistake. What am I missing?

**Comment by dickmao** [comment]
No mistake.  `tqdm` won't work, and similarly dynamic text *cum*
widgets will trip up EIN's fragile undo mechanism.

**Comment by kanodiaayush** [comment]
Hmmm what do you suggest then for training models that requires a progress bar?

**Comment by dickmao** [comment]
A proper browser.

**Comment by kanodiaayush** [comment]
Okay, thank you! So hard to move to browser sigh.
