### ISSUE TITLE
Ein connect to server stopped working with not much in log

### ISSUE THREAD

**Issue by ratnesh1729** [millejoh/emacs-ipython-notebook#864]
Hi @millejoh  for the amazing package. I have been using with good effect until somehow got following issue.
~~Login to https://ratneshk@192.168.1.219:8080 failed, error-thrown (error . exited abnormally with code 7 ), raw-header~~

```

ein: [error] Login to http://192.168.1.219:8888 failed, error-thrown (error . exited abnormally with code 7 ), raw-header
```

The bug template output:

[debug] request--curl: --silent --location --cookie /Users/ratneshk/.emacs.d/request/curl-cookie-jar --cookie-jar /Users/ratneshk/.emacs.d/request/curl-cookie-jar --include --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --junk-session-cookies --trace-ascii /var/folders/b2/fyl9mmd10_dbkp9r7nqyxzmw0000gn/T/curl-trace --compressed --header User-Agent: Mozilla/5.0 --url http://192.168.1.219:8888/login
[debug] request--curl-callback: event exited abnormally with code 7

[debug] request--callback: UNPARSED

(:num-redirects 0 :url-effective "http://192.168.1.219:8888/login")
[error] request--callback: peculiar error
[debug] request--callback: executing error
[debug] request--callback: executing complete
[debug] request--curl: --silent --location --cookie /Users/ratneshk/.emacs.d/request/curl-cookie-jar --cookie-jar /Users/ratneshk/.emacs.d/request/curl-cookie-jar --include --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --junk-session-cookies --trace-ascii /var/folders/b2/fyl9mmd10_dbkp9r7nqyxzmw0000gn/T/curl-trace --trace-ascii /var/folders/b2/fyl9mmd10_dbkp9r7nqyxzmw0000gn/T/curl-trace --compressed --header User-Agent: Mozilla/5.0 --url http://192.168.1.219:8888/login
[debug] request--curl-callback: event exited abnormally with code 7

[debug] request--callback: UNPARSED

(:num-redirects 0 :url-effective "http://192.168.1.219:8888/login")
[error] request--callback: peculiar error
[debug] request--callback: executing error
[debug] request--callback: executing complete

**Note** I started emacs by `emacs -Q -f package-initialize -f ein:dev-start-debug`

**Comment by dickmao** [comment]
Remove "ratneshk@" from  ***@***.***:8080.

**Comment by ratnesh1729** [comment]
I realized by using the examples in the manual (berkeley jupyterhub) that something was off in my server configuration. 

So I started by using 
```jupyter notebook --ip 0.0.0.0
```

which fixed it. 

I am not sure why earlier I did not need to. Maybe I mistakingly updated jupyter conf.

Anyways, Thank you! 

Also thank you for this awesome library, I can't imagine me coding without emacs!
