### ISSUE TITLE
ein:content-query-contents--error 404 

### ISSUE THREAD

**Issue by FinnFrotscher** [millejoh/emacs-ipython-notebook#870]
Hi, 
I installed EIN on emacs@30, m1mac, ipython 8.11.0.

In an org file i have this snippet:
```
#+BEGIN_SRC ein-python :session localhost
  print("hello python world")
#+end_src
```
When i `babel-execute` the block i get a range of errors
```
ein: [error] ein:content-query-contents--error 404 file or directory '/.ein-python.ipynb' does not exist
```
or
```
[error] request--callback: peculiar error: 400
ein: [error] Renaming content Untitled1.ipynb failed (error http 400) Cannot rename file or directory '/Untitled1.ipynb'.
```

what springs to mind is that its looking for the notebook in `/`, but the notebooks are in `~/[workdingdir]/nbs/*.ipynb`
what shall i do?

**Comment by dickmao** [comment]
True.  At some point jupyter disallowed hidden files, possibly around https://github.com/jupyter-server/jupyter_server/commit/877da10cd0d7ae45f8b1e385fa1f5a335e7adf1f

I made `ob-ein-anonymous-path` default to the unhidden "ob-%s.ipynb", thus ensuring a lawsuit when an unsuspecting user names a very important file "ob-%s.ipynb".

Thanks for reporting.  EIN 's semblance of functionality hangs by a thread.  Can't stop won't stop.

**Comment by FinnFrotscher** [comment]
I am sorry but this is not yet fixed.

i run the above codeblock in `[workdir]/workbook.org`
it asks me for a path, where i specify `[workbook]/nbs/`
this is my messages buffer:
```
Code block evaluation complete.
ein: [info] ein:jupyter-server--run: /opt/homebrew/bin/jupyter notebook --notebook-dir=~/valence/courses/fastai/nbs/ --no-browser
Code block evaluation complete (took 4.7s).
ein: [info] Login to http://127.0.0.1:8888 complete.
[error] request--callback: peculiar error: 404
ein: [error] ein:content-query-contents--error 404 file or directory '/.ein-python.ipynb' does not exist
Auto-saving...done
```
`[workbook]/nbs/` now contains `Untitled.ipynb`
and my codeblock is surrounded by

```
#+NAME: FBB9B3AC-5E06-4DFD-ABA9-C6CD1E614415
#+BEGIN_SRC ein-python :session localhost
  print("hello python world")
#+end_src

#+RESULTS: FBB9B3AC-5E06-4DFD-ABA9-C6CD1E614415
``` 
(same as before)

**Comment by FinnFrotscher** [comment]
i would love to run jupyter cells of remote notebooks from within org. thats pretty much the dream setup for me atm. so lets fix this @dickmao, what can i do? i am here for about 2 more hours.

**Comment by dickmao** [comment]
If `C-h v ob-ein-anonymous-path` still says ".%s.ipynb", you're still
running the old version.

Incidentally, you'll need ":results output" in your BEGIN_SRC.

**Comment by FinnFrotscher** [comment]
what function is bound to `C-h v` on your end? i have C-h mapped to some navigation in org mode

**Comment by FinnFrotscher** [comment]
ok its working now. i had to restart emacs in its entirety, not just all the things i did before. cest la vie. lovely
