### ISSUE TITLE
Get markdown latex to display in cell?

### ISSUE THREAD

**Issue by Clamwinds** [millejoh/emacs-ipython-notebook#88]
In the jupyter-notebook you can get the latex to render and now view the markdown yourself, but also get it to render in the browser by pressing shift + enter, is there any way to render it?

$y \in R$

**Comment by millejoh** [comment]
I'm not immediately certain how to do this in EIN, but [apparently](http://emacs.stackexchange.com/questions/215/how-can-i-preview-tex-formulas-inline-in-arbitrary-modes) org-mode supports this and [weechat](https://github.com/the-kenny/weechat.el/blob/master/weechat-latex.el) was able to abstract out the specific code. Certainly would be a cool feature to have.

**Comment by risantos** [comment]
In case this is implemented, would also like to suggest LaTeX in that same manner for the `%%Latex`  magic, which yields in ein:
> `<IPython.core.display.Latex object>`

As the images from matplotlib are rendered in the Outputs of the buffer, can images generated with dvipng or imagemagick  from [org-latex-preview](http://orgmode.org/worg/org-tutorials/org-latex-preview.html), also easilly be inserted?
In `Latex-mode`, I've seen in order to get inline buffer rendering the use of [preview-latex.el](https://www.gnu.org/software/auctex/preview-latex.html), and [magic-latex-buffer.el](https://github.com/zk-phi/magic-latex-buffer). The latter uses `iimage` to place the rendered images in the buffer.

If doing that, since I can't find anywhere if/how is it possible to render Javascript in an Emacs buffer,  is using the LaTeX compiler with MathJax's settings a solution?

Would that same method be adequate for the `Ipython Latex objects`, as they would just be placed in Output?
As org-mode does it, I suppose overlapping the code with images in the Markdown-cell could be tricky for symbols like `$\alpha^{2}$`, as they can be in the middle of the markdown, but line equations as 

`$$\sum_{n=0}^\infty\frac{u^n}{n!}\Delta^na_i = e^{-u}\sum_{j=0}^\infty\frac{u^j}{j!}a_{i+j} $$`
could possibly be easier for overlapping image placement.

I don't understand Emacs well enough to know how the package would have to deal with all of this, so I hope I didn't sound absurd.

**Comment by millejoh** [comment]
Not exactly seemless, but If org-latex-preview is working then [px](https://github.com/aaptel/preview-latex) will also work, though the code for `px--create-preview` needs to be patched as the signature for `org-format-latex` has changed.

Thinking about it, I can't see any reason why ein couldn't call `org-format-latex` directly, though it does introduce a dependency on org. Another interesting package is [magic-latex-buffer](https://github.com/zk-phi/magic-latex-buffer).

Getting cell output to generate Latex images is also very doable, Thanks for the suggestion!

**Comment by vanessa79** [comment]
Hi, a similar thing would be html/javascript:
from IPython.display import display, Javascript, HTML
html="some html or javascript, e.g. dypgrah"
display(HTML(html))

Should this be possible? It works with the notebook in the browser. It does not work with IPython in emacs (output is: <IPython.core.display.HTML object>) and neither with ein (no output at all)

I checked the log and find at the end: 
[debug] KERNEL--HANDLE-SHELL-REPLY: msg_type = execute_reply @#<buffer *ein: 8888/modalities.ipynb*>
[debug] no callback for: msg_type=execute_reply msg_id=7d783230-e206-493f-9cb9-60407fee5f95 @#<buffer *ein: 8888/modalities.ipynb*>
[debug] Event: execution_count\.Kernel @#<buffer *ein: 8888/modalities.ipynb*>
[debug] KERNEL--HANDLE-SHELL-REPLY: finished @#<buffer *ein: 8888/modalities.ipynb*>


Thank you for your answer - and thank you for all this work - I really appreciate it.

Vanessa

**Comment by milesstevenson** [comment]
Any update on the status of this? I wouldn't say it's a deciding feature but the lack of does bring me back to Jupyter in the browser when I'd like to see some markdown pretty printed. Adding this would be worth its bytes in gold.

**Comment by millejoh** [comment]
Still something I want to better support; it is just that I am easily distracted and don't always have much time to work on this project so issues that cause ein the break tend to get more attention than this one.

Some day...

**Comment by milesstevenson** [comment]
Is there a dedicated IRC channel, for if a user wanted to take a stab at this functionality and making a pull-request? Would be a useful place to ask questions. :)

**Comment by millejoh** [comment]
I am old and slow, so IRC doesn't suit me too well. I think EIN does get discussed periodically on IRC, but I honestly have no idea where. Pull requests are always welcome, though!

**Comment by JuanPabloMF** [comment]
Any news on this feature @millejoh? Would be glad to help on it.

**Comment by millejoh** [comment]
If you just want latex rendering in markdown cells than a very good 80% (maybe 90%) solution is [magic-latex-buffer](https://github.com/zk-phi/magic-latex-buffer). The package can be installed from MELPA, then a simple call to `M-x magic-latex-buffer` in the notebook buffer and you are ready to go.

**Comment by dickmao** [comment]
This is tricky.  Added an idle project.

**Comment by xor-xor** [comment]
As a poor/lazy man's solution for those who use org-mode anyway (and have it configured for rendering LaTeX), one may try this simple function:

```
(defun my-preview-md-cell-latex ()
  "Preview LaTeX from the current markdown cell in a separate buffer."
  (interactive)
  (let ((cell (ein:worksheet-get-current-cell))
	(buffer (get-buffer-create " *ein: LaTeX in Markdown preview*")))
    (unless (ein:markdowncell-p cell)
      (error "Not on a markdown cell"))
    (with-current-buffer buffer
      (when buffer-read-only
	(toggle-read-only))
      (unless (= (point-min) (point-max))
	(delete-region (point-min) (point-max)))
      (insert (slot-value cell :input))
      (goto-char (point-min))
      (org-mode)
      (org-toggle-latex-fragment 16)
      (special-mode)
      (unless buffer-read-only
	(toggle-read-only))
      (display-buffer
       buffer
       '((display-buffer-below-selected display-buffer-at-bottom)
         (inhibit-same-window . t)))
      (fit-window-to-buffer (window-in-direction 'below)))))
```
#works-for-me

**Comment by vvkisil** [comment]
> As a poor/lazy man's solution for those who use org-mode anyway (and have it configured for rendering LaTeX), one may try this simple function:
> #works-for-me

It is a nice functionality! Can it be extended to preview LaTeX output from Jupyter as well?

**Comment by xor-xor** [comment]
>  LaTeX output from Jupyter

@vvkisil what do you mean by that?

**Comment by vvkisil** [comment]
> > LaTeX output from Jupyter
> @vvkisil what do you mean by that?

I am using Jupyter with CAS PyGiNaC. It is able to output mathematical formulae as LaTeX-formatted strings. It will be nice to preview such LaTeX strings from the Jupyter output blocks as well. Currently it is not possible even if I would comment the check for the markdown cell in your command (the function try to previews the above code cell instead of its output).

**Comment by xor-xor** [comment]
@vvkisil here you go:
```
(defun my-preview-latex ()
  "Preview LaTeX from the current cell in a separate buffer.

Handles only markdown and code cells, but both in a bit different
ways: on the former, its input is being rendered, while on the
latter - its output."
  (interactive)
  (let* ((cell (ein:worksheet-get-current-cell))
	 (text-to-render
	  (cond ((ein:markdowncell-p cell) (slot-value cell :input))
		((ein:codecell-p cell)
		 (plist-get (car (cl-remove-if-not
				  (lambda (e) (string= (plist-get e :name) "stdout"))
				  (slot-value cell :outputs)))
			    :text))
		(t (error "Unsupported cell type"))))
	 (buffer (get-buffer-create " *ein: LaTeX preview*")))
    (with-current-buffer buffer
      (when buffer-read-only
	(toggle-read-only))
      (unless (= (point-min) (point-max))
	(delete-region (point-min) (point-max)))
      (insert text-to-render)
      (goto-char (point-min))
      (org-mode)
      (org-toggle-latex-fragment 16)
      (special-mode)
      (unless buffer-read-only
	(toggle-read-only))
      (display-buffer
       buffer
       '((display-buffer-below-selected display-buffer-at-bottom)
         (inhibit-same-window . t)))
      (fit-window-to-buffer (window-in-direction 'below)))))
```

<img width="648" alt="image" src="https://user-images.githubusercontent.com/2082842/82115564-d63b7a00-9763-11ea-8c4b-7fe5f005c93c.png">

Obviously, this function is not very robust, but you get the general idea, as the modification needed w.r.t. the previous one was rather simple.

**Comment by vvkisil** [comment]
> @vvkisil here you go:

@xor-xor  Excellent, many thanks!

**Comment by nickstares** [comment]
@xor-xor thanks so much for this!

**Comment by webloginwu** [comment]
I use emacs 29
replace  (toggle-read-only) with  (read-only-mode 'toggle)  in the code.

`(defun my-preview-latex ()
  "Preview LaTeX from the current cell in a separate buffer.

Handles only markdown and code cells, but both in a bit different
ways: on the former, its input is being rendered, while on the
latter - its output."
  (interactive)
  (let* ((cell (ein:worksheet-get-current-cell))
	 (text-to-render
	  (cond ((ein:markdowncell-p cell) (slot-value cell :input))
		((ein:codecell-p cell)
		 (plist-get (car (cl-remove-if-not
				  (lambda (e) (string= (plist-get e :name) "stdout"))
				  (slot-value cell :outputs)))
			    :text))
		(t (error "Unsupported cell type"))))
	 (buffer (get-buffer-create " *ein: LaTeX preview*")))
    (with-current-buffer buffer
      (when buffer-read-only
        (read-only-mode 'toggle))
      (unless (= (point-min) (point-max))
	(delete-region (point-min) (point-max)))
      (insert text-to-render)
      (goto-char (point-min))
      (org-mode)
      (org-toggle-latex-fragment 16)
      (special-mode)
      (unless buffer-read-only
        (read-only-mode 'toggle))
      (display-buffer
       buffer
       '((display-buffer-below-selected display-buffer-at-bottom)
         (inhibit-same-window . t)))
      (fit-window-to-buffer (window-in-direction 'below)))))
`
