### ISSUE TITLE
ein happily overwrites a notebook that has changed on disk

### ISSUE THREAD

**Issue by grothesque** [millejoh/emacs-ipython-notebook#90]
With recent Jupyter, if one opens a notebook, saves it, and then executes `touch name.ipynb`, jupiter will warn on the following save attempt that the file has been modified on disk.

This is also the general behavior of Emacs buffers.

Ein, howerver, happily overwrites files that have changed on disk since the last save.

Fixing this would help in cases where several jupiter instances share the same directory, or when the notebooks are kept under version control.
## System info:

``` cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.6)
 of 2016-01-22 on binet, modified by Debian"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux neron 4.3.0-1-amd64 #1 SMP Debian 4.3.5-1 (2016-02-06) x86_64 GNU/Linux
"
  :lsb-release
  "No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux testing (stretch)
Release:    testing
Codename:   stretch
")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.7"
           :source-dir "/home/cwg/.emacs.d/elpa/ein-0.7.1/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/elpa/websocket-1.5/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.5")
  (:name "request"
         :path "~/.emacs.d/elpa/request-0.2.0/request.elc"
         :featurep t
         :version-var request-version
         :version "0.2.0")
  (:name "python"
         :path "/usr/share/emacs/24.5/lisp/progmodes/python.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path "/usr/share/emacs24/site-lisp/emacs-goodies-el/markdown-mode.elc"
         :featurep t
         :version-var markdown-mode-version
         :version "2.0")))
```

**Comment by millejoh** [comment]
On Windows, at least, I can't reproduce this behavior using the web interface. I am probably missing something obvious, though.

I would be interested in seeing how the web interface would implement this, as it apparently is an undocumented feature. EIN uses the [Contents API](https://github.com/ipython/ipython/wiki/IPEP-27%3A-Contents-Service) to save and load notebooks from the Jupyter server. From what I can tell there is no provision in the API for detecting this situation, so I am not sure how this could be implemented in EIN.
