### ISSUE TITLE
symbols value as variable is void: default-kernel

### ISSUE THREAD

**Issue by wonbyte** [millejoh/emacs-ipython-notebook#92]
I have installed ein via melpa and after starting it with `jupyter notebook` in the console, when I run ein:notebooklist-open and connect to the default server on port 8888, I try to create a New Notebook and get **symbols value as variable is void: default-kernel**. If I open an existing notebook it opens fine. Any ideas what I need to do here?

**Comment by flamingbear** [comment]
I've experienced this.  A workaround is to go and "click" on the create new notebooks button on the notebooklist page.  That's done by just hitting return on the asterisk.   I don't have a solution yet.

```

[New Notebook] [Reload List] [Open In Browser]

Create New Notebooks Using Kernel: 
(*) python2
```

**Comment by millejoh** [comment]
Yes, that is unfortunately the only way to get this to work at the moment. EIN currently tries to select a default kernelspec when calling `ein:notebooklist-open` but is obviously failing miserably. I'm not sure why, but it is probably an async issue.

**Comment by millejoh** [comment]
Actually not an async issue, but one of lexical vs. dynamic binding. Sigh. I should get this fix in later today or early tomorrow.

**Comment by wonbyte** [comment]
Awesome, looking foward to seeing the fix. Is love to help out with this repo. It's a great extension
