### ISSUE TITLE
incredible latency for basic cell outputs

### ISSUE THREAD

**Issue by martibosch** [millejoh/emacs-ipython-notebook#93]
Hello,
I am using Jupyter 4.1.0, GNU Emacs 24.3.1, and the latest release of emacs-ipython-notebook from MELPA. I am getting incredible delays to get cell outputs that correspond to very light operations, for instance:
```
my_ser = pd.Series(['Hello', 'World'], index=np.arange(5,7))
my_ser
```
can take up to 3 seconds to output:
```
5    Hello
6    World
dtype: object
```
The same does not happen in the browser version of Jupyter notebooks. Does this happen to anyone else? Is it due to the emacs request package?
Thanks in advance!

**Comment by millejoh** [comment]
Unfortunately I'm not seeing these latencies on my Surface 3. It takes a few seconds for `import pandas as pd` to execute, but the code above executes in a fraction of a second.

Only thing I can think is to check if the ein lisp files have been bytecompile, which they should be if you are downloading from MELPA.

emacs-requests may indeed be causing issues; there are some customizable parameters for that package. You might try changing the backend from curl to url-request, or vice versa.

As a final desperate attempt you could call `ein:dev-enable-debug` and watch the *ein:log-all* buffer and see if you can catch where the slowdown is occurring.

**Comment by martibosch** [comment]
the problem is that I was using a very old-fashioned way for package-management so I still had old versions of some packages.
I reinstalled the later versions of the necessary packages and now it works as a charm.
I am then closing the issue. Thank you for your attention!
