### ISSUE TITLE
SSL wrong version number jupyter server

### ISSUE THREAD

**Issue by reconmaster** [millejoh/emacs-ipython-notebook#94]
When I try to connect to a remote jupyter/ipython server, I get the following error message when trying to connect to the notebook with ein (ein-20160323.1040):

```
[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
```

I can open the notebook with ein and browse around, but as soon as I try to run a code block or edit the notebook, I get this warning 

```
ein: [warn] Kernel is not ready yet! (or closed already.)
```

There is also this message periodically in *Messages* when using ein:

```
Blocking call to accept-process-output with quit inhibited!! [2 times]
```

As for the jupyter settings, I have no problem logging in and using the remote notebook with the web based interface. Let me know if you need more information.

**Comment by millejoh** [comment]
When you call `ein:notebooklist-open` do you specify the entire URL (e.g. as https://localhost:8888). Also, what backend is the request package using? I have found that curl, at least on windows, seems to not handle SSL requests well and I have to fall back to using url-retrieve.

**Comment by reconmaster** [comment]
I do use the entire address with https://localhost:8888. I have the following packages

```
curl 7.47.1 (x86_64-pc-linux-gnu) libcurl/7.47.1 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 libssh2/1.7.0
```

**Comment by millejoh** [comment]
If you call `M-x customize-group RET request RET` and change the 'Request Backend' setting to `url-retrieve` does calling `ein:notebooklist-open` then work? Note that if you have set a password on your jupyter server you need to instead call `ein:notebooklist-login`.

**Comment by reconmaster** [comment]
Though maybe it wasn't clear with my initial post, connecting to the remote notebook with a password isn't an issue. I can connect to the server and then proceed to open a notebook and view it if it has already been evaluated with the web interface.  However if I try to run any of the In[ ] sections through ein, I get the kernel not ready.

From the jupyter end, I have the following logs of this interaction

```
[I 2016-03-31 13:46:05.015 NotebookApp] 302 POST /login (10.10.10.10) 2.56ms
[W 2016-03-31 13:46:05.017 NotebookApp] 405 POST / (10.10.10.10) 0.65ms referer=None
[I 2016-03-31 13:46:38.347 NotebookApp] Kernel started: a76db3e1-db2e-447e-872f-4e5b5f0107e3
[W 2016-03-31 13:46:39.441 NotebookApp] Couldn't authenticate WebSocket connection
[W 2016-03-31 13:46:39.478 NotebookApp] 403 GET /api/kernels/a76db3e1-db2e-447e-872f-4e5b5f0107e3/channels?session_id=8b131deb-a420-4ed3-96e1-59c710feee17 (10.10.10.10) 40.14ms referer=None
```

The result is exactly the same after I cahnge the request backend to ```url-retrieve```

**Comment by millejoh** [comment]
Getting an error while trying to connect a session says to me that EIN is using 'ws' instead of 'wss', but that should have been fixed with 847d4a0 . How are you getting ein? Are you downloading it from MELPA stable?

**Comment by reconmaster** [comment]
I am getting ein from MELPA. Here is some more information I found in the ein log for the same problem (Version: 20160330.1938)

```
[info] Opened notebook list at https://research.comp.edu:9999 with path recon/tests/cfgs @#<buffer *ein:notebooklist https://research.comp.edu:9999*>
[info] Opening notebook recon/tests/cfgs/em_testing.ipynb... @#<buffer *ein:notebooklist https://research.comp.edu:9999*>
[info] Opened notebook list at https://research.comp.edu:9999 with path recon/tests/cfgs @#<buffer *ein:notebooklist https://research.comp.edu:9999*>
[info] Reading nbformat4 notebook. @#<buffer *ein:notebooklist https://research.comp.edu:9999*>
[info] Worksheet em_testing.ipynb is ready @#<buffer *ein: https://research.comp.edu:9999/em_testing.ipynb*>
[info] Notebook em_testing.ipynb is ready @#<buffer *ein:notebooklist https://research.comp.edu:9999*>
[info] Kernel started: f196b0ba-5b94-4cb8-a0d6-a544b3aa38bd @#<buffer  ein:mlf-fontification:python-mode>
[info] Starting channels WS: "wss://research.comp.edu:9999/api/kernels/f196b0ba-5b94-4cb8-a0d6-a544b3aa38bd/channels?session_id=d0f288e4-248d-478e-9ae7-2b24adde5399" @#<buffer  ein:mlf-fontification:python-mode>
[warn] Kernel is not ready yet! (or closed already.) @#<buffer *ein: https://research.comp.edu:9999/em_testing.ipynb*>
```

**Comment by millejoh** [comment]
I finally was able to cobble together a setup to test this. When I enable debugging I see the websocket connection is receiving a 403 error from the Tornado server when it tries to connect. Odd, as I would expect to see a 401 if authentication was failing. In any case this one is going to be a bugger as the problem is either in how emacs-websocket sends authentication or in how Jupyter/Tornado expects to receive authentication.

**Comment by millejoh** [comment]
Think I finally have a handle on what's happening. I just pushed some changes to github and MELPA should update in a few hours. Let me know if this works for you!

**Comment by reconmaster** [comment]
Well done! That took care of it. Thanks for forking this and bringing it up to speed with jupyter. I'll report back if I come across anything other strange behavior.
