### ISSUE TITLE
Blocking call warning in Emacs 25

### ISSUE THREAD

**Issue by millejoh** [millejoh/emacs-ipython-notebook#95]
Emacs 25 generates "Blocking call to accept-process-output with quit inhibited!!" warnings in the _Messages_ buffer. Some additional description of what this message [means](https://lists.gnu.org/archive/html/emacs-devel/2011-09/msg00360.html).

Not sure what is prompting these messages, but it seems something to do with changes introduced in Emacs 25 as these messages do not appear in Emacs 24 and earlier.

This message may be due to interaction with another package, as apparently this message has existed since at least Emacs 24.

**Comment by rafalcieslak** [comment]
I am probably experiencing this issue when I open any notebook from the notebook list buffer. The notebook open correctly, but the message

    Blocking call to accept-process-output with quit inhibited!!

appears, and the `notebooklist` buffer gets corrupted - it only shows the header and does not list any notebooks, it also switches to fundamental mode. `ein:notebooklist-reload` does not fix it, I need to kill the buffer and then re-open the list.

Is there anything I could do to help troubleshoot this issue?

**Comment by millejoh** [comment]
What versions of ipython/jupyter and emacs are you running? If you run `ein:dev-debug-template` it will generate some of this information for you automatically.

Try calling `ein:force-ipython-version-check`, also for good measure you can call `ein:byte-compile-ein`.

When you call `ein:notebooklist-open` what happens in the console where you are running the ipython/jupyter notebook server?

**Comment by rafalcieslak** [comment]
Interesting, it appears that `ein:byte-compile-ein` solved the problem for me. I am no longer able to reproduce this issue, the notebook list behaves correctly and the blocking call message does not appear. My `ein` was installed from MELPA, so I did not expect that I should compile anything.

**Comment by millejoh** [comment]
Seems to have gone away in recent versions of emacs. Warning was never more than a nuisance in any case, so I'm going to close this one.
