### ISSUE TITLE
zeroein.el broken on Emacs 24?

### ISSUE THREAD

**Issue by millejoh** [millejoh/emacs-ipython-notebook#96]
Errors out because it cannot find the `cl-generic` package. This package provides backwards compatibility for Emacs 25 features and needs to be installed via elpa.

Seems calling `(package-initialize)` would solve this, but is it the right thing to do?

**Comment by sebjameswml** [comment]
I came across this problem on emacs 24. I place cl-generic.el in the EIN/lisp directory when I byte-compiled EIN.

**Comment by millejoh** [comment]
With MELPA and el-get zeroein.el has become more of an anachronism, and I seriously wonder if anyone still actually uses it to load and launch ein. I may keep it around for ein's test suite (but using Cask may ultimately be the better option), but otherwise I am moving towards deprecating the use of zeroein.el.
